### ISSUE TITLE
project management

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#101]
我准备把 wiki 彻底翻新一下。另外，还想引入像 you-get 和 youtube-dl 那样的开新 issue 时先显示一系列的问题模板，可是翻了好些地方都不知道在哪儿弄。@zhangn1985 知道该在哪儿设置么？

**Comment by SeaHOH** [comment]
问题模板提交一个 `.github/ISSUE_TEMPLATE.md` 即可。

**Comment by mengmo** [comment]
这么一说，我就搜到了
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
还有这个
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by mengmo** [comment]
@zhangn1985
我改了改 wiki ，你看看有没有哪儿不妥？
还有，我照着 you-get 的`ISSUE_TEMPLATE.md`改了改，把这个添进去吧
https://gist.github.com/mengmo/da7ad3d5cad41180af49186ae7763516

**Comment by zhangn1985** [comment]
赞！

**Comment by zhangn1985** [comment]
改得很细致。
