### ISSUE TITLE
为什么ext == 'mp4'就cmd += ['-absf', 'aac_adtstoasc']  ？

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#108]
在https://github.com/zhangn1985/ykdl/blob/c74848ea14175985aa30ecd6ea18e241a363e704/ykdl/util/wrap.py
里，为什么为什么ext == 'mp4'就cmd += ['-absf', 'aac_adtstoasc']  ？
```
    cmd = ['ffmpeg','-f', 'concat', '-safe', '-1', '-y', '-i', inputfile.name, '-c', 'copy', '-hide_banner']
    if ext == 'mp4':
        cmd += ['-absf', 'aac_adtstoasc']
```
直接用
`cmd = ['ffmpeg','-f', 'concat', '-safe', '-1', '-y', '-i', inputfile.name, '-c', 'copy', '-hide_banner']`
有问题吗？

**Comment by mengmo** [comment]
https://github.com/soimort/you-get/issues/813

**Comment by zhangn1985** [comment]
@mengmo 就是这个，谢谢。

**Comment by redstoneleo** [comment]
乐视的那些 ts 片段，我不加 -bsf:a aac_adtstoasc 参数依然可以正常合并为MP4单文件，请你们也测试下看看这个参数是不是多余的

**Comment by redstoneleo** [comment]
根据我的测试，还有这位的确认https://github.com/soimort/you-get/issues/813#issuecomment-293594575
，高版本FFmpeg的不需要这个参数也能行
