### ISSUE TITLE
基于ykdl的GUI下载器开始测试

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#109]
我的乐影音下载器其实很早以前就开始做了，最新一个版本把ykdl作为了视频解析后盾之一，各位感兴趣可以试试看，欢迎反馈问题！
http://mathjoy.lofter.com/post/42208d_7cabd00
本软件没开源，请别鄙视我~~，后面打算也出Linux版，现在请大家用Windows版测试体验，不胜感激！

**Comment by SeaHOH** [comment]
这让人情何以堪，你不怕南山吗？

**Comment by redstoneleo** [comment]
什么意思？@SeaHOH

**Comment by zhangn1985** [comment]
挺好的。

**Comment by SeaHOH** [comment]
以商业为目的的话，肯定要搞推广，这搞多了不会被企鹅盯上吗？

**Comment by redstoneleo** [comment]
@zhangn1985 谢谢老大！现在有个问题：我需要把you-get编译成单独文件在这个软件里使用，到现在还没成功~~~谁能帮个忙呢？
@SeaHOH 这个软件主要是本人练手，顺便能赚点小钱就好（老大需要的话我可以捐赠！），没有大力商业推广的意思，因为做视频下载器软件就是“做大死”，不少前车之鉴啊，所以只能是低调玩玩啦

**Comment by zhangn1985** [comment]
多给本项目做贡献吧

**Comment by SeaHOH** [comment]
我还以为你没意识到，千万别搞大了哦。

**Comment by redstoneleo** [comment]
@SeaHOH 谢谢提醒，我就小打小闹玩玩

**Comment by redstoneleo** [comment]
Linux 64位版开始测试 https://bbs.deepin.org/forum.php?mod=viewthread&tid=137624&page=1&extra=#pid314973
