### ISSUE TITLE
请问这个在windows下怎么使用，谢谢！

### ISSUE THREAD

**Issue by nopss** [zhangn1985/ykdl#113]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 请问怎么用这个看huya的直播，谢谢

**Comment by zhangn1985** [comment]
先去release 页面下载full包，然后，再下载最新的独立exe，替换掉。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/wiki/Windows-User-Guide
