### ISSUE TITLE
可以考虑下载视频后合并成mp4格式吗

### ISSUE THREAD

**Issue by shikkoku** [zhangn1985/ykdl#116]
不知道为什么播放相同一个视频flv封装比mp4要卡很多。都是调用ffmpeg合并应该差不多？

**Comment by lamlam123tld3** [comment]
flv is Flash stream video designing for streaming
mp4 and mkv is designed more for playback

their binary structure is different

**Comment by Gokou-Ruri** [comment]
你可以自己写个批处理，把快捷方式丢到%sendto%，实现一键封装mp4并删除flv。
