### ISSUE TITLE
support gui

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#12]
CLI is not good for end user, GUI is planned for future. target to V1.2.X, candidate GUI tool kit is QT5 (python-Qt5).

**Comment by adslen** [comment]
乐视的tkey算法如何获取的?

**Comment by zhangn1985** [comment]
不知道，这个不是我写的。文件的History已经丢失。

**Comment by adslen** [comment]
http://player.letvcdn.com/lc06_p/201607/15/18/22/18/newplayer/1/KLetvPlayer.swf 
应该在这里，今天刚找到，反编译LetvPlayer.swf ，在导出DefineBinaryData(492:com.letv.player.model……)得到的

**Comment by zhangn1985** [comment]
目前用的似乎就是swf版的算法。只有html5的算法才能拿到one link。
