### ISSUE TITLE
网易云音乐解析出错

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#123]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i http://music.163.com/#/song/468490608
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 139, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 21, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\netease\music\musicbase.py", line 50, in prepare
    self.mp3_host = music['mp3Url'][8]
TypeError: 'NoneType' object is not subscriptable
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by rosynirvana** [comment]
估计还是现在这个接口拿不到mp3吧
如果不怕网易告，可以换他们web端现在那个接口

**Comment by Hello-everybody** [comment]
报错了   哎  直接上代码

Traceback (most recent call last):
  File "yk_dl.py", line 161, in <module>
  File "yk_dl.py", line 139, in main
  File "site-packages\ykdl\extractor.py", line 21, in parser
  File "site-packages\ykdl\extractors\netease\music\musicbase.py", line 50, in prepare
TypeError: 'NoneType' object is not subscriptable
Failed to execute script yk_dl

**Comment by zhangn1985** [comment]
目前我还不知道怎么解决这个问题。

**Comment by Hello-everybody** [comment]
之前都可以解析网易的，从前两天就是5月20日开始无法解析，我分析了网易代码，没有发现更改东西。不知道是不是需要yk_dl.py这个文件，但是我发现下载的文件里没有这个文件。头疼。Who can help me?  give me a hand !

**Comment by rosynirvana** [comment]
要网页端接口的demo吗？

**Comment by Hello-everybody** [comment]
补充！！:  网易MV还可以解析，音乐已经无法解析了

**Comment by Hello-everybody** [comment]
@rosynirvana   好的  我看看那个demo  谢谢

**Comment by Hello-everybody** [comment]
页面无法访问，这个链接打不开 @rosynirvana

**Comment by rosynirvana** [comment]
是说打不开gist? 那恐怕要你自己想办法

现在的接口用的不是网页端的
网页端的接口至少三个月没变过了

**Comment by dcln78** [comment]
@rosynirvana 大神 有空教教怎样抓包吗?

**Comment by rosynirvana** [comment]
网易云这个，在浏览器开发工具里看网络流，找出哪个请求的返回值带了关键的mp3 url
然后看这个请求的calling stack，找一些看上去不像共用函数的地方设置断点，选择好后刷页面分析断点处流过的数据

**Comment by dcln78** [comment]
@rosynirvana 其实我想说的是 如何抓取像爱奇艺 腾讯这两个网站的包 并获取真实地址 搜狐,乐视 我都知道

**Comment by rosynirvana** [comment]
抓包不都是差不多的吗，你卡在哪里了

**Comment by dcln78** [comment]
@rosynirvana  我用ykdl 解析出来1080P有20多段 我自己在开发者工具 搜索 flv 出来html和x-flv 只能分段一段一段的整理合并吗?还有爱奇艺 我抓不到- -！

http://v.youku.com/v_show/id_XMjQ3OTQxMjM3Mg==.html?spm=a2hww.20023042.md223500.1~3!2~5~5~A

**Comment by rosynirvana** [comment]
现在除了bilibili的mp4之外，大多都是分段的
分段的东西只有在播放时候才会出现在开发工具的网络流里
所以首要对象是抓包含分段url列表的那个请求

**Comment by dcln78** [comment]
@rosynirvana 抓包含分段url列表的那个请求  问题就是这个呀....如何判定呢

**Comment by rosynirvana** [comment]
慢慢找呗
例如根据发起者找，如果用flash播放器那么这个请求的发起者一般看不到
另外还可以根据类型找，例如xhr，json这些

**Comment by dcln78** [comment]
@rosynirvana 可以加你Q或者微信吗？

**Comment by zhangn1985** [comment]
@rosynirvana 看不懂你的代码。。。。

**Comment by rosynirvana** [comment]
那我晚些时候重新写一遍吧
只是要一个能处理AES-128的库

**Comment by lamlam123tld3** [comment]
```
from Crypto.Cipher import AES
import base64
import random
import json
import requests

def pksc7_padding(string):
    aes_block_size = 16
    padding_size = aes_block_size - len(string) % 16
    string = string.ljust(len(string)+padding_size, chr(padding_size))
    
def aes_128_enc(data, key, iv):
    obj = AES.new(key, AES.MODE_CBC, iv)
    data = pksc7_padding(data)
    encrypted_data = obj.encrypt(data)
    return base64.b64encode(encrypted_data).decode('utf8')

def make_json_data(url_id):
    fixed = {}
    fixed['br'] = 128000
    fixed['csrf_token'] = '' #in the cookie
    fixed['ids'] = '[{}]'.format(url_id)
    return json.dumps(fixed, separators=(',', ':'))

# Generate 16-digit Random Vector
base_str = '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
rv = ''
for i in range(0, 16):
    rv += base_str[random.randint(0, len(base_str) - 1)]

# Generate encText // 2-pass AES encryption
fixed_key = "0CoJUm6Qyw8W8jud"
iv = "0102030405060708"
encText = aes_128_enc(make_json_data(self.vid), fixed_key, iv)
encText = aes_128_enc(encText, rv, iv)

# Generate encSecKey // RSA
modular = 157794750267131502212476817800345498121872783333389747424011531025366277535262539913701806290766479189477533597854989606803194253978660329941980786072432806427833685472618792592200595694346872951301770580765135349259590167490536138082469680638514416594216629258349130257685001248172188325316586707301643237607
exp = 65537
to_number = 0
for i in rv[::-1]:
    to_number = to_number * 256 + ord(i)
encSecKey = (hex(pow(to_number, exp, modular))[2:]).rjust(256, '0')

payload = {}
payload['params'] = encText
payload['encSecKey'] = encSecKey 

url = 'http://music.163.com/weapi/song/enhance/player/url?csfr_token='
r = requests.post(url, data=payload)
```

@rosynirvana @zhangn1985 
something like this?

**Comment by rosynirvana** [comment]
I think ```encSecKey``` does not need zero pading to 256 bytes.

**Comment by lamlam123tld3** [comment]
@rosynirvana 
i've just tested
256 bytes is required

this will have a return (256 bytes encSecKey, with zero padding)

params=RXlJDHqL%2BT6qpvtI%2FLFwMRxCCqB4Wisptvz7%2Fc3bWlpMRY91yAVwyF3EIetpG4IIai5qmmCON24i6FoUaEPCEMJYO%2FR%2Fv3Rbk8rERNDbmIY11QD8P7hE%2B1RqSCDPm7DQ&encSecKey=06d0933b7c02811f137eab338a15f872699ff2d263ac0e5b89f28f6d370b17ef399ced77c6fbc62220c9cb8b02f6acaa445e4429dd65c7c5e37cc556d4434ba0d270637404b0d1455f9a5c7d1b02e0720e25d1e878e16aff8ca6341dfcf0a7fcf5725251d35e1798ba7e7cd312d4901d444f9b4de505dace731edd707ba07587

while this will not (255 bytes encSecKey, without zero padding)

params=RXlJDHqL%2BT6qpvtI%2FLFwMRxCCqB4Wisptvz7%2Fc3bWlpMRY91yAVwyF3EIetpG4IIai5qmmCON24i6FoUaEPCEMJYO%2FR%2Fv3Rbk8rERNDbmIY11QD8P7hE%2B1RqSCDPm7DQ&encSecKey=6d0933b7c02811f137eab338a15f872699ff2d263ac0e5b89f28f6d370b17ef399ced77c6fbc62220c9cb8b02f6acaa445e4429dd65c7c5e37cc556d4434ba0d270637404b0d1455f9a5c7d1b02e0720e25d1e878e16aff8ca6341dfcf0a7fcf5725251d35e1798ba7e7cd312d4901d444f9b4de505dace731edd707ba07587

**Comment by rosynirvana** [comment]
Yep, if ```encSecKey``` is shorter than 256, add ```'0'```at front until it's 256 bytes.

https://gist.github.com/rosynirvana/9678ff353e098910313c77494425a75c

**Comment by zhangn1985** [comment]
@rosynirvana `r.content.decode('utf8')` is empty.

**Comment by rosynirvana** [comment]
gist的代码更新过几次

总是空的吗？
song的id是啥？

**Comment by lamlam123tld3** [comment]
@zhangn1985 
rawText = make_json_data(GetId(self.vid))
GetId from this api
http://music.163.com/api/dj/program/detail/?id={}&ids=[{}]&csrf_token=

**Comment by zhangn1985** [comment]
@rosynirvana 就是你代码里面的`    test_ids = ['306672', '254095', '208934']`

**Comment by rosynirvana** [comment]
修了```encSecKey```的补位后，测试了30次没有出现过content为空了
```
{'data': [{'br': 128000, 'fee': 0, 'uf': None, 'gain': -2.83, 'md5': '574a2be2df717b2b1b0a57273fd3f873', 'payed': 0, 'code': 200, 'flag': 0, 'type': 'mp3', 'expi': 1200, 'url': 'http://m10.music.126.net/20170529204332/71e7dfe790ee8ecc76bb24741cbfa117/ymusic/2ba4/2130/8a71/574a2be2df717b2b1b0a57273fd3f873.mp3', 'canExtend': False, 'id': 306672, 'size': 4366086}], 'code': 200}
{'data': [{'br': 128000, 'fee': 0, 'uf': None, 'gain': -1.6, 'md5': '829e0e3e4ba0e9ac8e7f52a1ab6535e7', 'payed': 0, 'code': 200, 'flag': 0, 'type': 'mp3', 'expi': 1200, 'url': 'http://m10.music.126.net/20170529204332/f8e6a300474cec7edc86eba4e2f9066b/ymusic/1007/143f/a1e0/829e0e3e4ba0e9ac8e7f52a1ab6535e7.mp3', 'canExtend': False, 'id': 254095, 'size': 3842399}], 'code': 200}
{'data': [{'br': 128000, 'fee': 0, 'uf': None, 'gain': -0.09, 'md5': 'fe2b09d35bf5de0fc19ad482f2071532', 'payed': 0, 'code': 200, 'flag': 0, 'type': 'mp3', 'expi': 1200, 'url': 'http://m10.music.126.net/20170529204332/82c8f2425a2d0ce5e97b29a3cbfd559c/ymusic/5f39/7a76/6beb/fe2b09d35bf5de0fc19ad482f2071532.mp3', 'canExtend': False, 'id': 208934, 'size': 4445084}], 'code': 200}
```

**Comment by zhangn1985** [comment]
一直为空;
```
md5sum netease.py 
6bed14e736cf412fa02cf9a4cb178392  netease.py
```

**Comment by rosynirvana** [comment]
是这个hash没错，不理解了，要不打印出一组payload看看？

```
snd_key = 'abcdefgh12345678'
encSecKey = RSA_string(snd_key)
print(netease_req(snd_key=snd_key, encSecKey=encSecKey))
```
```{'encSecKey': '26ac8b545d6a8237a10910a0ca6464f826dffbf6681f10ae33174cb1dd18451e6cc0ac4ec2f0f80c84314b4fa1d36022d6343e5845f88e3705be8c458cf773ef8a16293291283cb1345353a9913930b714b64e2a191e1df4cdffbee47ad632753d2b8ef0fc95ff5ceae45d47a5dc863185ed71db0034652175a542053482d3fc', 'params': 'Uzo0JrY4YxKmqJfi13Vt6LdoCEmyjLKsJ5SC55OzHpat/LjXWr+D/QbHwo03VbB5HfGAP2gZYvMma3LhZQBNp8M5AtP32BNJgfzuUjqYoXWVMWV0McOIVSYeAuUOVRVO'}```

**Comment by zhangn1985** [comment]
```
{'params': u'nITJR6zu8c8Mh0Duc8IKadGH0xH40Uz5PxU9zc8WdKUYwE+pH9tW1OxXtIiGNRn/49x8iCVCV/UvR55W+17DKz/r0jfquHUO7f7NuKRxin0=', 'encSecKey': '880729bb91543b1bcd147d2f14974ca5825b408721e62c61db03933cff38784339140ad65e35c23050ad66cff09c4c19e4d2ac5758b496356dd838ca1aeec3e54ce97a5329f41037a5e7539a94fc117a951db33d4f23af92e27c01cc9507ecd2b7c6b037f7fbe0d5af6dfa595c19a93c191686c79c96c19738228afbf2380c6cL'}
```
params 变成了unicode了。

**Comment by zhangn1985** [comment]
`{'params': '+lenkW6DV/0Y9Y/ZZIyXTtCRL0IQqKRvO1eMw1+be/pqaAsyacnHBeGy8jueeY3GhfUZ36kMblkWPOBq64znJiFX1jxNzsGff1IhX6l7PL2RTgu3xPTcJV/ayF+7kBGH', 'encSecKey': '26ac8b545d6a8237a10910a0ca6464f826dffbf6681f10ae33174cb1dd18451e6cc0ac4ec2f0f80c84314b4fa1d36022d6343e5845f88e3705be8c458cf773ef8a16293291283cb1345353a9913930b714b64e2a191e1df4cdffbee47ad632753d2b8ef0fc95ff5ceae45d47a5dc863185ed71db0034652175a542053482d3fcL'}
`

**Comment by zhangn1985** [comment]
```python
if __name__ == '__main__':
    url = 'http://music.163.com/weapi/song/enhance/player/url?csfr_token='

    snd_key = 'abcdefgh12345678'
    encSecKey = RSA_string(snd_key)
    print(netease_req(snd_key=snd_key, encSecKey=encSecKey))
    encSecKey = RSA_string(snd_key)
    test_ids = ['306672', '254095', '208934']
    for test_id in test_ids:
        payload = netease_req(test_id, snd_key, encSecKey)
        r = requests.post(url, data=payload)
        print(json.loads(r.content.decode('utf8')))
```

**Comment by rosynirvana** [comment]
```encSecKey```多了一个'L'，我用python2也会多一个L

```
def RSA_string(input_str):
    modular = 157794750267131502212476817800345498121872783333389747424011531025366277535262539913701806290766479189477533597854989606803194253978660329941980786072432806427833685472618792592200595694346872951301770580765135349259590167490536138082469680638514416594216629258349130257685001248172188325316586707301643237607
    exp = 65537

    to_num = 0
    rev_str = input_str[::-1]
    for i in rev_str:
        to_num = to_num * 256 + ord(i)

    encSecKey = hex(pow(to_num, exp, modular))[2:]
    return encSecKey.rjust(256, '0')

print(RSA_string('abcdefgh12345678'))
```

```
python3 test.py
26ac8b545d6a8237a10910a0ca6464f826dffbf6681f10ae33174cb1dd18451e6cc0ac4ec2f0f80c84314b4fa1d36022d6343e5845f88e3705be8c458cf773ef8a16293291283cb1345353a9913930b714b64e2a191e1df4cdffbee47ad632753d2b8ef0fc95ff5ceae45d47a5dc863185ed71db0034652175a542053482d3fc

python2 test.py
26ac8b545d6a8237a10910a0ca6464f826dffbf6681f10ae33174cb1dd18451e6cc0ac4ec2f0f80c84314b4fa1d36022d6343e5845f88e3705be8c458cf773ef8a16293291283cb1345353a9913930b714b64e2a191e1df4cdffbee47ad632753d2b8ef0fc95ff5ceae45d47a5dc863185ed71db0034652175a542053482d3fcL
```

**Comment by zhangn1985** [comment]
恩，没错，是多了个L，因为你的程序 python3不能运行，我要理解了之后才能做。

**Comment by rosynirvana** [comment]
那问题就是pycrpto做AES时候的编码处理了

**Comment by zhangn1985** [comment]
python2 还有极少数情况出现 r.content.decode('utf8') is empty. 的情况，详情请`make test_163m`
