### ISSUE TITLE
如何将ykdl作为Python模块，并调用直接下载url视频？Wiki介绍不足

### ISSUE THREAD

**Issue by demostars** [zhangn1985/ykdl#124]
您好，已经阅读过Wiki中内容
https://github.com/zhangn1985/ykdl/wiki/develop-guide

这里返回的是 
<ykdl.extractors.weibo.Weibo object at 0x0193DD90>, 'http://weibo.com/tv/v/F3QzidoCR?fid=1034:9ff0092f6aa06280eb218828aeb42be8'

Object 和 url，后续如何处理呢？

如何调用下载呢？如何获取标题等信息呢？（因为wiki中说唯一途径是那样调用，所以多问一些使用方法）

打扰了，非常感谢~

**Comment by mengmo** [comment]
https://github.com/zhangn1985/ykdl/wiki
**2**. 可执行 module `cykdl`: `<PATH>/cykdl`。同时也是调用 library `ykdl` 的编程示例

**Comment by zhangn1985** [comment]
已更新
