### ISSUE TITLE
编码错误？部分中文乱码

### ISSUE THREAD

**Issue by demostars** [zhangn1985/ykdl#128]
错误视频地址 : http://weibo.com/tv/v/13458f8dda3eb9310bd1c4e7c02ad747?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747

错误信息 : (下载正常，合成报错如下)
```
ykdl: Merging video 一美国高中生制作了几分钟的短片，点击量几百万，生动透彻地介绍了狭义相对
论的精髓，并由此获得了硅谷科技大佬设立的“科学突破奖”25万美元！一起来感受下我的听译吧#分分 using
ffmpeg:
Input #0, concat, from 'D:\DOWNLOAD\WebVideo\tmp1sw0ir0o.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 856x480 [SAR 1:1 DAR 107:60], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 106 kb/s

Output #0, mp4, to '涓€缇庡浗楂樹腑鐢熷埗浣滀簡鍑犲垎閽熺殑鐭墖锛岀偣鍑婚噺鍑犵櫨涓囷紝鐢熷姩
閫忓交鍦颁粙缁嶄簡鐙箟鐩稿璁虹殑绮鹃珦锛屽苟鐢辨鑾峰緱浜嗙璋风鎶€澶т浆璁剧珛鐨勨€滅
瀛︾獊鐮村鈥?5涓囩編鍏冿紒涓€璧锋潵鎰熷彈涓嬫垜鐨勫惉璇戝惂#鍒嗗垎.mp4':
  Metadata:
    encoder         : Lavf57.65.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(progressive), 856x480 [SAR 1:1 DAR 107:60], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1(und): Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp, 106 kb/s

Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1194 fps=0.0 q=-1.0 size=    5972kB time=00:00:39.96 bitrate=1224.2kbits/s speed=79.8x
frame= 2551 fps=2548 q=-1.0 size=   13903kB time=00:01:25.42 bitrate=1333.3kbits/s speed=85.3x
frame= 3870 fps=2578 q=-1.0 size=   20205kB time=00:02:09.72 bitrate=1276.0kbits/s speed=86.4x
frame= 5664 fps=2830 q=-1.0 size=   29091kB time=00:03:09.83 bitrate=1255.3kbits/s speed=94.9x
frame= 7149 fps=2858 q=-1.0 size=   37990kB time=00:03:59.67 bitrate=1298.5kbits/s speed=95.8x
[concat @ 031e83a0] Impossible to open '涓€缇庡浗楂樹腑鐢熷埗浣滀簡鍑犲垎閽熺殑鐭墖锛岀偣鍑婚
噺鍑犵櫨涓囷紝鐢熷姩閫忓交鍦颁粙缁嶄簡鐙箟鐩稿璁虹殑绮鹃珦锛屽苟鐢辨鑾峰緱浜嗙璋风鎶€
澶т浆璁剧珛鐨勨€滅瀛︾獊鐮村鈥?5涓囩編鍏冿紒涓€璧锋潵鎰熷彈涓嬫垜鐨勫惉璇戝惂#鍒嗗垎_28_.mp4
'
D:\DOWNLOAD\WebVideo\tmp1sw0ir0o.txt: Invalid argument
frame= 7592 fps=2892 q=-1.0 Lsize=   40311kB time=00:04:14.51 bitrate=1297.5kbits/s speed=  97x

video:36346kB audio:3787kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.443234%
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python36\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "videos.py", line 33, in hello
    wbd.main()
  File "D:\DOWNLOAD\WebVideo\cykdl.py", line 153, in main
    handle_videoinfo(info)
  File "D:\DOWNLOAD\WebVideo\cykdl.py", line 101, in handle_videoinfo
    download(urls, name, ext, live)
  File "D:\DOWNLOAD\WebVideo\cykdl.py", line 77, in download
    clean_slices(name, ext,lenth)
  File "D:\DOWNLOAD\WebVideo\cykdl.py", line 50, in clean_slices
    os.remove(file_name)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '一美国高中生制作了几分钟的短片，点击量
几百万，生动透彻地介绍了狭义相对论的精髓，并由此获得了硅谷科技大佬设立的“科学突破奖”25万美元！一
起来感受下我的听译吧#分分_28_.mp4'
```

类似的问题也发生在这个视频上，但是正常合成，仅仅控制台名称乱码，实际正常。
http://weibo.com/tv/v/4863006f2d58ccee268b818e8723acdf?fid=1034:4863006f2d58ccee268b818e8723acdf

···
ykdl: Merging video 分享视频 using ffmpeg:
Input #0, concat, from 'D:\DOWNLOAD\WebVideo\tmpqj4uttny.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 95 kb/s Output #0, mp4, to '鍒嗕韩瑙嗛.mp4':
  Metadata:
    encoder         : Lavf57.65.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1(und): Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp, 95 kb/s Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1383 fps=0.0 q=-1.0 size=    2903kB time=00:00:55.69 bitrate= 427.0kbits/s speed= 108x
frame= 2585 fps=2539 q=-1.0 size=    5315kB time=00:01:44.11 bitrate= 418.2kbits/s speed= 102x
frame= 4428 fps=2917 q=-1.0 size=    8653kB time=00:02:58.33 bitrate= 397.5kbits/s speed= 117x
frame= 4496 fps=2787 q=-1.0 Lsize=    8855kB time=00:03:01.17 bitrate= 400.4kbits/s speed= 112x

video:6703kB audio:2056kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.093037%
D:\DOWNLOAD\WebVideo\cykdl.py:75: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 mode='w+t' encoding='utf-8'>
  ret = launch_ffmpeg(name, ext,lenth)
···

不太清楚具体问题可能出在哪？编码？

**Comment by zhangn1985** [comment]
编码可能是ffmpeg现实问题，找不到文件可能是这个文件没有下载下来。
可能和这个问题有关： https://github.com/zhangn1985/ykdl/issues/115

**Comment by rosynirvana** [comment]
这个下载合并后音画不同步比较明显，在你那里能重复吗？

**Comment by demostars** [comment]
@rosynirvana  我这边没注意这个问题，晚上回去检查下。
