### ISSUE TITLE
关于乐视解析的问题

### ISSUE THREAD

**Issue by nobadboy** [zhangn1985/ykdl#133]
现在解析到的乐视都是m3u8,而且有时不稳定，把一个参数换了 能得到单段MP4，个人感觉比价稳定，希望作者可以关注一下 
就是下面这个参数
 url = url.replace('tss=0', 'tss=ios')
把tss=0换成tss=no 再请求得到的是mp4
后面我就不会了

**Comment by rosynirvana** [comment]
你说看到的单段mp4不会是这样的吧？
```'http://61.240.143.82:8080/118/7/110/letv-uts/14/ver_00_22-302129555-avc-879562-aac-64001-2778320-330786597-0c33511e18d2652f5e28f457373a7af3-1420896942497.mp4?crypt=20aa7f2e1027&b=```

**Comment by rosynirvana** [comment]
I've checked this. won't work for some CDNs
https://github.com/soimort/you-get/issues/2047
