### ISSUE TITLE
acfun, youku open api failed?

### ISSUE THREAD

**Issue by lamlam123tld3** [zhangn1985/ykdl#135]
Could anyone decode the rc4 from the open api now?
using this key "8bdc7e1a"
i failed in multiple platforms
but the key i got from cloud.swf remains the same
http://player-vod.cn-beijing.aliyuncs.com/player/2017052716/core/cloud.swf

**Comment by rosynirvana** [comment]
ev changed

**Comment by lamlam123tld3** [comment]
you are right

**Comment by DayNYQ** [comment]
can you tell me how to get the key "8bdc7e1a" from cloud.swf?
i can't find this key in could.swf

**Comment by rosynirvana** [comment]
check binarydata， you can find a swf

**Comment by DayNYQ** [comment]
thank you, i have find it

**Comment by junges521** [comment]
can you tell me how to get the key "8bdc7e1a" from cloud.swf?
