### ISSUE TITLE
我在you-get那边是不是被禁了You can't perform that action at this time.

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#136]
这个问题可能和本项目无关，但是我真的很需要帮助.
我在you-get那边无法参与issue的评论和创建issue，每次要这么做的时候就提示我

> You can't perform that action at this time.

下面这张图就是我在you-get那边打算开新的issue的提示
![enter image description here](http://i.imgur.com/rk7cpSE.png)

希望各位玩GitHub熟练的大大帮我看看到底要怎么处理这个问题，我发过邮件给soimort，但是他还没有回复我，我是不是被那个项目给禁了啊。。。

**Comment by rosynirvana** [comment]
一般是网络卡顿……

**Comment by zhangn1985** [comment]
据我所知，没有这样的功能。关了。

**Comment by redstoneleo** [comment]
@rosynirvana 应该不可能是网络卡顿问题吧，若不然我为什么可以在这边发帖呢？
BTW，我觉得你具备成为you-get项目的管理员的资格，就是不知道为什么到现在还就只有soimort一个人在管you-get，都不会加几个管理员啊，所以我觉得you-get有点半死不活的状态
