### ISSUE TITLE
很多b站视频能够下载，不能mpv直接播放(403Error)  http://www.bilibili.com/video/av3441696?from=search&seid=10469448191343415878

### ISSUE THREAD

**Issue by andysendo** [zhangn1985/ykdl#138]
样例 http://www.bilibili.com/video/av3441696?from=search&seid=10469448191343415878
能够下载，不能mpv直接播放。

部分输出如下：
Real urls:
http://cn-jsks5-dx.acgvideo.com/vg8/d/68/5461441-1.mp4?expires=1497072000&platform=pc&ssig=7qx9w3E7Uf7eN08oaP9gFg&oi=3062391055&nfa=uTIiNt+AQjcYULykM2EttA==&dynamic=1&hfa=2064153468&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=
site:                哔哩哔哩 (Bilibili)
title:               《大话熊猫》第二季 7 ~ 神助攻要不要！
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          96.0 MiB (100638798 bytes)
    # download-with: ykdl --format=TD [URL]
Playing: edl://%186%http://cn-zjwz2-dx-v-05.acgvideo.com/vg4/9/f6/5461441-1.flv?expires=1497072000&platform=pc&ssig=WwkgeoWwIB9MnTxNZSPs5A&oi=3062391055&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2064153443
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://cn-zjwz2-dx-v-05.acgvideo.com/vg4/9/f6/5461441-1.flv?expires=1497072000&platform=pc&ssig=WwkgeoWwIB9MnTxNZSPs5A&oi=3062391055&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2064153443.

好像b站后端是乐视云的mpv都会出403错误，youku后端没这事。
既然下载能行（是不是技术处理了session/cookie之类），可否考虑针对mpv直接播放进行类似处理？谢谢

**Comment by zhangn1985** [comment]
会的。

**Comment by rosynirvana** [comment]
这个不是乐视云，bilibili一年前就彻底停用乐视云了

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/ykdl/commit/159968c384d04d6dc5a79ac1083f97c94054a103

这样简单hack一下，还是重构```launch_player```

**Comment by SeaHOH** [comment]
应该重构吧，不然以后改其它的很麻烦。

**Comment by rosynirvana** [comment]
不太容易约定接口

**Comment by SeaHOH** [comment]
支持自定义 header 的播放器我只知道 MPlayer 系列（包含 MPV），格式是一样的。
其实也可以不用管接口，只需要提供数据就行，怎么利用交给用户就好。

**Comment by rosynirvana** [comment]
重构的话是不是该动```download```，把ua和referer传给```launch_player```

**Comment by SeaHOH** [comment]
下载链接是否需要修改 header，是就构建一个 header 字典，然后可以传递给其它功能模块，由其它模块决定如何使用：
- 下载就直接使用
- 输出就转换为各种格式
- 直接播放就先检测播放器，再根据是否支持和支持格式传递转换后的 header 参数

**Comment by rosynirvana** [comment]
所以说最好的方法是把Extractor的instance直接传给下游 ;)

不过从我个人经验来看，get_content访问api的时候报告一次UA就能解决问题了 ;)
省不少代码量

**Comment by andysendo** [comment]
建议针对流行的播放器选1~3个，不考虑统一接口，分别处理播放器不同网站需要的交互参数。

目前我的体验是b站 pptv都存在许多视频需要特别参数处理，其它视频站看的少不清楚。视频站为了加强管制/保护什么的未来肯定会逐渐加独有的额外交互参数。

简言之，用例需要长期积累，短时间内考虑不完也不够。
先分散的的写处理代码，累计一定程度的代码量，再考虑统一库框架/接口比较轻松自然。

**Comment by SeaHOH** [comment]
@andysendo 
这样并不轻松自然，后期大量没有实质性改进的机械化作业让人心烦。
重要的是现在实现这种处理改变并不麻烦。

**Comment by rosynirvana** [comment]
pptv的CDN没限制

**Comment by andysendo** [comment]
是的，要写出实用的框架/接口，必然会经历一个部分代码无脑重复(觉得麻烦)的阶段。这个阶段的时间长短取决于用例积累的够不够 。

**Comment by SeaHOH** [comment]
>重要的是现在实现这种处理改变并不麻烦。

我的意思是需要处理的只有 header，最多还有 content。但是现在没有视频站点是用 POST 的方式获取视频的吧，而且也没有任何普通播放器支持 POST，所以现在就规划改变并不麻烦，不需要用例积累。

**Comment by rosynirvana** [comment]
要重构那么建一个 ```ParamsBuilder``` class，然后继承它建```MpvParamsBuilder```等等，成员有```process_name```，```ua```, ```referer```，cookies复杂一点另做考虑。默认情况下```ParamsBuilder```只有一个```ua```，就是```html.py```的```fake_headers['User-Agent']```。

然后所有Extractor返回的```streams```除url之外，还要ua和referer。同时改```download```和```launch_player```，然后```launch_player```检查进程名使用相应的builder来获取参数。

个人看法是没什么必要，CDN的限制不太可能有多少。如果CDN和api server或前端不是一个域名，那就无法通过cookies来限制；referer只能做粗糙的检查，或许只能检查有或无referer，例如某些flash播放器的referer不是页面的url；UA也只能ban掉```curl``` ```mpv```这些。曾经优酷把ua加密了放params里然后CDN检查是不是一致，现在也没了。
