### ISSUE TITLE
Unicode Error if  using php shell_exec

### ISSUE THREAD

**Issue by DoctorLai** [zhangn1985/ykdl#143]
本地装完 ykdl
然后 命令行运行没问题，但是如果放在 php 中有就问题，比如：

?php
$ykdl = "/usr/local/bin/ykdl";
$url = "http://v.youku.com/v_show/id_XMjgxMjk1MDEzMg==.html?spm=a2hww.20023042.m_223469.5~5!2~5~5~5~5~A'";
$cmd = "$ykdl -t 90 -i " . escapeshellarg($url) . " 2>&1";
echo $cmd;
$r = shell_exec($cmd);
echo $r;

得到如下结果:

/usr/local/bin/ykdl -t 90 -i 'http://v.youku.com/v_show/id_XMjgxMjk1MDEzMg==.html?spm=a2hww.20023042.m_223469.5~5!2~5~5~5~5~A' 2>&1
Traceback (most recent call last): File "/usr/local/bin/ykdl", line 11, in load_entry_point('ykdl==1.4.11', 'console_scripts', 'ykdl')() File "/usr/local/lib/python3.5/dist-packages/cykdl/__main__.py", line 157, in main handle_videoinfo(info) File "/usr/local/lib/python3.5/dist-packages/cykdl/__main__.py", line 85, in handle_videoinfo info.print_info(args.format, args.info) File "/usr/local/lib/python3.5/dist-packages/ykdl/videoinfo.py", line 49, in print_info print("site: %s" % self.site) **UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)**

**Comment by DoctorLai** [comment]
这个可能是原因?
https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by DoctorLai** [comment]
如果是换 成 you-get 就没有错误。

**Comment by zhangn1985** [comment]
哦。

**Comment by zhangn1985** [comment]
@DoctorLai 建议你用Python写网页。

**Comment by DoctorLai** [comment]
这。。。

**Comment by lamlam123tld3** [comment]
$url = "http://v.youku.com/v_show/id_XMjgxMjk1MDEzMg==.html?spm=a2hww.20023042.m_223469.5~5!2~5~5~5~5~A'";
why here u have a single quote at the end of $url

**Comment by DoctorLai** [comment]
多打了 .

实际在PHP里的字符串是
/usr/local/bin/ykdl -t 90 -i '
http://v.youku.com/v_show/id_XMjgxMjk1MDEzMg==.html?spm=a2hww.20023042.m_223469.5~5!2~5~5~5~5~A'
2>&1
运行结果是：
Traceback (most recent call last): File "/usr/local/bin/ykdl", line
11, in load_entry_point('ykdl==1.4.11',
'console_scripts', 'ykdl')() File
"/usr/local/lib/python3.5/dist-packages/cykdl/__main__.py", line 157, in
main handle_videoinfo(info) File
"/usr/local/lib/python3.5/dist-packages/cykdl/__main__.py", line 85, in
handle_videoinfo info.print_info(args.format, args.info) File
"/usr/local/lib/python3.5/dist-packages/ykdl/videoinfo.py", line 49, in
print_info print("site: %s" % self.site) UnicodeEncodeError: 'ascii' codec
can't encode characters in position 21-22: ordinal not in range(128)

**Comment by jindaxia** [comment]
print 方法的问题

**Comment by zhangn1985** [comment]
print_info print("site: %s" % self.site) UnicodeEncodeError: 'ascii' codec

我猜你的PHP 默认的codec是ascii，ykdl默认的是utf-8

**Comment by DoctorLai** [comment]
英文字符在  UTF-8 和 ascii 表示是一样的啊？我没记错的话

**Comment by zhangn1985** [comment]
好吧，ykdl只输出英文。。。

**Comment by DoctorLai** [comment]
没有问题了，在PHP里加上以下几行就可以。非常感谢。
$locale='en_US.UTF-8';
setlocale(LC_ALL,$locale);
putenv('LC_ALL='.$locale);
