### ISSUE TITLE
B站视频，403错误

### ISSUE THREAD

**Issue by jianghua** [zhangn1985/ykdl#144]
大神，你好：
      通过ykdl/cykdl/__main__.py --json http://www.bilibili.com/video/av11272051/  获取到视频地址后，在浏览器下载提示403 Forbidden，劳烦看下原因。
    ykdl/cykdl/__main__.py  http://www.bilibili.com/video/av11272051/  这种方式也下不动（下载了5分钟才到31%）
![image](https://user-images.githubusercontent.com/1780001/27163510-70e517de-51ba-11e7-8adb-0b13c208a962.png)

**Comment by zhangn1985** [comment]
拿到地址用浏览器打开，缺少Referer, 所以会403。
