### ISSUE TITLE
搜狐视频可以下载，mpv直接播放403Error

### ISSUE THREAD

**Issue by andysendo** [zhangn1985/ykdl#145]
样本 http://my.tv.sohu.com/us/294948593/84525582.shtml

部分错误输出如下：
Playing: edl://%398%http://58.216.27.203/sohu/v1/Tm1dTmsiTCXBqwjeqwOhXwJ29f5Ux9Dbomvmov7ytHrChWoIymcAr.mp4?k=BtinQZ&p=j9lvzSwC0SX3om1U0pXmopsWXZxIWhoVqTPcRYb4WJe4RYvS0SwcWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqt8ISCUkA3eOvlFsihHxLsAS5DvOaOw4vF9XSaFqHr709dUHAODOfoIWh1sfOoioMyclBds5BNtl20XW603f6ovyKPIlFFjv5e4poBomh0TW3dqr&q=OpCGoEOyzSwWsSCAopPmhWqDXpCG0pPyoSoUTLwdoA7CoAOCzSPC0SkBopo7hWCIWhNswmscWp&cip=182.136.103.43
[ffmpeg] http: HTTP error 403 Forbidden

**Comment by rosynirvana** [comment]
搜狐的CDN有问题
#95

你可以抓包确认是不是发出去了一个开区间的```range```请求，如果是那么没什么好办法
正常很多的客户端都是这么发请求的

**Comment by zhangn1985** [comment]
请自查播放器是否自带UA。搜狐播放不支持UA。

**Comment by SeaHOH** [comment]
Privoxy 可以改 header，删除 `Range` 即可播放。

**Comment by zhangn1985** [comment]
直接curl 解析出的地址，是能下载的，但是就是不能用mpv，不知道如何设置。

**Comment by SeaHOH** [comment]
我是用代理删除这个 `Range` 的，也许可以构建一个临时代理来走 mpv 链接？

**Comment by SeaHOH** [comment]
刚试了下，这样也可以：
```py
cmd += ['--http-header-fields', 'Range: ']
```

**Comment by zhangn1985** [comment]
@SeaHOH 我莱提交哦？

**Comment by SeaHOH** [comment]
好的
