### ISSUE TITLE
芒果tv的m3u8格式视频只能下载前五分钟

### ISSUE THREAD

**Issue by letlet** [zhangn1985/ykdl#147]
在提交前，请确保您已经检查了以下内容!

- [√] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [√] 您的`ykdl`为最新版。
- [√ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [√ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [√ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
无
```
[在这里粘贴完整日志]
```
python -m cykdl http://www.mgtv.com/b/110220/1140643.html
site:                芒果TV (HunanTV)
title:               盗梦空间
artist:              None
streams:
    - format:        TD
      container:     m3u8
      video-profile: 超清
    # download-with: ykdl --format=TD [URL]
Download: 盗梦空间_TD part 0
Download: 盗梦空间_TD part 1
Download: 盗梦空间_TD part 2
Download: 盗梦空间_TD part 3
 100%Download: 盗梦空间_TD part 4
 100%Download: 盗梦空间_TD part 5
  72%Download: 盗梦空间_TD part 6
  90%Download: 盗梦空间_TD part 7
 100%Download: 盗梦空间_TD part 8
  44%Download: 盗梦空间_TD part 9
 100%Download: 盗梦空间_TD part 10
 100%Download: 盗梦空间_TD part 11
 100%Download: 盗梦空间_TD part 12
  94%Download: 盗梦空间_TD part 13
 100%Download: 盗梦空间_TD part 14
 100%Download: 盗梦空间_TD part 15
 100%Download: 盗梦空间_TD part 16
 100%Download: 盗梦空间_TD part 17
 100%Download: 盗梦空间_TD part 18
 100%Download: 盗梦空间_TD part 19
  80%Download: 盗梦空间_TD part 20
 100%Download: 盗梦空间_TD part 21
   5%Download: 盗梦空间_TD part 22
 100%Download: 盗梦空间_TD part 23
 100%Download: 盗梦空间_TD part 24
 100%Download: 盗梦空间_TD part 25
 100%Download: 盗梦空间_TD part 26
 100%Download: 盗梦空间_TD part 27
 100%Download: 盗梦空间_TD part 28
 100%Download: 盗梦空间_TD part 29
  61%Download: 盗梦空间_TD part 30
 100%Download: 盗梦空间_TD part 31

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
windows10 python2.7 ykdl最新版本(10分钟前刚刚从github clone的）
芒果tv的m3u8格式视频只能下载前五分钟，比如这个： http://www.mgtv.com/b/110220/1140643.html

**Comment by rosynirvana** [comment]
这个试看片段就是5分钟

**Comment by zhangn1985** [comment]
这个是会员电影，只有5分钟。
