### ISSUE TITLE
应该在readme中注明下安装ykdl需要依赖pycrypto

### ISSUE THREAD

**Issue by skywang00** [zhangn1985/ykdl#148]
从某个版本的ykdl后，使用python setup.py install时报错
 `warning: no files found matching '.separate_namespace'`
使用git安装出现同样的错误提示，然后在setup.py中发现如下代码
```
REQ = ['m3u8']

if platform.system() == 'Windows':
    REQ.append('pycryptodome')
else:
    REQ.append('pycrypto')
```

我是win平台，然后`pip install pycryptodome`，就可以安装ykdl了，readme中应该注明下呀，好像是某个版本之后加入的

翻了下文件记录，commit 6f3425db37e0c821fa0bf713ea99b3d2da31e6a9 才刚刚加入的这个要求
所以只有最新的1.4.11版才需要这个先安装pycrypto，之前的版本是可以直接安装的

**Comment by rosynirvana** [comment]
话说，为什么会想到直接运行setup.py而不用pip装

**Comment by mengmo** [comment]
@skywang00
https://github.com/zhangn1985/ykdl/wiki
安装最新开发版最方便的方法
`pip / pip3 install https://github.com/zhangn1985/ykdl/archive/master.zip`

**Comment by skywang00** [comment]
@rosynirvana  

因为我不知道ykdl也可以pip安装了。。。。。
以前用you-get的时候为了方便改extractors已经习惯了setup.py安装

pip安装的话就会自动安装依赖包了对吧，和yum类似

**Comment by zhangn1985** [comment]
pip安装会自动解决依赖关系。
已更新wiki。那我就关闭这个issue了。

**Comment by mengmo** [comment]
@skywang00
you-get 其实也可以使用上述相同的方式安装

**Comment by mengmo** [comment]
@zhangn1985
1.5 有没有计划的发布时间？
现在的 wiki 排版还是有些问题，我想再改改。

**Comment by rosynirvana** [comment]
you-get patch合并得慢要自己fork

**Comment by zhangn1985** [comment]
这个周末吧
