### ISSUE TITLE
Youku新出的视频无法解析

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#149]
安装的是最新1.4.11版。

youku近期更新的视频均无法解析，比如楚乔传，前面几集可以解析，如下图是第一集，正常解析下载
![2017-06-27_222826](https://user-images.githubusercontent.com/12642186/27593558-0c9c317a-5b8a-11e7-9fc5-96c6cc143305.jpg)

后面的集数就不行了，解析不了，如第20集
![2017-06-27_223239](https://user-images.githubusercontent.com/12642186/27593805-c1367aa0-5b8a-11e7-967c-9bdb6f37cfb1.jpg)

错误提示如下：
C:\Python34>cd Scripts

C:\Python34\Scripts>ykdl http://v.youku.com/v_show/id_XMjgzODM5MDMwNA==.html
WARNING:html:wrong charset for http://61.128.153.49/6573B6ECD1A3681BF05C2C444E/0
3000207005949BCA4E2792BEEFCF996E06BF0-6C53-4A6E-ED1D-19004A6B6D40.flv?ccode=0401
&duration=393&expire=18000&psid=15c5f3360673daea6ab82f18e97abcdf&ups_client_neti
p=110.184.74.48&ups_ts=1498574254&ups_userid=&utid=rVvZEUEX%2BgACAW64SjAbpu8i&vi
d=XMjgzODM5MDMwNA%3D%3D&vkey=A401d47f2aa438b0e29c599f79a0a815f&yxon=1&special=tr
ue
Traceback (most recent call last):
  File "C:\Python34\Scripts\ykdl-script.py", line 9, in <module>
    load_entry_point('ykdl==1.4.11', 'console_scripts', 'ykdl')()
  File "C:\Python34\lib\site-packages\ykdl-1.4.11-py3.4.egg\cykdl\__main__.py",
line 149, in main
  File "C:\Python34\lib\site-packages\ykdl-1.4.11-py3.4.egg\ykdl\extractor.py",
line 24, in parser
  File "C:\Python34\lib\site-packages\ykdl-1.4.11-py3.4.egg\ykdl\extractors\youk
u.py", line 65, in prepare
  File "C:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

望修复，非常感谢！

**Comment by rosynirvana** [comment]
```Content-Type: video/x-flv```
看来是加了yxon后没有返回json，而是一个flv的片段

**Comment by zhangn1985** [comment]
是这样，先放一放，等api稳定之后再修改。
