### ISSUE TITLE
优酷视频无法解析... 

### ISSUE THREAD

**Issue by demonluo** [zhangn1985/ykdl#152]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
这个优酷视频无法解析...
http://v.youku.com/v_show/id_XNTgzNDM3ODg4.html

**Comment by rosynirvana** [comment]
mp4hd3的m3u8好像很快会失效
不知道能不能重复
