### ISSUE TITLE
希望能支持网易云课堂study.163.com

### ISSUE THREAD

**Issue by yadex** [zhangn1985/ykdl#153]
ykdl http://study.163.com/course/courseLearn.htm?courseId=716027#/learn/video?lessonId=880242&courseId=716027
[1] 9081
ning@ning:~$ Traceback (most recent call last):
  File "/home/ning/.local/bin/ykdl", line 11, in <module>
    sys.exit(main())
  File "/home/ning/.local/lib/python3.5/site-packages/cykdl/__main__.py", line 149, in main
    info = parser(u)
  File "/home/ning/.local/lib/python3.5/site-packages/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/home/ning/.local/lib/python3.5/site-packages/ykdl/extractors/netease/video.py", line 24, in prepare
    code = _vid[-2:]
TypeError: 'NoneType' object is not subscriptable

**Comment by rosynirvana** [comment]
curl 'http://study.163.com/dwr/call/plaincall/LessonLearnBean.getVideoLearnInfo.dwr?1499227848848' -H 'Content-Type: text/plain' --data-binary $'callCount=1\nscriptSessionId=${scriptSessionId}190\nhttpSessionId=80a8ad4a97144849a30143c333ada39e\nc0-scriptName=LessonLearnBean\nc0-methodName=getVideoLearnInfo\nc0-id=0\nc0-param0=string:880242\nc0-param1=string:716027\nbatchId=1499227846645' --compressed

接口应该是这个

另外这网站设计得……
```
//#DWR-REPLY
if (window.dwr) dwr.engine._remoteHandleBatchException({ name:'java.lang.SecurityException', message:'Call IDs may only contain Java Identifiers' });
else if (window.parent.dwr) window.parent.dwr.engine._remoteHandleBatchException({ name:'java.lang.SecurityException', message:'Call IDs may only contain Java Identifiers' });
```
把java的exception直接传给前端……

**Comment by jindaxia** [comment]
应该用的是一个叫dwr的工具直接部署的

**Comment by zhangn1985** [comment]
这个issue，除非有人提PR，我不会支持。

理由是，study.163.com需要登陆。如果不登陆，则没有可以测试的链接。
