### ISSUE TITLE
录制直播怎么停止？

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#159]
按“q”停不了啊，即使强行关闭命令窗口，ffmpeg仍然在继续工作。

请问如何停止录制并保存文件？

**Comment by rosynirvana** [comment]
ctrl+c

**Comment by jyuan15** [comment]
@rosynirvana 之前试过了，也停不了，无反应。

ctrl+s能停，但如果不关闭窗口的话，过一会儿它会自动又开始录制。关闭窗口后，ffmpeg还在继续运行（录制），只有强行中止进程才能停下来，但到的flv文件时长显示为00:00:00，须封装成mp4才能正常。

**Comment by zhangn1985** [comment]
Linux可以通过`q`停止，但是windows，估计不可以。

**Comment by zhangn1985** [comment]
Linux的话，ffmpeg在前台，受终端控制。
Windows，ffmpeg应该是脱离终端控制了。

不知道使用pipe能不能解决。

**Comment by jyuan15** [comment]
之前是用的Giet Bash，换cmd测试，按 q 可以停止录制
