### ISSUE TITLE
http://egame.qq.com/企鹅电竞

### ISSUE THREAD

**Issue by flfq** [zhangn1985/ykdl#160]
希望增加一个企鹅电竟

**Comment by flfq** [comment]
电竞,用的是FLASH控件播放的
要用什么工具解析
CHROME 的开发工具,看不到FLASH的请求的

**Comment by zhangn1985** [comment]
```videoInfo":{"anchorId":432863,"appid":"1104466820","appname":"王者荣耀","channelId":"3954_432863","pid":"432863_1500284827","title":"带房管上星耀","url":"http://shp.qpic.cn/pggamehead/0/1499941650_889_750x422/0?new=1.0&amp;w=750&amp;h=422","vid":"","videoType":1,"provider":2,"streamInfos":[{"bitrate":"0","desc":"超清","playUrl":"http://3954.liveplay.myqcloud.com/live/3954_432863.flv?bizid=3954&amp;txSecret=8968589db7a41a0dc27bf54f191a12cc&amp;txTime=5975c21b"},{"bitrate":"900","desc":"高清","playUrl":"http://3954.liveplay.myqcloud.com/live/3954_432863_900.flv?bizid=3954&amp;txSecret=257fbd8a5062a3fd43a4d5527898b3d0&amp;txTime=5975c21b"},{"bitrate":"550","desc":"标清","playUrl":"http://3954.liveplay.myqcloud.com/live/3954_432863_550.flv?bizid=3954&amp;txSecret=0db6ddb33345a314a45edb591b67f477&amp;txTime=5975c21b"}],
```

好傻

**Comment by flfq** [comment]
这个我已经搞定了
增加一个 qq/egame.py

代码如何
`class QQEGame(VideoExtractor):
    name = u'QQ EGAME (企鹅电竟)'

    mutli_bitrate = ['0', '900', '550']

    bitrate_2_type = {'0': 'BD', '900': 'HD', '550': 'SD'}

    bitrate_2_profile = {'0': u'超清', '900': u'高清', '550': u'标清'}

    def prepare(self):
        info = VideoInfo(self.name, True)
        if not self.vid:
            self.vid = match1(self.url, '/(\d+)')
        if not self.vid:
            '''
            fake_headers = {
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                'Accept-Encoding': 'gzip, deflate',
                'Accept-Language': 'zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3',
                'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3'
            }
            html = get_content(self.url, headers=fake_headers)
            '''
            html = get_content(self.url)
            self.vid = match1(html, '"liveAddr":"([0-9\_]+)"')
        self.pid = self.vid

        # from upstream!!
        serverDataTxt = match1(html, 'serverData = {([\S\ ]+)};')
        serverDataTxt = '{%s}' % (serverDataTxt)
        #print("serverDataTxt => %s" % (serverDataTxt))

        serverData = json.loads(serverDataTxt)
        # print(serverData)

        assert serverData["liveInfo"]["data"]["profileInfo"]["isLive"] == 1, 'error: live show is not on line!!'
        


        info.title = serverData["liveInfo"]["data"]["videoInfo"]["title"]
        info.artist = serverData["liveInfo"]["data"]["profileInfo"]["nickName"]

        for data in serverData["liveInfo"]["data"]["videoInfo"]["streamInfos"]:
            info.stream_types.append(self.bitrate_2_type[data["bitrate"]])
            info.streams[self.bitrate_2_type[data["bitrate"]]] = {'container': 'flv', 'video_profile': data["desc"], 'src': "%s&_t=%s000"%(HTMLParser().unescape(data["playUrl"]),int(time.time())) , 'size': float('inf')}
            print(info.streams[self.bitrate_2_type[data["bitrate"]]])

        return info

site = QQEGame()`

**Comment by jindaxia** [comment]
@flfq 可以发PR么

**Comment by flfq** [comment]
GITHUB不怎么用,不明白你说的PR是什么

**Comment by zhangn1985** [comment]
首先你要会用git
然后你fork我的项目
用git 克隆自己的fork
提交代码
在页面上点pull request

**Comment by zhangn1985** [comment]
不会的话过两天我来弄上去

**Comment by jindaxia** [comment]
@flfq 可以帮助你学习一下，不行的话就让楼上弄上去
