### ISSUE TITLE
图形化界面

### ISSUE THREAD

**Issue by sonichy** [zhangn1985/ykdl#161]
1.你这个好像是命令行，能不能做一个图形化界面？
2.能不能分2个功能，第一步解析出地址明(明文且可以复制)，第二步选择播放或者下载。

**Comment by snoopytl** [comment]
这个提议不错，希望能实现，这样就能傻瓜式操作了

**Comment by zhangn1985** [comment]
这个，我的确有计划，但是考虑到我并不擅长GUi，所以搁置下来了，如果有人能贡献代码，我可以维护。

**Comment by rosynirvana** [comment]
感觉应该优先考虑浏览器插件/内嵌server/desktop notification

**Comment by sonichy** [comment]
我擅长做UI，算法比较菜，主要在Linux做Qt开发，可以看看我做的项目，我希望能够将你的项目窗体化。
我是在这里找到你的，https://bbs.deepin.org/forum.php?mod=viewthread&tid=137624&extra=，他做了个窗体，没有源码，还想收费，不是一个人啊～

**Comment by rosynirvana** [comment]
这个就是 #109

**Comment by snoopytl** [comment]
这个涉及的领域太专业了，还得麻烦其他大神了，我等凡人不会开发

2017-07-17 11:39 GMT+08:00 rosynirvana <notifications@github.com>:

**Comment by rosynirvana** [comment]
一个builtin server需要设计，建立基本约定
浏览器插件(plugin or extension)和desktop notification仅仅是跨平台处理的事情

关键是old school GUI没什么用，一个url从浏览器地址栏复制到console还是其他窗口是一个工作量，只能少打几个字符（这个项目里就是ykdl加上一个空格），外加上在各式各样的MS win console里少点crash，这能不能抵得上新增的debug问题就难说了。

另外不知道现在的linux distro的桌面社区是什么样子，几年前gtk用户不愿意用qt的，qt用户总要抱怨有人喜欢把项目和gtk捆绑在一起。

**Comment by jindaxia** [comment]
说个和GUI无关的。我已经准备把ykdl模块加入KODI全家桶，作为一个国内视频站的解析模块

**Comment by zhangn1985** [comment]
@jindaxia 做好了加到wiki。

**Comment by baby1128** [comment]
额。。图形化的我这里有一个别人发给我的版本，是一个叫nilaoda制作的，但目录下的文件，得需要自己更新，我也是最近才发现这个问题。可是这个目录下面具体有youtube-dl，但图形化界面却没有这个...我纯粹是为了下载喜欢的高清视频和朋友分析才研究的，但是遇到好多困难，TT..........

**Comment by rosynirvana** [comment]
hdc是那个hdchina吗
推崇高清的怎么也来爬在线了
