### ISSUE TITLE
Chrome扩展版我来做

### ISSUE THREAD

**Issue by sonichy** [zhangn1985/ykdl#163]
想了很久，还是做成浏览器扩展方便使用。
仔细查看源码，终于找到了玄机：从网页视频参数中提取videoId，送到网站自己的秘密解析网址，返回JSON，从JSON中获取视频网址。
目前成功抓取了音悦台视频。
演示：http://v.youku.com/v_show/id_XMjkwMDk0NDcwMA==.html
扩展：http://sonichy.96.lt/VideoGrab.zip

**Comment by rosynirvana** [comment]
发url就行
从页面里找videoid相当于把url -> module的mapping和page parser又做了一遍

**Comment by skywang00** [comment]
@rosynirvana 

这种浏览器扩展的方式可以解决qq视频限速的问题吗？

**Comment by rosynirvana** [comment]
@skywang00

解决qq限速有两点要确保: 
- py里实现要正确，严格按qq js player里面的接口来写；flash里的接口应该也可以但是接口太复杂
- 获取一个guid。可以在py里生成一个随机的/[0-9][A-f]{32}/然后报告给腾讯的几个统计服务器，也可以从浏览器的local storage里找。我不确定浏览器extension or plugin读取local storage要什么权限，但在py里报告给腾讯的统计服务器代码量太大，应该没人会去做。

还有，现在ykdl或是you-get都不支持把参数传给下游module，所以还要改接口

**Comment by skywang00** [comment]
@sonichy 
有一个firefox扩展可以作为参考  Complete YouTube Saver  http://www.cys-audiovideodownloader.com/
这个扩展可以单独下载视频和音频后调用ffmpeg进行混流（需要用户指定ffmpeg目录）
目前开发者正在致力于将该扩展移植到其他浏览器

**Comment by jindaxia** [comment]
我觉得一个好的chrome扩展应该是这样的：在所观看的视频旁边显示一个“下载”按钮，点击之后下载

**Comment by jyuan15** [comment]
有个Fork好像就是专门解决腾讯娴限速的，可以满速下载。不过已经四个月没更新，已失效

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/pull/1685

这个pull request吗
可能只是理解错了

**Comment by jyuan15** [comment]
是这个，不过是在他的主页，我没用过这个，只是在其他地方看别人介绍过

**Comment by rosynirvana** [comment]
check this
https://github.com/soimort/you-get/issues/1855

那个pull request代码的主要部分，是issue里面的lvqier之前写的
