### ISSUE TITLE
能否增加 https://chushou.tv/ 触手网站

### ISSUE THREAD

**Issue by flfq** [zhangn1985/ykdl#166]
初部看了一下
https://chushou.tv/room/12738161.htm
比如这个直播
https://chushou.tv/timestamp/get.htm?0.4008549554273486
返回时间
1500962543650
然后
https://chushou.tv/live-room/get-play-url.htm?roomId=12738161&protocols=1,2&_t=1500962543650&_sign=6b8f625c83163ea0730389900107e3ab
但sign 不知道其算法
就可以得到播放地址,一个是FLASH,一个是RTMP

**Comment by zhangn1985** [comment]
```
      public static function GetPlayUrl(param1:int, param2:String) : String
      {
         return _domain + "/live-room/get-play-url.htm?roomId=" + param1 + "&protocols=1,2" + "&_t=" + param2 + "&_sign=" + MD5Util.MD5key([{
            "name":"roomId",
            "para":param1
         },{
            "name":"protocols",
            "para":"1,2"
         },{
            "name":"_t",
            "para":param2
         }]);
      }
```

**Comment by zhangn1985** [comment]
`     sign = hashlib.md5(compact_bytes('roomId={}&protocols=1,2&_t={}'.format(self.vid, t,), 'utf-8')).hexdigest()`

是这样吗？
