### ISSUE TITLE
代理参数应如何写？

### ISSUE THREAD

**Issue by qvghxf** [zhangn1985/ykdl#170]
这样写仍然是遵从IE代理，但也没有报错。
ykdl --proxy 127.0.0.1:8080 url

如果事先加一行set http_proxy，则可以使用指定代理。
set http_proxy=127.0.0.1:8080
ykdl url

请问正确写法是什么？

**Comment by zhangn1985** [comment]
`proxy_support = urllib.request.ProxyHandler({"http" : "http://ahad-haam:3128"})`

从文档上来看，应该是`ykdl --proxy http://127.0.0.1:8080 URL`

**Comment by qvghxf** [comment]
还是不行，仍然在用IE设置。IE用了代理能在代理软件中看到ykdl的连接，IE不用代理ykdl也直连。
