### ISSUE TITLE
WARNING: remove -F --format in next release

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#173]
-F --format will be replaced by --lvl

**Comment by SeaHOH** [comment]
上次征集建议时，我提了下格式别名，没想到要直接去掉替换成模糊级别。
那么下一个版本去掉 `-F --format` 后还能不能指定特定格式呢？感觉做不到耶 :sob:

**Comment by jyuan15** [comment]
现在这个 -F 挺好用的啊，为什么要改呢？

@SeaHOH 是在gop的那个吗？

**Comment by SeaHOH** [comment]
@jyuan15 叫我？这帐号不能有两个一样的吧。

**Comment by jyuan15** [comment]
@SeaHOH 你不是在社长那里的嘛

**Comment by zhangn1985** [comment]
这样看怎样？照顾了习惯。

**Comment by SeaHOH** [comment]
感谢。 :smile_cat: 
我觉得在没有能取到特定质量视频的替代参数前，保留原参数是必要的。虽然就像你之前讲的，其实 `cykdl.py` 这个完全可以自己写，但你这个官方用例大家都用得挺顺手的。
添加一致性的别名要改的地方确实比较多，但这不是必要特性，现在这种机智的处理（此处 :+1: ）感觉也不错，能用统一的参数在一定程度上控制质量。

---
另外，之前我那个 pr 最后还有个关于空白头域值的问题，你 merge 后可能就忽略了，烦请再看一下。
