### ISSUE TITLE
搜狐api的new变量是什么？

### ISSUE THREAD

**Issue by sonichy** [zhangn1985/ykdl#175]
做Chrome扩展解析搜狐视频的时候，API的new变量猜不透，请指教。

**Comment by zhangn1985** [comment]
哪个API的new变量？

**Comment by zhangn1985** [comment]
`            self.realurls[stream_id].append('http://'+host+'/?prot=9&prod=flash&pt=1&file='+clipURL+'&new='+new +'&key='+ ck+'&vid='+str(self.vid)+'&uid='+str(int(time.tim`
？

**Comment by zhangn1985** [comment]
`        for new, clip, ck, in zip(data['su'], data['clipsURL'], data['ck']):`
data['su'], 但是这里是zip过后的。

**Comment by sonichy** [comment]
就是这个new，赋值在哪里？

**Comment by rosynirvana** [comment]
就是```data['su']```中的元素
python迭代可以参考这个
http://python3-cookbook.readthedocs.io/zh_CN/latest/c04/p11_iterate_over_multiple_sequences_simultaneously.html

**Comment by sonichy** [comment]
是su，又解出了一个json，里面有真实地址。

**Comment by airdge** [comment]
`http://m.tv.sohu.com/phone_playinfo?callback=jsonpx1502084605435_74_8&vid=3887673&site=1&appid=tv&api_key=f351515304020cad28c92f70f002261c&plat=17&sver=1.0&partner=1&uid=1701311718202223&muid=1502084514106155&_c=1&pt=3&qd=680&src=11060001&_=1502084605435`
用手机端的接口应该比较方便整合(自媒体site=2)
另外,也可以这么拼接new
`http://sohu.vodnew.lxdns.com/159/206/McgnxNDUTf6t7Z9rRkAnvB.mp4`
