### ISSUE TITLE
调用 mpv 播放存在问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#176]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
D:\PortableApps\mpv>ykdl -p "mpv --no-ytdl" http://www.iqiyi.com/v_19rr8l58qo.html
site:                爱奇艺 (Iqiyi)
title:               狐妖小红娘日语版第6集
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 183, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 171, in main
    handle_videoinfo(info)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 115, in handle_videoinfo
    launch_player(args.player, urls, **player_args)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\util\wrap.py", line 23, in launch_player
    subprocess.call(cmd)
  File "D:\PortableApps\Python\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\PortableApps\Python\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "D:\PortableApps\Python\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
master 有相关更新，升级试试。

**Comment by SeaHOH** [comment]
不对，你这个原因好像是添加了额外的 `--no-ytdl` 导致的，之前的代码在一定程度上支持。
你是只更新了 ykdl，cykdl 没有更新吗？

**Comment by mengmo** [comment]
`pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip`
你看我这是像只更新了 ykdl 么？

**Comment by SeaHOH** [comment]
@mengmo 对哦，我看错了，zhangn1985 才又改了。
另外，我刚才仔细看了下 `shlex.split` 的用法，参数 `-p` 的内容里面单独的参数需要添加引号才能支持空格、反斜杠和引号之类。先前我测试的时候路径没有加引号所以报错，可见这样使用不直观，但是这么处理能支持添加播放器参数。
如果还是要支持添加播放器参数，那么 #174 把 `shlex.split` 修掉了就不对。请 @zhangn1985 考量下改如何处理。

**Comment by lki2019** [comment]
![qq 20170805153403](https://user-images.githubusercontent.com/30022431/28993935-571cb642-79f4-11e7-9577-4bf9391cc2cd.png)

ykdl -p mpv http://www.iqiyi.com/v_19rr8l58qo.html

**Comment by SeaHOH** [comment]
我刚才试了一下，也许用 `,` 来分割 `-p` 参数是一个不错的解决方案。
像这样：
`ykdl -p "D:\mpv\mpv,--no-ytdl,-pn2,p s 2" http://www.iqiyi.com/v_19rr8l58qo.html`
这样不用 `shlex.split` 也行，而且不用套引号也很直观，添加的参数也支持空格。

**Comment by SeaHOH** [comment]
@mengmo @lki2019
怎么你们的 mpv 都加到环境变量里面了，很流行这么干吗？

**Comment by lki2019** [comment]
加到环境变量，很麻烦么？

**Comment by SeaHOH** [comment]
嗯，加的多，太乱，我觉得。

**Comment by lki2019** [comment]
加的多，你还要加什么？
太乱，你又不打开环境变量那 看到的乱不乱么？

你这个理由还是很奇葩的

不过如果你就是因为个人喜好，那就没办法了

**Comment by rosynirvana** [comment]
因为不愿意加%PATH%又不愿意用正斜杠绕了一大圈？

**Comment by SeaHOH** [comment]
大概，就是这样~
不过，不加引号空格也没法用，有时参数里面也有空格。

**Comment by mengmo** [comment]
@SeaHOH @lki2019
mpv 本身有个功能：在 %PATH% 或 mpv 自身的目录下搜到 youtube-dl 时，可以 `mpv URL` 的方式播放 youtube-dl 所支持站点的视频。所以添加到 %PATH% 可以更方便使用（虽说我采用了另外的方法）

正因为上述 feature 的存在，所以只要是传给 mpv 的 URL 都会先被 youtube-dl 解析，这样会给视频播放带来一些问题（比如需要多等待些时间才能开始播放，有时甚至导致出错而无法播放），所以才需要添加`--no-ytdl`参数

youtube-dl，you-get 以及本项目在实现上各有侧重，所以这几个我都装了。

**Comment by jyuan15** [comment]
为何mpv不能播放douyu直播？因为有UA限制吗？

**Comment by lki2019** [comment]
@jyuan15 
![qq 20170805182143](https://user-images.githubusercontent.com/30022431/28994862-0c520ede-7a0b-11e7-92b1-365624c8532d.png)



<pre><code>ykdl -p PotPlayerMini https://www.douyu.com/274874  pot播放器也调用不起来

ykdl -p mpv https://www.douyu.com/274874 调用不起来

you-get -p mpv https://www.douyu.com/274874  可以调出MPV播放器

you-get -p potplayermini https://www.douyu.com/274874 可以调出pot播放器

you-get -p vlc  https://www.douyu.com/274874 可以调用出VLC播放器
</code></pre>

vlc mpv potplayermini 这3播放器我都放到环境变量里了

具体为啥ykdl 调用不出MPV 我就不知道啦 只能调用VLC

**Comment by jyuan15** [comment]
you-get和ykdl的解析接口不一样吧

**Comment by mengmo** [comment]
@jyuan15
youtube-dl 现在 douyu 的解析是坏的吧

**Comment by SeaHOH** [comment]
@mengmo 是这样的，我在配置中关闭了 youtube-dl，用的时候才传参数打开。
鼠标手势，向上是 youtube-dl，向下是 ykdl，you-get 不想用……

**Comment by zhangn1985** [comment]
看来要召回shlex了。

**Comment by SeaHOH** [comment]
shlex 用起来不直观，如果恢复的话应该修改描述，提示下引号用法。
还有个办法，可以添加 `--no-ytdl`到默认参数里面，反正除了这个好像也没什么需要自己添加的。
