### ISSUE TITLE
关于腾讯视频，有个不明白的地方

### ISSUE THREAD

**Issue by lki2019** [zhangn1985/ykdl#194]
- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

<pre><code>
ykdl -i https://v.qq.com/x/cover/y2xabppb6vi19ab.html
site:                腾讯视频 (QQ)
title:               第10期：薛之谦超严厉五次diss选手，杨幂即兴画画表白荷兹
artist:              None
streams:
    - format:        HD
      container:     mp4
      video-profile: 高清mp4
      size:          1295.4 MiB (1358289237 bytes)
    # download-with: ykdl --format=HD [URL]
Real urls:
http://1.31.173.148/variety.tc.qq.com/APFgw8z_b0FoQ_CiTWVfnCXYGE5dPT8-MBZ_ILyk77
KM/h0024loesda.mp4?stdfrom=v1090&type=mp4&vkey=661BEBB0354F2D100D73835BCE7D08F40
4020AA52BAE3A56347A8E0B7E836451254516D52F5B857E97CAA803768A5CF223500AD29E49CFBB6
5F3C352C4509608F6F75077992A46C4317DEF3B26903E822953A6BCE17B3369ADFB0A60FE29971D&
level=0&platform=1&br=127&fmt=mp4&sp=0
    - format:        LD
      container:     mp4
      video-profile: 急速
      size:          337.2 MiB (353550220 bytes)
    # download-with: ykdl --format=LD [URL]
Real urls:
http://lmbsy.qq.com/flv/16/134/h0024loesda.m1.mp4?stdfrom=v1090&type=mp4&vkey=54
91BE7F03B1DA7879265A8CAD501AB17DC937DBDDFC2B651357D3C4488AB08E9F7793F752EE3810DB
00FAEC5C64CCEF4BFEE6195CE9B8E1DD3236F9D6ACFF2F001A71EAA0F97FF87F9DC22B9B9E6CD427
DE98B92C582BF319967E5AC3F6C1B3&level=0&platform=1&br=33&fmt=msd&sp=0</code></pre>

ykd和you-get解析出来的地址是mp4的

而我在浏览器打开视频，浏览器嗅探扩展获取的地址是m3u8

http://ltslx.qq.com/XwXcFneUwl0ngQ-Piqh2T4q5SZ_rLenFalkmu_gxwbjSCPue3sjdzCk5DLVWPaZ_RSdR3tlWHBd9b4N76HHK0PHonNtLIkNMU0io6foVw50aksoELOqqEuNDgTvnKEyut5NwoiEt7HHDoLjbPfHauw/h0024loesda.321003.ts.m3u8?ver=4&sdtfrom=v1000&type=mp4&platform=11&br=201&fmt=shd&sp=0&charge=0&vip=0&guid=19BEC55D008E56CB628C595AEA488CF6

然后呢，mp4的地址，好像是下载限速

m3u8地址很明显下载速度会很快

但是我发现，有时候我观看腾讯的视频，有时候浏览器嗅探插件获取的是mp4直链
有时候获取的是m3u8 分段

同一个视频，可能多次刷新，出来的地址也许是mp4也许是m3u8

如果ykdl或者you-get 能解析出m3u8和mp4 2种地址，并优先下载m3u8 是不是更好啊？

或者可以解析m3u8地址，不能下载，自行下载也好

当然可能一些原因，是我想当然了，大神们既然获取到的是mp4直链，而不是m3u8.，肯定是有道理的

以上仅为我的一点疑惑··

**Comment by lki2019** [comment]
而在前几天，我遇到一个奇怪的现象，

https://v.qq.com/x/cover/3kxhegr3qwcfgsx/r0024zgp9rt.html?ptag=4_5  比如这个新剧

在那天的中午到下午3点之前，我测试的时候，
获取的m3u8地址，下载下来后，视频无法播放，【很确定，我测试了好几次，】

然后晚上我在测试，打开视频，获取m3u8 正常下载 正常播放了。

至于为什么我就不知道了，哟个群友他也是这样，用会员号获取的m3u8 下载后无法打开，好像是加密了

昨晚又出现了这个情况···

**Comment by nobadboy** [comment]
@lki2019  腾讯的m3u8只有用html5播放器才能抓到，而且不是所有宽带都能抓到，我测试大部分电信应该都可以，少部分移动可以 ，其他没有测试，还有你讲的加密是vip视频有加密，免费的都没有，确实m3u8不限速而且新剧基本没有水印。下面可以提供接口供测试
https://vv.video.qq.com/getinfo?callback=txplayerJsonpCallBack_getinfo_27080&&charge=1&vid=y00240ny2xe&defaultfmt=auto&otype=json&guid=e18040bca0a5fc82b48c971b02ce1fe7&platform=10201&defnpayver=1&appVer=3.2.162&sdtfrom=v1010&host=v.qq.com&ehost=https%3A%2F%2Fv.qq.com%2Fx%2Fcover%2Fg7jpq0qd0k8xdca%2Fj00224hjd08.html&sphttps=1&_rnd=1502434938&spwm=2&unid=e5459016b44e1035b62080fbd48ad00a&defn=fhd&fhdswitch=0&show1080p=1&isHLS=1&dtype=3&sphls=1&newplatform=10201&defsrc=2&_qv_rmt=N82iiNltA10443tw7%3D&_qv_rmt2=SV2RB0nh152398AJw%3D&_1502434938950=

**Comment by zhangn1985** [comment]
写成这样，没啥道理，因为搞不出来，或者搞出来了也没意义。腾讯视频的话题就此打住，除非你能解决腾讯视频所有区块的算法，不然都是有的限速，有的又不限速。
