### ISSUE TITLE
b站分段视频不能正确解析其它分段地址，都解析成第1段

### ISSUE THREAD

**Issue by andysendo** [zhangn1985/ykdl#195]
样例：http://www.bilibili.com/video/av12579880/?from=search&seid=5099387751167427295#page=2

地址转换成http://www.bilibili.com/video/av12579880/index_2.html可以正确解析。我自己通过bash脚本将字符串 ?from=search&seid=5099387751167427295#page=n  转换成 index_n.html，ykdl源码不知道从哪里改合适。

建议修改之。

**Comment by andysendo** [comment]
b站分段视频还有一种格式，如 http://www.bilibili.com/video/av11772163/#page=2
也可以将字符串 #page=n 替换成 index_n.html 的格式后正确解析视频。

**Comment by rosynirvana** [comment]
20f8bda
