### ISSUE TITLE
关于 pycrypto

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#198]
[pycrypto](https://github.com/dlitz/pycrypto) 的最新 stable 2.6.1 发布于 [2013-10-15](https://github.com/dlitz/pycrypto/releases)/[2014-06-20](https://pypi.python.org/pypi/pycrypto)，最后的 commit 时间是 2014-06-21

看起来作者已经放弃了这个项目 https://github.com/dlitz/pycrypto/issues/238

是不是有必要考虑一下这个提议了
https://github.com/zhangn1985/ykdl/issues/142#issuecomment-307789178
> @zhangn1985 要不要把非win上面也换成pycryptodome，看来有时候编译是会有困难的

**Comment by zhangn1985** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891619

因为debian 使用了错误的pycryptodome，所以，在已经安装了任意pycrypto的设备上，不再要求安装，
否则再要求安装pycryptodome

再调查redhat 系列。
