### ISSUE TITLE
pip安装的最新版没法用

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#20]
```
python -m ykdl -i http://www.iqiyi.com/v_19rr9h0t5g.html
D:\PortableApps\Python\python.exe: No module named ykdl.__main__; 'ykdl' is a package and cannot be directly executed
```

**Comment by zhangn1985** [comment]
请直接 `ykdl -i http://www.iqiyi.com/v_19rr9h0t5g.html`

`ykdl.__main__` 已经移除了。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/fc251875094c162d10426e228a3633159f9c1699  是这个改动导致的。有意为之。

@mengmo 你的python是怎么安装的？PortableApps? 你的python安装目录可有Scripts？ 安装版的python，是可以直接通过`ykdl`来运行的。

**Comment by zhangn1985** [comment]
注意：python安装目录下的Scripts目录必须在PATH变量中，.py要在PATHEXT变量中。
如下：

```
C:\Documents and Settings\new>echo %PATH%
C:\Python34\Scripts;C:\Python34\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem

C:\Documents and Settings\new>echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PY

C:\Documents and Settings\new>

```
具体怎么绣稿环境变量Google/Baidu吧。

**Comment by mengmo** [comment]
@zhangn1985
`Python`我是先安装，将安装目录打包以后卸载。再解压到`portableapps`目录下，然后修改环境变量。
个人不喜欢第三方软件修改注册表及向系统盘写文件，所及只要能满足需求，基本上都是用的`portable apps`
按照你的操作要求试了之后，发现还需要设置`.py`的文件关联，也不清楚还有坑没了。不打算继续试了

**Comment by mengmo** [comment]
@zhangn1985 顺便问个题外话，知道python的安装包是哪种打包格式么？本来我是打算直接手动解开python的安装包搞portable的，结果搜了好长时间，试了不少工具都不行。

**Comment by zhangn1985** [comment]
我对安装包这个不了解。只是知道python35是MSI。这个问题就关了哦。

**Comment by mengmo** [comment]
既然把这个问题发这儿了，我就把找到的答案也给出来（终于知道了，不发出来岂不是对不起花费在这上的时间）
`python`的安装包用的是叫做`WiX Toolset`的东东
顺便吐个槽：最讨厌这种`exe`里带`msi/cab`的。
`installer`我还是青睐`inno`

**Comment by zhangn1985** [comment]
:+1:
