### ISSUE TITLE
不支持熊猫星颜？

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#200]
刚发现星颜的直播不能下载，是不支持还是别的原因？

**Comment by mengmo** [comment]
目前不支持

**Comment by rosynirvana** [comment]
就在静态页上
```js
window.HOSTINFO = {
    "roominfo": {
        "rid": "82745120",
        "xid": 60626,
        "name": "Una \u6c42\u5b88\u62a4\u5b9d\u5b9d\uff5e",
        "notice": "",
        "photo": "\/\/i1.cdn.xiongmaoxingyan.com\/dda9b0eebc4810a9ba2bc897523ba452.jpeg",
        "picture": "",
        "playstatus": "1",
        "status": "0",
        "lock_reason": null,
        "personnum": "40104",
        "starttime": "1504774518",
        "endtime": "1504636402",
        "label": ["1", "4"],
        "shareimg": "https:\/\/i.ssl.pdim.gs\/dmfd\/100_100_70\/18eb353d60d9efc2ce79e0b0460a9bc6.jpg"
    },
    "videoinfo": {
        "streamurl": "http:\/\/flv-live-qn.xingyan.panda.tv\/panda-xingyan\/591d414b3fdcb5fb9b4dd2102e287752.flv",
        "hlsurl": "http:\/\/hls-live-qn.xingyan.panda.tv\/panda-xingyan\/591d414b3fdcb5fb9b4dd2102e287752.m3u8"
    },
    "hostinfo": {
        "rid": "82745120",
        "nickName": "\u5c0f\u4f18\u5a1cUna",
        "avatar": "https:\/\/i.ssl.pdim.gs\/dmfd\/100_100_70\/18eb353d60d9efc2ce79e0b0460a9bc6.jpg",
        "xid": "60626",
        "gender": "2",
        "signature": "\u5979\u53ef\u7231\u7684\u53d1\u75af\u3001\u7c89\u4e1d\u7fa4\uff1a390090924",
        "is_anchor": "1"
    },
    "leftads": [{
        "title": "pc\u793c\u7269\u5468\u699c",
        "img": "\/\/i0.cdn.xiongmaoxingyan.com\/0934bc9818b602814a1b28a58459bf59.jpeg",
        "linkurl": "\/\/xingyan.panda.tv\/activity\/pandaWeekly.html"
    }]
};
```

**Comment by jyuan15** [comment]
看不懂，IDM能捕捉媒体下载，但无法中途停止。

**Comment by mengmo** [comment]
@rosynirvana
可否告知下你用的什么工具？
我搞出来的都长这样
`<script>window.HOSTINFO={"roominfo":{"rid":"77755600","xid":66121,"name":"\u4e0b\u5348\u597d\uff5e","notice":"","photo":"\/\/i0.cdn.xiongmaoxingyan.com\/8602556f8f874bb164d1f93133c3adb2.jpeg","picture":"","playstatus":"1","status":"0","lock_reason":null,"personnum":"9869","starttime":"1504778757","endtime":"1504775260","label":["1"],"shareimg":"https:\/\/i.ssl.pdim.gs\/dmfd\/100_100_70\/34abc96b40861d2aa27d7e69a39336de.jpg"},"videoinfo":{"streamurl":"http:\/\/flv-live-qn.xingyan.panda.tv\/panda-xingyan\/2e3e48226d8e4c46f97c71f933ebfe44.flv","hlsurl":"http:\/\/hls-live-qn.xingyan.panda.tv\/panda-xingyan\/2e3e48226d8e4c46f97c71f933ebfe44.m3u8"},"hostinfo":{"rid":"77755600","nickName":"\u5c0f\u73bb\u7483\u513f","avatar":"https:\/\/i.ssl.pdim.gs\/dmfd\/100_100_70\/34abc96b40861d2aa27d7e69a39336de.jpg","xid":"66121","gender":"2","signature":"\u7c89\u4e1d\u7fa4164648636 \u5fae\u535a:\u5c0f\u73bb\u7483\u513f","is_anchor":"1"},"leftads":[{"title":"pc\u793c\u7269\u5468\u699c","img":"\/\/i0.cdn.xiongmaoxingyan.com\/0934bc9818b602814a1b28a58459bf59.jpeg","linkurl":"\/\/xingyan.panda.tv\/activity\/pandaWeekly.html"}]};</script><!--lastplaytime:1504778757|1504775260-->`

**Comment by rosynirvana** [comment]
从页面里copy出来
然后用```js-beautify```处理一次

**Comment by mengmo** [comment]
@rosynirvana
多谢！
http://jsbeautifier.org/
挺方便的

**Comment by rosynirvana** [comment]
还有个python包
