### ISSUE TITLE
虎牙 不能下载

### ISSUE THREAD

**Issue by TaoziDB** [zhangn1985/ykdl#206]
http://www.huya.com/s7

http://hls.yy.com/newlive/78941969_2559461593_100571200.m3u8?org=huya&appid=0&uuid=0e6add60f62b499e9d62af6894a4b004&t=1507540146&tk=2ee414a3f77349b1c4f1ee20fd002ad1&uid=0

**Comment by lki2019** [comment]
可以下载啊，

00_5783644687908495591_163602733_1507736658_8500_10057.ts?org=huya&uuid=d587a5cb
57a443a2b3c1378e60573446&seq=41859821&tk=182edc8654215e3856c5dcc294f1f067&tc=0&r
=1280x720' for reading
frame= 2159 fps= 33 q=-1.0 Lsize=   10582kB time=00:01:11.96 bitrate=1204.7kbits
/s speed=1.11x
video:10312kB audio:200kB subtitle:0kB other streams:0kB global headers:0kB muxi
ng overhead: 0.667286%

**Comment by lki2019** [comment]
ykdl  http://www.huya.com/s7

**Comment by TaoziDB** [comment]
ykdl http://www.huya.com/s7
site:                Huya Live (虎牙直播)
title:               S7全球总决赛10月8日重播
artist:              S7英雄联盟全球总决赛
streams:
    - format:        current
      container:     m3u8
    # download-with: ykdl --format=current [URL]
Now downloading: S7全球总决赛10月8日重播_2017-10-11T13-36-21.179116.mp4
stop downloading by press 'q'
[http @ 0000000000f47de0] HTTP error 404 Not Found
http://hls.yy.com/newlive/78941969_2559461593_100571200.m3u8?org=huya&appid=0&uuid=9b5bedd59c9c4455b59fa75ed3cdfff4&t=1507743380&tk=5c4d2f6db772becb0a605e04dc415f3b&uid=0: Server returned 404 Not Found
