### ISSUE TITLE
乐视的能解析1080p的吗？

### ISSUE THREAD

**Issue by 448Lucario** [zhangn1985/ykdl#207]
在提交前，请确保您已经检查了以下内容!

- [* ]你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [* ] 您的`ykdl`为最新版。
- [ *] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ *] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ *] 本问题确实关于`ykdl`，而不是其他项目。

> [您的内容]
我下载时选择了1080p，不过最后下好的还是超清的

**Comment by zhangn1985** [comment]
乐视的问题，假冒的1080p

**Comment by zhangn1985** [comment]
或者1080p是VIP专享

**Comment by 448Lucario** [comment]
1080p确实是要会员才能看的，我试的几个视频应该是有1080p的。这个有可能解决吗？优酷爱奇艺的1080p也是要会员才能看，但是都可以获取到地址
