### ISSUE TITLE
计划移除ffmpeg的依赖，改用mpv。

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#210]
mpv作为默认支持的播放器，自带视频合并转换功能，计划用它来替换ffmpeg。
另外计划添加参数：
--mpv-path 默认值为当前目录（windows）/空白（Linux），并影响下面 --player的搜索路径
-p/--play 为布尔参数，改变ykdl为直接播放
--player 为自定义播放器，默认为mpv

**Comment by zhangn1985** [comment]
依赖： https://github.com/mpv-player/mpv/issues/4982

**Comment by mengmo** [comment]
直播流是`flv over http`的，没必要用第三方工具吧？
