### ISSUE TITLE
希望支持优酷播单（播放列表）网址

### ISSUE THREAD

**Issue by jerry011235** [zhangn1985/ykdl#217]
发现一个脚本，应该对下载优酷播放列表有用，希望集成到ykdl里。
https://github.com/wwqgtxx/wwqLyParse/blob/master/wwqLyParse/parsers/youkulistparser.py
https://github.com/wwqgtxx/wwqLyParse/tree/master/wwqLyParse/parsers

**Comment by S-Kee** [comment]
希望支持列表，一个一个下载太麻烦了。
