### ISSUE TITLE
调用mpv播放斗鱼直播的问题

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#218]
这个现象目前只发现在播放斗鱼时存在，mpv开始播放时，下面的进度条会快速加载，几秒就加载完，然后mpv就退出了。播放其他网站视频，进度条不会加载。

![2017-10-30_131543](https://user-images.githubusercontent.com/12642186/32156021-d8d44c80-bd75-11e7-95a3-6b3c443be5a2.jpg)

翻了下issues，发现是youtube-dl引起的，要么卸载youtube-dl，要么在调用命令中加一个“--no-ytdl”，mpv才不会退出。
能不能把“--no-ytdl”加到ykdl中，免得每次都要去输入。。。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/blob/master/ykdl/util/wrap.py#L25

**Comment by zhangn1985** [comment]
要么就是 douyu解析出问题了。

**Comment by jyuan15** [comment]
找到原因了，看了下安装目录的wrap.py文件，里面没有“--no-ytdl”。问题是ykdl是今天才装的最新1.5.2版，可能是因为用pip install ykdl安装的原因。

用下载zip的方式重新安装一遍，现在已经正常，不会退出了。

**Comment by zhangn1985** [comment]
可能是你安装了多个ykdl. pip 安装升级要加`--upgrade`
