### ISSUE TITLE
可以下载vip的吗。。

### ISSUE THREAD

**Issue by 937686912** [zhangn1985/ykdl#221]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by zhangn1985** [comment]
没有计划支持VIP。如果购买了VIP想使用第三方工具下载，请用 https://github.com/soimort/you-get

**Comment by 937686912** [comment]
you-get能得到的不如你这个多。希望有可能的话ykdl能支持购买了vip的下载 在2017年11月05日 16:10 ，zhangn1985写道： 没有计划支持VIP。如果购买了VIP想使用第三方工具下载，请用 https://github.com/soimort/you-get — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
