### ISSUE TITLE
最新版 mpv 内置播放参数有问题

### ISSUE THREAD

**Issue by andysendo** [zhangn1985/ykdl#223]
最新版ykdl/util/wrap.py包装的mpv参数 "--no-ytdl"导致mpv播放失败，错误为"bad option..."。

参数"--merge-files"最好别默认，有些网站限速而视频分段很多时会等待很长时间(几十秒以上)，影响用户体验。播放直播视频--merge-files会导致mpv播放失败。

另外近期发现mpv播放youku视频，约几分钟后播放就停止了，以前没这事。ykdl下载和在线播放没问题。mpv加个什么交互参数？

**Comment by mengmo** [comment]
`youku`解析到的地址好像有效时间只有10分钟的样子，这是`youku`的限制，应该无解
`--no-ytdl`应该不会导致播放失败的，至少我这儿是没问题。
所以，能贴上用例么？不然怎么定位出错的原因

**Comment by SeaHOH** [comment]
可以自己控制合并数量，不使用 `--merge-files` 参数，尽量保持在 10 分钟内缓冲完最后一段。
```py
def launch_player(player, urls, **args):
...
        urls_len = len(urls)
        if urls_len > 1:
            playlist = []
            n = 1
            n_max = 2 if args['site'] == u"优酷 (Youku)" else 5 # 这个就是最大合并数量
            edl = 'edl://'
            for i in range(urls_len):
                url = urls[i]
                if n == 1 and i + 1 == urls_len:
                    playlist.append(url)
                    break
                edl += '%{}%{};'.format(len(url), url)
                n += 1
                if n > n_max or i + 1 == urls_len:
                    playlist.append(edl)
                    n = 1
                    edl = 'edl://'
            urls = playlist
...

def handle_videoinfo(info, index=0):
...
    player_args['site'] = info.site
...
```

**Comment by zhangn1985** [comment]
@andysendo  "--no-ytdl" bad option 是因为你编译的mpv没有使能ytdl或者没有使能lua。

--merge-files导致性能下降对于你说的情况有可能。

**Comment by jinlich** [comment]
@SeaHOH 
def launch_player(player, urls, **args):
...
        urls_len = len(urls)
        if urls_len > 1:
            playlist = []
            n = 1
            n_max = 2 if args['site'] == u"优酷 (Youku)" else 5 # 这个就是最大合并数量
            edl = 'edl://'
            for i in range(urls_len):
                url = urls[i]
                if n == 1 and i + 1 == urls_len:
                    playlist.append(url)
                    break
                edl += '%{}%{};'.format(len(url), url)
                n += 1
                if n > n_max or i + 1 == urls_len:
                    playlist.append(edl)
                    n = 1
                    edl = 'edl://'
            urls = playlist
...

def handle_videoinfo(info, index=0):
...
    player_args['site'] = info.site
...
这段代码放哪里？？

**Comment by SeaHOH** [comment]
@jinlich 不会改也不用在意，分开播放也挺好，不容易出状况。
