### ISSUE TITLE
新开了一个坑，webykdl，大家先凑合用吧。

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#224]
在远程：
1， pip3 install ykdl flask 
2， 安装mpv
3，下载web.py, 打开一个终端，运行`python3 web.py&`

在本地：
curl -X PUT  http://远程IP:5000/play --data-urlencode "url=video url"

目前如果不播放完毕，curl不会退，等以后更新，或者你们谁提个patch吧。

**Comment by huzy0909** [comment]
@zhangn1985 这个是什么意思？看不懂，不会用，能不能再说详细一点啊：）

**Comment by zhangn1985** [comment]
比如说你有一台下载机，或者树梅派。
这个东西可以让你在远程控制它来播放一个视频。

**Comment by huzy0909** [comment]
谢谢，目前还用不到这个，用到了再好好学习下

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/wiki/HOWTO-Webykdl
