### ISSUE TITLE
ykdl下载腾讯视频时，进度一直为0%

### ISSUE THREAD

**Issue by huzy0909** [zhangn1985/ykdl#225]
在腾讯视频下载《急诊科医生_01》 https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html

**1、在用you-get https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html 直接下载时，速度只有 28 kB/s**
[E:\dsj]$ you-get https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html
Site:       QQ.com
Title:      急诊科医生_01
Type:       MPEG-4 video (video/mp4)
Size:       716.73 MiB (751542385 Bytes)
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 急诊科医生_01.mp4 ...
 0.1% (  0.5/716.7MB) ├─────────────────────────────────────────┤[1/8]   28 kB/s

**2、用ykdl  https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html 直接下载时，进度一直为0%。**
[E:\dsj]$ ykdl  https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html
site:                腾讯视频 (QQ)
title:               急诊科医生_01
artist:              None
streams:
    - format:        HD
      container:     mp4
      video-profile: 高清mp4
      size:          191.1 MiB (200342325 bytes)
    # download-with: ykdl --format=HD [URL]
Download: 急诊科医生_01_HD
   0%

**3、用you-get -u 可以获取到1080格式的真实地址**
[E:\dsj]$ you-get -u https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html
Site:       QQ.com
Title:      急诊科医生_01
Type:       MPEG-4 video (video/mp4)
Size:       716.73 MiB (751542385 Bytes)
Real URLs:
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.1.mp4?vkey=925F6881587FF1EB50E8067B0A6A97EAD3A0D118D4AA33851A74CB9D122799BE88124FF73A88C9E55AAB0ED48C8ECAEA9491366BFB0F66F1847DA8EB8799FEDBE07170D2AFD70C2A25F5FAB3CBF73B645C85FF8F169A46FAB184D81A89501592
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.2.mp4?vkey=904139DC28FDDDDEBC624704EB89FEC12B104FE83AE7330B4B5BEDA851ECBBE37011D67CBAB2F2BE42FDB84569EB12AEB7DA42BADCDC1E91DF7D1D20A750DE841CDF16E9AE19BA1B955628CB3E75C9D31135125DBC7A30BED84C859364726E00
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.3.mp4?vkey=B7A6B2480FBE7E275560638381A3D251122BCB22DEF4FD773C152D90FB60F0E944C3D5412D15916DF95B7651AC742662290DA8C1E2A26FE999D39AF29DC00FBA14AD1BC3E3D739DFC4744174B40E8C7B777AE3582349E3BD5AF4DB8136EE1F6D
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.4.mp4?vkey=FEDD0D9334FA6C6A9351711DD21110D1311B88217C1F66C301E5FF34E1E9F2E03DF5A2FEAB383BCCAF636F07FEBF4F9BFC00D25D1C2223B61F0043FC03CF2D42154169A548FA684DF96334A0C18FDA418C108B778C5E22955A88CEA4040FD882
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.5.mp4?vkey=48EDAE2E285655DD59CE773BF546D66AD2C6DB919E2CDD0FA7259FFDF5BDD3645B5578D199D2983B01504F0B5DD4FF31CAB2ED4045C68F86CB37D200473DA3FCD9987423432304B20DC62791414DFAF1FB383D7A31A036A3AE604EFC225C63E0
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.6.mp4?vkey=5A54016AAB2A75A6F37A6BE76E7A971F6EC893BD1165543CE02FFC7768E8283E15DF0C737A361C3EADC179631D918D04A1FA45FDEE0939AB60B9FB9287868397D0862BE0D5C0A0D3447C4995F3A7BB919C1A49F5765E16A44BC7C0E4D4555A75
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.7.mp4?vkey=4BC7D1BE8E5CD8B2935DE4E2D12C0A0DB0F3A53EAECB604EA7D3FFE836540A4E1127FA808384D1D2627CECA07FDE055BD5A127317EE0B30F1E39C6B45D946220D50D09F71A97A65870653F2B2EE3943957E2A0595E03B2065020591CCB7A77D9
http://59.49.45.17/vlive.qqvideo.tc.qq.com/ARhYrgII480d5xox7c39uVQ4Op-mYrT6wmMFQJiB3vts/k0025re2d8o.p209.8.mp4?vkey=EF11008497DFCDCEFCC84AE9ECA548D16CA0C8FFB8792AD5EE5E6AB0213CE079ABA61143435F112EF6F53CB32FE5A9A3EEAAB4A850D40EA6758E06B2126236F7FFED981786BFA69842F64DDF4F98A589CA3A86EB21A06A0881B64D328E79BDA7

**4、再用IDM进行批量下载，发现8段视频可以同时被下载，每一段视频速度都基本稳定在240 kB/s左右，下载时每一段视频开8个线程,，再看you-get下载时的28 kB/s，刚好有一个8倍的关系,，我试好几个，都是这样的情况，能否实现用you-get -u的方式获取所有分段视频的真实地址,再对所有分段同时下载，每一段都开启8个线程，这样的话下载速度就会很快。我不会编程，说的不对请不要笑我：）**

**Comment by mengmo** [comment]
https://github.com/zhangn1985/ykdl/wiki/sites-status

> 对QQ视频的说明：据分析，QQ将旗下视频分为了多个区，每个区有不同的Ckey种子都不一样。而QQ对错误的Ckey非常宽容，于是空的Ckey也能得到正确的视频地址，但是被限速了。
> 
> 现在问题来了，每个尝试解析QQ视频的人都只能得到其中一个区的算法，而这个算法应用与另一个区就是一个低速链接。所有尝试修复QQ的行为都会被证明为无效。
***
@zhangn1985
顺便我想问一下：「每个区有不同的Ckey种子都不一样」这里边的「**种子**」是什么意思？

**Comment by zhangn1985** [comment]
很久之前研究的，现在都忘记了。

**Comment by huzy0909** [comment]
我试了好多个电视剧，电影 you-get  u  都能好的获取每一段视频的真是地址， 有了真实地址，用IDM，迅雷都可以下，在YKDL里开启多线程下载，能不能实现，我想的简单啊 ：）

**Comment by zhangn1985** [comment]
@SeaHOH 感觉你刚提的两个patch很给力！！速度上去了，有100K/s

**Comment by SeaHOH** [comment]
但是把其它搞砸了，正在研究……

**Comment by SeaHOH** [comment]
这回好像对了，先用着。

**Comment by huzy0909** [comment]
嗯，现在可以下载了，不过速度还是不快，我把下载的情况发出来，这应该是前4段视频被同时下载，每一段我不知道开了几个线程，跟IDM下载时做个对比

λ ykdl  https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2d8o.html
site:                腾讯视频 (QQ)
title:               急诊科医生_01
artist:              None
streams:
    - format:        BD
      container:     mp4
      video-profile: 蓝光
      size:          715.4 MiB (750104418 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 急诊科医生_01_BD part 0
Download: 急诊科医生_01_BD part 1
Download: 急诊科医生_01_BD part 2
Download: 急诊科医生_01_BD part 3
   5%

![qq 20171119150858](https://user-images.githubusercontent.com/33674729/32988272-a490d7ce-cd3b-11e7-9b14-9d50fc1c9eb7.png)

![ykdl-idm2](https://user-images.githubusercontent.com/33674729/32988256-355457a0-cd3b-11e7-8202-21886b77e862.png)

](url)

**Comment by SeaHOH** [comment]
4 任务 x 1线程 vs 8 任务 x 8线程，每线程大约 30KB/s，很稳定。
我这儿略慢。

**Comment by huzy0909** [comment]
嗯，是的，单线程30KB/s速度超稳定， ykdl要是能开启 8任务 x 8线程 就好了，4任务 x 1线程 下载小视频还能用，下载1集1080的电视剧，就得等好久了

**Comment by zhangn1985** [comment]
这个要改好多，特别是任务中断回放。。。

**Comment by SeaHOH** [comment]
过几天有空时，我尝试增加单任务多线程，有参考代码，不是很复杂。

**Comment by huzy0909** [comment]
两位辛苦啦，从实用角度出发，我觉得ykdl最终的目标还是应该多任务多线程，以最大速度下载

**Comment by jyuan15** [comment]
pptv用这方法下载不到了，把解析出的地址添加到IDM后，文件类型显示为“错误”，前段时间都还可以下的。

**Comment by nobadboy** [comment]
腾讯现在不是有m3u8的api吗

**Comment by rosynirvana** [comment]
@mengmo 
简单随机数发生器f(x) -> y
y是得到的伪随机数；
x是环境中拿到的一个值，有时候叫做种子

**Comment by airdge** [comment]
各appver版本对应的ckey算法各不一样
有些cKey算法必须经过url或者guid行为上报才不会限速

碰上QQ不限速时候,使用getinfo/getkey解析出的链接也能正常下载播放
分段算法比较麻烦 建议解析M3U8

**Comment by hahawo** [comment]
C:\Users\Administrator>ykdl -i https://v.qq.com/x/cover/g7m84rhikqkd772/k0025re2
d8o.html
site:                腾讯视频 (QQ)
title:               急诊科医生_01
artist:              None
streams:
    - format:        BD
      container:     mp4
      video-profile: 蓝光
      size:          715.4 MiB (750104418 bytes)
    # download-with: ykdl --format=BD [URL]
Real urls:
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.1.mp4?stdfrom=v1090&type=mp4&vkey=36B03422D1403888D
73F234A81CE46C3AA6E763612A73719D4B9610F9DAB8E66118066702595CC036AF6D0683DD7FE572
1F7870859C6648AB7DDA92326EC265DE592EA71303FA2F293BD33DDD852288CDA515DE323FA5AF11
D5320D9446754F9&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.2.mp4?stdfrom=v1090&type=mp4&vkey=8350CE4767E03DA35
04C2E13B91BC2CF1385D9A26F0421697D8F6C2083A23937B649B97C7E40B391EBA2064030A1BCC61
AB5D6FE991CFA78205CF318263C0958B9183D3E7CC3DC62EC9A9AF7724BFC39FE41C8BD95BC17413
E3669AFB518B3E8&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.3.mp4?stdfrom=v1090&type=mp4&vkey=EE51A203DBE0F7D51
9AEDE4C909474562028834955BC3F8DB252E4B2F474F28F6BE0E7A54B5A91B0FCF3D14C95A25475C
56C940745C9D13FCF3CFA76370D1F80E5602B648E0B5D24DC98F39459ACC5DCB021F38CE1A9A7EA8
05F018ED666B009&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.4.mp4?stdfrom=v1090&type=mp4&vkey=26CC47B65C6C40577
9A2BBBBD0F3ACC46456E469FE0BD7E244B97D1FD4933DD372443BC9941E3A8BF931330712FB9C91E
FBC112452E639ECC1E0AF56E3E7580EEF3D86FC1347D07600F89912CB301F2337A0211B4A433D4D7
5684AE2642B179C&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.5.mp4?stdfrom=v1090&type=mp4&vkey=8350CE4767E03DA35
04C2E13B91BC2CF1385D9A26F042169BE3348CBC4D8975B95D7770D694F681F74522489D8BD48521
5CB0A8CBAEA176783F4B496B20B1226B0D28112887AA75F43346CAE450F5AC002279C9D1F3556BFA
793CC763DEB9EBC&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.6.mp4?stdfrom=v1090&type=mp4&vkey=0AD9583A7EA0CE4BA
0FB2AB9F535FFCD8296E56D851EB753D538B8B0BD4BEEDB30FF6081DEE5D06B81872107DC21A4998
700917C67B398DC9F3758E5F6E97B860B1BE2580D5FC3D0D6F5B0B8A65A4EA42CF1821E50964B245
01EDF9E0B795DA2&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.7.mp4?stdfrom=v1090&type=mp4&vkey=6A5B26608CDA0229D
73174967F296D595A140B6218F30747EBF36999D944609879EDB4EAAAAAC60FB49BE3DE655BADE0E
EAE15D1D4F04CFE5F3948AB32149A8032DFBA3A48E36151500C71CF69825B9427D6B344121426C45
A9BDBC7C6C33AF1&level=0&platform=11&br=154&fmt=fhd&sp=0
http://101.227.216.146/vlive.qqvideo.tc.qq.com/ABvnp3wQDER8X-DdvFuyUiKeq59-RACYu
Z2GSWrsEO_I/k0025re2d8o.p209.8.mp4?stdfrom=v1090&type=mp4&vkey=26076E060BEAAA471
D0A7DEAC54C6E1CE072F1BA7751890269908E007DAF45B016E53B164D7BC476DBC266CDD74A9B458
2B240C548FE944AA74334048371841C1188CB3D1A613E49709CC9A021C6B9F60571F1933EC9880C3
471B41E2744E843&level=0&platform=11&br=154&fmt=fhd&sp=0--
不能用idm抓取为什么
