### ISSUE TITLE
[QQ] ip-copy limit

### ISSUE THREAD

**Issue by SeaHOH** [zhangn1985/ykdl#226]
随机测试时发现的，不知道只是我这个 IP 的问题还是其它原因。
http://vv.video.qq.com/getinfo?otype=xml&appver=3.2.19.333&platform=11&defnpayver=1&vid=f01801ute67
视频地址是 http://v.qq.com/x/page/f01801ute67.html
```xml
<root>
    <em>80</em>
    <exem>10</exem>
    <ip>***.***.***.***</ip>
    <msg>ip-copy limit</msg>
    <s>f</s>
    <exinfo>中国-***</exinfo>
</root>
```

**Comment by huzy0909** [comment]
我的IP是国内的
第一个地址打开以后显示这样
第二个视频本身违规，不能播放，我是腾讯会员，
![11](https://user-images.githubusercontent.com/33674729/32988311-62eb11b2-cd3c-11e7-9801-98e3b660ee2b.png)
![2222](https://user-images.githubusercontent.com/33674729/32988312-67b5b1ac-cd3c-11e7-8272-f170d6bed01d.png)

**Comment by SeaHOH** [comment]
哦，忘了开 javascript，没看见。 :sweat:
