### ISSUE TITLE
分段视频下载失败后重试

### ISSUE THREAD

**Issue by letlet** [zhangn1985/ykdl#227]
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> m3u8格式的视频可能会分为几百段，分段下载时会出现：
ERROR:downloader:downloader failed at part 39
ERROR:downloader:downloader failed at part 48
ERROR:downloader:downloader failed at part 76
类似这样的错误，提示某几段视频下载失败，导致ffmpeg合并视频时出现： Impossible to open xxxx 。 导致视频合并失败。
请问有无可能某段视频下载失败时重新尝试下载该段视频？

**Comment by zhangn1985** [comment]
在失败后，不会触发ffmpeg合并的。再次下载只会下载出错的几段。

**Comment by letlet** [comment]
我的意思是ykdl第一次下载失败时，ykdl会自动记录哪几段下载失败，并重新下载之前下载失败的几段视频。因为可能有这种使用场景，早上下班前批量下载电视剧，下班后回家投射到电视上看，中间如果下载失败了也不知道是哪个下载失败，要把几十集电视剧重新过一遍会比较费时间。

**Comment by huzy0909** [comment]
@letlet 你重新运行你下载的的命令就可以了，ykdl会自己忽略已经下载的，下载失败的会重新下载，然后下载完再合并
