### ISSUE TITLE
优酷无法正常解析

### ISSUE THREAD

**Issue by yutianzeabc** [zhangn1985/ykdl#228]
在提交前，请确保您已经检查了以下内容!

- [*] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [*] 您的`ykdl`为最新版。
- [*] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [*] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [*] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

CRITICAL:YKDL:客户端无权播放,201

包括所有优酷视频，网页可播放，版本为最新。

**Comment by mengmo** [comment]
https://github.com/soimort/you-get/issues/2506#issuecomment-346067480
本项目的话，改这儿
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/youku.py#L29

**Comment by zhangn1985** [comment]
改多少呀？

**Comment by SeaHOH** [comment]
忘了引用了……
