### ISSUE TITLE
能下载优酷.腾讯,爱奇艺的VIP资源吗

### ISSUE THREAD

**Issue by mcyt** [zhangn1985/ykdl#233]
youget不行
爱奇艺405免费的出现[error]oops,something went wrong
优酷,客户端无权限
腾讯[error]oops,something went wrong

不知道ykdl可不可以
...
小白!

**Comment by zhangn1985** [comment]
不可以。没计划支持。

**Comment by zhangn1985** [comment]
谢谢你对ykdl感兴趣。

**Comment by mcyt** [comment]
那大哥,你知道有什么方法吗

**Comment by zhangn1985** [comment]
主要是VIP下载坏了视频站的规矩，会被警告的。
