### ISSUE TITLE
Youku Tudou 不能用

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#234]
不能http://v.youku.com/v_show/id_XNDA5NzcyODY4.html?f=18523035

土豆不能下载 http://video.tudou.com/v/XMTc5ODcwMTAwOA==.html

**Comment by zhangn1985** [comment]
得到最小API:
```
curl 'http://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/?jsv=2.4.10&appKey=23536927&t=1511950880997&sign=f12f4e832c9e754702576cd52b2f6b7f&api=mtop.youku.play.ups.appinfo.get&v=1.1&timeout=20000&YKPid=20160317PLF000211&YKLoginRequest=true&type=json&data=%7B%22steal_params%22%3A%22%7B%5C%22ccode%5C%22%3A%5C%220502%5C%22%2C%5C%22client_ip%5C%22%3A%5C%22192.168.1.1%5C%22%2C%5C%22utid%5C%22%3A%5C%22oqikEO1b7CECAbfBdNNf1PM1%5C%22%2C%5C%22client_ts%5C%22%3A1511950880%2C%5C%22ckey%5C%22%3A%5C%22099%23KAFEmEEKEcIEIETLEEEEE6twScJ4D6VcDrB5V6PqS9l4n6DJDuRIV6N1ZXl7D6Dc%2FGFETKxqAjFJE7Eht3BlluZde7FE54Ej6fmqkUA6mGPVWwMai5GRvkxd0xEqBDdp03NDRSAcJGG%2Bs86akmL2a8%2BSo87IiqCcpO6SytYfkPPNlkQbJ5OXnJCdfkI21gDpoR0YoN4IwIWJE7TIbvs5Ai7WadVE99r6HsC6wQG3uz8nPvD3%2BMWdSsrBwqrKCKvLUz8HAG078fZerS51E7JW4LeZaoa3aWxXNVo7L7uqUMuAPGDtO7FEp3iSlllP%2F3iSt37qtuZdt8nStTwlsyanDliSF3lP%2F39Bt37qtuZdtgFfE7EIt37E9XOnLsC%2FE7EhtloFT6%2BRJGFETRpCD6xmE7EFt37EFE%3D%3D%23107%5C%22%7D%22%2C%22biz_params%22%3A%22%7B%5C%22vid%5C%22%3A%5C%22XMzE3OTQzMDUwNA%3D%3D%5C%22%7D%22%2C%22ad_params%22%3A%22%7B%5C%22site%5C%22%3A1%2C%5C%22wintype%5C%22%3A%5C%22interior%5C%22%2C%5C%22p%5C%22%3A1%2C%5C%22fu%5C%22%3A0%2C%5C%22vs%5C%22%3A%5C%221.0%5C%22%2C%5C%22rst%5C%22%3A%5C%22mp4%5C%22%2C%5C%22dq%5C%22%3A%5C%22flv%5C%22%2C%5C%22os%5C%22%3A%5C%22linux%5C%22%2C%5C%22osv%5C%22%3A%5C%22%5C%22%2C%5C%22d%5C%22%3A%5C%220%5C%22%2C%5C%22bt%5C%22%3A%5C%22%5C%22%2C%5C%22aw%5C%22%3A%5C%22w%5C%22%2C%5C%22needbf%5C%22%3A1%7D%22%7D'  -H 'Referer: http://v.youku.com/' -H 'Cookie: _m_h5_tk=afe71857d85975bdfe689548f11f4590_1511953043662; _m_h5_tk_enc=ea02cd1c6fb4acd7eaf305f0e1414993;'

```

**Comment by zhangn1985** [comment]
data= 后面解码出来是
```
{"steal_params":"{\"ccode\":\"0502\",\"client_ip\":\"192.168.1.1\",\"utid\":\"oqikEO1b7CECAbfBdNNf1PM1\",\"client_ts\":1511950880,\"ckey\":\"099#KAFEmEEKEcIEIETLEEEEE6twScJ4D6VcDrB5V6PqS9l4n6DJDuRIV6N1ZXl7D6Dc/GFETKxqAjFJE7Eht3BlluZde7FE54Ej6fmqkUA6mGPVWwMai5GRvkxd0xEqBDdp03NDRSAcJGG+s86akmL2a8+So87IiqCcpO6SytYfkPPNlkQbJ5OXnJCdfkI21gDpoR0YoN4IwIWJE7TIbvs5Ai7WadVE99r6HsC6wQG3uz8nPvD3+MWdSsrBwqrKCKvLUz8HAG078fZerS51E7JW4LeZaoa3aWxXNVo7L7uqUMuAPGDtO7FEp3iSlllP/3iSt37qtuZdt8nStTwlsyanDliSF3lP/39Bt37qtuZdtgFfE7EIt37E9XOnLsC/E7EhtloFT6+RJGFETRpCD6xmE7EFt37EFE==#107\"}","biz_params":"{\"vid\":\"XMzE3OTQzMDUwNA==\"}","ad_params":"{\"site\":1,\"wintype\":\"interior\",\"p\":1,\"fu\":0,\"vs\":\"1.0\",\"rst\":\"mp4\",\"dq\":\"flv\",\"os\":\"linux\",\"osv\":\"\",\"d\":\"0\",\"bt\":\"\",\"aw\":\"w\",\"needbf\":1}"}'  -H 'Referer: http://v.youku.com/' -H 'Cookie: _m_h5_tk=afe71857d85975bdfe689548f11f4590_1511953043662; _m_h5_tk_enc=ea02cd1c6fb4acd7eaf305f0e1414993;'
```

**Comment by zhangn1985** [comment]
现在问题是`_m_h5_tk` 和 `_m_h5_tk_enc`怎么搞出来

**Comment by zhangn1985** [comment]
`ckey`也搞不出来。

**Comment by zhangn1985** [comment]
搞出`ckey`才是关键。

**Comment by zhangn1985** [comment]
目测差不多全站都要检查ckey了。

**Comment by jyuan15** [comment]
ccode=0501，就没有超清了，0406 就有超清，这是什么原因？

**Comment by zhangn1985** [comment]
0406我这里不能播放
0501是苹果设备上用的

**Comment by jyuan15** [comment]
手机上也装了ykdl和you-get，奇怪的是，you-get改了ccode有效，ykdl改了却无效。

**Comment by xukongop** [comment]
现在是报错201
CRITICAL:YKDL:客户端无权播放,201

**Comment by redstoneleo** [comment]
@jyuan15  手机上怎么装ykdl和you-get？

**Comment by jyuan15** [comment]
@redstoneleo 装termux

**Comment by zhangn1985** [comment]
在android 上安装要修改安装脚本。详见wiki

**Comment by mengmo** [comment]
@jyuan15 需要做什么额外的改动么？或者只要装好 compiler 就行？

**Comment by jyuan15** [comment]
@mengmo 指什么？

**Comment by mengmo** [comment]
@jyuan15 pycrypto 的编译

**Comment by jyuan15** [comment]
@mengmo 我是用termux 0.53安装的，可能需要root权限，但不确定。

首先 apt install  clang、python、python-dev、proot
然后 termux-chroot
最后 pip install pycrypto

**Comment by airdge** [comment]
第一次访问acs.youku.com就会生成_m_h5_tk 和 _m_h5_tk_enc的cookies
ccode一直变动,有些ccode只提供预览 有些是手机端的 所以有些是没有高清选项的
建议还是以开放平台ccode为主 
以开放平台ccode=0512为例 acs.youku.com是完全不需要ckey参数的
`http://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/?jsv=2.4.2&appKey=23536927&t=1512456800777&sign=0d79f04902ddee777f0ccba934ff9a18&api=mtop.youku.play.ups.appinfo.get&v=1.1&YKPid=20160317PLF000211&YKLoginRequest=true&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=%7B%22steal_params%22%3A%22%7B%5C%22ccode%5C%22%3A%5C%220512%5C%22%2C%5C%22client_ip%5C%22%3A%5C%22192.168.1.1%5C%22%2C%5C%22utid%5C%22%3A%5C%22YzCtEgZzfhECAXgihyVl3jHF%5C%22%2C%5C%22client_ts%5C%22%3A1512456800%7D%22%2C%22biz_params%22%3A%22%7B%5C%22vid%5C%22%3A%5C%22XMjk4NzA1OTMzNg%3D%3D%5C%22%7D%22%2C%22ad_params%22%3A%22%7B%5C%22needad%5C%22%3A0%7D%22%7D`
响应
` mtopjsonp1({"ret":["SUCCESS::调用成功"],"data":{"cost":0.07200000435113907,"data":{"preview":{"thumb":["http://g4.ykimg.com/0521000B599D900100000102D202A905","http://g2.ykimg.com/0521010B599D900100000102D202A905","http://g4.ykimg.com/0521020B599D900100000102D202A905","http://g4.ykimg.com/0521030B599D900100000102D202A905","http://g3.ykimg.com/0521040B599D900100000102D202A905","http://g1.ykimg.com/0521050B599D900100000102D202A905","http://g2.ykimg.com/0521060B599D900100000102D202A905","http://g1.ykimg.com/0521070B599D900100000102D202A905","http://g1.ykimg.com/0521080B599D900100000102D202A905","http://g3.ykimg.com/0521090B599D900100000102D202A905","http://g1.ykimg.com/05210A0B599D900100000102D202A905"],"timespan":"6000"},"controller":{"yi_plus":false,"download_disable":false,"app_disable":false,"new_core":false,"continuous":false,"share_disable":false,"is_phone_stream":"0","play_mode":2,"like_disabled":false,"stream_mode":1,"circle":false,"html5_disable":false,"video_capture":true},"dvd":{"audiolang":[{"vid":"XMjk4NzA1OTMzNg==","langcode":"ja","lang":"日语"},{"vid":"XMjk4NzA1OTE0NA==","langcode":"guoyu","lang":"国语"}],"notsharing":"0","point":[{"ctype":"story","start":"260150","title":"早起摸胸被撞见 褪衣照镜惊慌失措","desc":""},{"ctype":"story","start":"886497","title":"姐妹俩神社表演 宫水三叶酿口嚼酒","desc":""},{"ctype":"story","start":"1333778","title":"咖啡馆享用点心 餐馆打工手忙脚乱","desc":""},{"ctype":"story","start":"1777211","title":"翻笔记发现端倪 身体互换订下约定","desc":""},{"ctype":"story","start":"2306713","title":"立花泷约会前辈 心不在焉表现失常","desc":""},{"ctype":"story","start":"2625759","title":"彗星闪亮耀长空 划破天际夺目坠落","desc":""},{"ctype":"standard","start":"2640800","title":"","desc":""},{"ctype":"story","start":"2965406","title":"彗星坠落糸守镇 绝美小镇一夜倾覆","desc":""},{"ctype":"story","start":"3628221","title":"品尝口嚼酒摔倒 时光倒流往事重现","desc":""},{"ctype":"story","start":"3875712","title":"身体互换被发现 决心阻止小镇覆灭","desc":""},{"ctype":"standard","start":"4601870","title":"","desc":""},{"ctype":"story","start":"4627030","title":"时空交错终相见 甜蜜交谈虐心闪离","desc":""},{"ctype":"story","start":"5011404","title":"联手好友炸电厂 紧急疏散拯救镇民","desc":""},{"ctype":"story","start":"5282760","title":"彗星分裂成流星 场面壮观梦幻炫丽","desc":""},{"ctype":"story","start":"5952565","title":"地铁邂逅似相识 众里寻她泪问名字","desc":""},{"ctype":"cut","start":"6073629","title":"","desc":""}]},"playlog":{},"stream":[{"audio_lang":"ja","milliseconds_video":6397592,"milliseconds_audio":6397682,"segs":[{"size":10884356,"cdn_url":"http://27.148.180.24/6572F674E1D3081C7A5D14380D/030020110059FF108B074C011BA6A9C2F44867-1C76-0682-BAD4-653A92E838B0.mp4?ccode=0512&duration=394&expire=18000&psid=3d6240c364b98e471669b7126aeabc36&ups_client_netip=78228725&ups_ts=1512456831&ups_userid=&utid=fjCtEoQpcFwCAXgihyUKMWu2&vid=XMjk4NzA1OTMzNg%3D%3D&vkey=A27dcf64cdc5ea779343543730db29c3f","total_milliseconds_video":394933,............`

**Comment by redstoneleo** [comment]
提交个土豆不能下载 http://video.tudou.com/v/XMTc5ODcwMTAwOA==.html

**Comment by abow258** [comment]
抱歉，我是新手，如太笨希望见谅> < 
输入指令 ykdl http://v.youku.com/v_show/id_XMzIwMjA4Mjk1Ng==.html  
或隨便试了好几个YOUKU连结都无法下载，
但bilibili等网站皆可正常下载没问题，
不知道是哪里有问题呢... 
附上图片做个参考 https://i.imgur.com/umU8dl4.png

**Comment by mengmo** [comment]
@abow258 请更新至最新的开发版，方法见项目的 [wiki](https://github.com/zhangn1985/ykdl/wiki)
另外，如无必要，还是尽量不要发截图的好

**Comment by abow258** [comment]
@mengmo 真奇怪.. 
我昨天才知道ykdl的，所以昨天才刚安装而已 
应该就是装最新版的了呀.... 
不好意思我不知道不要截图比较好，谢谢指正，
以为截图能够比较有利判断问题@@"

**Comment by mengmo** [comment]
@abow258 一般 pip 安装的都是最新的稳定版，而不是最新的开发版。
并不是说不能发图，只是有时候图片对于定位问题来说不是太方便。
汇报问题当然是信息越完整越有利，所以在 github 上一般推荐错误信息直接贴上来，用 markdown 的语法。
\`\`\`
比如这样
\`\`\`
```
比如这样
```

**Comment by abow258** [comment]
@mengmo 
原来差别在这里
不过用代码包安装实在是看不懂..
我再研究一下
非常感谢您

**Comment by zhangn1985** [comment]
截图没法复制粘帖，增加了一些工作量。再者不会质疑你们贴出的log。

**Comment by abow258** [comment]
@zhangn1985
 我理解了 真的对这方面很不熟悉呀...希望大家多担待

**Comment by abow258** [comment]
不好意思....若想使用開發版的話
m3u8、pycryptodome、ykdl此三個Python庫都必須要手動安裝嗎?
而手動安裝的方式，都是下載該庫的master檔並解壓縮，
cmd進入到該資料夾，執行python setup.py install，這樣對嗎?

因為剛剛照這樣的步驟
不管如何都沒辦法手動安裝成功只好上來求助...
然後移除又重開機又重新做，試了三個小時...

**Comment by mengmo** [comment]
@abow258
> 如果**下载源码**安装，需要先**手动**安装好上述 Python 库，否则 ykdl 无法安装。
使用 **pip** 安装则会**自动**解决 Python 库的依赖。

Windows 下这一行就够了
`pip install --upgrade https://github.com/zhangn1985/ykdl/archive/master.zip`

**Comment by 378804441** [comment]
有人 搞出来了 ckey 么？

**Comment by zhangn1985** [comment]
抱歉没有。

**Comment by airdge** [comment]
`i.ckey ? i.ckey = d.defaultUA : i.ckey = o.default.getUA();` 
现ckey也不是必要参数,直接转换算法会比较麻烦
```
            UPS_API_URL: "https://ups.youku.com/ups/get.json",
            OPEN_API_URL: "https://api.youku.com/players/custom.json",
            OPEN_API_URL_TOKEN: "https://api.youku.com/players/consume.json",
            defaultUA: "DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd+WOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3+nb0v72gZ6b0td+WOZsHHWxysSo/0y9D2K42SaB8Y/+aD2K42SaB8Y/+ahU+WOZsHcrxysooUeND"
```
```
 var l = {
     initUA_OPT: function() {
         if (!window.UA_Opt) {
             var t = new Object;
             window.UA_Opt = t, this.uaKey = "collina_" + (new Date).getTime(), t.OnlyHost = 1, t.SendMethod = 9, t.FormId = "login_submit_form", t.ExTarget = ["password"], t.LogVal = this.uaKey, window[t.LogVal] = "", t.Token = (new Date).getTime() + ":" + Math.random(), t.MaxMCLog = 50, t.MaxKSLog = 50, t.MaxMPLog = 50, t.MaxTCLog = 50, t.MaxFocusLog = 50, t.ResHost = "aeu.alicdn.com", t.Flag = 1670350
         }
         if (window.UA_Opt.callback = function() {
                 this.ckey = window[window.UA_Opt.LogVal];
             }, "undefined" == typeof window.acjs) {
             var e = document.createElement("script");
             e.src = "//af.alicdn.com/js/uac.js", document.head.appendChild(e)
         }
     },
     getUA: function() {
         var t = window[window.UA_Opt.LogVal];
         return window.UA_Opt.Token = (new Date).getTime() + ":" + Math.random(), window.UA_Opt.reload && window.UA_Opt.reload(), t && t.length > 1e3 && (t = t.substr(0, 1e3)), t
     },
 };
```

**Comment by zhangn1985** [comment]
恩，是蛮难算的。

**Comment by redstoneleo** [comment]
现在有的优酷土豆视频还是不能下载，比如http://v.youku.com/v_show/id_XNDA5NzcyODY4.html?f=18523035

**Comment by zhangn1985** [comment]
@redstoneleo 404

**Comment by redstoneleo** [comment]
@zhangn1985 你刷新试试，视频仍然在
http://v.youku.com/v_show/id_XNDA5NzkxNjQ4.html?spm=a2h0j.8191423.playlist_content.5!20~5~5~A&f=18523035

**Comment by SeaHOH** [comment]
ccode = 0502

**Comment by zhangn1985** [comment]
@SeaHOH 现在又要改回0502吗？

**Comment by zhangn1985** [comment]
@redstoneleo 还是404。。。

**Comment by SeaHOH** [comment]
只是我这里测试没问题，给你们试试~

**Comment by redstoneleo** [comment]
@zhangn1985 给你视频专辑
http://list.youku.com/albumlist/show/id_18523035.html

**Comment by jyuan15** [comment]
ykdl显示这个：
$ ykdl -i http://v.youku.com/v_show/id_XNDA5NzkxNjQ4.html
CRITICAL:YKDL:该视频暂无客户端版权

you-get解析结果：
$ you-get -i http://v.youku.com/v_show/id_XNDA5NzkxNjQ4.html
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
site:                优酷 (Youku)
title:               倚天屠龙记 20
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4hd
      container:     mp4
      video-profile: 高清
      size:          176.5 MiB (185122109 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDA5NzkxNjQ4&type=mp4&ups_client_netip=6eb84a1b&ups_ts=1514539258&utid=9vbMEqwiYBoCAW64Shu74NoM&ccode=0512&psid=de1eb24c27b89a60add4705bba80ba8c&duration=2687&expire=18000&ups_key=fc52e36cec11cbf4cf72e8abf3ab0729
    # download-with: you-get --format=mp4hd [URL]

    - format:        flvhd
      container:     flv
      video-profile: 渣清
      size:          92.1 MiB (96530443 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDA5NzkxNjQ4&type=flv&ups_client_netip=6eb84a1b&ups_ts=1514539258&utid=9vbMEqwiYBoCAW64Shu74NoM&ccode=0512&psid=de1eb24c27b89a60add4705bba80ba8c&duration=2687&expire=18000&ups_key=fc52e36cec11cbf4cf72e8abf3ab0729
    # download-with: you-get --format=flvhd [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDA5NzkxNjQ4

**Comment by jyuan15** [comment]
发现把ccode改成0512就可以了

**Comment by zhangn1985** [comment]
`
ykdl http://v.youku.com/v_show/id_XNDA5NzkxNjQ4.html --debug
DEBUG:common:video_host> v.youku.com
DEBUG:common:short_name> youku
DEBUG:优酷 (Youku):VID: XNDA5NzkxNjQ4
DEBUG:html:get_content> URL: https://ups.youku.com/ups/get.json?vid=XNDA5NzkxNjQ4&ccode=0512&client_ip=192.168.1.1&utid=fM7NEuMoKzwCAbfBeIqvWOqY&client_ts=1514594428&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxysooUeND
DEBUG:html:get_content> Charset: UTF-8
DEBUG:优酷 (Youku):data: {'e': {'code': 0, 'provider': 'hsfprovider', 'desc': ''}, 'cost': 0.012000000104308128, 'data': {'video': {'privacy': 'anybody', 'videoid_play': 102447912, 'type': ['show', 'dvd', 'bullet', 'bVideoinfo'], 'category_id': 97, 'id': 102447912, 'username': 'pk港剧', 'title': '倚天屠龙记 20', 'tags': ['倚天屠龙记'], 'limited': 0, 'subcategories': [{'id': '2039', 'name': '港剧'}, {'id': '2071', 'name': '武侠剧'}, {'id': '2084', 'name': '古装剧'}], 'logo': 'https://vthumb.ykimg.com/054102015A0D397E8B78D21F0405FCE1', 'weburl': 'http://v.youku.com/v_show/id_XNDA5NzkxNjQ4.html', 'seconds': 2688.08, 'category_letter_id': 'd', 'encodeid': 'XNDA5NzkxNjQ4', 'userid': 80413087, 'ctype': '媒资'}, 'show': {'copyright': '0', 'show_videotype': '正片', 'title': '倚天屠龙记', 'show_thumburl_huge': '', 'video_pay': 0, 'show_thumburl': 'http://r1.ykimg.com/050B00005241357967583910510C31D8', 'showcategory': '电视剧', 'show_vthumburl': 'http://r1.ykimg.com/050D0000524135926758390ED10879EA', 'id': 15321, 'episode_total': 42, 'stage': 20, 'exclusive': False, 'pay': 0, 'pay_type': [], 'show_vthumburl_big_jpg': 'http://r1.ykimg.com/050E0000524135926758390ED10879EA', 'video_type': 1, 'show_vthumburl_huge': '', 'encodeid': 'cbfd5d16962411de83b1', 'show_thumburl_big_jpg': 'http://r1.ykimg.com/050C00005241357967583910510C31D8'}, 'user': {'vip': False, 'ip': '183.193.120.138', 'uid': ''}, 'dvd': {'tail': '2643488', 'audiolang': [{'langcode': 'guoyu', 'vid': 'XNDA5NzkxNjQ4', 'lang': '国语'}], 'head': '78019', 'notsharing': '0'}, 'controller': {'is_phone_stream': '0', 'share_disable': False, 'circle': False, 'play_mode': 2, 'continuous': False, 'yi_plus': False, 'stream_mode': 2, 'like_disabled': False, 'video_capture': True, 'download_disable': False, 'new_core': False}, 'ups': {'ups_ts': '1514594428', 'ups_client_netip': '183.193.120.138', 'psid': 'f4d4d93043def20a4239d0dbe66f41cf'}, 'videolike': {'like': 5984, 'dislike': 267}, 'videos': {'next': {'encodevid': 'XNDA5ODAzNTky', 'title': '倚天屠龙记 21', 'vid': '102450898', 'seq': '21'}, 'list': [{'encodevid': 'XNDA5NzYzMTQw', 'title': '倚天屠龙记 15', 'vid': '102440785', 'seq': '15'}, {'encodevid': 'XNDA5NzcyODY4', 'title': '倚天屠龙记 16', 'vid': '102443217', 'seq': '16'}, {'encodevid': 'XNDA5NzgwMDg0', 'title': '倚天屠龙记 17', 'vid': '102445021', 'seq': '17'}, {'encodevid': 'XNDA5NzgxODk2', 'title': '倚天屠龙记 18', 'vid': '102445474', 'seq': '18'}, {'encodevid': 'XNDA5NzgzMTg0', 'title': '倚天屠龙记 19', 'vid': '102445796', 'seq': '19'}, {'encodevid': 'XNDA5NzkxNjQ4', 'title': '倚天屠龙记 20', 'vid': '102447912', 'seq': '20'}, {'encodevid': 'XNDA5ODAzNTky', 'title': '倚天屠龙记 21', 'vid': '102450898', 'seq': '21'}, {'encodevid': 'XNDA5ODI5MDU2', 'title': '倚天屠龙记 22', 'vid': '102457264', 'seq': '22'}, {'encodevid': 'XNDA5ODcyMzA0', 'title': '倚天屠龙记 23', 'vid': '102468076', 'seq': '23'}, {'encodevid': 'XNDEwMTg2NzA0', 'title': '倚天屠龙记 24', 'vid': '102546676', 'seq': '24'}, {'encodevid': 'XNDEwMjM1MjA0', 'title': '倚天屠龙记 25', 'vid': '102558801', 'seq': '25'}, {'encodevid': 'XNDEwMjgwMjU2', 'title': '倚天屠龙记 26', 'vid': '102570064', 'seq': '26'}, {'encodevid': 'XNDEwMzIwNDM2', 'title': '倚天屠龙记 27', 'vid': '102580109', 'seq': '27'}, {'encodevid': 'XNDEwMzI0NTQw', 'title': '倚天屠龙记 28', 'vid': '102581135', 'seq': '28'}, {'encodevid': 'XNDEwMzM4MjMy', 'title': '倚天屠龙记 29', 'vid': '102584558', 'seq': '29'}, {'encodevid': 'XNDEwMzUxMjM2', 'title': '倚天屠龙记 30', 'vid': '102587809', 'seq': '30'}, {'encodevid': 'XNDEwMzYyNTE2', 'title': '倚天屠龙记 31', 'vid': '102590629', 'seq': '31'}, {'encodevid': 'XNDEwMzk1ODIw', 'title': '倚天屠龙记 32', 'vid': '102598955', 'seq': '32'}, {'encodevid': 'XNDEwNDY3NDQw', 'title': '倚天屠龙记 33', 'vid': '102616860', 'seq': '33'}, {'encodevid': 'XNDEwNTM4NjE2', 'title': '倚天屠龙记 34', 'vid': '102634654', 'seq': '34'}]}, 'error': {'note': '抱歉，因版权原因无法观看此视频！', 'code': -4001}, 'play_policy': {'allow': False, 'paid': '0', 'policyData': {'access': 'deny', 'notice': {'code': -1, 'desc': '抱歉，因版权原因无法观看此视频！'}, 'desc': '禁五线、港澳台、国外所有。'}}, 'uploader': {'certification': True, 'username': 'pk港剧', 'crm_level': 12, 'uid': 'UMzIxNjUyMzQ4', 'homepage': 'http://i.youku.com/u/UMzIxNjUyMzQ4', 'avatar': {'large': 'https://static.youku.com/user/img/avatar/310/53.jpg', 'small': 'https://static.youku.com/user/img/avatar/30/53.jpg', 'big': 'https://static.youku.com/user/img/avatar/80/53.jpg', 'middle': 'https://static.youku.com/user/img/avatar/50/53.jpg'}, 'show_brand': 0, 'reason': '', 'fan_count': 0}, 'network': {'country_code': 'CN', 'dma_code': '24400', 'area_code': '310000'}, 'playlog': {}}}
CRITICAL:YKDL:抱歉，因版权原因无法观看此视频！
`
ccode=0512

**Comment by SeaHOH** [comment]
果然各地效果不一样，我这儿 0502 和 0512 都行。

**Comment by wangyi160** [comment]
我提供一个通用的思路吧，借助于selenium, browsermobproxy, 通过流量监控，可以获取所有视频网站的metadata， 通过metadata获取视频网址。
我写了个程序测试一下，发现利用这个方法，甚至可以下载VIP视频。。。

**Comment by redstoneleo** [comment]
@要是你之前没有买VIP视频，通过你的方法还能下载VIP视频？

**Comment by SeaHOH** [comment]
@wangyi160 哪儿通用了？这是妄想吧，完全看不到可行性。

**Comment by wangyi160** [comment]
@redstoneleo  获取优酷VIP视频的地址的前提当然是要有VIP账号，一旦有了地址，无需VIP登录即可下载

**Comment by wangyi160** [comment]
@SeaHOH 所谓通用是指这套思路，具体每个网站肯定还是要分析它的规则，跟目前ykdl的实现是类似的

**Comment by SeaHOH** [comment]
@wangyi160 这是要先看一遍的节奏，我们的目的不是要跳过广告么？
这跟直接用浏览器看有什么区别，就只是想下载？
如果只是下载，我还有更方便的方法，缓冲完就能下载好。

**Comment by wangyi160** [comment]
@SeaHOH 其实整个核心是为了获取视频地址，一旦获取完成就可以关闭浏览器了，进入下载步骤。浏览器是需要打开一下的，可能还需要加载等几秒，但是可以通过编程隐藏其窗口，然后关闭之，这都是细节问题了，不是说非得看完视频再下载。。。

**Comment by SeaHOH** [comment]
照这个说法，用 PhantomJS + selenium + Python 岂不更好？

**Comment by wangyi160** [comment]
@SeaHOH 其实我一开始也是这么想的，也尝试了一下，可惜没有成功，也许phantomjs本身做了裁剪

**Comment by SeaHOH** [comment]
没有时间啊，之前说过搞定 QQ 多线程下载也还没做……

**Comment by airdge** [comment]
这种边看边下载还是算了吧  只适合自己玩玩   大批量的行不通
再者此类下载还要排除AD和其他文件资源,单单这个 不比直接api解析来的快

**Comment by wangyi160** [comment]
看来大家还是比较享受破解的乐趣，那就继续努力破解吧

**Comment by zhangn1985** [comment]
先关了。感觉大家已经不受困扰了。
