### ISSUE TITLE
douyu 失效

### ISSUE THREAD

**Issue by a67878813** [zhangn1985/ykdl#238]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```
CRITICAL:YKDL:server error!!

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
curl 'https://www.douyu.com/lapi/live/getPlay/288016' --data 
'cptl=0002&sign=fd7cd4d162f9a320f91e1601928747ab&ver=2017122811&rate=2&did=72b982b370afe1b748e6965400081501&cdn=&tt=25243231'
\<html>
\<head><title>403 Forbidden</title></head>
\<body bgcolor="white">
\<center><h1>403 Forbidden</h1></center>
\<hr><center>nginx</center>
\</body>
\</html>

**Comment by zhangn1985** [comment]
```
curl 'https://www.douyu.com/lapi/live/getPlay/288016' -H 'Host: www.douyu.com' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2' --compressed -H 'Cookie: Hm_lvt_e99aee90ec1b2106afe7ec3b199020a7=1514593528; acf_did=72b982b370afe1b748e6965400081501; smidV2=20170730082226fc451b7ef066a0dcb01cc72dc116bee8b419785e21140ba30; dy_did=72b982b370afe1b748e6965400081501; Hm_lpvt_e99aee90ec1b2106afe7ec3b199020a7=1514593798' -H 'DNT: 1' -H 'Connection: keep-alive' --data 'cptl=0002&sign=fd7cd4d162f9a320f91e1601928747ab&ver=2017122811&rate=2&did=72b982b370afe1b748e6965400081501&cdn=&tt=25243231'
```

**Comment by TaoziDB** [comment]
there is a fix from streamlink

**Comment by a67878813** [comment]
curl 'https://www.douyu.com/lapi/live/getPlay/288016' --data 'cptl=0002&sign=fd7cd4d162f9a320f91e1601928747ab&ver=2017122811&rate=2&did=72b982b370afe1b748e6965400081501&cdn=&tt=25243231'

output:

\<html>
\<head><title>403 Forbidden</title></head>
\<body bgcolor="white">
\<center><h1>403 Forbidden</h1></center>
\<hr><center>nginx</center>
\</body>
\</html>

**Comment by a67878813** [comment]
thank you
https://github.com/zhangn198
https://github.com/TaoziDB5

**Comment by a67878813** [comment]
thankyou @zhangn1985 @TaoziDB

**Comment by Justsoos** [comment]
斗鱼如何选择 LPL2018 5个直播子房间，可看 aleng 房间，以及可选1，2，3分别流畅，高清，蓝光码率的 api 代码。
发到这里了：
https://gist.github.com/Justsoos/5287887068d902b6d3ed3534a47f3ff3

https://github.com/zhangn1985/ykdl/issues/168
