### ISSUE TITLE
请问如何把gz和zip结尾的文件打包成EXE

### ISSUE THREAD

**Issue by hf97542** [zhangn1985/ykdl#239]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by zhangn1985** [comment]
额，这个gzip不支持自解压，zip支持，但和ykdl有啥关系吗？

**Comment by hf97542** [comment]
就是像这种程序ykdl_win32.exe是怎么来的，

**Comment by hf97542** [comment]
请问你编译的是 python哪个版本？

**Comment by zhangn1985** [comment]
python34, 用pyinstaller做的。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/wiki/windows-release-script

照这个做。

**Comment by hf97542** [comment]
谢谢

**Comment by hf97542** [comment]
再请问下，在WINdows10系统中，要把Py生成EXE，要安装哪几个程序

**Comment by zhangn1985** [comment]
一个"pyinstaller"
