### ISSUE TITLE
花椒直播，VOD無法解析

### ISSUE THREAD

**Issue by andy199113** [zhangn1985/ykdl#24]
花椒直播的直播串流是可正常使用的，但VOD的部份無法解析，
直播與VOD解析是類似的，希望未來能加入，謝謝作者分享這好用工具

`http://g2.live.360.cn/vodplay?stype=m3u8&channel=live_huajiao_v2&bid=huajiao&sn={}&sid={}&_rate=xd&ts={}&r={}&_ostype=flash&_delay=0&_sign=null&_ver=13&dtype=non&tag=.m3u8
`

**Comment by zhangn1985** [comment]
可以提供一下VOD点播的一个网址吗？花椒上我找了半天都没找到。

**Comment by andy199113** [comment]
直播後的連結可以重播(VOD)
例如：http://www.huajiao.com/l/32734113
這個連結無法正常下載

**Comment by zhangn1985** [comment]
了解，回去看看。

**Comment by andy199113** [comment]
謝謝
