### ISSUE TITLE
添加爱奇艺eac3音轨的支持

### ISSUE THREAD

**Issue by macdavis** [zhangn1985/ykdl#247]
比如这部电影：http://www.iqiyi.com/v_19rr7p0jss.html。目前的ykdl即使选择了4K版本，解析出来的音轨也是he-aac，希望可以像you-get一样，解析出eac3的音轨。

**Comment by zhangn1985** [comment]
you-get 的iqiyi算法也是我提交的，应该来说，已经过时了。

**Comment by macdavis** [comment]
不过you-get目前确实可以解析出eac3来，像[http://www.iqiyi.com/v_19rra8tjv0.html#vfrm=2-4-0-1](http://www.iqiyi.com/v_19rra8tjv0.html#vfrm=2-4-0-1)甚至提供5.1声道。相比之下，HE-AAC压缩的真的有些太厉害了。

**Comment by zhangn1985** [comment]
you-get 的算法早就不能用了，#19

**Comment by macdavis** [comment]
现在annie可以解析出完整的eac3了，希望这个项目也可以支持。

**Comment by jindaxia** [comment]
annie解析出的你说支持eac3的 分辨率应该不是4K的

**Comment by macdavis** [comment]
@jindaxia 是的，而且两者采样率，时长也都不一样。

**Comment by jindaxia** [comment]
目前ydkl支持的最高分辨率为4K,默认不加其他参数下载的就是最高分辨率的视频,而这个视频不是eac3音频的
Annie目前只支持到最高1080P分辨率的视频,这个视频正好可能是eac3音频的.
ykdl已经覆盖了 annie支持的所有格式, 如果想让ykdl下载 正好Annie下载的那个视频,  可以加一个参数  

> --format=BD

**Comment by macdavis** [comment]
情况似乎要更复杂些。Annie在同分辨率下能解析出的好几档视频，包括H.264+AAC，H.265+AAC和H.264+EAC3。比如这个：

>  Site:      爱奇艺 iqiyi.com
 Title:     从你的全世界路过
 Type:      video
 Streams:   # All available quality
     [21]  -------------------
     Quality:         1200x504
     Size:            420.36 MiB (440779160 Bytes)
     # download with: annie -f 21 "URL"

     [1]  -------------------
     Quality:         856x360
     Size:            362.15 MiB (379745900 Bytes)
     # download with: annie -f 1 "URL"

     [2]  -------------------
     Quality:         1200x504
     Size:            549.62 MiB (576316256 Bytes)
     # download with: annie -f 2 "URL"

     [96]  -------------------
     Quality:         512x216
     Size:            144.82 MiB (151855872 Bytes)
     # download with: annie -f 96 "URL"

     [14]  -------------------
     Quality:         1280x536
     Size:            1446.20 MiB (1516449548 Bytes)
     # download with: annie -f 14 "URL"

     [default]  -------------------
     Quality:         1280x536
     Size:            803.66 MiB (842702480 Bytes)
     # download with: annie -f default "URL"

     [4]  -------------------
     Quality:         1280x536
     Size:            1253.20 MiB (1314071872 Bytes)
     # download with: annie -f 4 "URL"

其中[f 14]就是5.1声道的EAC3，[default]则是H.265。

**Comment by SeaHOH** [comment]
ykdl 对所有相同质量的解析结果只取其中一个，可以考虑改成列表，就像 cookies 那样。

**Comment by jindaxia** [comment]
嗯 可以稍微改一下 支持所有的结果

**Comment by macdavis** [comment]
不知是否可以考虑重新开启这个issue。

这好像又不是“ykdl 对所有相同质量的解析结果只取其中一个”的问题，而是在现有算法（commit [0bfd0](https://github.com/zhangn1985/ykdl/commit/0bfd0a0cece6f982df641337325862175602cae4#diff-5f7f459abf17b98d5275a80eb3baa0ae)）下，vps里返回给ykdl的解析结果本身就不全，比如不包含H.265。

**Comment by SeaHOH** [comment]
https://github.com/zhangn1985/ykdl/blob/0bfd0a0cece6f982df641337325862175602cae4/ykdl/extractors/iqiyi.py#L54-L55

相同质量指第一行定义的格式，注意第二行，已包含`14`。

**Comment by macdavis** [comment]
> def getvps(tvid, vid):
    tm = int(time.time() * 1000)
    host = 'http://cache.video.qiyi.com'
    src='/vps?tvid='+tvid+'&vid='+vid+'&v=0&qypid='+tvid+'_12&src=01012001010000000000&t='+str(tm)+'&k_tag=1&k_uid='+get_macid()+'&rs=1'
    vf = get_vf(src)
    req_url = host + src + '&vf=' + vf
    html = get_content(req_url)
    return json.loads(html)

似乎目前算法从爱奇艺源头上（`host + src + '&vf=' + vf`）就获取不到14、19和18，而不像是“算法本身有全部获取，而ykdl选择忽略“。比如这个：[vps.json](https://0x0.st/s4pK.json)，其中bid只有10，4，2，1，5。

**Comment by SeaHOH** [comment]
哦，确实没有。
使用的 API 不一样，可以更换。

**Comment by mengmo** [comment]
不建议更换。
没弄错的话，目前 annie 使用的 API 实际上是 TV APP 的，相对来说没有 ykdl 当前使用的 API 能解析的资源多。
```
annie -i http://www.iqiyi.com/v_19rro3wbto.html
2018/08/09 18:37:31 Can't play this video
```
```
annie -i http://www.iqiyi.com/v_19rrhd3cxv.html
2018/08/09 18:37:41 Can't play this video
```

**Comment by SeaHOH** [comment]
不换也行，添加就好。

**Comment by macdavis** [comment]
另外，在使用annie的时候发现了新的vd_2_id：12，属于H264/BD那一档。https://0x0.st/s4VT.json
