### ISSUE TITLE
不知道iqiyi和letv可否解析出完整视频地址？

### ISSUE THREAD

**Issue by 448Lucario** [zhangn1985/ykdl#248]
在提交前，请确保您已经检查了以下内容!

- [* ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ *] 您的`ykdl`为最新版。
- [ *] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [* ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ *] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
试了一下解析iqiyi，发现长视频都是分段的。
我用这个“http://api.baiyug.cn/vip/index.php?url=视频地址” 后，通过浏览器的查看器可以找到完整视频的m3u8地址，但是这个方法解析出来的不能保证清晰度。（乐视也可以）
自己折腾了一下，想解析出完整的1080p的m3u8地址，但是没能成功……
不知道能不能通过这些解析网站找到出解析完整地址的方法？

**Comment by lamlam123tld3** [comment]
letv 还没挂吗

**Comment by zhangn1985** [comment]
只要是非VIP视频都可以，只不过你要m3u8，iqiyi目前不是，letv是m3u8，不过是本地生成的。
