### ISSUE TITLE
Youku 解析存在问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#249]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 要下载的是这个日语版 https://v.youku.com/v_show/id_XMjg4MzEyMzMyNA
> 结果下载下来的是国语版的 https://v.youku.com/v_show/id_XMjg4MzEyMzMwOA

**Comment by zhangn1985** [comment]
是的，ykdl不支持语言选择。

**Comment by zhangn1985** [comment]
不过我试了，这两个链接并没有啥区别呀？

**Comment by SeaHOH** [comment]
视频相同，语音不同。
解析结果日语在前，被后面的国语覆盖了。

**Comment by SeaHOH** [comment]
可以用 `stream_ext` 字段来过滤。
