### ISSUE TITLE
优酷解析问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#26]
```
ykdl -i http://v.youku.com/v_show/id_XMTc0MTUxODEwNA==.html
ykdl: 优酷 (Youku) invalid segment key!
```
`you-get`还能解析
虽说现在付费视频都没法完整下载

**Comment by zhangn1985** [comment]
要强行解析还是可以的。效果和you-get一样。

**Comment by zhangn1985** [comment]
只要把这行的 assert 改成 break就可以了达到了you-get一样。但是没什么意义吧？
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/youkubase.py#L60
