### ISSUE TITLE
教学网站的m3u8无法下载，有解决方案吗？

### ISSUE THREAD

**Issue by google2013** [zhangn1985/ykdl#262]
比如：http://demo.edusoho.com/course/477/task/2964/show 这个网站的m3u8视频，我用http://demo.edusoho.com/hls/2878/playlist/testteee*****.m3u8   这样的地址（这个地址是网站生成的）是 ykdl无法下载的  ，有具体的命令行支持 或者 解决方案 吗？

**Comment by SeaHOH** [comment]
这只是一个 demo。
