### ISSUE TITLE
乐视不管用了

### ISSUE THREAD

**Issue by yang0000meng** [zhangn1985/ykdl#265]
http://www.le.com/ptv/vplay/31427306.html乐视不管用了
lTraceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.5.4', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 163, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

**Comment by SeaHOH** [comment]
```
site:                乐视 (Letv)
title:               远大前程11
artist:              None
streams:
    - format:        HD
      container:     m3u8
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
{
    "artist": null,
    "extra": {
        "header": "",
        "proxy": "",
        "rangefetch": "",
        "referer": "",
        "ua": ""
    },
    "site": "乐视 (Letv)",
    "stream_types": [
        "HD",
        "LD"
    ],
    "streams": {
        "HD": {
            "container": "m3u8",
            "size": 0,
            "src": [
                "C:\\Users\\SeaHOH\\AppData\\Local\\Temp\\tmp201od4c6.m3u8"
            ],
            "video_profile": "高清"
        },
        "LD": {
            "container": "m3u8",
            "size": 0,
            "src": [
                "C:\\Users\\SeaHOH\\AppData\\Local\\Temp\\tmp9g6gbu8c.m3u8"
            ],
            "video_profile": "流畅"
        }
    },
    "title": "远大前程11"
}
```

**Comment by yang0000meng** [comment]
分地区吗？
更新最新版  1.6.0照样出错
C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>

**Comment by yang0000meng** [comment]
网页可以 ，
我发现  'http://player-pc.le.com/mms/out/video/playJson?id={}&platid=1&splatid=101&format=1&tkey={}&domain=www.le.com&region=cn&source=1000&accesyx=1
中 
splatid=101 变成了splatid=105   tkey 也变的不一样了。 tkey 算法好像变了。

**Comment by SeaHOH** [comment]
不对，le.py 中没有 debug。。。

**Comment by yang0000meng** [comment]
经多次次数 换ip测试 发现 偶尔管用 
DEBUG:common:short_name> le
DEBUG:html:get_content> URL: http://player-pc.le.com/mms/out/video/playJson?id=3
1427306&platid=1&splatid=101&format=1&tkey=3479014109&domain=www.le.com&region=c
n&source=1000&accesyx=1
DEBUG:html:get_content> Charset: utf-8
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html --debug
DEBUG:common:video_host> www.le.com
DEBUG:common:short_name> le
DEBUG:html:get_content> URL: http://player-pc.le.com/mms/out/video/playJson?id=3
1427306&platid=1&splatid=101&format=1&tkey=3697117917&domain=www.le.com&region=c
n&source=1000&accesyx=1
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://play.g3proxy.lecloud.com/vod/v2/MjcwLzI2LzY1
L2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0xMTIwNjY3NjYyLWF2Yy00MTkyNzktYWFjLTQ4MDAwLTE5MjEw
ODAtMTE1MTQ1MDUzLWU4N2RiODg1ZmU2Y2M1OWI1ZTZkMDNjYWJjYjRlYjBjLTE1MjMwMjE0NTI0NzEu
bXA0?b=479&mmsid=66829392&tm=1523172864&key=c10a3d2e215a592b79b00d0f729131a6&pla
tid=1&splatid=101&playid=0&tss=ios&vtype=13&cvid=294338142908&payff=0&pip=f88a3d
1950e20cfa46105d3a8f06d136&m3v=1&termid=1&format=1&hwtype=un&ostype=MacOS10.12.4
&p1=1&p2=10&p3=-&expect=3&tn=0.8751693753690604&vid=31427306&uuid=0809d09364491e
ef3d93748cf2eb901595da03e1_0&sign=letv
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://123.125.39.231/play.videocache.lecloud.com/2
70/26/65/letv-uts/14/ver_00_22-1120667662-avc-419279-aac-48000-1921080-115145053
-e87db885fe6cc59b5e6d03cabcb4eb0c-1523021452471.m3u8?crypt=72aa7f2e538&b=479&nlh
=4096&nlt=60&bf=90&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&it
s=0&qos=3&fcheck=0&amltag=100&mltag=100&proxy=2071799785,1728279287,2031547778&u
id=3733667108.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw.
.&ntm=1523191200&nkey=1981a2254c6ce906bb0fa3ae2d9ed93c&nkey2=528fd211ece56423212
b0118057b1f76&auth_key=1523191200-1-0-1-101-2ce6539b2d41a2b90eb532d001f2989a&geo
=CN-16-203-2&mmsid=66829392&tm=1523172864&key=c10a3d2e215a592b79b00d0f729131a6&p
layid=0&vtype=13&cvid=294338142908&payff=0&m3v=1&hwtype=un&ostype=MacOS10.12.4&p
1=1&p2=10&p3=-&tn=0.8751693753690604&vid=31427306&uuid=0809d09364491eef3d93748cf
2eb901595da03e1_0&sign=letv&uidx=0&errc=0&gn=3334&ndtype=0&vrtmcd=102&buss=100&c
ips=222.139.61.36&r=1523172568092&appid=500
DEBUG:html:get_content> URL: http://play.g3proxy.lecloud.com/vod/v2/Mjc3LzI4Lzgx
L2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0xMTIwNjY3NjU2LWF2Yy0xOTk3MDktYWFjLTQ4MDAwLTE5MjEw
ODAtNjI0MTY2NjctZTBkYjExZTIwYzYyMGYzNTcxM2UwZDg0MDk3YjhmM2QtMTUyMzAyMTQ0NDY4Mi5t
cDQ=?b=259&mmsid=66829392&tm=1523172864&key=de45c736ace3d161315cac87e0fc4da4&pla
tid=1&splatid=101&playid=0&tss=ios&vtype=21&cvid=294338142908&payff=0&pip=f88a3d
1950e20cfa46105d3a8f06d136&m3v=1&termid=1&format=1&hwtype=un&ostype=MacOS10.12.4
&p1=1&p2=10&p3=-&expect=3&tn=0.664707042503415&vid=31427306&uuid=5e388fad07eed35
44ad9950ef0bc46b915919806_0&sign=letv
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://61.240.153.5/play.videocache.lecloud.com/277
/28/81/letv-uts/14/ver_00_22-1120667656-avc-199709-aac-48000-1921080-62416667-e0
db11e20c620f35713e0d84097b8f3d-1523021444682.m3u8?crypt=6aa7f2e291&b=259&nlh=409
6&nlt=60&bf=90&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&
qos=3&fcheck=0&amltag=100&mltag=100&proxy=2031547808,2007487174,2031547792&uid=3
733667108.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&nt
m=1523191200&nkey=52a95a9cc2d113b6eb20725cc805cceb&nkey2=528fd211ece56423212b011
8057b1f76&auth_key=1523191200-1-0-1-101-2ce6539b2d41a2b90eb532d001f2989a&geo=CN-
16-203-2&mmsid=66829392&tm=1523172864&key=de45c736ace3d161315cac87e0fc4da4&playi
d=0&vtype=21&cvid=294338142908&payff=0&m3v=1&hwtype=un&ostype=MacOS10.12.4&p1=1&
p2=10&p3=-&tn=0.664707042503415&vid=31427306&uuid=5e388fad07eed3544ad9950ef0bc46
b915919806_0&sign=letv&uidx=0&errc=0&gn=3337&ndtype=0&vrtmcd=102&buss=100&cips=2
22.139.61.36&r=1523172568655&appid=500
site:                乐视 (Letv)
title:               远大前程11
artist:              None
streams:
    - format:        HD
      container:     m3u8
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Download: 远大前程11_HD part 0
Download: 远大前程11_HD part 1
Download: 远大前程11_HD part 2
Download: 远大前程11_HD part 3
Skipped: file already downloaded
Download: 远大前程11_HD part 4
Skipped: file already downloaded
Download: 远大前程11_HD part 5
Skipped: file already downloaded
Download: 远大前程11_HD part 6
Skipped: file already downloaded
Download: 远大前程11_HD part 7
Skipped: file already downloaded
Download: 远大前程11_HD part 8
Skipped: file already downloaded
Download: 远大前程11_HD part 9
Skipped: file already downloaded
Download: 远大前程11_HD part 10
Skipped: file already downloaded
Download: 远大前程11_HD part 11
Skipped: file already downloaded
Download: 远大前程11_HD part 12
Skipped: file already downloaded
Download: 远大前程11_HD part 13
Skipped: file already downloaded
Download: 远大前程11_HD part 14
Skipped: file already downloaded
Download: 远大前程11_HD part 15
Skipped: file already downloaded
Download: 远大前程11_HD part 16
Skipped: file already downloaded
Download: 远大前程11_HD part 17
Skipped: file already downloaded
Download: 远大前程11_HD part 18
Skipped: file already downloaded
Download: 远大前程11_HD part 19
Skipped: file already downloaded
Download: 远大前程11_HD part 20
Skipped: file already downloaded
Download: 远大前程11_HD part 21
Skipped: file already downloaded
Download: 远大前程11_HD part 22
Skipped: file already downloaded
Download: 远大前程11_HD part 23
Skipped: file already downloaded
Download: 远大前程11_HD part 24
Skipped: file already downloaded
Download: 远大前程11_HD part 25
Skipped: file already downloaded
Download: 远大前程11_HD part 26
Skipped: file already downloaded
Download: 远大前程11_HD part 27
Skipped: file already downloaded
Download: 远大前程11_HD part 28
Skipped: file already downloaded
Download: 远大前程11_HD part 29
Skipped: file already downloaded
Download: 远大前程11_HD part 30
Skipped: file already downloaded
Download: 远大前程11_HD part 31
Skipped: file already downloaded
Download: 远大前程11_HD part 32
Skipped: file already downloaded
Download: 远大前程11_HD part 33
Skipped: file already downloaded
Download: 远大前程11_HD part 34
Skipped: file already downloaded
Download: 远大前程11_HD part 35
Skipped: file already downloaded
Download: 远大前程11_HD part 36
Skipped: file already downloaded
Download: 远大前程11_HD part 37
Skipped: file already downloaded
Download: 远大前程11_HD part 38
Skipped: file already downloaded
Download: 远大前程11_HD part 39
Skipped: file already downloaded
Download: 远大前程11_HD part 40
Skipped: file already downloaded
Download: 远大前程11_HD part 41
Skipped: file already downloaded
Download: 远大前程11_HD part 42
Skipped: file already downloaded
Download: 远大前程11_HD part 43
Skipped: file already downloaded
Download: 远大前程11_HD part 44
Skipped: file already downloaded
Download: 远大前程11_HD part 45
Skipped: file already downloaded
Skipped: file already downloaded
Download: 远大前程11_HD part 46
Skipped: file already downloaded
Download: 远大前程11_HD part 47
Download: 远大前程11_HD part 48
Skipped: file already downloaded
Download: 远大前程11_HD part 49
Skipped: file already downloaded
Download: 远大前程11_HD part 50
Skipped: file already downloaded
Download: 远大前程11_HD part 51
Skipped: file already downloaded
Download: 远大前程11_HD part 52
Skipped: file already downloaded
Download: 远大前程11_HD part 53
Skipped: file already downloaded
Download: 远大前程11_HD part 54
Skipped: file already downloaded
Download: 远大前程11_HD part 55
Skipped: file already downloaded
Download: 远大前程11_HD part 56
Skipped: file already downloaded
Download: 远大前程11_HD part 57
Skipped: file already downloaded
Download: 远大前程11_HD part 58
Skipped: file already downloaded
Download: 远大前程11_HD part 59
Skipped: file already downloaded
Download: 远大前程11_HD part 60
Skipped: file already downloaded
Download: 远大前程11_HD part 61
Skipped: file already downloaded
Download: 远大前程11_HD part 62
Skipped: file already downloaded
Download: 远大前程11_HD part 63
Skipped: file already downloaded
Download: 远大前程11_HD part 64
Skipped: file already downloaded
Download: 远大前程11_HD part 65
Skipped: file already downloaded
Download: 远大前程11_HD part 66
Skipped: file already downloaded
Download: 远大前程11_HD part 67
Skipped: file already downloaded
Download: 远大前程11_HD part 68
Skipped: file already downloaded
Download: 远大前程11_HD part 69
Skipped: file already downloaded
Download: 远大前程11_HD part 70
Skipped: file already downloaded
Download: 远大前程11_HD part 71
Skipped: file already downloaded
Download: 远大前程11_HD part 72
Skipped: file already downloaded
Download: 远大前程11_HD part 73
Skipped: file already downloaded
Download: 远大前程11_HD part 74
Skipped: file already downloaded
Download: 远大前程11_HD part 75
Skipped: file already downloaded
Download: 远大前程11_HD part 76
Skipped: file already downloaded
Download: 远大前程11_HD part 77
Skipped: file already downloaded
Download: 远大前程11_HD part 78
Download: 远大前程11_HD part 79
Skipped: file already downloaded
Download: 远大前程11_HD part 80
Skipped: file already downloaded
Download: 远大前程11_HD part 81
Download: 远大前程11_HD part 82
Skipped: file already downloaded
Download: 远大前程11_HD part 83
Skipped: file already downloaded
Download: 远大前程11_HD part 84
Skipped: file already downloaded
Download: 远大前程11_HD part 85
Download: 远大前程11_HD part 86
Skipped: file already downloaded
Download: 远大前程11_HD part 87
Skipped: file already downloaded
Download: 远大前程11_HD part 88
Skipped: file already downloaded
Download: 远大前程11_HD part 89
Skipped: file already downloaded
Download: 远大前程11_HD part 90
Skipped: file already downloaded
Download: 远大前程11_HD part 91
Skipped: file already downloaded
Download: 远大前程11_HD part 92
Skipped: file already downloaded
Download: 远大前程11_HD part 93
Skipped: file already downloaded
Download: 远大前程11_HD part 94
Skipped: file already downloaded
Download: 远大前程11_HD part 95
Skipped: file already downloaded
Download: 远大前程11_HD part 96
Skipped: file already downloaded
Download: 远大前程11_HD part 97
Skipped: file already downloaded
Download: 远大前程11_HD part 98
Skipped: file already downloaded
Download: 远大前程11_HD part 99
Skipped: file already downloaded
Download: 远大前程11_HD part 100
Download: 远大前程11_HD part 101
Skipped: file already downloaded
Download: 远大前程11_HD part 102
Skipped: file already downloaded
Download: 远大前程11_HD part 103
Skipped: file already downloaded
Download: 远大前程11_HD part 104
Skipped: file already downloaded
Download: 远大前程11_HD part 105
Skipped: file already downloaded
Download: 远大前程11_HD part 106
Skipped: file already downloaded
Download: 远大前程11_HD part 107
Skipped: file already downloaded
Download: 远大前程11_HD part 108
Skipped: file already downloaded
Skipped: file already downloaded
Skipped: file already downloaded
ERROR:downloader:downloader failed at part 59
ERROR:downloader:downloader failed at part 64
ERROR:downloader:downloader failed at part 71
ERROR:downloader:downloader failed at part 78
ERROR:downloader:downloader failed at part 83
CRITICAL:YKDL:远大前程11_HD> donwload failed

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html --debug^A
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yk
dl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\ykdl\extractors\le\le.py", line 70, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'

C:\Users\Administrator>ykdl http://www.le.com/ptv/vplay/31427306.html
site:                乐视 (Letv)
title:               远大前程11
artist:              None
streams:
    - format:        HD
      container:     m3u8
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Download: 远大前程11_HD part 0
Download: 远大前程11_HD part 1
Download: 远大前程11_HD part 2
Download: 远大前程11_HD part 3
Skipped: file already downloaded
Download: 远大前程11_HD part 4
Skipped: file already downloaded
Download: 远大前程11_HD part 5
Skipped: file already downloaded
Download: 远大前程11_HD part 6
Skipped: file already downloaded
Download: 远大前程11_HD part 7
Skipped: file already downloaded
Download: 远大前程11_HD part 8
Skipped: file already downloaded
Download: 远大前程11_HD part 9
Skipped: file already downloaded
Download: 远大前程11_HD part 10
Skipped: file already downloaded
Download: 远大前程11_HD part 11
Skipped: file already downloaded
Download: 远大前程11_HD part 12
Skipped: file already downloaded
Download: 远大前程11_HD part 13
Skipped: file already downloaded
Download: 远大前程11_HD part 14
Skipped: file already downloaded
Download: 远大前程11_HD part 15
Skipped: file already downloaded
Skipped: file already downloaded
Download: 远大前程11_HD part 16
Download: 远大前程11_HD part 17
Skipped: file already downloaded
Download: 远大前程11_HD part 18
Skipped: file already downloaded
Download: 远大前程11_HD part 19
Skipped: file already downloaded
Download: 远大前程11_HD part 20
Skipped: file already downloaded
Download: 远大前程11_HD part 21
Skipped: file already downloaded
Download: 远大前程11_HD part 22
Skipped: file already downloaded
Download: 远大前程11_HD part 23
Skipped: file already downloaded
Download: 远大前程11_HD part 24
Skipped: file already downloaded
Download: 远大前程11_HD part 25
Skipped: file already downloaded
Download: 远大前程11_HD part 26
Skipped: file already downloaded
Download: 远大前程11_HD part 27
Skipped: file already downloaded
Download: 远大前程11_HD part 28
Skipped: file already downloaded
Download: 远大前程11_HD part 29
Skipped: file already downloaded
Download: 远大前程11_HD part 30
Skipped: file already downloaded
Download: 远大前程11_HD part 31
Skipped: file already downloaded
Download: 远大前程11_HD part 32
Skipped: file already downloaded
Download: 远大前程11_HD part 33
Skipped: file already downloaded
Download: 远大前程11_HD part 34
Skipped: file already downloaded
Download: 远大前程11_HD part 35
Skipped: file already downloaded
Download: 远大前程11_HD part 36
Skipped: file already downloaded
Download: 远大前程11_HD part 37
Skipped: file already downloaded
Download: 远大前程11_HD part 38
Skipped: file already downloaded
Download: 远大前程11_HD part 39
Skipped: file already downloaded
Download: 远大前程11_HD part 40
Skipped: file already downloaded
Download: 远大前程11_HD part 41
Skipped: file already downloaded
Download: 远大前程11_HD part 42
Skipped: file already downloaded
Download: 远大前程11_HD part 43
Skipped: file already downloaded
Download: 远大前程11_HD part 44
Skipped: file already downloaded
Download: 远大前程11_HD part 45
Skipped: file already downloaded
Download: 远大前程11_HD part 46
Skipped: file already downloaded
Download: 远大前程11_HD part 47
Skipped: file already downloaded
Download: 远大前程11_HD part 48
Skipped: file already downloaded
Download: 远大前程11_HD part 49
Skipped: file already downloaded
Download: 远大前程11_HD part 50
Skipped: file already downloaded
Download: 远大前程11_HD part 51
Skipped: file already downloaded
Download: 远大前程11_HD part 52
Skipped: file already downloaded
Download: 远大前程11_HD part 53
Skipped: file already downloaded
Download: 远大前程11_HD part 54
Skipped: file already downloaded
Download: 远大前程11_HD part 55
Skipped: file already downloaded
Download: 远大前程11_HD part 56
Skipped: file already downloaded
Download: 远大前程11_HD part 57
Skipped: file already downloaded
Download: 远大前程11_HD part 58
Skipped: file already downloaded
Download: 远大前程11_HD part 59
Skipped: file already downloaded
Download: 远大前程11_HD part 60
Skipped: file already downloaded
Download: 远大前程11_HD part 61
Skipped: file already downloaded
Download: 远大前程11_HD part 62
Skipped: file already downloaded
Download: 远大前程11_HD part 63
Skipped: file already downloaded
Download: 远大前程11_HD part 64
Skipped: file already downloaded
Download: 远大前程11_HD part 65
Skipped: file already downloaded
Download: 远大前程11_HD part 66
Skipped: file already downloaded
Download: 远大前程11_HD part 67
Skipped: file already downloaded
Download: 远大前程11_HD part 68
Skipped: file already downloaded
Download: 远大前程11_HD part 69
Skipped: file already downloaded
Download: 远大前程11_HD part 70
Skipped: file already downloaded
Download: 远大前程11_HD part 71
Skipped: file already downloaded
Download: 远大前程11_HD part 72
Skipped: file already downloaded
Download: 远大前程11_HD part 73
Skipped: file already downloaded
Download: 远大前程11_HD part 74
Skipped: file already downloaded
Download: 远大前程11_HD part 75
Skipped: file already downloaded
Download: 远大前程11_HD part 76
Skipped: file already downloaded
Download: 远大前程11_HD part 77
Skipped: file already downloaded
Download: 远大前程11_HD part 78
Skipped: file already downloaded
Download: 远大前程11_HD part 79
Skipped: file already downloaded
Download: 远大前程11_HD part 80
Skipped: file already downloaded
Download: 远大前程11_HD part 81
Skipped: file already downloaded
Download: 远大前程11_HD part 82
Skipped: file already downloaded
Download: 远大前程11_HD part 83
Skipped: file already downloaded
Download: 远大前程11_HD part 84
Skipped: file already downloaded
Download: 远大前程11_HD part 85
Skipped: file already downloaded
Download: 远大前程11_HD part 86
Skipped: file already downloaded
Download: 远大前程11_HD part 87
Skipped: file already downloaded
Download: 远大前程11_HD part 88
Skipped: file already downloaded
Download: 远大前程11_HD part 89
Skipped: file already downloaded
Download: 远大前程11_HD part 90
Skipped: file already downloaded
Download: 远大前程11_HD part 91
Skipped: file already downloaded
Download: 远大前程11_HD part 92
Skipped: file already downloaded
Download: 远大前程11_HD part 93
Skipped: file already downloaded
Download: 远大前程11_HD part 94
Skipped: file already downloaded
Download: 远大前程11_HD part 95
Skipped: file already downloaded
Download: 远大前程11_HD part 96
Skipped: file already downloaded
Download: 远大前程11_HD part 97
Skipped: file already downloaded
Download: 远大前程11_HD part 98
Skipped: file already downloaded
Download: 远大前程11_HD part 99
Download: 远大前程11_HD part 100
Download: 远大前程11_HD part 101
Skipped: file already downloaded
Download: 远大前程11_HD part 102
Skipped: file already downloaded
Download: 远大前程11_HD part 103
Download: 远大前程11_HD part 104
Skipped: file already downloaded
Download: 远大前程11_HD part 105
Skipped: file already downloaded
Download: 远大前程11_HD part 106
Skipped: file already downloaded
Download: 远大前程11_HD part 107
Skipped: file already downloaded
Download: 远大前程11_HD part 108
Skipped: file already downloaded
Skipped: file already downloaded
Skipped: file already downloaded
ERROR:downloader:downloader failed at part 82
ERROR:downloader:downloader failed at part 87
ERROR:downloader:downloader failed at part 90
ERROR:downloader:downloader failed at part 99
CRITICAL:YKDL:远大前程11_HD> donwload failed

**Comment by SeaHOH** [comment]
你用的哪国 IP？这个是限制 CN 部分的。

**Comment by yang0000meng** [comment]
国产联通。。。。

**Comment by SeaHOH** [comment]
暂时先关闭
