### ISSUE TITLE
无法用git升级

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#266]
我是git安装的，按Wiki中的方法升级不成功，只能用git pull 更新，但这样更新的，查看版本号没有变。
这是什么原因？

`u0_a309@localhost:~ » git clone https://github.com/zhangn1985/ykdl.git`
`fatal: destination path 'ykdl' already exists and is not an empty directory.`

补充说明：git pull 后，安装目录中的version.py文件已经更新为1.6.0，但查看帮助信息，版本号还是1.5.5

**Comment by SeaHOH** [comment]
使用 git fetch

**Comment by zhangn1985** [comment]
再次运行setup.py
