### ISSUE TITLE
下載 qq.com 視頻失敗

### ISSUE THREAD

**Issue by lucemia** [zhangn1985/ykdl#268]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl http://v.qq.com/txp/iframe/player.html\?vid\=s0026ltd8v8
Traceback (most recent call last):
  File "/.../venv/bin/ykdl", line 11, in <module>
    sys.exit(main())
  File "/.../venv/lib/python2.7/site-packages/cykdl/__main__.py", line 171, in main
    info = parser(u)
  File "/.../venv/lib/python2.7/site-packages/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/.../venv/lib/python2.7/site-packages/ykdl/extractors/qq/video.py", line 241, in prepare
    for title, fmt_name, stream_profile, type_name, urls, size, rate in self.get_streams_info():
  File "/.../venv/lib/python2.7/site-packages/ykdl/extractors/qq/video.py", line 138, in get_streams_info
    for infos in self.get_streams_info('hd'):
  File "/.../venv/lib/python2.7/site-packages/ykdl/extractors/qq/video.py", line 145, in get_streams_info
    video = data['vl']['vi'][0]
KeyError: 'vl'
```

```
data 的值
{u'em': 100, u'exem': 2, u's': u'f', u'msg': u'cannot play outside', u'ip': u'x.xx.xxx.xxxx'}
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 其他視頻是可以的, 如
 ykdl http://v.qq.com/txp/iframe/player.html\?vid\=b0639cnz4tq

**Comment by SeaHOH** [comment]
请直接打开此链接查看

**Comment by lucemia** [comment]
@SeaHOH  不懂  這條視頻可以看  但不能下載

**Comment by SeaHOH** [comment]
你确定？我这儿是 404。麻烦截个图。

**Comment by SeaHOH** [comment]
我看到了，你给的链接有问题。

**Comment by lucemia** [comment]
http://v.qq.com/txp/iframe/player.html?vid=s0026ltd8v8 原始連結

初步測試

https://github.com/zhangn1985/ykdl/blob/7c377e641a8904d20518073afc7bca5fde42c753/ykdl/extractors/qq/video.py#L136

形成的網址為 
```
http://vv.video.qq.com/getinfo?vid=s0026ltd8v8&otype=json&platform=11&appver=3.2.19.333&defn=hd&defnpayver=1
```

會得到 `cannot play outside` 的訊息

移除 `platform` query 就可以了

http://vv.video.qq.com/getinfo?vid=s0026ltd8v8&otype=json&appver=3.2.19.333&defn=hd&defnpayver=1

**Comment by SeaHOH** [comment]
PLAYER_PLATFORM 改回 1 也能工作
