### ISSUE TITLE
有个问题，张哥来看看

### ISSUE THREAD

**Issue by mcyt** [zhangn1985/ykdl#272]
![tim 20180516001919](https://user-images.githubusercontent.com/6211784/40069851-081c3786-589f-11e8-83d7-2a5514094c60.jpg)
这个解析应该是你的，
但是怎么加载cookies下载呢？
你用过这个软件吗
lieying

**Comment by zhangn1985** [comment]
没有，你应该去 https://github.com/wwqgtxx/wwqLyParse 提问
ykdl不能加cookies。
