### ISSUE TITLE
EXE版的怎么还不更新~~

### ISSUE THREAD

**Issue by lleeopen** [zhangn1985/ykdl#280]
或者给个制作方法也行啊~~~

**Comment by mengmo** [comment]
https://github.com/zhangn1985/ykdl/wiki/windows-release-script

**Comment by lleeopen** [comment]
有没有具体步骤啊，看不懂啊~~~

**Comment by SeaHOH** [comment]
随性点，听说有人一天能发好几个版本。

**Comment by zhangn1985** [comment]
感觉优酷的问题还有反馈，再等等吧
