### ISSUE TITLE
下载优酷提示 用户账户异常 请重新登录？

### ISSUE THREAD

**Issue by yangfox** [zhangn1985/ykdl#290]
C:\>ykdl  https://v.youku.com/v_show/id_XMzU3MTMyMjE3Mg==.html?spm=a2h1n.8251845
.0.0
CRITICAL:YKDL:用户账户异常、请重新登录

他是一个免费视频。。。请问管理员这个是怎么回事呀？谢谢

**Comment by SeaHOH** [comment]
请更新，方法见 wiki。
