### ISSUE TITLE
请增加淘宝天猫宝贝详情页的视频解析

### ISSUE THREAD

**Issue by xfr54076** [zhangn1985/ykdl#30]
首先感谢....

发几个测试
https://item.taobao.com/item.htm?id=533920709493
https://detail.tmall.com/item.htm?id=527287172243
https://item.taobao.com/item.htm?id=44328703681
https://item.taobao.com/item.htm?id=538217173275

但是下面这种山寨视频链接的不算...
https://item.taobao.com/item.htm?id=18361523410

**Comment by zhangn1985** [comment]
淘宝的视频有点奇怪。可能要花点时间。

**Comment by zhangn1985** [comment]
should be in next release.

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/12c1de0c1765bf66dc3a67a542e2b9316d3d8fd3
目前只支持第一个链接。

**Comment by zhangn1985** [comment]
drop
