### ISSUE TITLE
腾讯视频为何下载下来是带有水印的?

### ISSUE THREAD

**Issue by sevenuki** [zhangn1985/ykdl#300]
在网页里看 那些LOGO都是浮在播放器上没有嵌入到视频里 有嗅探过单个很短的视频文件 ts 打开之后画面是无水印的 m3u8被限速 下载不动
有用you-get ykdl测试 结果下载下来的视频都是有水印的 

能不能把水印去掉呢? 有发现一些影视论坛和分享公众号 他们下载腾讯的视频就都是无水印的 不知用的什么办法

**Comment by airdge** [comment]
M3U8有效访问只有一次,之后的会限速
用FFMPEG直接去处理解析到的M3U8就可以

**Comment by skywang00** [comment]
那些无水印的腾讯视频好像是从移动端api下的

**Comment by airdge** [comment]
非独播类的视频,m3u8一般不带水印,就是清晰度不高
