### ISSUE TITLE
可以网页观看，但无法ykdl下载bili视频

### ISSUE THREAD

**Issue by skywang00** [zhangn1985/ykdl#301]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

`PS C:\Users\xxx> ykdl --d https://www.bilibili.com/video/av25694110
DEBUG:common:video_host> www.bilibili.com
DEBUG:common:short_name> bilibili
DEBUG:html:get_content> URL: https://www.bilibili.com/video/av25694110
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: https://interface.bilibili.com/v2/playurl?cid=7&player=1&qn=0&sign=6f8dc2cf6341431a6b2feceaad571517
DEBUG:html:get_content> Charset: utf-8
DEBUG:哔哩哔哩 (Bilibili):HTML> <?xml version="1.0" encoding="UTF-8"?>
<video>
   <result>error</result>
   <code>10004</code>
   <message><![CDATA[Video is hidden.]]></message>
</video>
CRITICAL:YKDL:can't play this video!!``
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

这个页面下的视频都无法下载：https://space.bilibili.com/50329118/#/video

**Comment by jindaxia** [comment]
这是B站的日志吧 不是iqiyi的

**Comment by seahog004** [comment]
你好，这边有部电视剧无法解析https://www.bilibili.com/bangumi/play/ep175110

> C:\Users\Administrator>ykdl -i --d https://www.bilibili.com/bangumi/play/ep17511
0
DEBUG:common:video_host> www.bilibili.com
DEBUG:common:short_name> bilibili
DEBUG:html:get_content> URL: https://www.bilibili.com/bangumi/play/ep175110
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://bangumi.bilibili.com/web_api/episode/175110.
json
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.1', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\ykdl\extractors\bilibili\bilibase.py", line 49, in prepare
    self.vid, info.title = self.get_vid_title()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\ykdl\extractors\bilibili\bangumi.py", line 26, in get_vid_title
    Episode_info = json.loads(get_content('http://bangumi.bilibili.com/web_api/e
pisode/{}.json'.format(eid)))['result']
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by SeaHOH** [comment]
@skywang00 请升级

@seahog004 这个的确不能解析，我换成 av 号试试。

**Comment by SeaHOH** [comment]
看见有 av 号，解析也没问题，以为换成 av 号就能用，浪费了点时间才发现并不能。。。

**Comment by seahog004** [comment]
@SeaHOH 可以啦，非常感谢！
