### ISSUE TITLE
The Latest Release Does Not Contain A Win32 (.exe) Version

### ISSUE THREAD

**Issue by hifocus** [zhangn1985/ykdl#308]
Hi there, I've got a site for downloading your project, particularly for the win32 (.exe) version - https://chajian.hxco.de

I want to know why the latest release v1.6.2 does not contain a win32 (.exe) version? My site relies on the GitHub Release API, but if once there isn't a win32 (.exe) file in the release, the download will fail and users will get confused. 

Thank you so much.

**Comment by hifocus** [comment]
@zhangn1985 Can I please suggest you that release the `exe` version with the source code at the same time, don't delay. If not some of my users cannot download it normally.

My project [HXCO Get](https://github.com/hxco/get) relies on the official GitHub API, which will get the latest release and then redirect the user to a specific file. Once there is no matching file, the user will receive a `404` error.

```
<script>
        const repo = "https://api.github.com/repos/zhangn1985/ykdl/releases/latest";
        $.getJSON(repo).done(function (data) {
            window.location = "https://github.com/zhangn1985/ykdl/releases/download/" + (data.tag_name) + "/ykdl_win32.exe";
        })
</script>
```

So if possible, please make sure every time you make a release, there is a win32 version.

And thank you for developing such good program!!!

**Comment by jindaxia** [comment]
You can use 
![image](https://user-images.githubusercontent.com/587992/43296444-fb3a62dc-917d-11e8-9c62-24863ea398d8.png)

**Comment by hifocus** [comment]
Thanks, but that’s what I am using.
