### ISSUE TITLE
熊猫tv解析同一个直播，地址不同。ykdl不能播放，you-get能。

### ISSUE THREAD

**Issue by loveproe** [zhangn1985/ykdl#31]
> 
D:\ykdl>ykdl video_urls http://www.panda.tv/11797
ykdl: invalid url: video_urls
site:                熊猫TV (Panda)
title:               战地1- Obang的浪漫就是拉大栓
artist:              哦棒
streams:
    - format:        current
      container:     flv
      video-profile: current
      size:          inf MiB (inf bytes)
    # download-with: ykdl --format=current [URL]
ykdl: Now downloading: 战地1- Obang的浪漫就是拉大栓_2016-10-31T19-24-33.924197.flv
ykdl: stop downloading by press 'q'
http://pl3.live.panda.tv/live_panda/fc7e94515e6b34161dfea57ab956e400.flv: Immediate exit requested
Exiting normally, received signal 2.

Interrupted by Ctrl-C

D:\ykdl>you-get -u http://www.panda.tv/11797
Site:       panda.tv
Title:      战地1- Obang的浪漫就是拉大栓
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Real URLs:
http://pl10.live.panda.tv/live_panda/fc7e94515e6b34161dfea57ab956e400.flv

> 

可以看到一个是pl3,一个是pl10.奇怪一个播放一个不行。。。

**Comment by zhangn1985** [comment]
我看到你是按下了ctrl+c导致的退出。是下载卡了很久吗？

**Comment by loveproe** [comment]
先是播放卡很久不能，我就看看链接用下载参数。其他网站测试斗鱼火猫都可以播放

**Comment by zhangn1985** [comment]
了解了，我看看有没有方法可以选择CDN。
