### ISSUE TITLE
本项目的获取到的视频清晰度从高到低是不是这个顺序['4k', 'BD', 'TD', 'HD', 'SD', 'LD']？

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#313]
我主要是想获得解析出来的清晰度最高的视频信息。
目前猜测本项目的获取到的视频清晰度从高到低是这个顺序['4k', 'BD', 'TD', 'HD', 'SD', 'LD']，依赖于此，我获得解析出来的清晰度最高的视频信息的方法如下：
```
for quality in ['4k', 'BD', 'TD', 'HD', 'SD', 'LD']:
    videoInfo = video_info.streams.get(quality)
    if videoInfo:
        print(videoInfo)
        break
```

- 不知道还有没有更好的方法？

- 本项目的获取到的视频清晰度从高到低是不是这个顺序['4k', 'BD', 'TD', 'HD', 'SD', 'LD']？

**Comment by SeaHOH** [comment]
默认 info.stream_types[0] 就是最大清晰度名称。

**Comment by redstoneleo** [comment]
这样的话，获得解析出来的清晰度最高的视频信息的方法  就可以简化成这样了
video_info.streams.get(videoInfoList.stream_types[0])
