### ISSUE TITLE
添加骑士电影支持

### ISSUE THREAD

**Issue by jindaxia** [zhangn1985/ykdl#317]
> http://www.74zu.com/play/17737/1/1.html

**Comment by SeaHOH** [comment]
这网站没有备案，是盗版资源吧？

**Comment by airdge** [comment]
这相当解析第三方播放器了

**Comment by jindaxia** [comment]
@SeaHOH 是盗版网站

**Comment by SeaHOH** [comment]
域名百度的，CDN 腾讯的，不知道服务器在哪？
这个根本不用解析，它自己搞了个 API，服务器在腾讯，这是要被举报的节奏。

**Comment by jindaxia** [comment]
已解决,但是否要加进来 目前的想法是不加
