### ISSUE TITLE
sohu无法访问链接

### ISSUE THREAD

**Issue by songyingxin** [zhangn1985/ykdl#318]
请将错误输出粘贴在下面:
```
ykdl.exe https://tv.sohu.com/v/MjAxODA3MTAvbjYwMDU2NjY0Ny5zaHRtbA==.html
ERROR:YKDL:Playlist is not supported for GeneralEmbed (通用嵌入视频)with url: https://tv.sohu.com/v/MjAxODA
3MTAvbjYwMDU2NjY0Ny5zaHRtbA==.html
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

>  我用fiddler分析了整个url过程，在链接 https://vipbjyz.vod.tv.itc.cn/cdnList?new=/222/140/clLIauECTAGRbdrdGNdOwC.mp4&vid=4857390&uid=15325972986917956545&tvid=103682531&ch=tv&sz=1271_923&md=78UT29C7ggr4jXHmKzxMf5uvEvgx5lpT2Peo9g==134&prod=flash&pt=1&uuid=bee55c28-44da-1ef6-e41f-83c749862b83  下找到了视频链接： url=https://646-6.vod.tv.itc.cn/sohu/v1/TmPAo6IsWF1HNtsWhTK2befeP80DoSPBo60Ro6cVbOXUyYbSoO2B0p.mp4?k=BZLT4Y&p=jWlvzSx7qSXm0SrWj9lvzSw3omP30SXA0S1U0Swi0SkUqSx3hRYAtUxINmsdytxS0pbcWhoGgY220f&r=TUqvtvGDXixnyLbUZDWSqTPGRDN4fGoioMycY&q=OpCmhW7IWJodRDbsWD1SotE7ZDvsfJXsWYdHfhbHfJbswmbcWJe4Rh6XWGWSqD2sWBeSqF2sY&cip=202.108.14.240， 但是这个视频链接无法在浏览器上访问，这是我疑惑的一点，有懂的大牛麻烦解答一下。

**Comment by airdge** [comment]
vipbj域问题,prod=flash会有问题 改成prod=h5应该可以

**Comment by SeaHOH** [comment]
我这里是正常解析和播放的。

**Comment by airdge** [comment]
播放正常,大部分是data.vod.itc.cn的
部分地区/视频,解析出来的是vipbj**.vod.tv.itc.cn,  用prod=flash访问就会403

 http://vipbjyz.vod.tv.itc.cn/?u=1&new=/131/207/kQlTgo1PReeWp3uYIr5rkB.mp4&key=mJ5Y_X7g92o5K7aEN_8bA6dHDcFTdsCI&uid=&ca=3&pg=1&pt=&ch=my&cv=&vid=98601647&qd=mweb&mkey=0CT6F_gv1aI9zuF35LK4CYsbAKqZJy6x&uid=1917493391329808&qd=68001&src=11050001&ca=4&cateCode=101&_c=1&appid=tv&oth=&cd=&prod=flash

http://vipbjyz.vod.tv.itc.cn/?u=1&new=/131/207/kQlTgo1PReeWp3uYIr5rkB.mp4&key=mJ5Y_X7g92o5K7aEN_8bA6dHDcFTdsCI&uid=&ca=3&pg=1&pt=&ch=my&cv=&vid=98601647&qd=mweb&mkey=0CT6F_gv1aI9zuF35LK4CYsbAKqZJy6x&uid=1917493391329808&qd=68001&src=11050001&ca=4&cateCode=101&_c=1&appid=tv&oth=&cd=&prod=h5

**Comment by songyingxin** [comment]
当我用ipdb调试时，发现了下面这个问题， 这是因为无法访问：http://vipgdbgp.vod.tv.itc.cn/?prot=9&prod=flash&pt=1&file=/tv/Sample2/BackUp_Sample2/svc/20180813/104950639_4909581_tv_S_151906_78947/104950639_4909581_tv_S_151906_78947_001.mp4&new=/253/93/dr8isfqrI1hEvLvSc7IzfG.mp4&key=ZNF3Gzw87PPn13UbDTKQvFqZSe0NWD0P&vid=4909577&uid=1535523540499&t=0.2512190832210385&rb=1， 难道只是我有问题？

代码如下： 在tv.py中添加如下代码：
site = TvSohu()
site.url = "https://tv.sohu.com/v/MjAxODA4MTUvbjYwMDU4MzEzMS5zaHRtbA==.html"

info = site.prepare()
print(info.streams)

错误输出如下：
Traceback (most recent call last):
  File "tv.py", line 14, in <module>
    info = site.prepare()
  File "E:\Github\ykdl\ykdl\extractors\sohu\sohubase.py", line 67, in prepare
    self.parser_info(video, info, stream, lvid)
  File "E:\Github\ykdl\ykdl\extractors\sohu\sohubase.py", line 44, in parser_info
    self.extract_single(video, stream_id)
  File "E:\Github\ykdl\ykdl\extractors\sohu\sohubase.py", line 74, in extract_single
    info = json.loads(get_content(url))
  File "E:\Github\ykdl\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by SeaHOH** [comment]
我这里是 vipgdbgp.vod.tv.itc.cn，`prod=h5` 反而完蛋 403。

**Comment by airdge** [comment]
h5好像有限制,用html5/app/ios/android/ugc这些试下

**Comment by songyingxin** [comment]
我将中间的链接部分改为：  `json_url = 'https://vipbjyz.vod.tv.itc.cn/cdnList?new=' + new + '&vid='+str(self.vid) + '&uid='+str(int(time.time()*1000)) + '&tvid' + str(tvid) + '&ch=tv&prod=h5&pt=1' `， 然后就可以了。 请教一下两位，为什么有的地区flash可以， h5不行， 有的h5可以，而flash不行。

**Comment by songyingxin** [comment]
多谢两位的解答，十分感谢。

**Comment by SeaHOH** [comment]
@songyingxin 
你是不是之前修改过？缺少`key`参数，ykdl 也没有使用`tvid`和`ch=tv`。
尝试恢复成 ykdl 的最新版本。

**Comment by SeaHOH** [comment]
@songyingxin 改成下面这样试试
`self.realurls[stream_id].append('http://'+host+'/cdnList?prot='+str(prot)+'&prod=flash&pt=1&file='+clipURL+'&new='+new +'&key='+ ck+'&vid='+str(self.vid)+'&tvid='+str(tvid)+'&uid='+str(int(time.time()*1000))+'&t='+str(random())+'&rb=1')`

**Comment by songyingxin** [comment]
的确会限速， 但是我的域名的确需要改为： `https://vipbjyz.vod.tv.itc.cn`, 不然无法访问。 flash的确要比h5要快很多。

**Comment by SeaHOH** [comment]
@songyingxin 上面修改了一些参数，你实际试过吗？

**Comment by airdge** [comment]
uid没上报注册会限速,注册一下就不会卡了
'https://z.m.tv.sohu.com/h5_cc.gif?t=' + parseInt(new Date().getTime()) + '&uid=' + p.uid + '&position=page_adbanner&op=click&details=%7B%7D&nid=&url=http%253A%252F%252Fm.tv.sohu.com%252Fus%252F209059447%252F55773385.shtml&refer=http%253A%252F%252Fmy.tv.sohu.com%252Fus%252F209059447%252F55773385.shtml&screen=1366x768&os=ios&platform=ipad&passport=&vid=55773385&pid=6960285&channeled=1211020000&MTV_SRC=11060001';

**Comment by songyingxin** [comment]
@SeaHOH 试过了， 但是没有分离参数测试，直接把你的链接改了一下： `json_url = 'http://vipbjyz.vod.tv.itc.cn'+'/cdnList?prot='+str(prot)+'&prod=flash&pt=1&file='+clipURL+'&new='+new +'&key='+ ck+'&vid='+str(self.vid)+'&tvid='+str(tvid)+'&uid='+str(int(time.time()*1000))+'&t='+str(random())+'&rb=1'` ， 能跑已经很开心了， js不熟，实在看不下去。

**Comment by airdge** [comment]
`https://z.m.tv.sohu.com/h5_cc.gif?t=' + parseInt(new Date().getTime()) + '&uid=' + p.uid + '&position=page_adbanner&op=click&details=%7B%7D&nid=&url=http%253A%252F%252Fm.tv.sohu.com%252Fus%252F209059447%252F55773385.shtml&refer=http%253A%252F%252Fmy.tv.sohu.com%252Fus%252F209059447%252F55773385.shtml&screen=1366x768&os=ios&platform=ipad&passport=&vid=55773385&pid=6960285&channeled=1211020000&MTV_SRC=11060001`
上面的参数替换下,然后访问这个链接

**Comment by SeaHOH** [comment]
注册有效，等会儿更新下。

**Comment by songyingxin** [comment]
@SeaHOH @airdge  请教一个关于mgtv的问题， 当我尝试使用requests重写mgtv.py时 ， 如何获取cookie？ 源代码的这部分我理解不了：
```
handlers = [HTTPCookieProcessor()]
        if default_proxy_handler:
            handlers += default_proxy_handler
        install_opener(build_opener(*handlers))
```
请两位大佬指点一下。

**Comment by SeaHOH** [comment]
default_proxy_handler 是默认 handler 列表
HTTPCookieProcessor 处理 cookies
最后一句就是重新安装添加处理 cookies

**Comment by songyingxin** [comment]
但是是如何获取cookie的？我的意思是，cookie在一个会话中维持， 那最初的那个cookie从何而来。 感谢大佬解答。

**Comment by jindaxia** [comment]
```Python
cookie = cookiejar.CookieJar()
    handler = urllib.request.HTTPCookieProcessor(cookie)
    opener = urllib.request.build_opener(handler)
    resp = opener.open(url)

    cookieStr = ''
    for item in cookie:
        cookieStr = cookieStr + item.name + '=' + item.value + ';'
```

**Comment by songyingxin** [comment]
@jindaxia 这个我知道，我就是不知道最初的那个cookie从何而来， 我将url换为真实的mgtv 视频url， 返回的cookie只有一个条目，且并不是需要的。

**Comment by SeaHOH** [comment]
>将url换为真实的mgtv 视频url， 返回的cookie只有一个条目，且并不是需要的。

没有看明白，能再说详细点吗？
使用了 HTTPCookieProcessor 之后，request 模块会自动管理 cookies，就像浏览器一样。

**Comment by songyingxin** [comment]
from http import cookiejar
import urllib

url = "https://www.mgtv.com/l/100021955/4506798.html"
cookie = cookiejar.CookieJar()
handler = urllib.request.HTTPCookieProcessor(cookie)
opener = urllib.request.build_opener(handler)
resp = opener.open(url)

cookieStr = ''
for item in cookie:
    cookieStr = cookieStr + item.name + '=' + item.value + ';'
print(cookieStr)


然而输出是为空的。

**Comment by songyingxin** [comment]
不是首先是url1， 然后从url2中获取pm参数， 生成url3， 整个过程我是了解的。 测试如下：

```
from urllib.request import Request, urlopen, HTTPSHandler, build_opener, HTTPCookieProcessor, install_opener, ProxyHandler

fake_headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1'
}

def get_content(url, headers=fake_headers, data=None, charset = None, cookie=None):
    """Gets the content of a URL via sending a HTTP GET request.

    Args:
        url: A URL.
        headers: Request headers used by the client.
        decoded: Whether decode the response body using UTF-8 or the charset specified in Content-Ty  pe.

    Returns:
        The content as a string.
    """
    req = Request(url, headers=headers, data=data)
    #if cookies_txt:
    #    cookies_txt.add_cookie_header(req)
    #    req.headers.update(req.unredirected_hdrs)
    response = urlopen(req)
    data = response.read()
    return data

default_proxy_handler = []

handlers = [HTTPCookieProcessor()]
if default_proxy_handler:
    handlers += default_proxy_handler
install_opener(build_opener(*handlers))

url1 = "https://www.mgtv.com/l/100021955/4506798.html"
url2 = 'https://pstream.api.mgtv.com/player/video?video_id=4506798&did=c477fa3e-84d5-4086-9bec-a29a61bce900&suuid=c44f04ba-8d3a-4394-b087-6199d527274d&cid=323716&pid=100021955&tk2=wADMx0zbuBHfwATOlNmYxYTY5ITYtMWZilTL2gDM00SNkRDOtU2MhZ2N3QzY9QWakxnNxEjM0UTNzUTM9QXasNGfxADMw4yMuATPyVmd&_support=10000000'

url3 = 'https://pstream.api.mgtv.com/player/getSource?video_id=4506798&did=c477fa3e-84d5-4086-9bec-a29a61bce900&suuid=c44f04ba-8d3a-4394-b087-6199d527274d&collection_id=323716&pm2=pA2E9Mq5nY6YDjXVIBHklmn70HN2cfUHeK~GOXz~jtZyLmHUZUuJo1y~_oXYeAQEa_A9nF~x~pMvEwC5AR7ckOM01O2DNpudvMKblN9x3GvNXC_8f7a~NGPoaDVJnpUS_n9afYN8Q6eRx9mhS0rJEEkXmWPQU5mjExuYQLmP6B1eMe8ajv2QHC6JbGHauePfs0kiPFp03fDv9LBIWJXGQKWwJ4AUU83MP4VffHYLdaoyGoE0zvs8S3Jmy622GX9pR6sArZgiq9PKVi5BTaZJptcACSdeZspiULG80FF3oQmvPvLEjI3wT7hdlYPmROqfc6~b32Z4dxw-&tk2=wADMx0zbuBHfwATOlNmYxYTY5ITYtMWZilTL2gDM00SNkRDOtU2MhZ2N3QzY9QWakxnNxEjM0UTNzUTM9QXasNGfxADMw4yMuATPyVmd&_support=10000000'

res1 = get_content(url1)
res2 = get_content(url2)
res3 = get_content(url3)
print(res2)
```

**Comment by songyingxin** [comment]
我是直接将url抓出来测试，难道这样测试有问题？

**Comment by SeaHOH** [comment]
ykdl 定义的 get_content 无法获取 cookies，安装 HTTPCookieProcessor 到默认 opener 能让它自动处理。
如果你要干预其中的过程，就必须自定义，就是你先前使用 CookieJar 的做法。

**Comment by songyingxin** [comment]
原来如此，但是我是无法显式的获取cookie的，正如前面所言，返回的cookie为空， 如果我用requests来写的话应该怎么处理？ 如果您有时间的话，能不能写一个小demo演示一下，十分感谢。 您能回答这么多已经很感谢了。

**Comment by SeaHOH** [comment]
之前学习的时候在网络上能搜到许多很详细的资料，但是我用不到就没有实际写过 CookieJar 相关的代码，
你可以直接搜索相关关键字。

**Comment by songyingxin** [comment]
谢谢了，我再思考思考。

**Comment by jindaxia** [comment]
需要用同一个opener的实例 去访问多个url,才能传递cookie吧, 调用三次get_content是三个不同的连接..你可以试一下

**Comment by airdge** [comment]
不太懂python语法,,,大概就是这样
```
from urllib import request
from http import cookiejar
import json
 
if __name__ == '__main__': 
    vid = '4149630'
    cookie = cookiejar.CookieJar() 
    handler=request.HTTPCookieProcessor(cookie) 
    opener = request.build_opener(handler) 

    getVideo = opener.open('http://pcweb.api.mgtv.com/player/video?video_id='+ vid +'&keepPlay=0&vid=&watchTime=0&did=8434090f-2c42-9019-0ba7-37dbcef3333c&tk2=5kzM2kTN1MTNx0Ddpx2Y8FTMyEjLz4CM9IXZ2xXMwAzM98mbwx3YzMzMzYWZjJGZ3MTL3EmYw0SOxATOtIDNjJTLmBTOwQzM0gTPklGZ') 
    videoJSON = json.loads(getVideo.read().decode('utf-8'))
    atc = videoJSON['data']['atc'] 
 
    getSource= opener.open('https://pstream.api.mgtv.com/player/getSource?tk2=' + atc['tk2'] + '&pm2=' + atc['pm2'] + '&video_id=' +  vid + '&type=pch5') 
    sourceJson = json.loads(getSource.read().decode('utf-8'))
    stream = sourceJson['data']['stream']

    getHls = opener.open('https://web-disp.titan.mgtv.com'+stream[0]['url'])
    hlsJson = json.loads(getHls.read().decode('utf-8'))

    print(hlsJson['info'])
```

**Comment by songyingxin** [comment]
@airdge 原来如此， 我懂了， cookie显式的获取是不可行的吧， 我尝试打印出cookie，只有`PM_CHKID=3bf6c949ca410418;` 这个参数。 感谢大佬。

**Comment by airdge** [comment]
@songyingxin  你用封装的函数去获取其他链接,在此过程没有把第一次获取的cookies传递进去 所以就获取不到数据
