### ISSUE TITLE
youku视频

### ISSUE THREAD

**Issue by songyingxin** [zhangn1985/ykdl#319]
对于youku视频的破解我提一点看法， 我使用pychrome来获取包含m3u8文件的地址，如下：
```
https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/?jsv=2.4.11&appKey=24679788&t=1535681880170&sign=aa028f99577371af04ca29efc09eea6a&api=mtop.youku.play.ups.appinfo.get&v=1.1&timeout=20000&YKPid=20160317PLF000211&YKLoginRequest=true&AntiFlood=true&AntiCreep=true&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=%7B%22steal_params%22%3A%22%7B%5C%22ccode%5C%22%3A%5C%220502%5C%22%2C%5C%22client_ip%5C%22%3A%5C%22192.168.1.1%5C%22%2C%5C%22utid%5C%22%3A%5C%22KAzfE6LzUAcCAcpsDvDsMj4%2F%5C%22%2C%5C%22client_ts%5C%22%3A1535681880%2C%5C%22version%5C%22%3A%5C%220.5.68%5C%22%2C%5C%22ckey%5C%22%3A%5C%22110%23ZkckAUkfkJDK5%2B2ugUcUMuy2kMZXmTkeceNOFUK2hQ7%2F8xPg4UUzcMdyjwucSltVLSsQ3HmMhxFqfxGu2EsjYMwujwa0oG%2BX8zLYmwckhJSTHcUIbRjIuKxGqLyufv81JYHQYlZZtdm9XTvwsTvsZBEj%2BAciskT47Tm04Ek4Dh23pOBGDabUdZX3bgyivbG9GpIiuvSiBm23sLgis9FkkcjQstvBs8ZkGLmwjTSI9r1Zgs05jtPkIcaOIwh9GThD2wHakT6UQ566JuQJe2RjrmnODVbCzUJGbllHCn8JxfCzzPqP7LIKLfiW%2FGE2KcYHIt69%2FuIzbvfaNmXv1bv8n%2FU%2B7tfCvvLeRXrilutzVTEXX8txUYrv%2F7Cy98EzRnub4FWMpn%2FuTeHyYNX24wA2qcNalfrU3QAHqqvwPs7pYtlxV1DhpsyFsLJmIz7FnKUMrTqkkWIcoO5BVsy%2FYgA06g4CKTRjF%2Fr2WCZftPvkajFlwL1XFz99%2BDCClmV4r4bBX1Pg5ytLfI3s0YCY0WZWHTrCEEYGgwWiBKEiTTzKjqz3M0v46dvCnHjXnwQyUI53VZ6CO2M7OFcD8Rw%2BoYq1mfOHZnX29OgHyI5GEabwNXeX64LAfsZm6MMvLkLTGp61XnBl1r9cWCjszV1J5%2FAPL9a%2FFNuAhSpmJgnRviH3ljf80bhfxzg7TJQbsu10rN1TKXc7fF7QQQKRJKDDgTgh%5C%22%7D%22%2C%22biz_params%22%3A%22%7B%5C%22vid%5C%22%3A%5C%22XMzc1NDEyMDQ3Ng%3D%3D%5C%22%2C%5C%22current_showid%5C%22%3A%5C%22310741%5C%22%7D%22%2C%22ad_params%22%3A%22%7B%5C%22site%5C%22%3A1%2C%5C%22wintype%5C%22%3A%5C%22interior%5C%22%2C%5C%22p%5C%22%3A1%2C%5C%22fu%5C%22%3A0%2C%5C%22vs%5C%22%3A%5C%221.0%5C%22%2C%5C%22rst%5C%22%3A%5C%22mp4%5C%22%2C%5C%22dq%5C%22%3A%5C%22flv%5C%22%2C%5C%22os%5C%22%3A%5C%22win%5C%22%2C%5C%22osv%5C%22%3A%5C%22%5C%22%2C%5C%22d%5C%22%3A%5C%220%5C%22%2C%5C%22bt%5C%22%3A%5C%22pc%5C%22%2C%5C%22aw%5C%22%3A%5C%22w%5C%22%2C%5C%22needbf%5C%22%3A1%2C%5C%22atm%5C%22%3A%5C%22%5C%22%7D%22%7D
```
然后，我想访问获取视频url的话，直接访问该url就行，但该视频的访问需要添加cookie与referer， 其中，cookie中两个重要的参数分别为： _m_h5_tk 和  _m_h5_tk_enc（目前来看，这两个参数是固定的）。
该方法的好处在于不需要不断的破解js， 只需要关注cookie的这两个参数即可
缺点在于： 解析速度可能较慢，大概5-10秒， 且需要先打开chrome的headless模式， 且windows下，chrome不能命令行运行。

**Comment by airdge** [comment]
类似于phantomjs
把所有的流程跑一遍 再来操作DOM
批量下载估计不适用,也行不通

**Comment by songyingxin** [comment]
比phantomjs强大， selenium + phantomjs是无法获取整个过程中访问的链接的。 pychrome是对chrome接口的封装， 记录了访问的整个过程， 类似抓包。 我认为这不是操作dom， 而是直接获取json文件或视频地址。 批量下载的话开多线程 + docker我觉得是可行的。 再说对于个人用户而言， 往往只是下载一个视频， 如果应用到公司中并发， 我觉得docker是一个比较好的方案。

我觉得，这样可维护性更好。 可以极大的降低开发成本。

**Comment by airdge** [comment]
优酷有频率限制,超出一定量会有账户异常提示,要登陆才能正常播放 
这种依托浏览器内核的访问,短时间内,获取部分视频确实没啥问题
但对于大批量应该是行不通的,还是要解决账户cookies问题

**Comment by songyingxin** [comment]
账户cookie， 我能不能每次直接读取chrome中保存的cookie信息？ 如果我使用pychrome来访问的话， 我的cookie信息就一定是最新的了。

**Comment by songyingxin** [comment]
我是觉得是维护问题， 如果网站再次变更的话， 有需要破解，这样维护成本太大了。 我的思路是找到一个维护成本很低的方案， 效率之类的我觉得问题不大， 添加服务器就是了， 服务器总比人力要便宜不是。

**Comment by airdge** [comment]
```
import pychrome
import os

os.system("/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222")

browser = pychrome.Browser(url="http://127.0.0.1:9222")
tab = browser.new_tab()


def ChromeSent(**kwargs):
    if kwargs.get('request').get('url').find('acs.') > 0:
        print(kwargs)


tab.set_listener("Network.requestWillBeSent", ChromeSent)
tab.start()
tab.call_method("Network.enable")
tab.call_method("Page.navigate", url="https://v.youku.com/v_show/id_XMzc3ODI0NzA4MA==.html", _timeout=5)
tab.wait(5)
tab.stop()

browser.close_tab(tab)
```
响应
`{'requestId': '1000022934.622', 'loaderId': 'A7C5E2F2203CB1D7573556AAC7FD28CF', 'documentURL': 'https://v.youku.com/v_show/id_XMzc3ODI0NzA4MA==.html', 'request': {'url': 'https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/?jsv=2.4.11&appKey=24679788&t=1535812896761&sign=c12261dae4121aa3f1b106606ae0b427&api=mtop.youku.play.ups.appinfo.get&v=1.1&timeout=20000&YKPid=20160317PLF000211&YKLoginRequest=true&AntiFlood=true&AntiCreep=true&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=%7B%22steal_params%22%3A%22%7B%xxxxxxxxxxxxxxxxxxxxxxxxxx', 'method': 'GET', 'headers': {'Referer': 'https://v.youku.com/v_show/id_XMzc3ODI0NzA4MA==.html', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}, 'mixedContentType': 'none', 'initialPriority': 'Low', 'referrerPolicy': 'no-referrer-when-downgrade'}, 'timestamp': 531456.092231, 'wallTime': 1535812896.7647, 'initiator': {'type': 'script', 'stack': {'callFrames': [{'functionName': 'r', 'scriptId': '32', 'url': 'https://g.alicdn.com/player/ykplayer/0.5.68/youku-player.min.js', 'lineNumber': 1, 'columnNumber': 177271}]}}, 'type': 'Script', 'frameId': 'EED1611BDD0CFC9C491E7018B51059C7', 'hasUserGesture': False}`
不太清楚这个模块,但从输出看
pychrome只输出头响应,并没有返回内容,也没cookies信息


另外:pychrome是不是只能用于原生chrome?
       第三方应用调用,或者部署在服务器的,还要一系列的设置,用户学习使用成本增加

**Comment by redstoneleo** [comment]
谷歌官方文档 Headless Chrome
https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by songyingxin** [comment]
@redstoneleo  这个我看过， 用过， 没什么价值啊，就是介绍了一下headless 模式而已。

**Comment by airdge** [comment]
这个必须要chrome浏览器,然鹅,并不是所有的用户都在使用原生浏览器
对于那些第三方/GUI集成,一部分用户是解析不到的

对于部署在服务器上的,用这种方式去解析JSON的,更行不通
pychrome是打开一个实体标签,等超时再关闭该标签,如果遇到高并发,是不是要同时打开大量的标签,消耗更多的内存

当然,自己本地使用完全没问题

**Comment by songyingxin** [comment]
额， 高并发的话，， 的确是个问题， 但是我觉得， 视频爬虫，维护成本要 》服务器成本。 此外，如果我采用docker + pychrome来做集群完成高并发的话， 不知道可行不可行，正在试。 您的意思是，如果不考虑高并发因素的话，在服务器端使用该方案可行吗？

**Comment by airdge** [comment]
自用/量小 不考虑解析耗时  基本没问题
但如果,视频网站更改策略,在加载完AD,才加载解析,这种方式也没用

**Comment by redstoneleo** [comment]
1 把ykdl放在服务器上面用的话基本不用想了，即便能解析，也是根据服务器的位置分配出当地的视频url（为了加速视频传输），当然除非你们可以解析到自动根据客户端地理位置分配的视频url；
2 视频前面的广告我看不必要太担心，有个“广告终结者”的Chrome插件，可以屏蔽国内主流视频网站的广告，用了好一段时间了，一直有效，所以可以参考一下；
3 不一定非要用pychrome呀，也可以用Selenium，它似乎更出名一点，我用的是百分浏览器，可以和它搭配使用，此外也可以考虑`PyQt5.QtWebEngine`（包装了blink内核），

**Comment by HuShanquan3** [comment]
cookie很好获取啊，asc获取就可以了

**Comment by redstoneleo** [comment]
你的这个方法还有效吗？我访问你说的url返回
`mtopjsonp1({"api":"mtop.youku.play.ups.appinfo.get","data":{},"ret":["FAIL_SYS_TOKEN_EMPTY::令牌为空"],"v":"1.1"})`
