### ISSUE TITLE
请求添加北邮人电视直播

### ISSUE THREAD

**Issue by Kimi-Arthur** [zhangn1985/ykdl#329]
起始地址：http://ivi.bupt.edu.cn/
视频流逻辑：
- 每个电视台有一个对应的m3u8，如http://ivi.bupt.edu.cn/hls/cctv5hd.m3u8
- 该文件包含当前视频片段的相对路径，如：
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:78055
#EXT-X-TARGETDURATION:10
#EXTINF:10.000,
cctv5hd-1537371574000.ts
#EXTINF:10.000,
cctv5hd-1537371584000.ts
#EXTINF:10.000,
cctv5hd-1537371594000.ts
#EXTINF:10.000,
cctv5hd-1537371605000.ts
#EXTINF:10.000,
cctv5hd-1537371614000.ts
#EXTINF:10.000,
cctv5hd-1537371625000.ts
```

比如第一条对应的视频地址为：http://ivi.bupt.edu.cn/hls/cctv5hd-1537371574000.ts

视频文件地址过一段时间即会失效

- m3u8文件的内容会随时间不断变化，但基本是当前时间的时间戳附近的时间点

**Comment by SeaHOH** [comment]
HLS 直播不是该用播放器么？

**Comment by SeaHOH** [comment]
速度不够就没法

**Comment by SeaHOH** [comment]
就是想看体育频道吧，不一定非要用这个源啊，其它手段多的是。

**Comment by zhangn1985** [comment]
`ffmpeg -y -protocol_whitelist file,tcp,http -i http://ivi.bupt.edu.cn/hls/cctv5hd.m3u8 -c copy -absf aac_adtstoasc aaa.mp4`

**Comment by zhangn1985** [comment]
因为该页面直接提供m3u8，可以直接使用现有工具，必须要ykdl来支持。

**Comment by SeaHOH** [comment]
他是国外速度太慢，放不了也录不成。
换个源就成，比如 cntv 官网的，不过这个估计要代理。

**Comment by zhangn1985** [comment]
国内也很慢

**Comment by SeaHOH** [comment]
哦，可能是人家校内用的，校外就 GG 了。

**Comment by mengmo** [comment]
教育网内的源会有多快?

**Comment by Kimi-Arthur** [comment]
其实我就想问问基于ykdl好不好做

**Comment by SeaHOH** [comment]
上面说了，这个跟 ykdl 完全无关，一直都有现成的工具。
比如 zhangn1985 提到的 ffmpeg，还有一些播放器也能录。

**Comment by airdge** [comment]
这类工具只是简化下载流程,并没有cdn加速   除非资源有cdn节点     
下载速度还是要看自己的网速和资源的带宽

**Comment by jindaxia** [comment]
我只能安利个 我主要参与的项目了,  KODI  配一个 PVR搞定, 如果有EPG数据,可以定时定频道录像
