### ISSUE TITLE
列表下载，-l 只能下载部分

### ISSUE THREAD

**Issue by hpuyj** [zhangn1985/ykdl#331]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
![tim 20180929213910](https://user-images.githubusercontent.com/38468895/46246456-8003b100-c430-11e8-83d9-2d54df0b4720.png)

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
ykdl --format=TD -l https://v.qq.com/x/cover/lcpwn26degwm7t3/a002708679j.html这个链接，。每次下到第四集就结束了，后面的视频没法下载

**Comment by SeaHOH** [comment]
直接播放列表没有问题，我不用下载，不清楚结果如何。
只能看出是 API 未返回结果，主动断开了连接。
也许你可以把`--debug`加进去，看看到底是哪个请求失败。
