### ISSUE TITLE
优酷解析 的python 能解释下执行的细节么？

### ISSUE THREAD

**Issue by wnpllrzodiac** [zhangn1985/ykdl#334]
需要翻译成java版本
hashCode() 函数实现的是什么功能？
struct.pack 是什么作用？

```
def hashCode(str):
    res = c_int(0)
    if not isinstance(str, bytes):
        str = str.encode()
    for i in bytearray(str):
        res = c_int(c_int(res.value * 0x1f).value + i)
    return res.value

def generateUtdid():
    timestamp = int(time.time()) - 60 * 60 * 8
    i31 = random.randint(0, (1 << 31) - 1)
    imei = hashCode(str(i31))
    msg = struct.pack('!2i2bi', timestamp, i31, 3, 0, imei)
    key = b'd6fc3a4a06adbde89223bvefedc24fecde188aaa9161'
    data = hmac.new(key, msg, hashlib.sha1).digest()
    msg += struct.pack('!i', hashCode(base64.standard_b64encode(data)))
return base64.standard_b64encode(msg)
```

**Comment by airdge** [comment]
hashCode()应该是这个
```
  public static int b(String paramString)
  {
    int i = paramString.length();
    int j = 0;
    if (i > 0)
    {
      paramString = paramString.toCharArray();
      i = 0;
      for (;;)
      {
        k = i;
        if (j >= paramString.length) {
          break;
        }
        i = i * 31 + paramString[j];
        j++;
      }
    }
    int k = 0;
    return k;
  }
```

**Comment by airdge** [comment]
反编译优酷apk 直接提取算法不是更快

**Comment by SeaHOH** [comment]
https://github.com/iawia002/annie/pull/238
来源是这里，至于对方怎么获取的，没有说明。

**Comment by wnpllrzodiac** [comment]
BTW，优酷TV版支持倍速播放么？ LP提的需求，好像没找到，问下各位大神。。。。

**Comment by wnpllrzodiac** [comment]
> 
> 
> 反编译优酷apk 直接提取算法不是更快

竟然没有用apk加固？
现在很多apk都用了万恶的加固技术，反编译不了啊。

**Comment by airdge** [comment]
早期版本有未加固的 还有部分apk有关联优酷的 都能提取

**Comment by SeaHOH** [comment]
感觉再过段时间，这个 key 又会报废，做好心理准备。 :smiling_imp:

**Comment by wnpllrzodiac** [comment]
哎，搞起来越来越复杂了。。。。。pptv的ppbox sdk一劳永逸啊。用到现在了。

**Comment by SeaHOH** [comment]
你这个是 0516，0103010102 确实还能用，是完整的。

**Comment by airdge** [comment]
此类ccode属于网页端的,分为全长和预览两种形式
比如访问手机优酷网页,播放连续剧只会给几分钟播放,并要求前往app观看全集,这种就是使用了预览ccode

全长:0502/0511/0512/0515/0519... 预览:0505/0503/0516/0517/0590..
部分视频使用预览ccode不能解析全长视频,具体由json.data.show.copyright字段控制

**Comment by wnpllrzodiac** [comment]
```
private static int hashCode(String str) {
        int k = 0;
        if (str.length() > 0) {
            int i = 0;
            for (int j=0;j<str.length();j++) {
                k = i;
                i = i * 31 + str.charAt(j);
            }
        }
        return k;
    }

    private static String generateUtdid() {
        long timestamp = System.currentTimeMillis() / 1000 - 60 * 60 * 8;
        Random rand = new Random();
        int i31 = rand.nextInt();
        int imei = hashCode(String.valueOf(i31));

        ByteArrayOutputStream b = new ByteArrayOutputStream();
        DataOutputStream d = new DataOutputStream(b);
        try {
            //msg = struct.pack('!2i2bi', timestamp, i31, 3, 0, imei);
            d.writeInt((int)timestamp);
            d.writeInt(i31);
            d.writeChar(3);
            d.writeChar(0);
            d.writeInt(imei);
            byte[] text = b.toByteArray();

            // data = hmac.new(key, msg, hashlib.sha1).digest()
            final String KEY_ENCODING = "utf-8";
            final String MAC_NAME = "HmacSHA1";
            String key = "d6fc3a4a06adbde89223bvefedc24fecde188aaa9161";
            SecretKey secretKey = new SecretKeySpec(key.getBytes(KEY_ENCODING), MAC_NAME);
            //生成一个指定 Mac 算法 的 Mac 对象
            Mac mac = Mac.getInstance(MAC_NAME);
            //用给定密钥初始化 Mac 对象
            mac.init(secretKey);
            //完成 Mac 操作
            byte[] encrypted = mac.doFinal(text);
            if (encrypted == null) {
                LogUtil.error(TAG, "failed to do sha1");
                return null;
            }

            //msg += struct.pack('!i', hashCode(base64.standard_b64encode(data)))
            //return base64.standard_b64encode(msg)
            d.writeInt(hashCode(Base64Util.encode(encrypted)));

            return Base64Util.encode(b.toByteArray());
        } catch (IOException e) {
            e.printStackTrace();
            LogUtil.error(TAG, "generateUtdid IOException: " + e.getMessage());
            return null;
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (InvalidKeyException e) {
            e.printStackTrace();
        }

        return null;
    }
```

**Comment by wnpllrzodiac** [comment]
generateUtdid 我写的好像不行

https://ups.youku.com/ups/get.json?vid=XMzg1MjkyNDI1Mg&ccode=0103010102
&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026&client_ip=192.168.1.1&utid=W7qiA0Ht9wcAAwAAjU0zDHrOnxg=&client_ts=1538986627

**Comment by SeaHOH** [comment]
https://github.com/zhangn1985/ykdl/issues/334#issuecomment-427739753
上面不是有嘛，干嘛要自己写？

**Comment by wnpllrzodiac** [comment]
改了下，好像可以拿到json了

https://ups.youku.com/ups/get.json?vid=XMzg1MjkyNDI1Mg&ccode=0103010102&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026&client_ip=192.168.1.1&utid=W7skOvwlG94DABeRJw3nrmom&client_ts=1538991162

**Comment by wnpllrzodiac** [comment]
最后返回的k有点诡异啊。

public static int b(String paramString)
  {
    int i = paramString.length();
    int j = 0;
    if (i > 0)
    {
      paramString = paramString.toCharArray();
      i = 0;
      for (;;)
      {
        k = i;
        if (j >= paramString.length) {
          break;
        }
        i = i * 31 + paramString[j];
        j++;
      }
    }

    **int k = 0;
    return k;**

  }

**Comment by wnpllrzodiac** [comment]
> 
> 
> [#334 (comment)](https://github.com/zhangn1985/ykdl/issues/334#issuecomment-427739753)
> 上面不是有嘛，干嘛要自己写？

有点不对啊。

**Comment by airdge** [comment]
早前反编译其他apk顺手得到的,非cibn/优酷apk  
nodejs/php转换后都能用,就发出来了
从代码上看 也知道要return i

**Comment by pierswu** [comment]
> ```
> private static int hashCode(String str) {
>         int k = 0;
>         if (str.length() > 0) {
>             for (int j=0;j<str.length();j++) {
>                 k = k * 31 + str.charAt(j);
>             }
>         }
>         return k;
>     }
> 
> 
>     private static class msi
>     {
>         public static byte[] a(int paramInt)
>         {
>             int j = (byte)(paramInt % 256);
>             paramInt >>= 8;
>             int k = (byte)(paramInt % 256);
>             paramInt >>= 8;
>             int i = (byte)(paramInt % 256);
>             return new byte[] { (byte)((paramInt >> 8) % 256), (byte)i, (byte)k, (byte)j };
>         }
>     }
> 
>     private static String generateUtdid() {
>         int timestamp = (int)(System.currentTimeMillis() / 1000);
>         Random rand = new Random();
>         int i31 = rand.nextInt();
>         byte[] ts_bytes = msi.a(timestamp);
>         byte[] i31_bytes = msi.a(i31);
>         byte[] imei_bytes = msi.a(hashCode(String.valueOf(i31)));
> 
>         ByteArrayOutputStream b = new ByteArrayOutputStream();
>         DataOutputStream d = new DataOutputStream(b);
>         try {
>             //msg = struct.pack('!2i2bi', timestamp, i31, 3, 0, imei);
>             d.write(ts_bytes, 0, 4);
>             d.write(i31_bytes, 0, 4);
>             d.write(3);
>             d.write(0);
>             d.write(imei_bytes, 0, 4);
> 
>             byte[] text = b.toByteArray();
>             StringBuffer sb = new StringBuffer();
>             for (int i=0;i<text.length;i++) {
>                 sb.append(text[i]);
>             }
>             LogUtil.info(TAG, "text: " + sb.toString());
> 
>             // data = hmac.new(key, msg, hashlib.sha1).digest()
>             final String KEY_ENCODING = "utf-8";
>             final String MAC_NAME = "HmacSHA1";
>             String key = "d6fc3a4a06adbde89223bvefedc24fecde188aaa9161";
>             SecretKey secretKey = new SecretKeySpec(key.getBytes(KEY_ENCODING), MAC_NAME);
>             //生成一个指定 Mac 算法 的 Mac 对象
>             Mac mac = Mac.getInstance(MAC_NAME);
>             //用给定密钥初始化 Mac 对象
>             mac.init(secretKey);
>             //完成 Mac 操作
>             byte[] encrypted = mac.doFinal(text);
>             if (encrypted == null) {
>                 LogUtil.error(TAG, "failed to do sha1");
>                 return null;
>             }
> 
>             //msg += struct.pack('!i', hashCode(base64.standard_b64encode(data)))
>             //return base64.standard_b64encode(msg)
>             int last = hashCode(Base64Util.encode(encrypted));
>             byte[] last_bytes = msi.a(last);
>             d.write(last_bytes, 0, 4);
> 
>             return Base64Util.encode(b.toByteArray());
>         } catch (IOException e) {
>             e.printStackTrace();
>             LogUtil.error(TAG, "generateUtdid IOException: " + e.getMessage());
>             return null;
>         } catch (NoSuchAlgorithmException e) {
>             e.printStackTrace();
>         } catch (InvalidKeyException e) {
>             e.printStackTrace();
>         }
> 
>         return null;
>     }
> ```

您好，这段代码我运行拿到的utid不能够获取视频
能发一下您最终的代码吗？

**Comment by airdge** [comment]
时间戳减8小时

**Comment by pierswu** [comment]
> 时间戳减8小时

谢谢，可以获取了。
`package com.yuxun.fantuan.country;

import org.springframework.util.Base64Utils;

import javax.crypto.Mac;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.management.openmbean.InvalidKeyException;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.URLEncoder;
import java.security.NoSuchAlgorithmException;
import java.util.Random;

public class YoukuUtid {


    private static byte[] intToByte(int paramInt) {
        int j = (byte) (paramInt % 256);
        paramInt >>= 8;
        int k = (byte) (paramInt % 256);
        paramInt >>= 8;
        int i = (byte) (paramInt % 256);
        return new byte[]{(byte) ((paramInt >> 8) % 256), (byte) i, (byte) k, (byte) j};
    }

    private static String generateUtdid() {
        int timestamp = (int) (System.currentTimeMillis() / 1000) - 60 * 60 * 8;
        Random rand = new Random();
        int i31 = rand.nextInt();
        byte[] ts_bytes = intToByte(timestamp);
        byte[] i31_bytes = intToByte(i31);
        byte[] imei_bytes = intToByte(String.valueOf(i31).hashCode());

        ByteArrayOutputStream b = new ByteArrayOutputStream();
        DataOutputStream d = new DataOutputStream(b);
        try {
            //msg = struct.pack('!2i2bi', timestamp, i31, 3, 0, imei);
            d.write(ts_bytes, 0, 4);
            d.write(i31_bytes, 0, 4);
            d.write(3);
            d.write(0);
            d.write(imei_bytes, 0, 4);

            byte[] text = b.toByteArray();
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < text.length; i++) {
                sb.append(text[i]);
            }

            // data = hmac.new(key, msg, hashlib.sha1).digest()
            final String KEY_ENCODING = "utf-8";
            final String MAC_NAME = "HmacSHA1";
            String key = "d6fc3a4a06adbde89223bvefedc24fecde188aaa9161";
            SecretKey secretKey = new SecretKeySpec(key.getBytes(KEY_ENCODING), MAC_NAME);
            //生成一个指定 Mac 算法 的 Mac 对象
            Mac mac = Mac.getInstance(MAC_NAME);
            //用给定密钥初始化 Mac 对象
            mac.init(secretKey);
            //完成 Mac 操作
            byte[] encrypted = mac.doFinal(text);
            if (encrypted == null) {
                return null;
            }

            //msg += struct.pack('!i', hashCode(base64.standard_b64encode(data)))
            //return base64.standard_b64encode(msg)
            byte[] encode = Base64Utils.encode(encrypted);
            int last = new String(encode).hashCode();
            byte[] last_bytes = intToByte(last);
            d.write(last_bytes, 0, 4);

            byte[] encode1 = Base64Utils.encode(b.toByteArray());
            return URLEncoder.encode(new String(encode1),"utf-8") ;
        } catch (IOException | java.security.InvalidKeyException | NoSuchAlgorithmException | InvalidKeyException e) {
            return null;
        }
    }

    public static void main(String[] args) {
        String s = generateUtdid();
        System.out.println(s);
    }

}`
