### ISSUE TITLE
请问现在下载优酷电视剧为什么不完整？

### ISSUE THREAD

**Issue by hf97542** [zhangn1985/ykdl#341]
请问现在下载优酷电视剧为什么不完整，只有13分钟时间？

看着下载时有2.3百M，下好以后只有60多M

**Comment by redstoneleo** [comment]
确实如此，只能下载6min
https://v.youku.com/v_show/id_XMzgxNDM5Mzg2MA==.html?spm=a2hww.11359951.m_26657.5~1~3~A

**Comment by SeaHOH** [comment]
#314
