### ISSUE TITLE
爱奇艺下载出错

### ISSUE THREAD

**Issue by damoguyanzero** [zhangn1985/ykdl#35]
这两天下载爱奇艺视频时，下载了几个片段后就出现“由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。”的错误。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/issues/39 应该和这个问题类似。

iqiyi的链接在一段时间之后超时，失效。
