### ISSUE TITLE
QQ分段下载，某分段下载失败后无法自动重试，错误文件也不会删除。

### ISSUE THREAD

**Issue by scegg** [zhangn1985/ykdl#351]
下载QQ视频，如果某段失败（未100%），错误文件会保留，并在ffmpeg合并时报错。
错误文件不会被删除。
人工重试之前要手工看日志，并猜测哪个文件是不完整的来删除。

**Comment by SeaHOH** [comment]
刚看了下，没发现问题。
你不要额外进行任何操作，只是重新运行下载一次即可。
