### ISSUE TITLE
芒果TV解析失效

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#357]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i --debug https://www.mgtv.com/b/291694/2999502.html
DEBUG:common:video_host> www.mgtv.com
DEBUG:common:short_name> mgtv
DEBUG:html:get_content> URL: https://pcweb.api.mgtv.com/player/video?video_id=2999502&did=603da02e-0233-420b-b8b9-4b8795e64ffd&tk2=zgDN5IjN0QTNx0Ddpx2Y8RmZmRjNlVTO3gjY00SOihjYtIGMyQTLzMjMw0SZyATYkNDM20DZpRGfxADMw4yMuATPyVmd8BDMwETPv5Gc
DEBUG:html:get_content> Charset: utf8
DEBUG:html:get_content> URL: https://pcweb.api.mgtv.com/player/getSource?video_id=2999502&did=603da02e-0233-420b-b8b9-4b8795e64ffd&pm2=swQFbvijSfGlHHL_A9j9lIW9GScptUNvm1zn8FSwgrQddFnpAEnjUEkUxV0PyEzPdKXeRwreMuPGCjbz0OIwIiHo9Nh6hsseICuDCBOyeBCmd3XIw5X8xPlmnNQGD0Z86iFwmP7i2nBrLOn4k2M1KheRFT0q~Njm5bGp7UfNoPouSDhYgzfJRWWWj5Jc7BMkra_mavfWsW61t3g9XUj~K4OG00wlFMwF8r6ZiXjGMPKXIDmim64R9kInwfPiSr5Q&tk2=zgDN5IjN0QTNx0Ddpx2Y8RmZmRjNlVTO3gjY00SOihjYtIGMyQTLzMjMw0SZyATYkNDM20DZpRGfxADMw4yMuATPyVmd8BDMwETPv5Gc
DEBUG:html:get_content> Charset: utf8
DEBUG:html:get_content> URL: http://web-disp.titan.mgtv.com/atcl?pm2=ORtWQtcQ~nGJm8Pu4Yh2rK3ayMjX6TNw2Iz3Q0_gvJfML_swktenLr6Tddocsg0wlxqEATifop0Nd3kzBguK0aKwaysPlFOhoKFAhhbrMUa2gfO__7wOzm5RGMVCANq8jouxyzldJa43YICOx11A5byunWhz~tQVhQUxFpHHI_ne8OFa9TyAmdfmmRcPzjYuVGDdxeJiOgKqopd9KybVgKa0NcKxXNS_VPFOM5q8hw8b5P64jbUl2HrQXPj~d26or740zNE9PpbtI_EyHy0ulh4PUh0ZxohNNHvQy2rjEdu5I94o72S~0wJ~4ZO3EvOW02eA8vFuY_tQnUvS4SgEPCIkTzA~CEsvMkwtSouMKHbzoSjMVHL8xfC_V2PMYND8PwNRkcrjf1~hUUahjOcj83gtCqxbjABzV~ZqTI2u2GxFMLgtD6IY~khc41wQpi4DD12ZnEYLeNfLmi_w9VP5u4GvhWbq~Ppnj1_Hshc5C3rmV~fxTR4yS94U3VlDxumIi7HReg--&gsid=558ab066-61d6-4afd-8dc7-27d0c40df14a&pno=1000
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://web-disp.titan.mgtv.com/atcl?pm2=Mci3NNW_TWSXL_krsUCbGGCqNUac5JR1dd3il5SKZU5vUwPqGghOSjlKBKG1GiAv9Aeps~1sgAJ_BnB9cTdhggbl3HpXKSMnITFXGTFlXoCnDQWLYsP8Vj_q1ngJOoNszCFKQZY6pimPrAU2xgNk1e~0Fk6ICpF7cAMjIorVp5R2HFKGW6W~YF3hoyHYpGc_7~nF4kaQ34jYZtuGtK1OoBnh1eat39gI71b_o8AcXeZhzQXdQw~VK0vjN2DBUSRiTfhacQlVz~uOxXkjqb~BAU7d8dAf25Rt_K~O7fM_a2~cb0btg8VUVTFnm7tji8KV1aMBlF_3A7J_~4NpIKCWIvfhFBjz51nVYRxxpKL9NLA2Ez8NYuUSIRlFuNiZu4OZlBz1ciG_AMlJAWbAdHP1Eu2bLhHA5hlLC0krwqZTvUY2uP4BjMXeNHGyXlCKvXdN5IRB~dQy47IT96gTSjwY8ByxiCWF8o4qB~dsMOTgBH_0ymAIvtFyPLn7FKr8h1ZMv5ARPg--&gsid=90a7183a-ba01-4a70-83e2-10d4e5b48eb2&pno=1000
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://web-disp.titan.mgtv.com/atcl?pm2=cd874SvKUaFOdV4EZheN8e0_U6cmYERp3ZeG9Xv33Jy2Q3dezh_s807H9QXkYYVmO1Ht59536O5Aook3CTt6NhEq3VdzU5drDr~YOZsnu_MO1HEVSJRV~Ix1RyWjfp3xRSA4ElRbZPfNHRhX1XfO9UMK0pL71APrhf3R_Kq7qBLakDmUenG7jOR6l7P25QVSWYQh7I2lMGpk5UMW1eOnyOjxoJ0xBgGuInGUcxZTfh2M3w5pgkEr68myr5DOaXWttv3IIC8YwUnbn9PzJTmXUkgsURgDmpDFMunMZzCXY_r6WuMwIOztGI05iLeIdnTuZ1p3YDaIigNASuTI5Eh0Sys926bJIKoyFbUnAVkMmbLMpJaJ9rT0dv7U68T9TEKZtPXZpj5EzLX0u6TzsLq34SXk_N_1c1QcQJauyxgBv4vprbm0tls3s5afSNQzkseh_SqxO0dB6DWT886j2igFR~CZ6VmNdEKYPsa2lf4FYCZAcpipEwNcnTa2xrTlj5M7uewALQ--&gsid=9f5168c2-f0dd-4414-90c7-a5d95ce690b7&pno=1000
DEBUG:html:get_content> Charset: utf-8
site:                芒果TV (HunanTV)
title:               加菲猫的幸福生活全集
artist:              None
streams:
    - format:        TD
      container:     m3u8
      video-profile: 超清
    # download-with: ykdl --format=TD [URL]
Real urls:
busy
    - format:        HD
      container:     m3u8
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Real urls:
busy
    - format:        SD
      container:     m3u8
      video-profile: 标清
    # download-with: ykdl --format=SD [URL]
Real urls:
busy
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by jyuan15** [comment]
可以下载吧

$ ykdl -o /f/download https://www.mgtv.com/b/291694/2999502.html
site:                芒果TV (HunanTV)
title:               加菲猫的幸福生活全集
artist:              None
streams:
    - format:        TD
      container:     m3u8
      video-profile: 超清
    # download-with: ykdl --format=TD [URL]
Download: 加菲猫的幸福生活全集_TD part 0
Download: 加菲猫的幸福生活全集_TD part 1
 100%Download: 加菲猫的幸福生活全集_TD part 2
 100%Download: 加菲猫的幸福生活全集_TD part 3
  80%Download: 加菲猫的幸福生活全集_TD part 4
 100%Download: 加菲猫的幸福生活全集_TD part 5
 100%Download: 加菲猫的幸福生活全集_TD part 6
 100%Download: 加菲猫的幸福生活全集_TD part 7
  56%Download: 加菲猫的幸福生活全集_TD part 8
 100%Download: 加菲猫的幸福生活全集_TD part 9
  37%Download: 加菲猫的幸福生活全集_TD part 10
 100%Download: 加菲猫的幸福生活全集_TD part 11
 100%Download: 加菲猫的幸福生活全集_TD part 12
 100%Download: 加菲猫的幸福生活全集_TD part 13
 100%Download: 加菲猫的幸福生活全集_TD part 14
 100%Download: 加菲猫的幸福生活全集_TD part 15
 100%Download: 加菲猫的幸福生活全集_TD part 16
 100%Download: 加菲猫的幸福生活全集_TD part 17
 100%Download: 加菲猫的幸福生活全集_TD part 18
 100%Download: 加菲猫的幸福生活全集_TD part 19
  90%Download: 加菲猫的幸福生活全集_TD part 20
 100%Download: 加菲猫的幸福生活全集_TD part 21
 100%Download: 加菲猫的幸福生活全集_TD part 22
 100%Download: 加菲猫的幸福生活全集_TD part 23
 100%Download: 加菲猫的幸福生活全集_TD part 24
 100%Download: 加菲猫的幸福生活全集_TD part 25
 100%Download: 加菲猫的幸福生活全集_TD part 26
 100%Download: 加菲猫的幸福生活全集_TD part 27
 100%Download: 加菲猫的幸福生活全集_TD part 28
 100%Download: 加菲猫的幸福生活全集_TD part 29
 100%Download: 加菲猫的幸福生活全集_TD part 30
 100%Download: 加菲猫的幸福生活全集_TD part 31
 100%Download: 加菲猫的幸福生活全集_TD part 32
 100%Download: 加菲猫的幸福生活全集_TD part 33
 100%Download: 加菲猫的幸福生活全集_TD part 34
   1%Download: 加菲猫的幸福生活全集_TD part 35
 100%Download: 加菲猫的幸福生活全集_TD part 36
 100%Download: 加菲猫的幸福生活全集_TD part 37
 100%Download: 加菲猫的幸福生活全集_TD part 38
 100%Download: 加菲猫的幸福生活全集_TD part 39
 100%Download: 加菲猫的幸福生活全集_TD part 40
 100%Download: 加菲猫的幸福生活全集_TD part 41
 100%Download: 加菲猫的幸福生活全集_TD part 42
 100%Download: 加菲猫的幸福生活全集_TD part 43
 100%Download: 加菲猫的幸福生活全集_TD part 44
 100%Download: 加菲猫的幸福生活全集_TD part 45
 100%Download: 加菲猫的幸福生活全集_TD part 46
 100%Download: 加菲猫的幸福生活全集_TD part 47
 100%Download: 加菲猫的幸福生活全集_TD part 48
 100%Download: 加菲猫的幸福生活全集_TD part 49
 100%Download: 加菲猫的幸福生活全集_TD part 50
 100%Download: 加菲猫的幸福生活全集_TD part 51
 100%Download: 加菲猫的幸福生活全集_TD part 52
 100%Download: 加菲猫的幸福生活全集_TD part 53
 100%Download: 加菲猫的幸福生活全集_TD part 54
 100%Download: 加菲猫的幸福生活全集_TD part 55
 100%Download: 加菲猫的幸福生活全集_TD part 56
 100%Download: 加菲猫的幸福生活全集_TD part 57
 100%Download: 加菲猫的幸福生活全集_TD part 58
 100%Download: 加菲猫的幸福生活全集_TD part 59
 100%Download: 加菲猫的幸福生活全集_TD part 60
   1%Download: 加菲猫的幸福生活全集_TD part 61
 100%Download: 加菲猫的幸福生活全集_TD part 62
 100%Download: 加菲猫的幸福生活全集_TD part 63
 100%Download: 加菲猫的幸福生活全集_TD part 64
 100%Download: 加菲猫的幸福生活全集_TD part 65
 100%Download: 加菲猫的幸福生活全集_TD part 66
 100%Download: 加菲猫的幸福生活全集_TD part 67
 100%Download: 加菲猫的幸福生活全集_TD part 68
 100%Download: 加菲猫的幸福生活全集_TD part 69
 100%Download: 加菲猫的幸福生活全集_TD part 70
 100%Merging video 加菲猫的幸福生活全集_TD using ffmpeg:
Input #0, concat, from 'F:\download\tmptzeq1zy_.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1(und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 104 kb/s
Output #0, mp4, to '加菲猫的幸福生活全集_TD.mp4':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 104 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 6005 fps=0.0 q=-1.0 size=   22272kB time=00:04:01.78 bitrate= 754.6kbits/frame=12755 fps=12754 q=-1.0 size=   44544kB time=00:08:33.68 bitrate= 710.4kbitframe=17500 fps=12962 q=-1.0 Lsize=   59083kB time=00:11:44.92 bitrate= 686.6kbits/s speed= 522x
video:50541kB audio:7888kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.118524%

**Comment by SeaHOH** [comment]
@jyuan15 可能分地区，我这里也不能，不过把缺少的参数加上后就好了。

**Comment by mengmo** [comment]
@SeaHOH
```
ykdl -i --debug https://www.mgtv.com/b/291694/2999502.html
DEBUG:common:video_host> www.mgtv.com
DEBUG:common:short_name> mgtv
DEBUG:common:> Try HTTP Redirection!
DEBUG:common:> NO HTTP Redirection
DEBUG:common:> Go Generalembed
DEBUG:html:get_content> URL: https://www.mgtv.com/b/291694/2999502.html
DEBUG:html:get_content> Charset: utf-8
ERROR:YKDL:Playlist is not supported for GeneralEmbed (通用嵌入视频)with url: https://www.mgtv.com/b/291694/2999502.html
```

**Comment by mengmo** [comment]
@SeaHOH
我这儿还是不行，错误与上边的一样。
要不看看 [annie](https://github.com/iawia002/annie/blob/master/extractors/mgtv/mgtv.go) 的

**Comment by mengmo** [comment]
不对，刚试了其他网站居然出现相同的错误
之前我一直用的是https://github.com/zhangn1985/ykdl/commit/aea70f47cbe06cc500120c6b89c16cd0905ca19f
直接下载 [mgtv.py](https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/mgtv.py) 替换的话是可以正确解析的
应该是与 https://github.com/zhangn1985/ykdl/commit/d4e7516a870605cf28fa43299285798cc662caba 之间的某个改动有问题

**Comment by SeaHOH** [comment]
没搞懂哪里有问题，如果你发现是怎么回事，而且会影响到用户，请反馈到单独的 issues。

**Comment by icetech233** [comment]
没看懂代码 不知道你们怎么抓的
