### ISSUE TITLE
[qq]下载速度为零

### ISSUE THREAD

**Issue by hahaha108** [zhangn1985/ykdl#365]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
C:\Users\yzx>ykdl https://v.qq.com/x/page/x0029cv9b9w.html
site:                腾讯视频 (QQ)
title:               原创时尚京剧舞台剧将亮相
artist:              None
streams:
    - format:        BD
      container:     mp4
      video-profile: 蓝光;(1080P)
      size:          39.4 MiB (41358064 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 原创时尚京剧舞台剧将亮相_BD
   0%
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
https://v.qq.com/x/page/x0029cv9b9w.html，还有这个https://v.qq.com/x/cover/nqmxae531yjmbua/h00270gz57j.html 解析出来的地址下载没有速度，换电脑，换IP地址、使用代理等方法都试过，没有效果。

**Comment by SeaHOH** [comment]
#286
