### ISSUE TITLE
bilibili无法下载,得到的视频源超时无法访问

### ISSUE THREAD

**Issue by StephenPaul25** [zhangn1985/ykdl#367]
能得到正常的播放源地址,但是该地址无法访问并超时

例如源视频:https://www.bilibili.com/video/av39147655/

site:                哔哩哔哩 (Bilibili)
title:               【一分钟让你awsl】圣诞狐的暖心中文放送（12月台词回精选）【#2】 - 最终修订版（个别字）
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 高清 1080P
      size:          145.4 MiB (152469794 bytes)
    # download-with: ykdl --format=BD [URL]
Real urls:
https://cn-jlcc-gd-acache-01.acgvideo.com/upgcxcode/12/89/68838912/68838912-1-80.flv?e=ig8euxZM2rNcNbTV7zUVhoMjhwuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1546081244&gen=playurl&nbs=1&oi=712526675&os=acache&platform=pc&trid=b7e3ff5afaf846c2a53f17deb8fdc324&uipk=5&upsig=596b5d6b04d5c64220cd8bed442f1d11

**Comment by SeaHOH** [comment]
可能和 CDN 有关，我这里能播放。
