### ISSUE TITLE
腾讯视频无法下载

### ISSUE THREAD

**Issue by karma-sun** [zhangn1985/ykdl#368]
ykdl http://v.qq.com/x/cover/sifd2an7kx2h9h8.html?vid=z00294mly5y
site:                腾讯视频 (QQ)
title:               雪鹰领主_01
artist:              None
streams:
    - format:        BD
      container:     mp4
      video-profile: 蓝光;(1080P)
      size:          258.1 MiB (270658677 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 雪鹰领主_01_BD part 0
Download: 雪鹰领主_01_BD part 1
Download: 雪鹰领主_01_BD part 2
Download: 雪鹰领主_01_BD part 3
ERROR:downloader:downloader failed at part 0
ERROR:downloader:downloader failed at part 1
ERROR:downloader:downloader failed at part 2
ERROR:downloader:downloader failed at part 3
CRITICAL:YKDL:雪鹰领主_01_BD> donwload failed

**Comment by karma-sun** [comment]
用的是master最新代码，之前还能用的，腾讯又改了？

**Comment by SeaHOH** [comment]
需要登录获取 key，已经修改好几天了。
不知道有没有其它方法。

**Comment by redstoneleo** [comment]
请问一下腾讯网页视频播放的时候请求到视频信息的是哪一个特征url？

**Comment by karma-sun** [comment]
能否模拟登录？

**Comment by fondoger** [comment]
似乎这个网站的腾讯视频解析接口一直能用：
http://old.flvurl.cn/

**Comment by SeaHOH** [comment]
发现好像是 format id 的原因，但是修正后仍然有些视频的后续部分拒绝访问。

**Comment by SeaHOH** [comment]
就是限速的视频，其它还是原来的 id。。。

**Comment by SeaHOH** [comment]
转到 #286

**Comment by SeaHOH** [comment]
昨天图方便，简单改了下，没有仔细研究。
现在想想不太对，晚上再改。
