### ISSUE TITLE
优酷较长视频无法下载

### ISSUE THREAD

**Issue by connierhu** [zhangn1985/ykdl#371]
无法下载较长视频（https://v.youku.com/v_show/id_XNDAwMjkxNTU2NA==.html）
整个视频差不多一个小时左右 但是下载到的只有6分钟 也只有64MB
<img width="741" alt="screen shot 2019-02-09 at 6 52 27 pm" src="https://user-images.githubusercontent.com/47149156/52527765-fb595700-2c9b-11e9-8ad5-991810b18b41.png">

**Comment by coslyk** [comment]
与 #321  #314 重复
需要模拟DOM跑优酷的JS，目前暂时无解

**Comment by surisuri117** [comment]
这个视频可以用youtube-dl下载
![image](https://user-images.githubusercontent.com/54299935/63403886-b5800700-c413-11e9-8329-52d2e9205784.png)

**Comment by SeaHOH** [comment]
ykdl 不会提供加载外部 cookies 的功能。
