### ISSUE TITLE
斗鱼 jsengine PRINT

### ISSUE THREAD

**Issue by a67878813** [zhangn1985/ykdl#378]
ubuntu16.04
nodejs 4.2.6

--------------------

ykdl --debug 'https://www.douyu.com/2743616'
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:html:get_content> URL: https://www.douyu.com/2743616
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://www.douyu.com/swf_api/homeH5Enc?rids=2743616
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/core.min.js
DEBUG:html:get_content> Charset: utf-8
/tmp/execjs3560t4et.js:24
        print(JSON.stringify(['err', '' + err]));
        ^

ReferenceError: print is not defined
    at /tmp/execjs3560t4et.js:24:9
    at /tmp/execjs3560t4et.js:2:30
    at Object.<anonymous> (/tmp/execjs3560t4et.js:2:48)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 9, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/cykdl/__main__.py", line 173, in main
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/extractor.py", line 24, in parser
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/extractors/douyu/live.py", line 60, in prepare
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 132, in eval
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 168, in _eval
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 174, in _exec
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 205, in _run_interpreter_with_tempfile
ykdl.util.jsengine.RuntimeError: Javascript interpreter returns non-zero value!

**Comment by mengmo** [comment]
@SeaHOH 
我这儿发现一个问题：更新到最新后 /extractors/douyu 下并无 crypto-js-md5.min.js

**Comment by SeaHOH** [comment]
#376

**Comment by SeaHOH** [comment]
> 我这儿发现一个问题：更新到最新后 /extractors/douyu 下并无 crypto-js-md5.min.js

没搞懂，你怎么更新的？

**Comment by mengmo** [comment]
> > 我这儿发现一个问题：更新到最新后 /extractors/douyu 下并无 crypto-js-md5.min.js
>
> 没搞懂，你怎么更新的？

`pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip`

**Comment by SeaHOH** [comment]
重新安装应该可以。

**Comment by mengmo** [comment]
不知道有没有人遇到同样的问题，但是感觉应该与此相关
https://github.com/pypa/pip/issues/3666#issuecomment-218375005
https://www.python.org/dev/peps/pep-0503/#normalized-names
> This PEP references the concept of a "normalized" project name. As per [PEP 426](https://www.python.org/dev/peps/pep-0426) the only valid characters in a name are the ASCII alphabet, ASCII numbers, ., -, and _. The name should be lowercased with all runs of the characters ., -, or _ replaced with a single - character. This can be implemented in Python with the re module:
> ```
> import re
> 
> def normalize(name):
>     return re.sub(r"[-_.]+", "-", name).lower()
> ```

**Comment by a67878813** [comment]
ubuntu 18使用正常，但不知为何，我的16.04就会出上面的错误

**Comment by coslyk** [comment]
@a67878813 Ubuntu18下会调用自带的gjs，里面有print函数，Ubuntu16下自己装的Node就没有

这个bug已确认了，稍候会修复

**Comment by SeaHOH** [comment]
@mengmo 名称已修改。试试 
`pip install -U https://github.com/zhangn1985/ykdl/archive/name-patch.zip`

**Comment by a67878813** [comment]
Traceback (most recent call last):
  File "/home/uu18/.local/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "/home/uu18/.local/lib/python3.6/site-packages/cykdl/__main__.py", line 183, in main
    handle_videoinfo(info)
  File "/home/uu18/.local/lib/python3.6/site-packages/cykdl/__main__.py", line 99, in handle_videoinfo
    info.print_info(stream_id, args.info)
  File "/home/uu18/.local/lib/python3.6/site-packages/ykdl/videoinfo.py", line 60, in print_info
    self.print_stream_info(stream_id, show_all)
  File "/home/uu18/.local/lib/python3.6/site-packages/ykdl/videoinfo.py", line 24, in print_stream_info
    stream = self.streams[stream_id]
KeyError: 'BD'

**Comment by SeaHOH** [comment]
已修复。因为我的 cykdl 修改过，没发现这个错误。

**Comment by mengmo** [comment]
@SeaHOH 还是不行。但是原先的`iqiyi.js`是没出现这个问题的，要不改成`crypto.js`或者`douyu.js`试试？

**Comment by mengmo** [comment]
@SeaHOH 尝试改成`crypto.js`或者`douyu.js`都不行
尝试不要扩展名`douyujs`也不行
只有改成这样`crypto.py`或者`douyujs.py`才行

也不知道这算不算是 bug

**Comment by mengmo** [comment]
> @SeaHOH 尝试改成`crypto.js`或者`douyu.js`都不行
> 尝试不要扩展名`douyujs`也不行
> 只有改成这样`crypto.py`或者`douyujs.py`才行
>
> 也不知道这算不算是 bug

`crypto-js-md5.min.js.py`也行

**Comment by SeaHOH** [comment]
真是神奇，试试 `live.js`。

**Comment by mengmo** [comment]
`live.js`和`video.js`都不行

**Comment by SeaHOH** [comment]
放在 `/util` 下面呢？

**Comment by SeaHOH** [comment]
现在行了吗？

**Comment by mengmo** [comment]
@SeaHOH 改成目前这样倒是可以了

另外，试了下`pip install -U git+https://github.com/zhangn1985/ykdl@master`
生成的`ykdl-1.6.3-cp37-none-any.whl`里边有`crypto-js-md5.min.js`
但是文件名被改成了`crypto-js-md5-min.js`
然而安装后的目录下还是没有任何扩展名为`.js`的文件

而`pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip`
生成的`ykdl-1.6.3-cp37-none-any.whl`里根本就没有`crypto-js-md5.min.js`

将`crypto-js-md5.min.js`移动到`/util`下没用

**Comment by SeaHOH** [comment]
@zhangn1985 来整下这个 package_data 问题，我们搞不懂。。。

**Comment by SeaHOH** [comment]
@mengmo 我修改的不是 master，你再试试
`pip install -U https://github.com/zhangn1985/ykdl/archive/name-patch.zip`

**Comment by simonfire007** [comment]
@SeaHOH  ，下面这里是不是要加两个key：蓝光8M、蓝光，不然当key为这两个时，
`stream = self.profile_2_id[video_profile]`
这一句会报错：KeyError: '蓝光'
```

profile_2_id = {
        u'蓝光10M': '4k',
        u'蓝光4M': 'BD',
        u'超清': 'TD',
        u'高清': 'HD',
        u'流畅': 'SD'
     }
```

**Comment by SeaHOH** [comment]
@simonfire007 好的，麻烦给个视频地址，看看如何改合适。

**Comment by mengmo** [comment]
> @SeaHOH 改成目前这样倒是可以了

我这个测试的就是 name-patch

**Comment by SeaHOH** [comment]
可以了？我更新到 master 啦。

**Comment by mengmo** [comment]
@SeaHOH
OK
目前`pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip`也可以了

**Comment by Justsoos** [comment]
> @SeaHOH ，下面这里是不是要加两个key：蓝光8M、蓝光，不然当key为这两个时，
> `stream = self.profile_2_id[video_profile]`
> 这一句会报错：KeyError: '蓝光'
> 
> ```
> 
> profile_2_id = {
>         u'蓝光10M': '4k',
>         u'蓝光4M': 'BD',
>         u'超清': 'TD',
>         u'高清': 'HD',
>         u'流畅': 'SD'
>      }
> ```

没有实测所有房间，改成这样可以用了：
```
stream_ids = ['10M', '8M', '4M', 'BD', 'TD', 'HD', 'SD']
    profile_2_id = {
        u'蓝光10M': '10M',
        u'蓝光8M': '8M',
        u'蓝光4M': '4M',
        u'蓝光': 'BD',                                                                   u'超清': 'TD',                                                                   u'高清': 'HD',                                                                   u'流畅': 'SD'
     }
```
但斗鱼新加入的rate选择并没有在接口数据里体现，目前拿到的，都是最高码率(存疑判断)url。
也是萝卜快了不洗泥？我们这说完，斗鱼程序员明天加KPI还是罚工资？😂

**Comment by TaoziDB** [comment]
> 但斗鱼新加入的rate选择并没有在接口数据里体现，目前拿到的，都是最高码率(存疑判断)url。
> 也是萝卜快了不洗泥？我们这说完，斗鱼程序员明天加KPI还是罚工资？😂


rate选择在接口里呀
```
        params = {
            'v': match1(ub98484234, 'v=(\d+)'),
            'did': did,
            'tt': tt,
            'sign': match1(ub98484234, 'sign=(\w{32})'),
            'cdn': '',
            'rate': 0,
            'iar': 1,
            'ive': 0
}
```
rate就是，可选项在multirates
cdn可选项在cdnsWithName
经过实测，最好不要iar和ive，如果要的话，rate=0有可能得到rate不为0的较低画质的结果

**Comment by Justsoos** [comment]
> > 但斗鱼新加入的rate选择并没有在接口数据里体现，目前拿到的，都是最高码率(存疑判断)url。
> > 也是萝卜快了不洗泥？我们这说完，斗鱼程序员明天加KPI还是罚工资？joy
> 
> rate选择在接口里呀
> 
> ```
>         params = {
>             'v': match1(ub98484234, 'v=(\d+)'),
>             'did': did,
>             'tt': tt,
>             'sign': match1(ub98484234, 'sign=(\w{32})'),
>             'cdn': '',
>             'rate': 0,
>             'iar': 1,
>             'ive': 0
> }
> ```
> rate就是，可选项在multirates
> cdn可选项在cdnsWithName
> 经过实测，最好不要iar和ive，如果要的话，rate=0有可能得到rate不为0的较低画质的结果

哦，去年用的api通过`url&rate=`选码率，而且码率放在api里可以后选，新api要提前，没有注意到，的确存在这个先有鸡蛋还是有鸡的逻辑问题。
实测：
1，rate=空，返回最高码率。没有事先读api拿到rate范围，就先用这个方式。
2，rate设置不同码率，返回流有_550, _2000, _4000等等后缀码率不同，直接改后缀将导致流无效，无法播放！
`real_url = real_url.replace('_550', '_4000')`
这个方式不可用
3，url最后附加类似 `&rate=4000` 来改码率无效。终于… 也就是一码一流了
斗鱼码农加个鸡腿😂

**Comment by TaoziDB** [comment]
> 
> 
> > > 但斗鱼新加入的rate选择并没有在接口数据里体现，目前拿到的，都是最高码率(存疑判断)url。
> > > 也是萝卜快了不洗泥？我们这说完，斗鱼程序员明天加KPI还是罚工资？joy
> > 
> > 
> > rate选择在接口里呀
> > ```
> >         params = {
> >             'v': match1(ub98484234, 'v=(\d+)'),
> >             'did': did,
> >             'tt': tt,
> >             'sign': match1(ub98484234, 'sign=(\w{32})'),
> >             'cdn': '',
> >             'rate': 0,
> >             'iar': 1,
> >             'ive': 0
> > }
> > ```
> > rate就是，可选项在multirates
> > cdn可选项在cdnsWithName
> > 经过实测，最好不要iar和ive，如果要的话，rate=0有可能得到rate不为0的较低画质的结果
> 
> 哦，去年用的api通过`url&rate=`选码率，而且码率放在api里可以后选，新api要提前，没有注意到，的确存在这个先有鸡蛋还是有鸡的逻辑问题。
> 实测：
> 1，rate=空，返回最高码率。没有事先读api拿到rate范围，就先用这个方式。
> 2，rate设置不同码率，返回流有_550, _2000, _4000等等后缀码率不同，直接改后缀将导致流无效，无法播放！
> `real_url = real_url.replace('_550', '_4000')`
> 这个方式不可用
> 3，url最后附加类似 `&rate=4000` 来改码率无效。终于… 也就是一码一流了
> 斗鱼码农加个鸡腿😂
在multirates的rate是0，1，2 ...

**Comment by Justsoos** [comment]
> > > > 但斗鱼新加入的rate选择并没有在接口数据里体现，目前拿到的，都是最高码率(存疑判断)url。
> > > > 也是萝卜快了不洗泥？我们这说完，斗鱼程序员明天加KPI还是罚工资？joy
> > > 
> > > 
> > > rate选择在接口里呀
> > > ```
> > >         params = {
> > >             'v': match1(ub98484234, 'v=(\d+)'),
> > >             'did': did,
> > >             'tt': tt,
> > >             'sign': match1(ub98484234, 'sign=(\w{32})'),
> > >             'cdn': '',
> > >             'rate': 0,
> > >             'iar': 1,
> > >             'ive': 0
> > > }
> > > ```
> > > rate就是，可选项在multirates
> > > cdn可选项在cdnsWithName
> > > 经过实测，最好不要iar和ive，如果要的话，rate=0有可能得到rate不为0的较低画质的结果
> > 
> > 
> > 哦，去年用的api通过`url&rate=`选码率，而且码率放在api里可以后选，新api要提前，没有注意到，的确存在这个先有鸡蛋还是有鸡的逻辑问题。
> > 实测：
> > 1，rate=空，返回最高码率。没有事先读api拿到rate范围，就先用这个方式。
> > 2，rate设置不同码率，返回流有_550, _2000, _4000等等后缀码率不同，直接改后缀将导致流无效，无法播放！
> > `real_url = real_url.replace('_550', '_4000')`
> > 这个方式不可用
> > 3，url最后附加类似 `&rate=4000` 来改码率无效。终于… 也就是一码一流了
> > 斗鱼码农加个鸡腿joy
> 
> 在multirates的rate是0，1，2 ...
> 例如对于某个房间如果rate 4对应4M，用rate:4得到的url/live就是4M的，不用替换
> 唯一不方便的是，每次换线路和画质需要重新读api
> 也许斗鱼出于加密的考虑，哔哩哔哩好像也是一码一流的

4M默认不准的，颜值区太多达不到4M，比如刚测了一个
```
[{"name":"主线路","cdn":"ws-h5"},{"name":"备用线路5","cdn":"tct-h5"}],"multirates":[{"name":"超清","rate":0,"highBit":0}]
```
目前看还是rate=0普遍些

**Comment by TaoziDB** [comment]
> 
> 
> > > > > 但斗鱼新加入的rate选择并没有在接口数据里体现，目前拿到的，都是最高码率(存疑判断)url。
> > > > > 也是萝卜快了不洗泥？我们这说完，斗鱼程序员明天加KPI还是罚工资？joy
> > > > 
> > > > 
> > > > rate选择在接口里呀
> > > > ```
> > > >         params = {
> > > >             'v': match1(ub98484234, 'v=(\d+)'),
> > > >             'did': did,
> > > >             'tt': tt,
> > > >             'sign': match1(ub98484234, 'sign=(\w{32})'),
> > > >             'cdn': '',
> > > >             'rate': 0,
> > > >             'iar': 1,
> > > >             'ive': 0
> > > > }
> > > > ```
> > > > rate就是，可选项在multirates
> > > > cdn可选项在cdnsWithName
> > > > 经过实测，最好不要iar和ive，如果要的话，rate=0有可能得到rate不为0的较低画质的结果
> > > 
> > > 
> > > 哦，去年用的api通过`url&rate=`选码率，而且码率放在api里可以后选，新api要提前，没有注意到，的确存在这个先有鸡蛋还是有鸡的逻辑问题。
> > > 实测：
> > > 1，rate=空，返回最高码率。没有事先读api拿到rate范围，就先用这个方式。
> > > 2，rate设置不同码率，返回流有_550, _2000, _4000等等后缀码率不同，直接改后缀将导致流无效，无法播放！
> > > `real_url = real_url.replace('_550', '_4000')`
> > > 这个方式不可用
> > > 3，url最后附加类似 `&rate=4000` 来改码率无效。终于… 也就是一码一流了
> > > 斗鱼码农加个鸡腿joy
> > 
> > 
> > 在multirates的rate是0，1，2 ...
> > 例如对于某个房间如果rate 4对应4M，用rate:4得到的url/live就是4M的，不用替换
> > 唯一不方便的是，每次换线路和画质需要重新读api
> > 也许斗鱼出于加密的考虑，哔哩哔哩好像也是一码一流的
> 
> 4M默认不准的，颜值区太多达不到4M，比如刚测了一个
> 
> ```
> [{"name":"主线路","cdn":"ws-h5"},{"name":"备用线路5","cdn":"tct-h5"}],"multirates":[{"name":"超清","rate":0,"highBit":0}]
> ```
> 
> 目前看还是rate=0普遍些



我是举个例子，默认用0的，然后由multirates定rate的范围，最好去掉iar和ive，否则rate为0也可能得到rate不为0的结果，你可以用结果中的rate来验证，有时会不为0

**Comment by Justsoos** [comment]
> 我是举个例子，默认用0的，然后由multirates定rate的范围，最好去掉iar和ive，否则rate为0也可能得到rate不为0的结果，你可以用结果中的rate来验证，有时会不为0，结果就是得不到最高码率的流文件。

一般来说，这种情况还会有个前置免auth，免tls的接口可以读可选码率，不用纠结这个问题，让软件作者们搞定吧。你能提交个完整代码也行

**Comment by Justsoos** [comment]
https://github.com/wbt5/real-url/blob/c42f16fe6d8a44c9eb2560417c17abedf7d757f3/douyu.py#L129

这里有人找到了另外一种方法，好处是，没有token，不会作连接检查！每个直播间固定流URI ！
