### ISSUE TITLE
下载的格式

### ISSUE THREAD

**Issue by BearChu** [zhangn1985/ykdl#38]
huyaLive下载 抓取的是m3u8下载保存的是mp4 也有flv流的 
但mp4要完整视频才能播放 直播基本很难完整 只要中断mp4就会错误
希望改成TS或mkv 中断也能观看下载的视频 mp4只能删除无法使用
谢谢

**Comment by zhangn1985** [comment]
用 ffmpeg 下载直播时，不能泳ctrl+c 结束下载，必须使用q 结束下载，不然视频的时间轴是错的。

**Comment by zhangn1985** [comment]
也许你要更新一下ffmpeg，等我下一个release。
