### ISSUE TITLE
请问，斗鱼直播视频，如何得到不同码率的下载地址？

### ISSUE THREAD

**Issue by shithappens2016** [zhangn1985/ykdl#387]
感谢作者的代码，能顺利取到斗鱼直播视频的下载地址。
这里想问一下，取到的斗鱼下载地址是1080高码率下载地址，如果要换其他**码率**，该怎么操作呢？

**Comment by zhangn1985** [comment]
试试 -i 能否列出支持的码率。有的话可以根据提示选择。

**Comment by shithappens2016** [comment]
非常感谢
