### ISSUE TITLE
http://tw.iqiyi.com/v_19rr9axpf8.html#vfrm=2-3-0-1

### ISSUE THREAD

**Issue by Saullric** [zhangn1985/ykdl#39]
解析的1080p m3u8 下载到94%后无法继续下载 也无法播放

**Comment by zhangn1985** [comment]
我怎么下载的是广告？

**Comment by Hugo-Hui** [comment]
tw.iqiyi.com 是愛奇藝臺灣站,應該需要臺灣ip

**Comment by Saullric** [comment]
我是台湾ip

**Comment by zhangn1985** [comment]
m3u8 下载强制中断，旧版的ffmpeg会产生没有时间轴的mp4。而下载卡住，按Q又不响应，只能强制结束。是这样的吗？

如果是这样的请更新ffmpeg试试。https://ffmpeg.zeranoe.com/builds/

**Comment by Saullric** [comment]
不是的。用Potplayer播放解析出的m3u8第643 644段  无法播放  其他正常

**Comment by Saullric** [comment]
http://tw.iqiyi.com/v_19rra7q5wg.html#vfrm=2-3-0-1这个地址也是 66.1%就不行了

**Comment by zhangn1985** [comment]
以前iqiyi是有链接超时的概念，超时了要重新请求。但原来是url出来就是分段的，而不是m3u8，我的做法是每段都重新请求，但这个m3u8怎么办，我得想想。

**Comment by Saullric** [comment]
感谢
