### ISSUE TITLE
下载的优酷视频分段被加密了，找不到方法合并

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#397]
比如说这个视频
https://v.youku.com/v_show/id_XMzczMjQ1Nzgw.html
我可以下载它的所有视频片段，但是因为每个视频分段被加密了以至于我找不到方法合并这些分段，各位有破解方法吗？

顺便一提，我觉得需要的关键信息应该都在以`https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/`开头的那个url里了

**Comment by SeaHOH** [comment]
我测试是正常下载并合并的。
你的 ffmpeg 是否有正确安装？加入环境变量没有？

**Comment by redstoneleo** [comment]
这个视频你的合并了能播放吗？
https://v.youku.com/v_show/id_XMzg5Njg2NjY2MA==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ&refer=baiduald1705

**Comment by SeaHOH** [comment]
会员视频游客只能看大概 6 分钟，合并后可以正常播放。

**Comment by redstoneleo** [comment]
我给的这个第二集是完全免费的啊，应该可以完全下载才是。
我是通过这个视频的m3u8网址下载所有视频片段的，结果合并不了
另外，以`https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/`开头的那个url返回信息里面包含drm字样，所以我觉得是有对这些分段加密过，并且也无法正常播放每一个分段，我觉得这也可能是加密过的迹象

**Comment by SeaHOH** [comment]
你没有使用 ykdl？
这个视频，当前 ykdl 使用的 API 只有下载粤语 m3u8 才是完整的。
破解 DRM 不属于这个应用的范畴。

**Comment by airdge** [comment]
这种情况是地方节点问题  很早之前就有了   
SEGS里面没有分段URL,但有M3U8
遍历下SEGS,没有分段URL就输出M3U8

**Comment by SeaHOH** [comment]
他用的是 `https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/` 这个新 API。
可能是哪个浏览器扩展导出的。
我看过，这个视频使用新 API 的解析结果确实有 DRM 加密。
但是 ykdl 并没有解决 ckey 的问题（还有新 API 的 sign），无法使用新 API。

**Comment by redstoneleo** [comment]
@SeaHOH 对，那个url就是用浏览器扩展导出来的，直接拼凑url我也没那个本事。

现在的情况是即便是拼凑出这个url，结果也还是要解密DRM才行，我看里面倒是有各种key，其中一个是copyright_key……
