### ISSUE TITLE
这是都安装还是安装其中一个？

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#401]
在arch下解析斗鱼直播，出现以下提示：

➜  home ykdl -i https://www.douyu.com/6436067
Please install at least one of the following Javascript interpreter: gjs, cjs, nodejs
CRITICAL:YKDL:No JS Interpreter found, can't parse douyu live!

是是三个都安装还是只安装其中一个就可以了？

**Comment by BigMangos** [comment]
安装一个就可以

**Comment by jyuan15** [comment]
试了下，只装nodejs解析出错，安装gjs或cjs都能解析，但都要先出来几排警告：

➜  home ykdl -i https://www.douyu.com/1010383
Gjs-Message: 18:43:51.632: JS WARNING: [/tmp/execjs8qqtai2i.js 10]: assignment to undeclared variable result
Gjs-Message: 18:43:52.111: JS WARNING: [/tmp/execjskd7y_y1b.js line 5 > eval 1]: reference to undefined property 0
Gjs-Message: 18:43:52.116: JS WARNING: [/tmp/execjskd7y_y1b.js line 5 > eval 1]: reference to undefined property 0
Gjs-Message: 18:43:52.152: JS WARNING: [/tmp/execjskd7y_y1b.js 10]: assignment to undeclared variable result

这是什么意思？

**Comment by Jaqen00** [comment]
@jyuan15 请问gjs是怎么安装的呀

**Comment by jyuan15** [comment]
@Jaqen00 软件源里面就有啊，直接装就行了
