### ISSUE TITLE
斗鱼“房间被封禁”

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#403]
解析时出现以下提示：

$ ykdl -i https://www.douyu.com/20520
CRITICAL:YKDL:房间被封禁

但该房间并未被封禁，不登录也可以观看啊，这是什么原因？

**Comment by SeaHOH** [comment]
放弃从网址匹配了。。。

**Comment by gitterliu** [comment]
@SeaHOH 放弃默认输出的网址匹配有点不好, 斗鱼经常会有重定向到活动的网页, 这种重定向之后的网页有可能经常变化. 所以`self.vid = match1(self.url, 'douyu.com/(\d+)')`最好还是保留.

**Comment by SeaHOH** [comment]
> 放弃默认输出的网址匹配有点不好, 斗鱼经常会有重定向到活动的网页, 这种重定向之后的网页有可能经常变化. 所以`self.vid = match1(self.url, 'douyu.com/(\d+)')`最好还是保留.

先前使用网址匹配是因为直接请求 API 能更快获取视频信息，但是有许多房间号和 API 需要视频流编号并不一致，区分困难才放弃的。
你说的问题没看明白，能否举个具体的例子说明保留它的必要性？
