### ISSUE TITLE
关于爱奇艺分段问题

### ISSUE THREAD

**Issue by xyuanmu** [zhangn1985/ykdl#404]
今天才知道有这个工具，然后我发现下载爱奇艺1080p分段太多，如果视频比较大的话就无法正常合并了，比如这个：http://www.iqiyi.com/v_19rrj5rtow.html

这个视频一共有538个分段，试了不下10遍，每次都有提示失败的文件，即使538个文件全都下载下来了也还是提示，然后我用 -i 获取了 m3u8 地址：https://cache.m.iqiyi.com/mus/text/90058601/73536049831c1a49f3f054239d97b5fd/afbe8fd3d73448c9//20180426/30/a2/56def1e8a793f8c793ce7eadd68b5d31.m3u8?qd_originate=tmts_py&tvid=90437500&bossStatus=0&qd_vip=0&px=&src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1556261780578&qd_p=78ef1e2f&qd_asc=2f55e22d084df4571f14e5bf50daab9b&qypid=90437500_04022000001000000000_18&qd_k=50de372a85e7a7a9d4ae67146635ecac&isdol=0&code=1&ff=265ts&iswb=0&qd_s=otv&vf=8312890ff67b4b4a592d7221be2578ab&np_tag=nginx_part_tag

该地址打开后也是538段，但有很多链接是重复的，通过 `start=122628452&end=124227768&contentlength=1599316` 这三个参数来控制文件长度，去掉这三个参数并将 `sd=一连串数字` 替换为 `sd=0` 即可获得该完整分段的地址
下面是我写的简单提取地址的代码
```
m3u8 = m3u8内容
m3u8 = re.sub('start\=\d+&end\=\d+&contentlength\=\d+&sd\=\d+', 'sd=0', m3u8)
urls = re.compile(r'http://[^\s]+').findall(m3u8)
idx = urls
m3u8 = list(set(urls))
m3u8.sort(key=idx.index)
for i in m3u8:
    print(i)
```

提取后就只剩下7段了，当时就非常惊喜，然后我试着下载，改后缀为 ts 合并，完美合并
```
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/8eb9ea876b719f576ee576e2d6786f31.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=c3ac6eb920f16e1d4d2a5fa0f79650ee
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/5c2ea2e6660a2cdba64a3ac8bc3076f9.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=49007e68a50f1b0321cbb1d59a2c8405
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/1864c1f7a0093c4cead774db8905148f.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=16945906264554b39d68bd8b7244b4a2
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/232d3c25f1abac462ec0a7576ebd15c7.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=a34ceaa2f98fc9590c063fcb59225ace
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/9a65d93c3c47eb1b33cab4258e2090a2.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=7c83dde2c10b995a9d1a56554f8f7028
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/afeac7fcc5b4e7ea2487ee8eb734e95f.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=f9fec6202775f7c10574e2cd2f7f6c39
http://dx.data.video.iqiyi.com/videos/v0/20180426/30/a2/c1289b1cfa761ec8abd4775527e40506.265ts?qypid=90437500_04022000001000000000_18&sd=0&qdv=1&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1556261893210&qd_ip=78ef1e2f&qd_p=78ef1e2f&qd_k=50de372a85e7a7a9d4ae67146635ecac&sgti=&dfp=&qd_sc=fa8bd0c7a7c287f790e2ee94413a7379
```

就是不知道要怎么将其合并到源代码里，所以在这里提一下，希望可以用这种方法下载，成功率应该会很高

**Comment by SeaHOH** [comment]
关于参数问题，这并不是通用的，所以不会这么处理。

合并有两个方案：
1. 分段下载，再合并。优点是可以多线程加速，缺点这个方案的错误处理是否简陋，需要反复运行命令。
1. 使用 FFmpeg 录制。优点是下载的分段会直接写到一个文件，似乎、好像是有错误重试。

你可以试试第二种方式，使用方法为：把 cykdl 的 `m3u8_internal` 赋值为 `False`。

**Comment by xyuanmu** [comment]
分段下载对于这种分段太多感觉不可行，比如上面的500多段，我手动执行 ffmpeg 合并命令执行不了，反而变成了同时打开这500多个文件，导致电脑卡死，估计是命令太长了。
修改这三个参数在爱奇艺上是没有问题的，已经通过这个方法提取链接下载了这部电视剧，至于其他的网站可以保留原有的方案
m3u8_internal 赋值 False 录制非常慢，速度只有 0.1 这样

**Comment by xyuanmu** [comment]
刚才试了下，上方提取出的地址还是有效的，你可以打开看看，这样每段就有6分钟，而不是几秒钟

**Comment by SeaHOH** [comment]
> 关于 Url 参数问题，这并不是通用的，所以不会这么处理。

这个真不会改。

> m3u8_internal 赋值 False 录制非常慢，速度只有 0.1 这样

差不多，1Mbps = 1/8MBps，也就是 128kB/s 上下。
小分段就这样，速度没上来就下完了，你上面提到的没分段的速度会在几秒钟内涨到 10 倍以上。

**Comment by mozbugbox** [comment]
好像是爱起义的ts下载并不支持部分下载，但是重复下载分段的时候，ykdl 自动当他支持部分下载，所以所有需要重复下载的分段全部超长。

在 `util/download.py/save_url()` 中需要检查`HEAD`请求是否返回 `Accept-Ranges`，正是下载的请求回复内容也需要检查是否是206或者`Content-Range` 是否正确。

**Comment by SeaHOH** [comment]
>下载并不支持部分下载

确实有可能出现这种状况，修正它也不麻烦，但是问题还是没法很好地解决。
当前的下载模块太简单，可以考虑直接使用其它更完善的下载模块或方案。

**Comment by wnpllrzodiac** [comment]
不支持206 partial content显然会把客户端流量刷爆啊。1个G的视频，反复下载分片（实际是每个都下了完整的一个文件）导致流量好几十个G？

**Comment by airdge** [comment]
os.listdir获取path里所有文件名
判断有没有下载过的切片,没有就执行下载

`inputfile = 'concat:%s' % '|'.join(inputfile)`
用这种形式来合并切片
如果切片过多,在win下会出现文件名或扩展名太长的错误

**Comment by mengmo** [comment]
@airdge https://github.com/zhangn1985/ykdl/issues/399
有更好的方法吗？

**Comment by airdge** [comment]
这个好像是文件夹有这个ts切片,但ts下载不完整 才会出现这个错误
```
missing picture in access unit
    Last message repeated 2 times
```

 

我自己用的是
将切片命名 1.ts.temp 进行下载
如果下载完成,再改名成 1.ts
等到所有的下载任务都完成,在执行一遍os.listdir
查询有没有错漏的

最后用 ffmpeg safe -1 -y -f concat -i xxx.txt 合并

**Comment by mozbugbox** [comment]
检查服务器是否支持206部分下载
[partial-download.patch.txt](https://github.com/zhangn1985/ykdl/files/4075889/partial-download.patch.txt)
