### ISSUE TITLE
[Feature Request]请求支持kjs

### ISSUE THREAD

**Issue by IsoaSFlus** [zhangn1985/ykdl#408]
我发现好像只支持gjs cjs 和 node
但是作为linux使用最多的桌面环境之一的kde所使用的js运行时kjs却没有被支持，作者能否添加一下呢？

**Comment by coslyk** [comment]
kjs似乎没有提供可执行程序，C++的库也不方便Python直接调用 -_-

**Comment by mengmo** [comment]
好像是`/usr/bin/kjs5`

@IsoaSFlus
KDE 桌面默认就装的有 kjs 吗？

**Comment by IsoaSFlus** [comment]
@mengmo 是的，默认就装有kjs。
![image](https://user-images.githubusercontent.com/5125031/57575792-23677a80-7484-11e9-93da-8820035c1468.png)

**Comment by coslyk** [comment]
kjs不支持ES6标准，所以对本项目来说没有什么意义。
以下是我测试爱奇艺cmd5x脚本的结果，并不能返回正确结果：
![kjs](https://user-images.githubusercontent.com/6695223/57584598-9224f200-74dd-11e9-9e9b-0f2b9473d640.png)
