### ISSUE TITLE
[临时]斗鱼JS替换

### ISSUE THREAD

**Issue by airdge** [zhangn1985/ykdl#417]
之前的太过麻烦
```
oog=oog(otg+ttg+htg); var otc="test"; var cns=otc;tog=oog;
...
...
...
var re=oog[otc](tsg[wtf]);v[216]^=lk[0];!re && (function(){for(var i=0;i<v.length;i++){v[i]=i;}})();
var re=oog[cns](tsg[wtf]);v[238]=(v[238]<<(lk[0]%16))|(v[238]>>>(32-(lk[0]%16)));!re && (function(){ wea=400;})();
var re=tog[cns](tsg[wtf]);re && (function(){v[275]^=lk[1];})();
var re=tog[otc](sck[dtf]);v[298]=(v[298]<<(lk[0]%16))|(v[298]>>>(32-(lk[0]%16)));!re && (function(){for(var i=0;i<v.length;i++){v[i]=i;}})();
```
函数通过获取`oog['test'](obj)`真假来给v赋值
所以只要强行将`oog['test'](obj)`返回true就行了
 
```
                      //eval(Ee); 
                      var newString = "'" + Ee + "';";
                      var evalString = eval(newString);
                      evalString = evalString.replace(/(.*oog\(.*)/, "$1oog['test'] = function(a) { return 1; }");
                      eval(evalString);
```

![图片](https://user-images.githubusercontent.com/7813960/61586243-b407b880-aba1-11e9-8eb2-a87feec4d545.png)

========================================================================

========================================================================

========================================================================

大概流程就是通过匹配 eval(encrypt)的encrypt
通过
```
var  enc ="'" + encrypt + "';";
var  decrypt = eval(enc);
eval(decrypt);
```
来获取还原代码decrypt
再通过decrypt代码分析斗鱼js所要执行的情况,做进一步的替换处理和还原
![图片](https://user-images.githubusercontent.com/7813960/58804630-e20e5900-8644-11e9-94ca-76120fce1523.png)

不是每次都能使用,现在并没有完全解决问题
现只遇到三种形式,只对其中两种情况作了处理,还有一种情况相对麻烦
因homeH5Enc返回的数据不是每次都相同,刷新几次或者等几分钟应该能解析
先做临时使用,另外的有时间再分析
![图片](https://user-images.githubusercontent.com/7813960/58804586-cc009880-8644-11e9-8ee2-b249bbc3fe7f.png)

不影响原有的py代码,只在解析不到ub98484234时候运行
但必须给所有的房间都添加DOM对象,这个不影响正常房间的解析
```
        js_ctx = JSEngine(js_md5) 

        # 此处必须给js添加DOM,不然ub98484234会因缺少DOM出现报错,不影响其他房间解析
        dom = "let window = {},document  = {};" 
        js_ctx.eval(dom)

        js_ctx.eval(js_enc)
        did = uuid.uuid4().hex
        tt = str(int(time.time())) 
        ub98484234 = js_ctx.call('ub98484234', self.vid, did, tt) 
        if not ub98484234:
            # 对function ub98484234的eval字段进行匹配
            func = match1(js_enc,'function ub98484234(.*)')
            workflow= match1(func,'eval\((\w+)\)') 
            # 替换字符串
            replaceString = ''' 
                    // eval(%(workflow)s); 
                    // let workfolw = %(workflow)s ; 
                    var newString = "'" + %(workflow)s + "';";
                    // 获取还原过的代码
                    var evalString = eval(newString);
                    // DOM检测
                    if (/(\w+)=(window|document)/g.exec(evalString)) {
                        var execWin = /(\w+)=window/g.exec(evalString);
                        var execDoc = /(\w+)=document/g.exec(evalString);
                        window.isWin = execWin ? execWin[1] : '';
                        document.isDoc = execDoc ? execDoc[1] : '';
                    } 
                    // 如果还原代码中还有eval()函数
                    if (/eval\(/g.exec(evalString)) {
                        var encString=evalString.replace(/eval\(\w+\)/g,'');
                        eval(encString);
                        if (/function/g.exec(%(workflow)s) && (%(workflow)s.indexOf(window.isWin) > 0 || %(workflow)s.indexOf(document.isDoc) > 0)) {
                            var reString = /var (\w+)=/g.exec(%(workflow)s);
                            reString && (evalString = %(workflow)s.replace(reString[0], reString[0] + "!"));
                            // 如果还原代码中还包含了混淆代码段
                            let reEval = /\(function\(\)\{(.*)\}\)\(\)/g.exec(encString);
                            if (reEval && />>>|<<<|^/g.exec(reEval[1])) { 
                                  var xxxxxxxxxxx = function() {
                                      eval(reEval[1]);
                                      var funcString = /var (\w+)=/g.exec(%(workflow)s);
                                      funcString && (evalString = %(workflow)s.replace(reString[0], reString[0] + "!"));
                                      return evalString;
                                  }();
                              }
                        }
                    } else {
                        // 如果还原代码中含有function函数,以及包含DOM,则对function test逻辑取反(a = b -> a = !b)
                        if (/function/g.exec(evalString) && (evalString.indexOf(window.isWin) > 0 || evalString.indexOf(document.isDoc) > 0)) {
                            var reString = /var (\w+)=/g.exec(evalString);
                            reString && (evalString = evalString.replace(reString[0], reString[0] + "!"));
                        }
                    }
                    eval(evalString);
            '''% {'workflow': workflow}

            js_Dom = js_enc.replace('eval('+workflow+');', replaceString)
            js_ctx.eval(js_Dom)  
            ub98484234 = js_ctx.call('ub98484234', self.vid, did, tt) 
        self.logger.debug('ub98484234: ' + ub98484234)
```

![图片](https://user-images.githubusercontent.com/7813960/58805834-71b50700-8647-11e9-8c49-e0728d7ca0a6.png)
douyu/live.py

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from ykdl.util.html import get_content, add_header
from ykdl.util.match import match1, matchall
from ykdl.util.jsengine import JSEngine, javascript_is_supported
from ykdl.extractor import VideoExtractor
from ykdl.videoinfo import VideoInfo
from ykdl.compact import urlencode

import time
import json
import uuid


douyu_match_pattern = [ 'class="hroom_id" value="([^"]+)',
                        'data-room_id="([^"]+)'
                      ]

class Douyutv(VideoExtractor):
    name = u'斗鱼直播 (DouyuTV)'

    stream_ids = ['BD10M', 'BD8M', 'BD4M', 'BD', 'TD', 'HD', 'SD']
    profile_2_id = {
        u'蓝光10M': 'BD10M',
        u'蓝光8M': 'BD8M',
        u'蓝光4M': 'BD4M',
        u'蓝光': 'BD',
        u'超清': 'TD',
        u'高清': 'HD',
        u'流畅': 'SD'
     }

    def prepare(self):
        assert javascript_is_supported, "No JS Interpreter found, can't parse douyu live!"

        info = VideoInfo(self.name, True)
        add_header("Referer", 'https://www.douyu.com')

        html = get_content(self.url)
        self.vid = match1(html, 'room_id\s*=\s*(\d+)',
                                '"room_id.?":(\d+)',
                                'data-onlineid=(\d+)')
        title = match1(html, 'Title-headlineH2">([^<]+)<')
        artist = match1(html, 'Title-anchorName" title="([^"]+)"')

        if not title or not artist:
            html = get_content('https://open.douyucdn.cn/api/RoomApi/room/' + self.vid)
            room_data = json.loads(html)
            if room_data['error'] == 0:
                room_data = room_data['data']
                title = room_data['room_name']
                artist = room_data['owner_name']

        info.title = u'{} - {}'.format(title, artist)
        info.artist = artist

        html_h5enc = get_content('https://www.douyu.com/swf_api/homeH5Enc?rids=' + self.vid)
        data = json.loads(html_h5enc)
        assert data['error'] == 0, data['msg']
        js_enc = data['data']['room' + self.vid]

        try:
            # try load local .js file first
            # from https://cdnjs.com/libraries/crypto-js
            from pkgutil import get_data
            js_md5 = get_data(__name__, 'crypto-js-md5.min.js')
            if isinstance(js_md5, bytes):
                js_md5 = js_md5.decode()
        except IOError:
            js_md5 = get_content('https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js')

        js_ctx = JSEngine(js_md5) 

        # 此处必须给js添加DOM,不然ub98484234会因缺少DOM出现报错,不影响其他房间解析
        dom = "let window = {},document  = {};" 
        js_ctx.eval(dom)

        js_ctx.eval(js_enc)
        did = uuid.uuid4().hex
        tt = str(int(time.time())) 
        ub98484234 = js_ctx.call('ub98484234', self.vid, did, tt) 
        if not ub98484234:
            # 对function ub98484234的eval字段进行匹配
            func = match1(js_enc,'function ub98484234(.*)')
            workflow= match1(func,'eval\((\w+)\)') 
            # 替换字符串
            replaceString = ''' 
                    // eval(%(workflow)s); 
                    // let workfolw = %(workflow)s ; 
                    var newString = "'" + %(workflow)s + "';";
                    // 获取还原过的代码
                    var evalString = eval(newString);
                    // DOM检测
                    if (/(\w+)=(window|document)/g.exec(evalString)) {
                        var execWin = /(\w+)=window/g.exec(evalString);
                        var execDoc = /(\w+)=document/g.exec(evalString);
                        window.isWin = execWin ? execWin[1] : '';
                        document.isDoc = execDoc ? execDoc[1] : '';
                    } 
                    // 如果还原代码中还有eval()函数
                    if (/eval\(/g.exec(evalString)) {
                        var encString=evalString.replace(/eval\(\w+\)/g,'');
                        eval(encString);
                        if (/function/g.exec(%(workflow)s) && (%(workflow)s.indexOf(window.isWin) > 0 || %(workflow)s.indexOf(document.isDoc) > 0)) {
                            var reString = /var (\w+)=/g.exec(%(workflow)s);
                            reString && (evalString = %(workflow)s.replace(reString[0], reString[0] + "!"));
                            // 如果还原代码中还包含了混淆代码段
                            let reEval = /\(function\(\)\{(.*)\}\)\(\)/g.exec(encString);
                            if (reEval && />>>|<<<|^/g.exec(reEval[1])) { 
                                  var xxxxxxxxxxx = function() {
                                      eval(reEval[1]);
                                      var funcString = /var (\w+)=/g.exec(%(workflow)s);
                                      funcString && (evalString = %(workflow)s.replace(reString[0], reString[0] + "!"));
                                      return evalString;
                                  }();
                              }
                        }
                    } else {
                        // 如果还原代码中含有function函数,以及包含DOM,则对function test逻辑取反(a = b -> a = !b)
                        if (/function/g.exec(evalString) && (evalString.indexOf(window.isWin) > 0 || evalString.indexOf(document.isDoc) > 0)) {
                            var reString = /var (\w+)=/g.exec(evalString);
                            reString && (evalString = evalString.replace(reString[0], reString[0] + "!"));
                        }
                    }
                    eval(evalString);
            '''% {'workflow': workflow}

            js_Dom = js_enc.replace('eval('+workflow+');', replaceString)
            js_ctx.eval(js_Dom)  
            ub98484234 = js_ctx.call('ub98484234', self.vid, did, tt) 
        self.logger.debug('ub98484234: ' + ub98484234)
        params = {
            'v': match1(ub98484234, 'v=(\d+)'),
            'did': did,
            'tt': tt,
            'sign': match1(ub98484234, 'sign=(\w{32})'),
            'cdn': '',
            'iar': 0,
            'ive': 0
        }

        def get_live_info(rate=0):
            params['rate'] = rate
            data = urlencode(params)
            if not isinstance(data, bytes):
                data = data.encode()
            html_content = get_content('https://www.douyu.com/lapi/live/getH5Play/{}'.format(self.vid), data=data)
            self.logger.debug(html_content)

            live_data = json.loads(html_content)
            if live_data['error']:
                return live_data['msg']

            live_data = live_data["data"]
            real_url = '{}/{}'.format(live_data['rtmp_url'], live_data['rtmp_live'])
            rate_2_profile = dict((rate['rate'], rate['name']) for rate in live_data['multirates'])
            video_profile = rate_2_profile[live_data['rate']]
            stream = self.profile_2_id[video_profile]
            if stream in info.streams:
                return
            info.stream_types.append(stream)
            info.streams[stream] = {
                'container': 'flv',
                'video_profile': video_profile,
                'src' : [real_url],
                'size': float('inf')
            }

            error_msges = []
            if rate == 0:
                rate_2_profile.pop(0, None)
                rate_2_profile.pop(live_data['rate'], None)
                for rate in rate_2_profile:
                    error_msg = get_live_info(rate)
                    if error_msg:
                        error_msges.append(error_msg)
            if error_msges:
                return ', '.join(error_msges)

        error_msg = get_live_info()
        assert len(info.stream_types), error_msg
        info.stream_types = sorted(info.stream_types, key=self.stream_ids.index)
        return info

    def prepare_list(self):

        html = get_content(self.url)
        return matchall(html, douyu_match_pattern)

site = Douyutv()
```

**Comment by SeaHOH** [comment]
不确定性太大，除非有人专门维护才会 merge。
其实直接替换成以下 js 就能工作。
```diff
+++if (Ee.indexOf("!re &&") == -1) {
+++    var Ee = Ee.replace("re &&", "!re &&");
+++} else {
+++    var Ee = Ee.replace("!re &&", "re &&");
+++}
eval(Ee);
```

**Comment by yoyosnart** [comment]
> 不确定性太大，除非有人专门维护才会 merge。
> 其实直接替换成以下 js 就能工作。
> 
> ```diff
> +++if (Ee.indexOf("!re &&") == -1) {
> +++    var Ee = Ee.replace("re &&", "!re &&");
> +++} else {
> +++    var Ee = Ee.replace("!re &&", "re &&");
> +++}
> eval(Ee);
> ```

請問這個要加在livepy的哪裡才能運作

**Comment by SeaHOH** [comment]
@airdge 给出的代码就能正常工作，我给出的是极简化版本，容错性非常差。

**Comment by DayChan** [comment]
Thanks very much!

**Comment by airdge** [comment]
添加eval(a)(b,c,d)判断
因还原形式基本都差不多,故没做进一步判断

```
            # 替换字符串
            replaceString = ''' 
                    // eval(%(workflow)s); 
                    // let workfolw = %(workflow)s ; 
                    var endEval = '';
                    var newString = "'" + %(workflow)s + "';";
                    // 获取还原过的代码
                    var evalString = eval(newString);
                    // DOM检测
                    if (/(\w+)=(window|document)/g.exec(evalString)) {
                        var execWin = /(\w+)=window/g.exec(evalString);
                        var execDoc = /(\w+)=document/g.exec(evalString);
                        window.isWin = execWin ? execWin[1] : '';
                        document.isDoc = execDoc ? execDoc[1] : '';
                    } 
                    // 如果还原代码中含有eval自执行  eval(a)(b,c,d)
                    if (/eval\(\w+\)\(/g.exec(evalString)) {
                          endEval = 1;
                    }
                    // 如果还原代码中还有eval();
                    else if (/eval\(/g.exec(evalString)) {
                        var encString=evalString.replace(/eval\(\w+\)/g,'');
                        eval(encString);
                        if (/function/g.exec(%(workflow)s) && (%(workflow)s.indexOf(window.isWin) > 0 || %(workflow)s.indexOf(document.isDoc) > 0)) {
                            var reString = /var (\w+)=/g.exec(%(workflow)s);
                            reString && (evalString = %(workflow)s.replace(reString[0], reString[0] + "!"));
                            // 如果还原代码中还包含了混淆代码段
                            let reEval = /\(function\(\)\{(.*)\}\)\(\)/g.exec(encString);
                            if (reEval && />>>|<<<|^/g.exec(reEval[1])) { 
                                  var xxxxxxxxxxx = function() {
                                      eval(reEval[1]);
                                      var funcString = /var (\w+)=/g.exec(%(workflow)s);
                                      funcString && (evalString = %(workflow)s.replace(reString[0], reString[0] + "!"));
                                      return evalString;
                                  }();
                              }
                        }
                        // 如果还原代码不包含function
                        else if (/>>>|<<<|^/g.exec(%(workflow)s)) { 
                             endEval = 1;
                         }
                    } else {
                        // 如果还原代码中含有function函数,以及包含DOM,则对function test逻辑取反(a = b -> a = !b)
                        if (/function/g.exec(evalString) && (evalString.indexOf(window.isWin) > 0 || evalString.indexOf(document.isDoc) > 0)) {
                            var reString = /var (\w+)=/g.exec(evalString);
                            reString && (evalString = evalString.replace(reString[0], reString[0] + "!"));
                        }
                    }
                    endEval ? eval(%(workflow)s) : eval(evalString);
            '''% {'workflow': workflow}
```

**Comment by SeaHOH** [comment]
虽然写了是『临时』，还是问一下，请问你有兴趣持续维护吗？仅单指这种 javascript patch。

**Comment by SeaHOH** [comment]
斗鱼所有直播都改成这种混淆了，看来不改不行。。。

**Comment by BigMangos** [comment]
全部需要DOM了，斗鱼的网页端很是难搞，还经常变

**Comment by incharges** [comment]
修改 @airdge 提供的代码后解决了原本出现的异常 'document' is not defined
然而又出现了 'window' is not defined 异常

**Comment by SeaHOH** [comment]
我重写了一个看起来不那么复杂的，以 `/;(!?)(\w+ && \(function\()/g` 来判断替换反转，并添加了调试代码。

如果有更好的方法，请继续提出来，非常感谢！

**Comment by incharges** [comment]
> 我重写了一个看起来不那么复杂的，以 `/;(!?)(\w+ && \(function\()/g` 来判断替换反转，并添加了调试代码。
> 
> 如果有更好的方法，请继续提出来，非常感谢！

经测试基本完美，可以正常录制
只是偶尔会出现以下讯息
Unexpected identifier after numeric literal
然而还是非常感谢几位大老的协助

**Comment by incharges** [comment]
再次感谢 @SeaHOH 修正新的程式码
经测试不再出现 Unexpected identifier after numeric literal 讯息
这次是真的完美了

**Comment by SeaHOH** [comment]
使用的方法就是 @airdge 提供的，只是重写针对的点不同，可以稍微简化逻辑处理。
而这个 bug 也是我使用随机名称才引入的，并不是混淆的结果。

**Comment by xiatiantiantian** [comment]
YKDL https://www.douyu.com/288016 https://www.douyu.com/998 https://www.douyu.com/987

1.随意选几个正在直播的直播间，只能录制第一个，其他的都不能。（不知道怎么弄，麻烦指点下，谢谢）

2. 偶尔会出现断开（但是手机打开直播间看还在直播的）  
![989](https://user-images.githubusercontent.com/51699978/59260806-ddfac080-8c6e-11e9-9011-8f04c3e9df59.jpg)


3.不知道能不能监听直播间，以防断流后，自动再次录制。

**Comment by BigMangos** [comment]
`PS F:\> ykdl https://www.douyu.com/topic/2019SpringKPL
site:                斗鱼直播 (DouyuTV)
title:               重播丨15日总决eStar vs RNG - 王者荣耀官方赛事
artist:              王者荣耀官方赛事
streams:
    - format:        BD10M
      container:     flv
      video-profile: 蓝光10M
    # download-with: ykdl --format=BD10M [URL]
Now downloading: 重播丨15日总决eStar vs RNG - 王者荣耀官方赛事_BD10M_2019-06-11T18-57-43.170329.flv`

测试正常，直接输入打开网页链接url，用靓号还是要跳转到直接打开的url，目前好像没做跳转，找不到room_id

**Comment by SeaHOH** [comment]
> 1.随意选几个正在直播的直播间，只能录制第一个，其他的都不能。

测试直接播放和录制都正常。

> 2.偶尔会出现断开（但是手机打开直播间看还在直播的）
> 3.不知道能不能监听直播间，以防断流后，自动再次录制。

不能。

**Comment by xiatiantiantian** [comment]
> > 1.随意选几个正在直播的直播间，只能录制第一个，其他的都不能。
> 
> 测试直接播放和录制都正常。
> 
> > 2.偶尔会出现断开（但是手机打开直播间看还在直播的）
> > 3.不知道能不能监听直播间，以防断流后，自动再次录制。
> 
> 不能。

I:\新建文件夹 (4)\ykdl\新建文件夹> YKDL https://www.douyu.com/288016 https://www.douyu.com/998 https://www.douyu.com/987
site:                斗鱼直播 (DouyuTV)
title:               LPL夏季赛FPXvs RW - 英雄联盟赛事
artist:              英雄联盟赛事
streams:
    - format:        BD10M
      container:     flv
      video-profile: 蓝光10M
    # download-with: ykdl --format=BD10M [URL]
Now downloading: LPL夏季赛FPXvs RW - 英雄联盟赛事_BD10M_2019-06-11T20-01-46.497040.flv
stop downloading by press 'q'
Input #0, flv, from 'https://tc-tct.douyucdn2.cn/dyliveflv1a/288016rlols5_1024p.flv?wsAuth=015c97826b518386ceba2d82019ca756&token=web-h5-0-288016-e9416291174176ee3b7ad1c01c0d54b42b75ed5d79e37fa7&logo=0&expire=0&did=224063bc7eed414fb2e5dc62b73459e8&pt=2&st=0&mix=0&isp=':
  Metadata:
    audiochannels   : 2
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : false
    7.1             : false
    encoder         : Lavf57.0.100
    topSpeedMode    : 1
    cdn_ip          : 14.204.139.162
  Duration: 00:00:00.00, start: 7455.450000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 196 kb/s
    Stream #0:1: Video: h264 (High), yuv420p(progressive), 1920x1080, 15561 kb/s, 62 fps, 59.94 tbr, 1k tbn, 124 tbc
Output #0, flv, to 'LPL澶忓璧汧PXvs RW - 鑻遍泟鑱旂洘璧涗簨_BD10M_2019-06-11T20-01-46.497040.flv':
  Metadata:
    audiochannels   : 2
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : false
    7.1             : false
    cdn_ip          : 14.204.139.162
    topSpeedMode    : 1
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=2-31, 15561 kb/s, 62 fps, 59.94 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 48000 Hz, stereo, fltp, 196 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 3087 fps= 74 q=-1.0 Lsize=   33219kB time=00:00:51.48 bitrate=5285.7kbits/s speed=1.23x
video:32330kB audio:788kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.304725%
site:                斗鱼直播 (DouyuTV)
title:               重播丨15日总决eStar vs RNG - 王者荣耀官方赛事
artist:              王者荣耀官方赛事
streams:
    - format:        BD10M
      container:     flv
      video-profile: 蓝光10M
    # download-with: ykdl --format=BD10M [URL]
Now downloading: 重播丨15日总决eStar vs RNG - 王者荣耀官方赛事_BD10M_2019-06-11T20-02-30.248290.flv
stop downloading by press 'q'
Input #0, flv, from 'https://tc-tct.douyucdn2.cn/dyliveflv1/1863767rkpl_1024p.flv?wsAuth=ee7c5c597cd289c12a8dc0e0072047b3&token=web-h5-0-1863767-7b520f6fe0a2b18dfd8cbc7c0efc8f3725df64cacaf653f0&logo=0&expire=0&did=e433f78a42c64d78a8f5e35096224bda&pt=2&st=0&mix=0&isp=':
  Metadata:
    audiodelay      : 0
    server          : SRS/2.0.234(ZhouGuowen)
    srs_primary     : SRS/1.0release
    srs_authors     : winlin,wenjie.zhao
    server_version  : 2.0.234
    encoder         : Lavf58.27.103
    topSpeedMode    : 1
    cdn_ip          : 58.144.154.113
  Duration: 00:00:00.00, start: 105489.618000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 327 kb/s
    Stream #0:1: Video: h264 (High), yuv420p(progressive), 1920x1080, 3072 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc
Output #0, flv, to '閲嶆挱涓?5鏃ユ€诲喅eStar vs RNG - 鐜嬭€呰崳鑰€瀹樻柟璧涗簨_BD10M_2019-06-11T20-02-30.248290.flv':  Metadata:
    audiodelay      : 0
    server          : SRS/2.0.234(ZhouGuowen)
    srs_primary     : SRS/1.0release
    srs_authors     : winlin,wenjie.zhao
    server_version  : 2.0.234
    cdn_ip          : 58.144.154.113
    topSpeedMode    : 1
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=2-31, 3072 kb/s, 25 fps, 25 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 327 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  430 fps= 39 q=-1.0 size=    6656kB time=00:00:17.16 bitrate=3177.5kbits/s speed=1.56x

还是不可以同时录制几个直播间啊，不知道是不是我操作错误，这3个直播间都在直播。

**Comment by BigMangos** [comment]
开三个命令行窗口

**Comment by SeaHOH** [comment]
> 开三个命令行窗口

是这样的，无法同时播放或录制单个命令，需要分别运行。

**Comment by a67878813** [comment]
此时，下载的zip包，对任意房间使用后显示如下错误

Gjs-Message: JS WARNING: [/tmp/execjsze1d78o3.js 5]: variable n redeclares argument
Gjs-Message: JS WARNING: [/tmp/execjsze1d78o3.js 10]: assignment to undeclared variable result
Gjs-Message: JS WARNING: [/tmp/execjsrry1siij.js 6]: variable n redeclares argument
Gjs-Message: JS WARNING: [/tmp/execjsrry1siij.js 11]: assignment to undeclared variable hqznH926
Gjs-Message: JS WARNING: [/tmp/execjsrry1siij.js 12]: "window" is read-only
Gjs-Message: JS WARNING: [/tmp/execjsrry1siij.js 13]: assignment to undeclared variable document
Gjs-Message: JS WARNING: [/tmp/execjsrry1siij.js 10]: assignment to undeclared variable result
Gjs-Message: JS WARNING: [/tmp/execjsu02q3fly.js 6]: variable n redeclares argument
Gjs-Message: JS WARNING: [/tmp/execjsu02q3fly.js 11]: assignment to undeclared variable hqznH926
Gjs-Message: JS WARNING: [/tmp/execjsu02q3fly.js 12]: "window" is read-only
Gjs-Message: JS WARNING: [/tmp/execjsu02q3fly.js 13]: assignment to undeclared variable document
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 9, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/cykdl/__main__.py", line 178, in main
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/extractor.py", line 21, in parser
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/extractors/douyu/live.py", line 126, in prepare
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 135, in eval
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 171, in _eval
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 187, in _exec
ykdl.util.jsengine.ProgramError: SyntaxError: illegal character

**Comment by TaoziDB** [comment]
only possible illegal character might be ` in js_enc due to limited support of some js engine for template string, in this case, replace all ` with " should work too

**Comment by a67878813** [comment]
@TaoziDB Which character should i replace?

**Comment by TaoziDB** [comment]
only possible illegal character might be back-tick in js_patch due to limited support of some js engine for template string, in this case, replace all back-tick with " should work too

**Comment by a67878813** [comment]
\fdsdfsd\

**Comment by a67878813** [comment]
`asdasd`

**Comment by a67878813** [comment]
I replaced back-tick with " in js_patch and it failed.

`ykdl.util.jsengine.ProgramError: SyntaxError: unterminated string literal`
seems there are too many " to accomplish ''' ''' str's grammar

**Comment by TaoziDB** [comment]
only 2 \`, don't confuse with single quote

**Comment by a67878813** [comment]
![Image 2](https://user-images.githubusercontent.com/16067382/59452791-19e57f80-8e41-11e9-9071-eaf14e9ce442.png)
it just did not work.

**Comment by SeaHOH** [comment]
`"`不支持换行，删掉换行试试。

**Comment by a67878813** [comment]
@SeaHOH 测试成功 ubuntu16.04
![Image 3](https://user-images.githubusercontent.com/16067382/59453603-d68c1080-8e42-11e9-9add-e8f9adb7210d.png)

**Comment by SeaHOH** [comment]
再次简化，只修改 DOM 检测函数。

**Comment by zxdong262** [comment]
试了下,似乎很短时间之后就会中断?

**Comment by TaoziDB** [comment]
三个线路：主线路 ws-h5，备用线路5 tct-h5，备用线路6 ali-h5
只有用备用线路5 tct-h5的时候不会断，其它两个线路过几秒就会断，怀疑流文件格式不标准

**Comment by SeaHOH** [comment]
关于线路问题，这只和用户网络相关，即使同一线路，不同用户播放效果也会有不同表现。

本项目不会强制选择，如有需要请自行修改源码中的`cdn`参数。

**Comment by guest6379** [comment]
@airdge @SeaHOH 
天才，神一样的存在，感谢你们的commit

**Comment by xiatiantiantian** [comment]
@SeaHOH 

ROOMID:   7020364
报错
kinako鏌効    鐨勭洿鎾棿 - kinako鏌効_BD4M_2020-03-13T00-16-51.395533.flv: Invalid argument

**Comment by SeaHOH** [comment]
感谢反馈！不过，像这种不太相关的 bug 能单独提 issue 就更好了。

**Comment by xiatiantiantian** [comment]
douyu.com/g_yz    （随便选一个手机播的，2人正在PK的，竖屏的都是手机播的）

只要是用手机播的，2人PK的话，只能下载到一个人的画面。（电脑播的没有这个问题）

遇到2人PK，它会刷新一个新的视频源（2人PK的画面），原始源降码率且一直有效（但是一直是一个人画面）。 PK结束后这个视频源自动失效。
