### ISSUE TITLE
哪个方法是开始在写文件（创建）

### ISSUE THREAD

**Issue by xinshen18** [zhangn1985/ykdl#425]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 为了实现抓取的视频与弹幕时间轴对上，我需要知道文件（视频文件）创建时间，即开始写文件的时间

**Comment by SeaHOH** [comment]
没搞懂文件创建时间和弹幕能有什么联系。
如果你想看弹幕，好些其它仓库已经有相关实现了。比如：https://github.com/xjbeta/iina-plus
如果你想自己写一个的话，或者说想用 ykdl 修改，建议你先看一遍主要模块的源码，数量并不大。

**Comment by xinshen18** [comment]
get 已经实现啦，在launch_ffmpeg_download这个方法里，谢谢
