### ISSUE TITLE
文件类型改为mp4

### ISSUE THREAD

**Issue by xinshen18** [zhangn1985/ykdl#426]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 在抓取斗鱼直播时会把视频存为flv文件，但是想存为mp4文件，有看到以前类似的issue说改wrap.py中launch_ffmpeg方法的ext，但是斗鱼抓的时候走的是wrap.py的launch_ffmpeg_download方法，请问可以如何修改？

**Comment by SeaHOH** [comment]
扩展名就是文件名的一部分，直接改文件名就行。
你这是打算干嘛？
没必要在 issues 讨论这些和使用无关的细节问题，可以直接[邮件](mailto:SeaHOH@Gmail.com)或[私信](https://gitter.im/SeaHOH)我。
还有就是，善用搜索引擎，python 是脚本语言，随便折腾就是，基本不可能搞坏系统。
