### ISSUE TITLE
虎牙最新问题

### ISSUE THREAD

**Issue by eleeeeeee** [zhangn1985/ykdl#432]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
site:                Huya Live (虎牙直播)
title:               虎牙2230034393的直播间「Dae-狙神小抠脚 - 【狙神】认证号2v98求狙」
artist:              Dae-狙神小抠脚
streams:
    - format:        current
      container:     m3u8
      video-profile: current
    # download-with: ykdl --format=current [URL]
Download: 虎牙2230034393的直播间「Dae-狙神小抠脚 - 【狙神】认证号2v98求狙」 part 0
Download: 虎牙2230034393的直播间「Dae-狙神小抠脚 - 【狙神】认证号2v98求狙」 part 1
Download: 虎牙2230034393的直播间「Dae-狙神小抠脚 - 【狙神】认证号2v98求狙」 part 2
 100%Merging video 虎牙2230034393的直播间「Dae-狙神小抠脚 - 【狙神】认证号2v98求狙」 using ffmpeg:
Input #0, mpegts, from 'concat:铏庣墮2230034393鐨勭洿鎾棿銆孌ae-鐙欑灏忔姞鑴?- 銆愮嫏绁炪€戣璇佸彿2v98姹傜嫏銆峗0_.ts|铏庣墮2230034393鐨勭洿鎾棿銆孌ae-鐙欑灏忔姞鑴?- 銆愮嫏绁炪€戣璇佸彿2v98姹傜嫏銆峗1_.ts|铏庣墮2230034393鐨勭洿鎾棿銆孌ae-鐙欑灏忔姞鑴?- 銆愮嫏绁炪€戣璇佸彿2v98姹傜嫏銆峗2_.ts':  Duration: 00:00:25.00, start: 17833.365011, bitrate: 8389 kb/s
  Program 1
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt709/bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1[0x101]: Audio: aac (HE-AACv2) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 23 kb/s
Output #0, mp4, to '铏庣墮2230034393鐨勭洿鎾棿銆孌ae-鐙欑灏忔姞鑴?- 銆愮嫏绁炪€戣璇佸彿2v98姹傜嫏銆?mp4':
  Metadata:
    encoder         : Lavf58.18.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt709/bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 23 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  750 fps=0.0 q=-1.0 Lsize=   24969kB time=00:00:24.94 bitrate=8199.4kbits/s speed= 175x
video:24876kB audio:73kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.080034%
```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
最新的huya site 下载几秒自动退出了  请大佬解决一下

**Comment by SeaHOH** [comment]
确认你的网速足够，或者更新 FFmpeg 。

**Comment by SeaHOH** [comment]
之前设置的下载方式不太对，你再试试。
