### ISSUE TITLE
视频只能下载一半，而且命令行报错

### ISSUE THREAD

**Issue by WordWang** [zhangn1985/ykdl#437]
请将错误输出粘贴在下面:
只能下载一半的视频，在优酷网页上看视频中间会有广告，只能下载开头到广告的那一半，广告之后的一部分就无法下载。而且命令行中最后会有一个报错。

> [您的内容]
C:\Users\王齐>ykdl https://v.youku.com/v_show/id_XMjg5OTg0OTc2MA==.html?spm=a2h0j.11185381.listitem_page1.5!16~A&&s=311801efbfbd111211ef
site:                优酷 (Youku)
title:               留级危机
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          98.7 MiB (103493344 bytes)
    # download-with: ykdl --format=TD [URL]
Download: 留级危机_TD part 0
Download: 留级危机_TD part 1
Download: 留级危机_TD part 2
Download: 留级危机_TD part 3
 100%Merging video 留级危机_TD using ffmpeg:
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001e9de4e2b40] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'C:\Users\鐜嬮綈\tmpm175r8d0.txt':
  Duration: N/A, start: -0.046440, bitrate: 664 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 536 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
Output #0, flv, to '鐣欑骇鍗辨満_TD.flv':
  Metadata:
    encoder         : Lavf58.30.100
    Stream #0:0(und): Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 536 kb/s, 25 fps, 25 tbr, 1k tbn, 12800 tbc
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001e9de4e2b40] Auto-inserting h264_mp4toannexb bitstream filter
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001e9ded199c0] Auto-inserting h264_mp4toannexb bitstream filter
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001e9de4e2b40] Auto-inserting h264_mp4toannexb bitstream filter
frame=19581 fps=0.0 q=-1.0 Lsize=   56930kB time=00:13:03.19 bitrate= 595.5kbits/s speed=2.22e+03x
video:43749kB audio:12238kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.683993%
's' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by zhangn1985** [comment]
使用引号吧网址保护起来，或者删除`?`及之后的字符。

**Comment by WordWang** [comment]
> 使用引号吧网址保护起来，或者删除`?`及之后的字符。

命令行里不会报错了，但是视频还是只有一半耶( •̀ ω •́ )y
