### ISSUE TITLE
以后有可能下载到vip视频吗？

### ISSUE THREAD

**Issue by ShekBoy** [zhangn1985/ykdl#44]
因为爱奇艺一堆版权VIP独播，所以在外面很难找到高清的下载(虽说爱奇艺那渣画质也是...)
不是指破解VIP那些，例如导入cookies那种方法也可以，因为最近you-get跟youtube-dl的爱奇艺解析经常出错，也解析不了1080p，所以就一直用这个ykdl来下载了，另外希望加入you-get或者youtube-dl那种只在解析时候用proxy的功能，you-get参数是-y，youtube-dl的参数是--geo-verification-proxy

**Comment by zhangn1985** [comment]
proxy 是支持的。-p参数，默认是使用系统代理。

**Comment by zhangn1985** [comment]
爱奇艺的vip（暂时）破解不了。而且爱奇艺还有部分视频无法下载

**Comment by zhangn1985** [comment]
另说，我不太明白youtube-dl 的 --geo-verification-proxy，或者 you-get的-p /-y 输入的代理，和普通的代理有何区别。。
大统一不很好吗？

**Comment by ShekBoy** [comment]
好的，谢谢，暂时我下载连续剧还没遇到不能下载的情况
因为很多proxy都不稳定，或者速度比较慢，所以如果只在解析的时候用proxy，下载的时候用回原来的，速度跟稳定性都会比较快和高

**Comment by zhangn1985** [comment]
更正一下，--proxy 才是本项目的代理参数。

**Comment by zhangn1985** [comment]
如果你把链接导入到外部下载器，那么就没有使用代理了。

**Comment by ShekBoy** [comment]
爱奇艺这类m3u8的话不可以
而且试过用proxy解析到爱奇艺的m3u8链接以后用livestreamer无论用不用proxy也报错无法下载... :'(

**Comment by zhangn1985** [comment]
应该不行，应该不会支持，不想动官方下载器的地盘。
