### ISSUE TITLE
爱奇艺部分视频下载后只有音频

### ISSUE THREAD

**Issue by StephenPaul25** [zhangn1985/ykdl#447]
例如以下地址：
http://www.iqiyi.com/v_19rt4jyg3s.html
http://www.iqiyi.com/v_19rt4bnpmg.html
http://www.iqiyi.com/v_19rt4az034.html
http://www.iqiyi.com/v_19rt4b7ihw.html
http://www.iqiyi.com/v_19rt4iv5ik.html

下载后仅有音频没有画面。

**Comment by SeaHOH** [comment]
估计是爱奇艺转换 HLS 的时候出现错误，导致 m3u8 格式视频部分丢失。

如果是那种特别想下载的，可以修改代码获取 fv4 格式地址。
看下面，在 L189 - 192 之间（版本不同的话不一定是这个行数）增加一行 `raise`。
https://github.com/zhangn1985/ykdl/blob/460561585e0a8c94c9f5ea4c72c6587059395f45/ykdl/extractors/iqiyi/video.py#L189-L192

**Comment by airdge** [comment]
```
        def push_stream_vd(vs):
            vd = vs['vd']
            stream = self.vd_2_id[vd]
            if not stream in info.streams:
                info.stream_types.append(stream)
            elif int(vd) < 10: 
                return
            m3u8 = vs['m3utx']
            stream_profile = self.id_2_profile[stream]
            info.streams[stream] = {
                'video_profile': stream_profile,
                'container': 'm3u8',
                'src': [m3u8],
                'size': 0
            }
```
这个函数有问题, 
vd要在 [96, 1, 2, 4] 里面

`    lists = {i: j['m3u'] for i in [96, 1, 2, 4] for j in data['data']['vidl'] if i == j['vd']}`

**Comment by SeaHOH** [comment]
那么还是优先解析 H264 好了，等会儿和 dash 一起发。
