### ISSUE TITLE
IQIYI download not working; string index out of range

### ISSUE THREAD

**Issue by BowDown097** [zhangn1985/ykdl#462]
Using 1.6.2, Windows (I hope you understand English)
Got this index out of range video when trying to rip from IQIYI. I tried 2 versions of the same URL, thinking it was perhaps a URL issue, but I don't think it is. I don't understand how IQIYI works much, so maybe it is a problem with the URL, but I don't know. The outputs from both URLs are the same.

![image](https://user-images.githubusercontent.com/42720004/68062678-1c018b00-fcc9-11e9-8de9-f265d02e10f1.png)
![image](https://user-images.githubusercontent.com/42720004/68062773-726ec980-fcc9-11e9-97c4-a795aa9617e6.png)

They are both VIP videos, but I tried with a non-VIP video as well and got the same error.

**Comment by SeaHOH** [comment]
Please update to master branch:

`pip install --upgrade https://github.com/zhangn1985/ykdl/archive/master.zip`
