### ISSUE TITLE
可否添加对 QuickJS 的支持

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#465]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 看了一下，`Termux`现在已经提供了`QuickJS`
加上`QuickJS`的支持的话
如果不需要`Node.js`就无需在`Termux`上安装`Node.js`了
减少空间的占用
[QuickJS precompiled binaries (linux-x86_64)](https://bellard.org/quickjs/binary_releases/)
[QuickJS](https://bellard.org/quickjs/)

**Comment by airdge** [comment]
https://github.com/PetterS/quickjs

倒是挺方便的 不过要python版本支持

**Comment by SeaHOH** [comment]
@mengmo Termux 下有的话，你直接添加 `qjs` 到这里试试看：
https://github.com/zhangn1985/ykdl/blob/94be39f4cb3b017cf7aede5448678b041cfae9ad/ykdl/util/jsengine.py#L104

那个 python pkg 倒是很方便，不过没有提供更多的 wheel，需要用源码安装编译。

**Comment by mengmo** [comment]
@SeaHOH
按照你给的方法修改过之后，执行解析后一直卡着不动

测试用的是这个
```
ykdl -i https://www.douyu.com/122402
```

尝试在 Windows 上测试
注释掉这几行
https://github.com/zhangn1985/ykdl/blob/94be39f4cb3b017cf7aede5448678b041cfae9ad/ykdl/util/jsengine.py#L90-L94
修改这一行为`interpreter = which('qjs')`
https://github.com/zhangn1985/ykdl/blob/94be39f4cb3b017cf7aede5448678b041cfae9ad/ykdl/util/jsengine.py#L96

结果与`Termux`上遇到一样的问题

直接结束`qjs.exe`的进程，居然出来解析结果了

试着在`Termux`上干掉`qjs`的进程，居然也出来解析结果了

这算是哪儿的问题？

**Comment by mengmo** [comment]
顺带着测试了下几个`js engine`

以下几个顺利解析
[ChakraCore](https://github.com/Microsoft/ChakraCore) v1.11.15 `ch.exe`
[Duktape](https://duktape.org/) v2.4.0 `duk.exe`
[SpiderMonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey) v70.0.1 `js.exe`

这个能解析，但是不顺
[QuickJS](https://bellard.org/quickjs/) v2019-10-27 `qjs.exe`

以下几个解析失败，直接报错
[V8](https://v8.dev/) v8.0.353 `d8.exe`
[Hermes JS Engine](https://hermesengine.dev/) v0.3.0 `hermes.exe`

**Comment by SeaHOH** [comment]
QuickJS 有 Termux 提供，确实方便，不过我没找到预编译的 Windows 版本。试过 PetterS 的 python binding，挺不错的。

V8 挺有名的，我也没找到 alone 版本。python binding 倒是有人写过，但是都未更新，编译过程也很复杂。

请问上面两个 js engine 的具体发布链接是在哪里？可提供给我用以调试。
另外，其余几个 js engine 都获取不便，不太适合 python 使用。

**Comment by mengmo** [comment]
QuickJS 的 Windows release https://github.com/mengmo/QuickJS-Windows-Build/releases
V8 8.0.354 https://storage.googleapis.com/chromium-v8/official/canary/v8-win64-rel-8.0.354.zip

V8 prebuilt 的下载可以从这个项目 [jsvu](https://github.com/GoogleChromeLabs/jsvu) 的代码里找(当然也可以直接用 jsvu 装)

另外，如果不麻烦的话。可以把上边我测试没问题的`js engine`都加到 Windows 和 Linux 上
提示的话就还提示易获取的`js engine`就行

**Comment by SeaHOH** [comment]
上面测试中所有不能使用的 js engine 都已修复兼容。

ChakraCore、SpiderMonkey、V8 都属于主流浏览器使用的 core，但是其 alone 版本都不算是正式的 Javascript 工具，没有安装包，不主动设置系统变量的话，没法用名称自动找到。

默认只增加了自动发现 QuickJS，另外可以使用新添加的 `set_external_interpreter` 函数来自定义要使用的 js engine。

测试没问题再合并主分支。

**Comment by mengmo** [comment]
你不会觉得如果能弄到其他`js engine`的连设置系统环境变量都不会吧？
系统环境变量都不会设置的只要按照提示的来安装相应的`js engine`就行了
只推荐易安装的js engine就可以了

即使添加了其他`js engine`自动发现，实际使用上也不会有什么问题
而现在的改动，如果要用其他的`js engine`还得自己改

还有，又翻了下。
Termux 也提供了`duktape`，这是目前能找到的最小的支持 ES6 的`js engine`
也是最好编译的`js engine`

对比`aarch64`上最新版的 Duktape 与 QuickJS
QuickJS 不只有`qjs`，还有`qjsbn` `qjsc` `qjsbnc`等，装好后占用空间接近 4MB
Duktape 只有一个`duk`，`322.1 KB`大

**Comment by SeaHOH** [comment]
这其实是个使用定位的问题，这个 module 只是设计来提供一种尽可能简单的在 python 中运行 ES6 及以上版本 Javascript code 的方法。就按之前考虑的那样，支持 system built-in、 python binding 和最常规的 Node，没必要去收集过多的 interpreter，而且由于不是正式发布的通用工具，因此使用了像 `ch`、`js`、`d8` 等独特性太少的名称，它们不适合用于自动发现，说不定就能找上其它重名文件。

我昨天修改的时候，心血来潮，一下子添加了好几个新功能，最后反应过来就都删掉了，因为真的不合适。其实如果想做一个比较全面的东西，可以考虑写成一个单独的 package，就像 execjs 那样的，可以做得更好更方便。

不过看到上面提到 Termux 也提供 Duktape，然后我就发现了 [amol-/dukpy](https://github.com/amol-/dukpy)，不涉及其它 engine，但是功能非常全面，估计使用体验会比较接近 Node，还能灵活配合 python。把这个 binding 弄进来也只能使用到它最基本的能力，不过好处是它支持的 python 版本足够多，wheel 最大也才 2MB；缺点是不完全支持 ES6，具体不清楚，不知道实际使用会不会受到影响。

Duktape 情况与 QuickJS 类似，添加问题不大，只是我又双叒叕找不到 Windows prebuilt 版本来调试。。。

最后有个问题，Duktape 和 QuickJS 到底是 Termux built-in 还是要 install？doc 和 error 文本可能还需要修改。

**Comment by SeaHOH** [comment]
试了下 dukpy，真的是不完全支持 ES6，没法用，不知道最新版 Duktape 情况如何。

**Comment by SeaHOH** [comment]
去 https://github.com/svaarala/duktape/issues 看了下，情况并不乐观，短期内是不可能完全支持了。

**Comment by mengmo** [comment]
Termux 本身只提供了最基础的 Linux tool，要使用其他功能都要自己装
Termux 上要用 Python，要使用任何`js engine`都要自己装
就像 Windows 10 之外的其他 Windows 版本一样

至于 Duktape 不完全支持 ES6，目前也没有一个`js engine`能完整的支持全部的 ES 特性
但是我们用`js engine`只是用来解析视频，只要能做到这一点就够了

至于 Duktape 的 Windows prebuilt
只要下载源码包，装好编译工具。
按照官方的文档操作，编译就是一行命令的事。
还是，要不我编译一个传上来？

**Comment by SeaHOH** [comment]
Duktape 连许多常用的 ES6 特性都不支持，至少当前版本的 dukpy 是这样的，你可以先测试一下 svaarala 最新的 release 是不是还是这个状况，不然真没法用。

话说有必要在乎 3MB 的差距？我情愿用这点空间交换更多的可靠性。

**Comment by mengmo** [comment]
你向上翻一下，看我两天前的测试结果

**Comment by mengmo** [comment]
刚发现前几天编译的 Duktape 没删，64位的
[duktape-2.4.0.zip](https://github.com/zhangn1985/ykdl/files/3886943/duktape-2.4.0.zip)

**Comment by SeaHOH** [comment]
嗯，还真是小巧，douyu 和 iqiyi 的 js 现在都能运行。
稍微测试了下，dukpy 不支持的 `**` 也能用了，但是像
```js
let v = 1
function f(x=1) {}
f = () => {}
f(`$(1+2)`)
for (i of a) {}
for (i in o) {}
```
以上这些都还是不支持，说不定哪天就会需要运行包含这些特性的 js，就是我上面说的，不可靠不保险。

**Comment by mengmo** [comment]
方便的话，麻烦将你测试的完整代码发上来看看

**Comment by SeaHOH** [comment]
重新整理了昨天的测试，又添加了一些常用的 ES6 特性。
结果是 Hermes 和 Duktape 支持不足，Duktape 表现尤其惨烈，不过因为支持 TypedArray 所以 iqiyi 才没挂。

**Comment by SeaHOH** [comment]
@mengmo 还有没有哪里不对？准备合并。

**Comment by mengmo** [comment]
@SeaHOH 当前没有发现什么问题
