### ISSUE TITLE
寻一名合作伙伴| looking for Collaborators, deadline: 2017.3.31

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#47]
寻一名合作伙伴。
looking for Collaborators

可以直接提交代码到本项目，可以merge自己和他人的pull requests。
after you become collaborator, you can merge pull requests form you and others

需要在python/破解视频网站上有一定的经验。
require: python & related experience.

**Comment by jindaxia** [comment]
我可以加入

**Comment by zhangn1985** [comment]
需要你自我介绍一下，为什么你满足条件？
