### ISSUE TITLE
bilibili 视频 can't play this video!!

### ISSUE THREAD

**Issue by a67878813** [zhangn1985/ykdl#471]
更新至今日master后

ubuntu19.10
命令：ykdl -o '/mnt/nvliu/' https://www.bilibili.com/video/av7573860/
输出：can't play this video!!

**Comment by SeaHOH** [comment]
请贴出 `ykdl -i --debug https://www.bilibili.com/video/av7573860/` 的结果。

**Comment by a67878813** [comment]
@SeaHOH ykdl -i --debug https://www.bilibili.com/video/av7573860/
video_host> www.bilibili.com
short_name> bilibili
get_content> URL: https://www.bilibili.com/video/av7573860/
get_content> Charset: utf-8
get_content> URL: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&platform=html5&player=0&qn=0&cid=12402137&sign=80dd163a92529160a4ec65a346728d2a
get_content> Charset: utf-8
HTML> <?xml version="1.0" encoding="UTF-8"?>
<video>
   <result>error</result>
   <code>10002</code>
   <message><![CDATA[Invalid signature parameter.]]></message>
</video>
can't play this video!!

**Comment by SeaHOH** [comment]
好像在抽风，大部分时候都正常，偶尔出现不同的 error code。
暂时不用管，过两天再看。

**Comment by mengmo** [comment]
@a67878813  你是不是挂了全局代理？

**Comment by a67878813** [comment]
@mengmo 没设置全局代理

**Comment by a67878813** [comment]
@SeaHOH @mengmo 问题找到了，本地的DNS解析有问题，更换阿里云DNS解决。
