### ISSUE TITLE
建议增加wetv.vip支持

### ISSUE THREAD

**Issue by fanxy121** [zhangn1985/ykdl#480]
建议增加wetv.vip的支持
如https://wetv.vip/play?vid=h0033xd0rj1

**Comment by fanxy121** [comment]
请粗略浏览一下，此站是腾讯视频国际版，绝大多为免费内容。可考虑纳入支持列表。

**Comment by SeaHOH** [comment]
这个 vip 太能迷惑人，确实有免费内容。
不过现有代码还是无法顺利下载，年后再弄吧。

话说，wetv 是人 USA 的付费频道名称。

**Comment by apt42541** [comment]
https://access.wetv.vip/overseas/vplay_getinfo
https://access.wetv.vip/overseas/vplay_proxy

don't know any useful?

**Comment by SeaHOH** [comment]
尝试用 https://github.com/zhangn1985/ykdl/issues/286#issuecomment-546285766 提到的方法规避下载限制，没有成功。如果要下载第二及之后的视频分段，可能需要重复运行多次。
