### ISSUE TITLE
douyu直播下载

### ISSUE THREAD

**Issue by BigMangos** [zhangn1985/ykdl#486]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。

请将错误输出粘贴在下面:

执行 `ykdl https://www.douyu.com/337852`，一段时间后，出现错误

```
[mp4 @ 000001b8687e0740] Non-monotonous DTS in output stream 0:0; previous: 89808097, current: 89808064; changing to 89808098. This may result in incorrect timestamps in the output file.
[mp4 @ 000001b8687e0740] Non-monotonous DTS in output stream 0:0; previous: 89808098, current: 89808064; changing to 89808099. This may result in incorrect timestamps in the output file.
[mp4 @ 000001b8687e0740] Non-monotonous DTS in output stream 0:0; previous: 92212656, current: 92212656; changing to 92212657. This may result in incorrect timestamps in the output file.
frame=100017 fps= 15 q=-1.0 size= 1730816kB time=01:51:09.73 bitrate=2125.8kbits/s speed=1.01x
```

直播没结束，ffmpeg 出现警告，然后不再下载，也不报错退出，此时终止 ffmpeg，下载的视频提示损坏无法观看。

**Comment by SeaHOH** [comment]
没有复现，请确定你的 ffmpeg 版本和网络均正常。

**Comment by SeaHOH** [comment]
还有一种情况是主播的网络出现故障或切换，造成无法继续录制，此时应等待 ffmpeg 自动结束，或按下 `q` 键等待。如手动杀死 ffmpeg 进程后无法顺利打开录制的视频，尝试运行以下命令：
```
ffmpeg -i 录制视频路径 -c copy 输出修复视频路径
```

**Comment by BigMangos** [comment]
> 没有复现，请确定你的 ffmpeg 版本和网络均正常。

ffmpeg 版本为 `20200203-1c15111` Static 版本，网络应该没问题，一般录制时间 2h 左右才会出现

> 还有一种情况是主播的网络出现故障或切换，造成无法继续录制，此时应等待 ffmpeg 自动结束，或按下 `q` 键等待。如手动杀死 ffmpeg 进程后无法顺利打开录制的视频，尝试运行以下命令：
> 
> ```
> ffmpeg -i 录制视频路径 -c copy 输出修复视频路径
> ```

现在主播信号不好也会自动结束，问题是比如想要录制一晚上，ffmpeg 录制 2h 左右就卡住了，也没结束，也不继续录制新的，直接卡死了，以后不管直播是否结束，这个 ffmpeg 进程一直在

**Comment by BigMangos** [comment]
现在临时用 `ffmpeg -t 3600 ...` 临时录制 1h 自动终止，重启 ffmpeg 进程

**Comment by SeaHOH** [comment]
录一晚上。。。这些主播晚上不睡觉都在干嘛，能挣钱？
不过，这种长时间录制的问题确实受网络影响，还真没有什么好办法，估计 ffmpeg 也不会管得太细致，只能自己写个专门的脚本处理。对于已录制的损坏视频，可以尝试各种办法来修复，祝好运。

**Comment by BigMangos** [comment]
hhh，这些主播在凑时长，长时间确实会出问题，出现问题自动结束 ffmpeg 进程就好办，写了一个小脚本自动获取 url 启动 ffmpeg 进程，但是卡死就没办法了。

by the way，感谢 @SeaHOH，修复损坏视频的方法学到了

**Comment by SeaHOH** [comment]
那个命令不一定会成功，更多的修复方法或软件可搜索网络学习。

**Comment by BigMangos** [comment]
确实，目前没找到问题所在，huya 就没这个问题

**Comment by BigMangos** [comment]
`ffmpeg -t ...` 命令无效，修复有效，录制卡死挂起还是没办法解决

**Comment by SeaHOH** [comment]
用 python 写比较方便，调用 => 定时 => 终结 => 调用，这样循环。调用参数可参考 util.wrap.launch_ffmpeg_download 。

**Comment by BigMangos** [comment]
这个办法好，谢谢 @SeaHOH
