### ISSUE TITLE
[调研]关于放弃对低版本 python 的支持，请发表你的意见

### ISSUE THREAD

**Issue by SeaHOH** [zhangn1985/ykdl#487]
**此调研在置顶期间有效，请发表你的意见，这对 ykdl 的后续开发和维护很重要。**

起因：
* 版本跨度过大，考虑兼容性，写起代码来比较麻烦，有时还会忘记考虑。（测试另论，此处不讨论）
* 无法利用新的语言特性，简化和复用代码易受挫。
* python2 的官方支持已结束，有潜在的安全风险。

预计放弃的版本范围：
* 3.5 及以下版本。

问卷调查：
* 你会在哪些版本的 python 上运行 ykdl？
* 你是否赞成放弃对低版本 python 的支持？
* 赞成的，你觉得放弃的范围应该是哪些？
* 不赞成的，你的理由是什么？

**Comment by zhangn1985** [comment]
看看是否根据ubuntu18.04 lts ， debian 10， deepin 15.11， UOS 的python3版本来作为支持对象？

**Comment by zhangn1985** [comment]
ubuntu18.04 3.6.9
debian 10 3.7.3

**Comment by SeaHOH** [comment]
嗯，没有仔细统计过，凭感觉 3.5 系列已经被主流淘汰。3.6 还算过得去吧，暂时不太会有兼容性方面的问题，不过也快淘汰了。

话说，能同步一下 PyPI 版本吗？其实通过 CI 自动发布最方便了，写好脚本后就不用管了。不过，Windows 的单文件版仍然需要手动打包。

**Comment by airdge** [comment]
deepin默认3.5
如果没用到F'格式化和字典排序,3.5问题不大

**Comment by SeaHOH** [comment]
> 如果没用到F'格式化和字典排序,3.5问题不大

有点想用，你看我这个 [commit](https://github.com/zhangn1985/ykdl/commit/3e42d703bf5e126d5da06bbaee858e8a3c29d888) ，用了写起来就很简洁。

主要是想看看有没有什么非要兼容它们的理由，虽然我预计不会有太大问题。deepin 安装多版本也能用，在启动时检查环境版本，给不支持的写个升级指导说明就可以了。

**Comment by coslyk** [comment]
> 嗯，没有仔细统计过，凭感觉 3.5 系列已经被主流淘汰。3.6 还算过得去吧，暂时不太会有兼容性方面的问题，不过也快淘汰了。

感觉还是要支持一下 3.5 比较好？考虑到 Ubuntu 16.04 和 Debian 9 还没有 EOF，还会有人在用
> 
> 话说，能同步一下 PyPI 版本吗？其实通过 CI 自动发布最方便了，写好脚本后就不用管了。不过，Windows 的单文件版仍然需要手动打包。


Windows / Linux 单文件版都可以通过 Travic CI 自动发布，可以参考下我的另一个项目：https://github.com/coslyk/moonplayer-plugins

**Comment by BigMangos** [comment]
Python 支持多版本共存，问题不大，同步 PyPI 比较好，现在可以用 GitHub Actions 吧

**Comment by SeaHOH** [comment]
@coslyk 以前好像不支持 Windows，现在能用非常好。另，给你发了封电邮，注意查看。

**Comment by toorich** [comment]
> Python 支持多版本共存，问题不大，同步 PyPI 比较好，现在可以用 GitHub Actions 吧

的确可以，但是使用包管理的Linux有一定困难（因软件包名问题，更新后原版本会被覆盖）

**Comment by toorich** [comment]
我支持放弃旧版本，这样方便移植一些you-get的脚本（比如风行）

**Comment by SeaHOH** [comment]
Python 是个天坑，3.5 也不好现在就放弃，是这个意思吧？

**Comment by lleeopen** [comment]
不要放弃旧版

**Comment by SeaHOH** [comment]
> 不要放弃旧版

全部？有什么理由吗？

**Comment by Justsoos** [comment]
@coslyk 你的 moonplayer 在 mac 上默认系统 python27，还是很难受的啊

**Comment by toorich** [comment]
> 我支持放弃旧版本，这样方便移植一些you-get的脚本（比如风行）

补一句：保留3.4以及更高版本的支持，这样还可以支持XP（x

**Comment by mengmo** [comment]
@SeaHOH 需要我把这个的第三条 tip 给删了吗？
https://github.com/zhangn1985/ykdl/wiki/Windows-Build-script

**Comment by SeaHOH** [comment]
> 需要我把[这个](https://github.com/zhangn1985/ykdl/wiki/Windows-Build-script)的第三条 tip 给删了吗？

再讨论下，看有没有足够的理由来支持 3.4。支持 XP 这个理由似乎没有足够的说服力，还有许多 ykdl 用户必须使用它吗？

根据以上讨论，3.5 还是要暂时支持的，那么把它的废弃时间定在各大发行版使用 3.5 的版本 EOF 后，如何？

**Comment by netlovehf** [comment]
高版本 python下载会不会出现SSL的问题
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)>

**Comment by andysendo** [comment]
支持放弃python2 debian10 stable软件就够老的 也有python3.x

**Comment by andysendo** [comment]
windows 装个python3更不是问题

**Comment by andysendo** [comment]
xp/7还是有很多人用的

**Comment by wnpllrzodiac** [comment]
18.04 起点有点高啊。我还在用 16.04呢。
上次尴尬的发现 lAdder没有x86的预编译版本了。尴尬。xp真的没法玩了。

**Comment by tian-le** [comment]
希望还是能尽量提升代码的兼容性的 毕竟在很多场合我们不得不用比较老的版本的python 比如我在Kodi里使用ykdl 很多时候 是能提升兼容性的

**Comment by SeaHOH** [comment]
> 希望还是能尽量提升代码的兼容性的 毕竟在很多场合我们不得不用比较老的版本的python 比如我在Kodi里使用ykdl 很多时候 是能提升兼容性的

Kodi 的话，有现成的扩展可用，整体生态好像还不错，而且是支持 Python 3 的。关键 ykdl 并不是设计为 Kodi 扩展，不太懂你是怎么使用的。
