### ISSUE TITLE
v.douyu.com is not working anymore

### ISSUE THREAD

**Issue by Erk-** [zhangn1985/ykdl#49]
It is getting a 403 error.

**Comment by zhangn1985** [comment]
could you show me the link, and log?

**Comment by zhangn1985** [comment]
and i tested 2 links, both ok.
maybe you are use not in china mainland.

**Comment by Erk-** [comment]
Did some more testing it looks like it works on most on the main page but it does not work for this [https://v.douyu.com/show/jworZv0e3mZ7JBk3](https://v.douyu.com/show/jworZv0e3mZ7JBk3) it gives a 403 error.

**Comment by zhangn1985** [comment]
no 403 for me. can't debug.

**Comment by zhangn1985** [comment]
I use iphone UA to get the algorithm, and narrow down the headers by using curl, and finally find only need the header:
        add_header('X-Requested-With', 'XMLHttpRequest')

so if you could find 403 on lots of the pages, you can easily debug it.

I tried to proxy to US, and still notget 403.

**Comment by zhangn1985** [comment]
??? reproducible???

**Comment by GGshawn** [comment]
I got 403 too.
