### ISSUE TITLE
请支持 dililitv 视频下载

### ISSUE THREAD

**Issue by atbest** [zhangn1985/ykdl#490]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

网址为 `http://www.dililitv.com`，谢谢！

**Comment by SeaHOH** [comment]
#361 这个已经挂了，同理，我也不再支持加入这种侵权内容。说不定哪天就没了，白费功夫，还容易惹腥臊。
