### ISSUE TITLE
文件名包含非法字符，无法下载

### ISSUE THREAD

**Issue by SeaHOH** [zhangn1985/ykdl#496]
@SeaHOH 

ROOMID:   7020364
报错
kinako鏌効    鐨勭洿鎾棿 - kinako鏌効_BD4M_2020-03-13T00-16-51.395533.flv: Invalid argument

_Originally posted by @xiatiantiantian in https://github.com/zhangn1985/ykdl/issues/417#issuecomment-598288931_

**Comment by SeaHOH** [comment]
感谢反馈！不过，像这种不太相关的 bug 能单独提 issue 就更好了。

**Comment by airdge** [comment]
GBK转utf8

**Comment by SeaHOH** [comment]
Windows 测试通过，使用其它系统的请帮忙也测试一下。

这次触发 bug 的是 `tab (\t/\x09)`，现已将 `\x00-\x31` 全部过滤处理，顺便修复了对超长文件名的裁剪处理。

**Comment by xiatiantiantian** [comment]
> Windows 测试通过，使用其它系统的请帮忙也测试一下。
> 
> 这次触发 bug 的是 `tab (\t/\x09)`，现已将 `\x00-\x31` 全部过滤处理，顺便修复了对超长文件名的裁剪处理。

更新后所有的都报错了。


> Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32


濂戒箙涓嶈 闈炲父鎯冲康  - 涓嬪嚒娓″姭鐨勯樋鏈坃TD_2020-03-13T18:00:30.036539.flv: Invalid argument

**Comment by SeaHOH** [comment]
不好意思，第二个修复忘记测试了，现在好了。

**Comment by xiatiantiantian** [comment]
> 不好意思，第二个修复忘记测试了，现在好了。

发现使用Windows Powershell  这里始终显示乱码。

Output #0, flv, to 'kinako鏌効 鐨勭洿鎾棿 - kinako鏌効_BD_2020-03-13T21锛?2锛?3.074040.flv':  Metadata:

**Comment by SeaHOH** [comment]
> 发现使用Windows Powershell 这里始终显示乱码。

这个是 FFmpeg 的输出，除非给它重定向，再编码输出。但是没有必要，不要去干别人的工作，而且除打印错误外并无不良影响。

**Comment by xiatiantiantian** [comment]
> > 发现使用Windows Powershell 这里始终显示乱码。
> 
> 这个是 FFmpeg 的输出，除非给它重定向，再编码输出。但是没有必要，不要去干别人的工作，而且除打印错误外并无不良影响。

好的，谢谢。
