### ISSUE TITLE
直播时视频源更新，ykdl 无法自动切换

### ISSUE THREAD

**Issue by SeaHOH** [zhangn1985/ykdl#497]
douyu.com/g_yz    （随便选一个手机播的，2人正在PK的，竖屏的都是手机播的）

只要是用手机播的，2人PK的话，只能下载到一个人的画面。（电脑播的没有这个问题）

遇到2人PK，它会刷新一个新的视频源（2人PK的画面），原始源降码率且一直有效（但是一直是一个人画面）。 PK结束后这个视频源自动失效。

_Originally posted by @xiatiantiantian in https://github.com/zhangn1985/ykdl/issues/417#issuecomment-598873941_

**Comment by SeaHOH** [comment]
不相干的问题，请另开 issue，谢谢合作！

**Comment by SeaHOH** [comment]
先说说浏览器为什么能自动切换，因为它和服务器之间保持通讯（一般是使用 WebSocket），服务器会在视频源更新时通知浏览器，然后浏览器执行切换操作。

如果 ykdl 也要这么做也行，但是实现上可能会有困难，开发也颇麻烦，因为必须等它切换时才能观察到通讯数据格式。有兴趣的小伙伴可以尝试实现它。

**Comment by airdge** [comment]
这个得setInterval轮询刷新api获取地址

传递一个extra.reloadUrl, FFMPEG下载过程成,轮询刷新reloadUrl
如果有新视频源,调用FFMPEG

方法也能用在QQ视频下载,每次下载3个分段后,解析新数据后再继续下载

**Comment by SeaHOH** [comment]
没有多少使用轮询这种办法的站点吧，都是使用 WebSocket 实时更新数据。分个线程监视通讯 API，根据消息内容判断重载。我觉得麻烦的地方在于抓取数据和调试。

关于腾讯视频，我自己早就是下载前才解析，不过如果要完全兼容之前的输出（我自用的就只考虑 launch_player），会在短时间内产生大量重复请求，而且不是对每个受限视频都有效（估计再以后这么做也没用了），尤其是现在的三分钟限制根本没办法。

**Comment by airdge** [comment]
python总得监听斗鱼api才能获取新数据

腾讯视频,我自己用的就是3个分段重新解析一次,大部分测试都是正常的
一次性下载到第四个第五个分段(高清以上) 基本会限速
网页用的上报方法比较麻烦,还不如直接再次解析来的快

还有ykdl使用的getkey是循环获取分段vkey
可以添加参数 idx=1|2|.....|10 (11|12|..|20) (20|21|...)一次性获取10个vkey来避免短期内大量请求

```
import time
import urllib.parse 
import requests

def get(url):
	c=requests.get(url)
	return  c.text 
 
vid='h0681q2fdgv'
platform = "10201"
sdtfrom = "v1010"
appver="3.4.31"
fmt='10709'
guid='1234563763bd61cdb47ed71077224db2'
tm=int(time.time()) 
# 单次
idx='1' 
params = {
                "otype": "ojson",
                "vid": vid,
                "format": fmt,
                "idx": idx,
                "vt": "116",
                "sdtfrom": sdtfrom,
                "platform": platform,
                "guid": guid, 
                "charge": "0",
                "linkver": "2",
                "lnk": vid,
                "tm": tm,
                "referer": "https://v.qq.com/x/page/h0681q2fdgv.html",
                "ehost": "https://v.qq.com/x/page/h0681q2fdgv.html",
                "appVer": "3.4.31",
                "host": "v.qq.com",
                "sphttps": "1", 
            }
 
url_one='http://vv.video.qq.com/getkey?%s'%(urllib.parse.urlencode(params))
print(get(url_one))

idx_all= '1|2|3'
params['idx']=idx_all
url_all='http://vv.video.qq.com/getkey?%s'%(urllib.parse.urlencode(params))
print(get(url_all))
```
```

{"ct":21600,"ip":"120.40.170.192","keyid":"h0681q2fdgv.10709","s":"o","vl":{"vi":[{"cl":{"ci":[{"idx":1,"key":"4BF28C42B6E68988FAC5F64F3940ADEF56C7B877A2312841583C06485585AE3D2B098FA025D4A7A8DB4701306AC1E54A3CF31A5850B111DFA5086E5E31F69A5827A35EA0C748A8B8C1D7026B0C3A86B08F94E7F4169EF52B13C011DE5CA26AA526D41BFA27529EE1A4C32417EC977CE13071FEF15D7FCEC9D1F61BED4AD26EDF","keyid":"h0681q2fdgv.10709.1"}]},"filename":"h0681q2fdgv.p709.mp4","format":10709,"vid":"h0681q2fdgv"}]}}


{"ct":21600,"ip":"120.40.170.192","keyid":"h0681q2fdgv.10709","s":"o","vl":{"vi":[{"cl":{"ci":[{"idx":1,"key":"DB5412CACD980470047B22A36EFB32CCB941A0E880FB3AE74345036FE062CBCFAAB808F0F47A9DF42716DDD2C0E9AA2CEC393118CE590C0F9B4F4731B58996A9DB9C64707B935EE386D745E12D4048BFB50EBFE51E1B7C48A75F02CAF1278BF44297D8DF65E8DB54C347FA5A188CC3392ECD42750AA01B9E2AF0C85D5BCAB478","keyid":"h0681q2fdgv.10709.1"},{"idx":2,"key":"03723237BD4B94335E9C9AFBFCFC63058161CE3910B4CF73A343176661473586C3F28B26ED13114B04B51C3231B72DBCFDAF2B0BA04EC89ECD42673D78E96DE8DF41604FC32755B2D4792D7624130EF46237AB36DA924D90D371D16F0294B7FD6FA80C14E9CEB8F9450DA83151E65ED382A156A392452C60547A2EFDE5358DEC","keyid":"h0681q2fdgv.10709.2"},{"idx":3,"key":"068F609AACD6813AC73A308625D8CB62BEBE6144EFD1F9EFD0E70BEF956C8791FD18017F71581696760C9412250ADCBC94216FAA19F1582D78FA83DF5058A2EF39C2F15E3041B1E39C9BA845D3C9D3BC3BC4366E25B4BA5B000C9CE0C682A0694578B6EBE86C7B679C4B62D797186F40CAA0CF350F51C53EABE85B1EC48BF3DE","keyid":"h0681q2fdgv.10709.3"}]},"filename":"h0681q2fdgv.p709.mp4","format":10709,"vid":"h0681q2fdgv"}]}}
```
或者也可以下载三个分段后,再去请求下一轮3个分段的vkey,替换streams.urls的vkey参数后下载

**Comment by SeaHOH** [comment]
腾讯视频使用 `idx` 参数可以能简化代码，这个不错。 :+1:

有没有办法准确地判断视频是否被限制？不然调用播放器时没办法根据这个来选择，是逐一解析多次调用，还是一次性解析单次调用。

上面说的下载前解析就是指每个独立分段，传递 function （闭包保持参数状态）代替 string 作为 url 的值。但是要保证完全兼容的输出还需要仔细处理，等空了我慢慢改。就是不知道这方法还能用多久，要是有哪位大佬能解析整理出一个简单清晰的上报流程就好了，不要有严重依赖那种。。。

突然发现，楼歪了，这个和直播自动换源关系不大，不用另起线程操作。不过也无所谓了，添加这个功能的机率实在不大，这个 issue 算是备注吧。当然，如果有人愿意去实现它，还是很欢迎的。

**Comment by xiatiantiantian** [comment]
> 现在斗鱼已经没有这种问题了。

这个手机播的，只要是2人连麦，都是只有一个人的画面  （目前2020-6-13 问题依旧存在）

**Comment by SeaHOH** [comment]
嗯，问题仍然存在，我以为你最开始说的是有手机直播参与 PK 就会出现问题。

捋了捋应该是这样的。PK 时会合成新的左右布局视频流，由于 PC 直播的尺寸比例与之相同，可以直接切换画面而不换流；反之，手机直播的尺寸比例与之不同，就只能换流，PK 完再换回来。我起的标题不太符合此问题，视频流并没有更新，它一直在那儿。

完整录制无需断开原始的流，可单独录制 PK 流。直接录不是不可能，但由于分辨率不同需要重编码，没这个必要。如果斗鱼可以再给手机直播匹配个上下布局的 PK 流就没这些麻烦了，当然这很不节能，也没必要，录这玩意儿来干嘛？

虽然这是个技术问题，但由于没有实质上使用问题（大概），我决定就此结束。

**Comment by xiatiantiantian** [comment]
> 嗯，问题仍然存在，我以为你最开始说的是有手机直播参与 PK 就会出现问题。
> 
> 捋了捋应该是这样的。PK 时会合成新的左右布局视频流，由于 PC 直播的尺寸比例与之相同，可以直接切换画面而不换流；反之，手机直播的尺寸比例与之不同，就只能换流，PK 完再换回来。我起的标题不太符合此问题，视频流并没有更新，它一直在那儿。
> 
> 完整录制无需断开原始的流，可单独录制 PK 流。直接录不是不可能，但由于分辨率不同需要重编码，没这个必要。如果斗鱼可以再给手机直播匹配个上下布局的 PK 流就没这些麻烦了，当然这很不节能，也没必要，录这玩意儿来干嘛？
> 
> 虽然这是个技术问题，但由于没有实质上使用问题（大概），我决定就此结束。


![image](https://user-images.githubusercontent.com/51699978/84588322-03f60a80-ae59-11ea-90b7-0e367778fcf2.png)



听君一席话，突然恍然大悟。
只需要单独开一个YKDL刷新API检测is_mixed值，获取地址然后下载。

is_mixed=True   （刷新API检测is_mixed）
mixed_live=11111vs22222.flv?   （获取地址下载 ） 云端合成PK视频的地址
rtmp_live=              （源视频流）

--------
其实不管手机还是电脑，只要PK都会再刷新一个PK的视频流（云端自动合成的），源视频流是一直有效的。
PC端可以在源视频流出现2人，是因为PK的时候会直接拉取PK对手的视频流添加到本地OBS的界面推流。
就算是PC端（PK画面）mixed_live和rtmp_live有时候都是不一样的，mixed_live是云端自动等比例合成，rtmp_live是主播本地OBS可编辑。


手机端不可以应该是性能不行，太多手机型号（大家直播的设备性能不一）。

**Comment by SeaHOH** [comment]
Mixed 状态是可以返回到各个 API 中，但是切换动作肯定是根据 WS 通讯监视来实施的，轮询这种古董技术大家早就不用了。明白怎么回事就行，没必要去实现，投资回报不成正比。

另，虽然没用过，我猜测不是本地 OBS 拉取合成的，手机直播单纯是因为不愿意搞上下布局。

**Comment by xiatiantiantian** [comment]
> Mixed 状态是可以返回到各个 API 中，但是切换动作肯定是根据 WS 通讯监视来实施的，轮询这种古董技术大家早就不用了。明白怎么回事就行，没必要去实现，投资回报不成正比。
> 
> 另，虽然没用过，我猜测不是本地 OBS 拉取合成的，手机直播单纯是因为不愿意搞上下布局。

PC端DY直播软件是 直接拉取PK对方的视频流到自己界面（实时推流），我去PK试过可以编辑对方画面拉大缩小，到处移动对方的画面，然后我这边观众看见的也是我自己看见的推流界面。

**Comment by SeaHOH** [comment]
逻辑不对啊，本地推流能编辑很正常，但是 PK 时的直播流应该由平台合成才公平，你的推流最终也只占直播流的一半。不然大家想怎么搞就搞，可以发生很多奇妙的事情。当然，不使用官方平台 PK 功能就可以顺便搞。

如果实际情况是你描述的这种，那么我估计原因可能是为了节省计算开销，全部工作都由 OBS 包圆，平台方面只负责中转完全不用担心计算资源不足。这可能就是为什么有的直播只提供一个分辨率，自己使用的机器不给力啊。
