### ISSUE TITLE
iqiyi encode

### ISSUE THREAD

**Issue by goodneo** [zhangn1985/ykdl#5]
我套用了不同的ffmpeg都出現這問題 不知道有沒有辦法解決
ffmpeg-20160629-57d30fd-win64-static.zip
ffmpeg-2.8.6-win32-static.7z
ffmpeg-2.8.6-win64-static.7z

[mp4 @ 06c7fb00] Non-monotonous DTS in output stream 0:0; previous: 32464160, cu
rrent: 27900000; changing to 32464161. This may result in incorrect timestamps i
n the output file.
[mp4 @ 06c7fb00] Non-monotonous DTS in output stream 0:0; previous: 32464161, cu
rrent: 27903600; changing to 32464162. This may result in incorrect timestamps i
n the output file.
[mp4 @ 06c7fb00] Non-monotonous DTS in output stream 0:0; previous: 32464162, cu
rrent: 27907200; changing to 32464163. This may result in incorrect timestamps i
n the output file.
[mp4 @ 06c7fb00] pts has no value
[NULL @ 02f70180] Error parsing ADTS frame header!
Failed to open bitstream filter aac_adtstoasc for stream 0 with codec copy: Inva
lid data found when processing input
[mp4 @ 06c7fb00] Non-monotonous DTS in output stream 0:1; previous: 15918749, cu
rrent: 13677108; changing to 15918750. This may result in incorrect timestamps i
n the output file.
[mp4 @ 06c7fb00] aac bitstream error
frame=34755 fps=315 q=-1.0 Lsize=  251800kB time=00:06:01.01 bitrate=5713.7kbits
/s
video:240434kB audio:10791kB subtitle:0kB other streams:0kB global headers:0kB m
uxing overhead: 0.229120%

**Comment by zhangn1985** [comment]
这个我也遇到过

**Comment by zhangn1985** [comment]
解析m3u8，并且单独下载分片，然后合并，只能得到错误的视频。

网上的分析是说视频源就是坏的。

**Comment by zhangn1985** [comment]
http://ffmpeg.org/pipermail/ffmpeg-user/2013-May/015184.html

**Comment by zhangn1985** [comment]
直接播放，到6分钟时也会挂掉。

**Comment by goodneo** [comment]
載了幾次都是出現錯誤斷掉 幾乎都是6分鐘壞掉的影片
不知道有無辦法解決這問題
看起來m3u8好像不可行..

**Comment by zhangn1985** [comment]
VIP视频是坏的，可能需要登陆才能下载。

所以暂时去掉了vip 视频。

**Comment by goodneo** [comment]
H264編碼也是如此嗎?

**Comment by zhangn1985** [comment]
我稍后试一下，如果是这样，我就push 提交了。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/b925ca281b30f8ef5fd4a3fbaa02fb770ac9a8b3

**Comment by goodneo** [comment]
所以H264 720p 1080還是無解..... 感謝

**Comment by zhangn1985** [comment]
当1080p的视频是放在vip区域就不行了。

如果iqiyi为普通用户提供了1080p，那么1080p还是有效的。

**Comment by goodneo** [comment]
@zhangn1985 想請問一下 為何修改後 我使用python -m ykdl 反而無法執行了
還是改了使用方式?

**Comment by zhangn1985** [comment]
自带bin/ykdl， 我把ykdl这个模块改成了纯lib，不具有可执行。

你可以`python bin/ykdl`

**Comment by zhangn1985** [comment]
最新的已经修复了。可能晚上我会再更新wiki，你照着做就没问题了。

**Comment by goodneo** [comment]
昨天試了一下 好像720p只要載了H265的就會卡在Non-monotonous DTS
H264的卻正常
所以才疑問了一下1080 是卡在VIP 還是H265的問題
想問看看而已

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/e365860eb48824ad59c331f7d7a127ca3cbe981e

**Comment by goodneo** [comment]
這影片用目前的腳本
抓不到264 profile的樣子
http://www.iqiyi.com/v_19rrmad2yk.html

**Comment by zhangn1985** [comment]
这个视频是VIP专享，所以并不能下载这种视频。
