### ISSUE TITLE
能否添加以下这种形式的CNTV网址的支持

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#516]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i http://ncpa-classic.cntv.cn/2020/06/13/VIDEsTFtFcX7R2qKO6AwIZ6t200613.shtml
CRITICAL:YKDL:cant find vid
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by mengmo** [comment]
我也试着比葫芦画瓢自己改，但毕竟不太熟悉，结果被制表符给坑得不轻。
我改出来的是这样的
```
self.vid = match1(content, 'guid = "([^"]+)', '"videoCenterId","([^"]+)', "initMyAray=\s'([^']+)")
```

**Comment by SeaHOH** [comment]
正则匹配规则还是比较简洁明确的，估计你只是没有完整阅读过，再看一次就好了。

推荐个工具做练习 http://www.regexlab.com/mtracer/
