### ISSUE TITLE
iqiyi视频全都不能下载和mpv播放

### ISSUE THREAD

**Issue by andysendo** [zhangn1985/ykdl#523]
以前iqiyi没问题，最近突然都不能直接播放和下载了。mpv播放提示"tcp拒绝连接"，下载只提示"下载失败"。网页在线播放是可以的。

**Comment by mengmo** [comment]
请给出具体细节以便于复现问题

我这儿是没发现有这个问题

**Comment by SeaHOH** [comment]
https://github.com/zhangn1985/ykdl/blob/4040fb11ec329cd2b3690a5ba6c2b6446e99891f/ykdl/extractors/iqiyi/video.py#L202-L205
tmts 分配的 CDN 可能有什么变化，在 205 行前面插一行 `raise`，这样就可以跳过它使用其它 API。
因为不确定具体原因和影响范围，请先自行修改。

**Comment by andysendo** [comment]
加了raise播放和下载都可以了

**Comment by inoton** [comment]
> 以前iqiyi没问题，最近突然都不能直接播放和下载了。mpv播放提示"tcp拒绝连接"，下载只提示"下载失败"。网页在线播放是可以的。

能否粘贴一行使用mpv播放的网页视频的示例给我参考 一下，谢谢

**Comment by inoton** [comment]
> 加了raise播放和下载都可以了
能否粘贴一行使用mpv播放的网页视频的示例给我参考 一下？谢谢。
我是这么用的，不知道错在哪里了：
ykdl -p mpv  https://www.iqiyi.com/v_19ru53qb00.html

**Comment by inoton** [comment]
> 加了raise播放和下载都可以了

能否粘贴一行使用mpv播放的网页视频的示例给我参考 一下？谢谢。
我是这么用的，不知道错在哪里了：
ykdl -p mpv https://www.iqiyi.com/v_19ru53qb00.html

site: 爱奇艺 (Iqiyi)
title: 酷狗音乐党支部《我和我的祖国》
artist: None
streams:
- format: BD
container: flv
video-profile: 1080p
# download-with: ykdl --format=BD [URL]

_Error parsing commandline option demuxer-lavf-o: option requires parameter_

Exiting... (Fatal error)

**Comment by inoton** [comment]
> 加了raise播放和下载都可以了

能否粘贴一行使用mpv播放的网页视频的示例给我参考 一下？谢谢。
我是这么用的，不知道错在哪里了：
ykdl -p mpv https://www.iqiyi.com/v_19ru53qb00.html

site: 爱奇艺 (Iqiyi)
title: 酷狗音乐党支部《我和我的祖国》
artist: None
streams:
- format: BD
container: flv
video-profile: 1080p
# download-with: ykdl --format=BD [URL]

**Error parsing commandline option demuxer-lavf-o: option requires parameter**

Exiting... (Fatal error)

**Comment by inoton** [comment]
> 加了raise播放和下载都可以了

能否粘贴一行使用mpv播放的网页视频的示例给我参考 一下？谢谢。

我是这么用的，不知道错在哪里：
$ ykdl -p mpv  https://www.iqiyi.com/v_19ru53qb00.html
site:                爱奇艺 (Iqiyi)
title:               酷狗音乐党支部《我和我的祖国》
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Error parsing commandline option demuxer-lavf-o: option requires parameter

Exiting... (Fatal error)
