### ISSUE TITLE
可以下载 ，但无法调用mpv播放

### ISSUE THREAD

**Issue by inoton** [zhangn1985/ykdl#524]
$ ykdl -p mpv  https://www.iqiyi.com/v_19ru53qb00.html
site:                爱奇艺 (Iqiyi)
title:               酷狗音乐党支部《我和我的祖国》
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
**Error parsing commandline option demuxer-lavf-o: option requires parameter**

Exiting... (Fatal error)

**Comment by SeaHOH** [comment]
升级没有？不会就看 readme 的 install from source 部分。

**Comment by inoton** [comment]
> 升级没有？不会就看 readme 的 install from source 部分。

解决了，十分感谢！
当时是按 “简要安装指南” 部分来安装的。

运行一下：pip3 install git+git://github.com/zhangn1985/ykdl.git --upgrade --user  就好了。

**Comment by inoton** [comment]
> 升级没有？不会就看 readme 的 install from source 部分。

解决了，十分感谢！
当时是按 “简要安装指南” 部分来安装的。

按您的提示，再运行一下：pip3 install git+git://github.com/zhangn1985/ykdl.git --upgrade --user 就好了。
