### ISSUE TITLE
虎牙视屏报错KeyError: 1440 或 KeyError: 450

### ISSUE THREAD

**Issue by adamslin** [zhangn1985/ykdl#536]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
系统为macOS 11
地址在海外
▶ ykdl https://v.huya.com/play/413313517.html
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/cykdl/__main__.py", line 193, in main
    info = parser(u)
  File "/usr/local/lib/python3.8/site-packages/ykdl/extractor.py", line 23, in parser
    info = self.prepare()
  File "/usr/local/lib/python3.8/site-packages/ykdl/extractors/huya/video.py", line 63, in prepare
    stream = self.quality_2_id[quality]
KeyError: 1440


▶ ykdl https://v.huya.com/play/420246225.html
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/cykdl/__main__.py", line 193, in main
    info = parser(u)
  File "/usr/local/lib/python3.8/site-packages/ykdl/extractor.py", line 23, in parser
    info = self.prepare()
  File "/usr/local/lib/python3.8/site-packages/ykdl/extractors/huya/video.py", line 63, in prepare
    stream = self.quality_2_id[quality]
KeyError: 450
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
测试了几十个视频都没有**高清**画质，暂时忽略，以后遇到再修改。

**Comment by adamslin** [comment]
您好，请问是因为源视频（https://v.huya.com/play/413313517.html）没有高清画质所以下不了吗。该视频虽然只有原画和超清画质，但是我试过我下该网站别的只有原画和超清画质视频，是可以下的。

**Comment by SeaHOH** [comment]
已经修复，但是如果有**高清**画质会解析失败。

**Comment by adamslin** [comment]
您好，感谢您的回复与修复。我安装时使用pip3，可是当我利用pip3 （pip3 install ykdl --upgrade --user 和 ip3 install https://github.com/zhangn1985/ykdl/archive/master.zip 都试过） 更新时，报错：
  ERROR: Failed building wheel for pycryptodome
  Running setup.py clean for pycryptodome
Failed to build pycryptodome
Installing collected packages: urllib3, pycryptodome, ykdl
    Running setup.py install for pycryptodome ... error

在 反馈该问题之前，使用pip3更新，没有报错。
请问是更新的方法不对还是需要重新安装，谢谢！

**Comment by adamslin** [comment]
您好，在本地文件中更新 ykdl/extractors/huya/video.py后，可以正常下载该视频（https://v.huya.com/play/413313517.html）。 但是使用pip3更新，仍无法成功。

**Comment by adamslin** [comment]
1. 您好，在本地文件中更新 ykdl/extractors/huya/video.py后，可以正常下载该视频（https://v.huya.com/play/413313517.html）。 
但是会出现部分part下载不全的情况， 如：
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 472
 100%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 473
  34%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 474
  60%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 475
  68%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 476
 100%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 477
  31%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 478
 100%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 479
  42%
Download: 宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD part 480

2. 使用pip3更新，仍会报错。但这不影响正常使用。
再次感谢您！

**Comment by adamslin** [comment]
该视频下载完成后，报错如下：
 100%ERROR:downloader:downloader failed at part 2177
ERROR:downloader:downloader failed at part 4001
CRITICAL:YKDL:宇宙第一鱼人峡谷乱杀 - 聆听丶芒果鱼_BD> donwload failed
且parts未合并，请问可以手动合并分parts吗，能确定视频所有parts已经下载完成。
谢谢！

**Comment by SeaHOH** [comment]
更新不要直接使用 ykdl，PyPI 并未更新。
```command
$ pip3 install git+https://github.com/zhangn1985/ykdl.git --upgrade --user
```

下载不完整时是不会合并的，可以重复运行相同命令直到下载完整。
自带的下载功能非常简陋，parts 数量太大时，可能会出现一直无法完整下载的情况，使用专门的 m3u8 下载工具进行下载更方便。
