### ISSUE TITLE
ykdl is broken due to Python upgraded to 3.9 in Arch Linux

### ISSUE THREAD

**Issue by whriedplanck** [zhangn1985/ykdl#537]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
Traceback (most recent call last):
  File "/usr/bin/ykdl", line 33, in <module>
    sys.exit(load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')())
  File "/usr/bin/ykdl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ykdl
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 以下是软件包信息：
名字           : ykdl-git
版本           : 1.6.3.r184.08923e6-1
描述           : a video downloader focus on China mainland video sites.
架构           : any
URL            : https://github.com/zhangn1985/ykdl
软件许可       : MIT
组             : 无
提供           : ykdl
依赖于         : python-setuptools  python-m3u8  python-pycryptodome  python-urllib3
                 python-iso8601
可选依赖       : nodejs: JavaScript runtime for DouyuTV [已安装]
                 gjs: JavaScript runtime for DouyuTV
                 cjs: JavaScript runtime for DouyuTV
依赖它         : 无
被可选依赖     : 无
与它冲突       : ykdl
取代           : 无
安装后大小     : 979.85 KiB
打包者         : lilac (on behalf of Bruce Zhang) <zttt183525594@gmail.com>
编译日期       : 2020年11月29日 星期日 17时55分30秒
安装日期       : 2020年11月30日 星期一 14时40分52秒
安装原因       : 作为其他软件包的依赖关系安装
安装脚本       : 否
验证者         : 数字签名

**Comment by SeaHOH** [comment]
Try install via pip.

**Comment by wordlesswind** [comment]
@BruceZhang1993

**Comment by whriedplanck** [comment]
> @BruceZhang1993

Thanks! Sorry for bothering ......

**Comment by whriedplanck** [comment]
This issue has been fixed after the package's maintainer repacking it. Close issue.
