### ISSUE TITLE
ykdl 下载iqiyi视频长度不完全

### ISSUE THREAD

**Issue by lowprofileusername** [zhangn1985/ykdl#538]
在提交前，请确保您已经检查了以下内容!

- [X ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ X] 您的`ykdl`为最新版。
- [X ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [X ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ X] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
https://www.iqiyi.com/v_19rr9hx7n8.html
最后时常才00:22:09.41 ，这个视频总时长应该为00:26:30
[在这里粘贴完整日志]
root@ubuntu:/home/leo/sid# /root/.local/bin/ykdl https://www.iqiyi.com/v_19rr9hx7n8.html
site:                爱奇艺 (Iqiyi)
title:               That&#39;s the Way the Ball Bounces
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Download: That&#39;s the Way the Ball Bounces_BD part 0
Download: That&#39;s the Way the Ball Bounces_BD part 1
Download: That&#39;s the Way the Ball Bounces_BD part 2
Download: That&#39;s the Way the Ball Bounces_BD part 3
Download: That&#39;s the Way the Ball Bounces_BD part 4
Download: That&#39;s the Way the Ball Bounces_BD part 5
Download: That&#39;s the Way the Ball Bounces_BD part 6
Download: That&#39;s the Way the Ball Bounces_BD part 7
 100%Merging video That&#39;s the Way the Ball Bounces_BD using ffmpeg:
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from '/home/leo/sid/tmp1xz2rwpc.txt':
  Duration: N/A, start: 0.000000, bitrate: 2018 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709), 1920x1080, 1828 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp, 190 kb/s
[flv @ 0x2624240] Codec for stream 0 does not use global headers but container format requires global headers
[flv @ 0x2624240] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, flv, to 'That&#39;s the Way the Ball Bounces_BD.flv':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p, 1920x1080, q=2-31, 1828 kb/s, 25 fps, 25 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac ([10][0][0][0] / 0x000A), 44100 Hz, stereo, 190 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY7.4kbits/s    
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY60.0kbits/s    
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY44.3kbits/s    
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY64.7kbits/s    
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY70.4kbits/s    
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x2560d80] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY38.4kbits/s    
[flv @ 0x2560d80] Auto-inserting h264_mp4toannexb bitstream filter
[NULL @ 0x266d5c0] AVC: nal size 58122125kB time=00:20:36.55 bitrate=2770.0kbits/s    
[NULL @ 0x266d5c0] missing picture in access unit with size 7693
/home/leo/sid/tmp1xz2rwpc.txt: Invalid argument
frame=33227 fps=7793 q=-1.0 Lsize=  438032kB time=00:22:09.41 bitrate=2699.2kbits/s    
video:405612kB audio:30820kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.366597%

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

同一个视频每次下载随机少时间，有的时候就正常。可能是某个部分没下载完?

**Comment by SeaHOH** [comment]
你这个问题比较奇怪，未下载完整是不会进行合并的，建议你试试更新 FFmpeg。

**Comment by lowprofileusername** [comment]
> 你这个问题比较奇怪，未下载完整是不会进行合并的，建议你试试更新 FFmpeg。

[sudo] password for leo: 
root@debian:/home/leo# /root/.local/bin/ykdl https://www.iqiyi.com/v_19rr9hxa2g.html
site:                爱奇艺 (Iqiyi)
title:               Reused Robot
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Download: Reused Robot_BD part 0
 100%Download: Reused Robot_BD part 1
  11%Download: Reused Robot_BD part 2
 100%Download: Reused Robot_BD part 3
 100%Download: Reused Robot_BD part 4
 100%Download: Reused Robot_BD part 5
 100%Download: Reused Robot_BD part 6
 100%Download: Reused Robot_BD part 7
 100%Merging video Reused Robot_BD using ffmpeg:
[flv @ 0x561f41e90440] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
[flv @ 0x561f41e90440] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from '/home/leo/tmpr4q8rxpn.txt':
  Duration: N/A, start: 0.000000, bitrate: 1815 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, 1625 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp, 190 kb/s
Output #0, flv, to 'Reused Robot_BD.flv':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 1625 kb/s, 25 fps, 25 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 190 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[flv @ 0x561f41e913c0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
[flv @ 0x561f41e913c0] Auto-inserting h264_mp4toannexb bitstream filter
[NULL @ 0x561f41e928c0] Invalid NAL unit size (111780 > 92057).
[NULL @ 0x561f41e928c0] missing picture in access unit with size 92061
[concat @ 0x561f41e85900] h264_mp4toannexb filter failed to receive output packet
/home/leo/tmpr4q8rxpn.txt: Invalid argument
frame= 6146 fps=0.0 q=-1.0 Lsize=   51871kB time=00:04:05.80 bitrate=1728.7kbits/s speed= 702x    
video:45901kB audio:5674kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.574376%
我换了一台电脑也出现这个情况。。 这次这个才4分钟。
ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers
应该不是FFMPEG的问题把。

**Comment by SeaHOH** [comment]
这是合并了不完整的下载，我没法重复，代码也看不出问题。请确定你使用的代码和当前主分支一致。

**Comment by SeaHOH** [comment]
试一试 d1a6e53b04240457350e5e61b6a8493edc9bf84b ，可能会对你的问题有帮助。
