### ISSUE TITLE
能支持芒果TV的藍光嗎?

### ISSUE THREAD

**Issue by Hugo-Hui** [zhangn1985/ykdl#54]
芒果tv有藍光選項了

**Comment by zhangn1985** [comment]
蓝光为VIP专享，所以没有VIP的我，没法了。
或者你可以帮忙实现一下。

**Comment by zhangn1985** [comment]
部分的支持了一下。
https://github.com/zhangn1985/ykdl/commit/f8251276be09c69d7cbcc33253a9925e15660581

**Comment by zhangn1985** [comment]
#44 目前暂时没法支持VIP视频
