### ISSUE TITLE
斗鱼视频（不是直播）可以支持原画吗？

### ISSUE THREAD

**Issue by speaknowpotato** [zhangn1985/ykdl#548]
douyu video现在只有两种画质，high和normal，
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/douyu/video.py#L18
可否支持原画画质？
谢谢！

**Comment by wordlesswind** [comment]
> douyu video现在只有两种画质，high和normal，
> https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/douyu/video.py#L18
> 可否支持原画画质？
> 谢谢！

页面上写原画需要登录，ykdl 似乎不支持 cookie。

**Comment by speaknowpotato** [comment]
网页上的确显示需要登录才能原画，谢谢解答！　另外想问下这个cookie以后会支持吗？

**Comment by SeaHOH** [comment]
> 网页上的确显示需要登录才能原画，谢谢解答！　另外想问下这个cookie以后会支持吗？

支持 cookies 处理，但是不会支持直接导入。

**Comment by wordlesswind** [comment]
> 网页上的确显示需要登录才能原画，谢谢解答！　另外想问下这个cookie以后会支持吗？

https://github.com/zhangn1985/ykdl/issues/548#issuecomment-766347283

所以你自己改吧，也不难

https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/douyu/video.py#L38

配合 [EditThisCookie](https://chrome.google.com/webstore/detail/fngmhnnpilhplaeedifhccceomclgfbg)，然后在设置里改一下导出格式就行。

**Comment by speaknowpotato** [comment]
按照你说的方法，我通过EditThisCookie拿到了dy_did的值，一共32位，
然后我把这个值替换到
did = uuid.uuid4().hex
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/douyu/util.py#L96

但是依然无法拿到原画，请问哪里操作错误了吗？

**Comment by airdge** [comment]
> 按照你说的方法，我通过EditThisCookie拿到了dy_did的值，一共32位，
> 然后我把这个值替换到
> did = uuid.uuid4().hex
> https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/douyu/util.py#L96
> 
> 另外我也把这个commit加到我本地代码了，
> [wordlesswind@7d43743](https://github.com/wordlesswind/ykdl/commit/7d43743ff2b62dde3ceea7dd43d83fcc015f93c9)
> 
> 但是依然无法拿到原画，请问哪里操作错误了吗？

要cookie.acf_auth才能获取登陆信息

**Comment by speaknowpotato** [comment]
> > 按照你说的方法，我通过EditThisCookie拿到了dy_did的值，一共32位，
> > 然后我把这个值替换到
> > did = uuid.uuid4().hex
> > https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/douyu/util.py#L96
> > 另外我也把这个commit加到我本地代码了，
> > [wordlesswind@7d43743](https://github.com/wordlesswind/ykdl/commit/7d43743ff2b62dde3ceea7dd43d83fcc015f93c9)
> > 但是依然无法拿到原画，请问哪里操作错误了吗？
> 
> 要cookie.acf_auth才能获取登陆信息

cookie.acf_auth可以通过EditThisCookie获取到，请问如何传进去？貌似没找到相应的接口。谢谢！

**Comment by SeaHOH** [comment]
`名称=值`，使用逗号分隔多个 cookies。acf_auth 好像就是记录登录信息的。

**Comment by speaknowpotato** [comment]
> `名称=值`，使用分号分隔多个 cookies。acf_auth 好像就是记录登录信息的。

大佬可以给个代码链接吗？感谢！

**Comment by SeaHOH** [comment]
如果你实在不会，没必要非下载原画，视频质量差不大许多。

**Comment by speaknowpotato** [comment]
谢谢！我再试试
