### ISSUE TITLE
寻找愿意继续开发的继任者

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#554]
各位朋友，大家好。

ykdl这个项目在各位朋友，特别是@SeaHOH 的帮助下运行了许多年。

开始这个项目的原因，起始非常简单。一台老式电脑：2010年的Thinkpad， CPU是8400。

Flash这个玩意实在太卡，发热巨大。而且我只用Linux，能用FlashPlayer已经是万幸了。

那时，我在论坛（主要是A站）发现有人讨论优酷（主要是看Dota1的视频，9神从0单排系列）的油猴脚本，试过之后，非常棒，直接在浏览器上下载一个m3u8文件，可以用MPV直接播放。虽然那时的英特尔集显还只是孱弱的硬件解码，但CPU软解的CPU占用还是比FlashPlayer少太多。

突然有一天好日子结束了，优酷换了算法，脚本不能用了。这才来Github找各种方案。最初并不知道Youtube-dl，即使后来了解到了，也觉得它巨复杂不已，看起来头大。

you-get则不一样，很小巧。虽然支持的网站不多，但是写的很直观，很容易懂，略懂一点Python的我也能简单debug，当然从它那里也学了不少，特别是爬虫相关的库，flash 反编译，居然还硬啃JS，手工翻译youku的JS，当然现在全部还给老师了。

因为刚进入这个领域，特别有干劲，而you-get的作者，审核代码太慢了，而我不想总等他审核再去工作，索性自己fork出来单干，顺便把做了大范围重构，就有了ykdl。

在ykdl发展的早期主要是我自己，根据you-get报告的错误自己修bug，然后回报给you-get新算法，这样逐渐吸引了一些用户和开发者，他们逐渐贡献了大多数新的算法，还引入jsengine （我完全看不懂）。

随着时间的推移，我的生活也迎来了新的阶段，我的小孩出生了，照顾小孩还有家里的琐事已经占用了绝大部分空闲时间，只能挤时间来看各用户的报告的问题。

在前年暑假，陪了我多年的笔记本从板凳上摔了下去，开不了机了。后来也没有再买新电脑了。家里也没有PC可以开发了。在家上网全靠手机和一台230元的Chromebook(RK3288)

当然后来我的兴趣也转到了Arm开发板，最早是H3的 orangePi PC，我一直在用它跑ykdl，让它联这电视看视频。后来又有了Khadas 的VIM1 VIM2 VIM3 和Edge-V。。兴趣转到Armbian项目了。当然这些都是在工作时间干的（ykdl要开网页看视频，不敢不敢）当然，我对Armbian项目也失去了兴趣，逐渐只维护自己的debian Linux kernel和uboot。不过最近的兴趣是Lakka和LibreELEC， 刚在LibreELEC的主线上重新使能了Lakka，已经在H3上面验证完工了。有兴趣可以看看：https://gitee.com/zhangn1985/reka

咯咯索索一大堆，就是想找一个还愿意开发的继任者，来接替我这个不合格的。

需要留下pypi的帐号名以便添加为pypi包的所有者。

**Comment by SeaHOH** [comment]
@airdge 这个问题算是最高优先级应该不过分，但也不会无限期置顶，至多一两个月肯定会给出个结果，请不要在问题没有解决时取消置顶。

**Comment by airdge** [comment]
> @airdge 这个问题算是最高优先级应该不过分，但也不会无限期置顶，至多一两个月肯定会给出个结果，请不要在问题没有解决时取消置顶。

应该是不注意点到了 不好意思

也得有个大概的开发文档,prepare函数返回啥格式的info数据,同domain不同category(视频/直播)如何区分开来等  别人才好上手

**Comment by jindaxia** [comment]
我原来是作为xbmc的插件开发者接触到这个项目，以前基本上每天回来看看，但是基本上没贡献过代码。现在随着年龄和家庭的原因也已经不玩xbmc了。ykdl也很少来看了

**Comment by SeaHOH** [comment]
@zhangn1985 看来只好由我先接下来，转让权限时请先在这里通知我。

**Comment by zhangn1985** [comment]
OK. 5/13号转给你。

**Comment by SeaHOH** [comment]
14号了，还没收到邮件，请检查。

**Comment by zhangn1985** [comment]
你应该能看到我通过github转给你了，还有pip包也加你作为owner了，

**Comment by SeaHOH** [comment]
巧了，我正好刚才接收完毕。

**Comment by SeaHOH** [comment]
我暂时先维持住，后面会再重新写一篇招募贴。
