### ISSUE TITLE
ykdl 下载优酷视频不全！

### ISSUE THREAD

**Issue by qpb** [zhangn1985/ykdl#559]
Mac电脑通过以下方式安装的ykdl , python版本为3.9

0. install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
1. install FFmpeg and mpv [optional]
brew install ffmpeg mpv
2. install ykdl (v1.7.0)
3. brew install ykdl
/usr/local/bin is already in your PATH, if it is not, add it

通过以上四步骤安装后下载视频只有几十M，原视频完整版是几百M。

这种安装方式有问题吗，还是说需要通过源码安装？

**Comment by SeaHOH** [comment]
安装没有问题，当前情况 (#314) 就是这样。
