### ISSUE TITLE
怎么让ykdl.py -i <url>只显示最高清晰度视频的URL信息而不显示其他较低清晰度的信息

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#56]
希望通过
ykdl.py -i http://tv.cctv.com/2016/05/28/VIDE6DkbIG75oopHh075dyFV160528.shtml

展示信息的时候可以只显示最高清晰度视频的URL信息而不显示其他较低清晰度的信息

**Comment by zhangn1985** [comment]
这是为了保持和you-get的命令行一致。

**Comment by redstoneleo** [comment]
显示结果的第一组real urls就是最清晰的视频地址吗？

**Comment by zhangn1985** [comment]
是的，除非有bug
