### ISSUE TITLE
acfun error

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#61]
{"e":{"desc":"","provider":"play","code":0},"data":{"id":2884016,"security":{"encrypt_string":"LsJqKu6NAKyANTijibwSWcPYBs+Bw26ZCXA=","ip":3082922314},"network":{"dma_code":"24400","area_code":"310000","country_code":"CN"}},"cost":0.00800000037997961}

拿不到streams

**Comment by zhangn1985** [comment]
大概应该是这个调用：
http://aauth-vod.cn-beijing.aliyuncs.com/acfun/web?vid=CMTE1NjkzMDg=&ct=85&sign=MXwxNDg3Mzc0OTc5fDI3Njc3ZmFkMmM5ZWFhMGIxNmYzZWQ5NmZkZmY0Njlj&time=1487374980375

第一这个API是怎么来的暂时不知道，参数来源，与之前一致。
第二如何解析其结果暂时不清楚， 只是大概知道应该要使用base64去解密。

不知道是不是这段AS:
```
 public static function decode(param1:String) : String
      {
         var _loc3_:uint = 0;
         var _loc4_:uint = 0;
         var _loc5_:uint = 0;
         var _loc6_:int = 0;
         var _loc7_:int = 0;
         var _loc8_:int = 0;
         var _loc9_:int = 0;
         var _loc2_:String = "";
         var _loc10_:uint = 0;
         var _loc11_:uint = param1.length;
         var _loc12_:RegExp = /[^A-Za-z0-9\+\/\=]/g;
         if(_loc12_.exec(param1))
         {
            throw new Error("There were invalid base64 characters in the input text.\n" + "Valid base64 characters are A-Z, a-z, 0-9, \'+\', \'/\', and \'=\'\n" + "Expect errors in decoding.");
         }
         param1 = param1.replace(/[^A-Za-z0-9\+\/\=]/g,"");
         do
         {
            _loc6_ = param1.indexOf(param1.charAt(_loc10_++));
            _loc7_ = param1.indexOf(param1.charAt(_loc10_++));
            _loc8_ = param1.indexOf(param1.charAt(_loc10_++));
            _loc9_ = param1.indexOf(param1.charAt(_loc10_++));
            _loc3_ = _loc6_ << 2 | _loc7_ >> 4;
            _loc4_ = (_loc7_ & 15) << 4 | _loc8_ >> 2;
            _loc5_ = (_loc8_ & 3) << 6 | _loc9_;
            _loc2_ = _loc2_ + String.fromCharCode(_loc3_);
            if(_loc8_ != 64)
            {
               _loc2_ = _loc2_ + String.fromCharCode(_loc4_);
            }
            if(_loc9_ != 64)
            {
               _loc2_ = _loc2_ + String.fromCharCode(_loc5_);
            }
         }
         while(_loc10_ < _loc11_);
         
         return _loc2_;
      }
```

**Comment by wukongtea** [comment]
可不可以通过抓包工具，抓到真实地址 然后逆向推测呢。

**Comment by denobisipsis** [comment]
self.__class__.trans_e(
            "328f45d8",
            base64.b64decode(bytes(self.data, 'ascii'))
        )

**Comment by zhangn1985** [comment]
不懂。

**Comment by denobisipsis** [comment]
Sorry, you should use youku trans_e function

def trans_e(a, c):
        """str, str->str
        This is an RC4 encryption."""
        f = h = 0
        b = list(range(256))
        result = ''
        while h < 256:
            f = (f + b[h] + ord(a[h % len(a)])) % 256
            b[h], b[f] = b[f], b[h]
            h += 1
        q = f = h = 0
        while q < len(c):
            h = (h + 1) % 256
            f = (f + b[h]) % 256
            b[h], b[f] = b[f], b[h]
            if isinstance(c[q], int):
                result += chr(c[q] ^ b[(b[h] + b[f]) % 256])
            else:
                result += chr(ord(c[q]) ^ b[(b[h] + b[f]) % 256])
            q += 1

        return result

with key 328f45d8. Data is the encrypted result from 

http://aauth-vod.cn-beijing.aliyuncs.com/acfun/web?vid=CMTE1NjkzMDg=&ct=85&sign=MXwxNDg3Mzc0OTc5fDI3Njc3ZmFkMmM5ZWFhMGIxNmYzZWQ5NmZkZmY0Njlj&time=1487374980375

**Comment by zhangn1985** [comment]
sign我已经能正确得到啦。
只是这个api调用是怎么来的不清楚。

**Comment by zhangn1985** [comment]
你们写的trans_e根本读不懂，sign也不知道你们怎么弄的，根本没法和Youku的JS/AS对应。你让别人怎么维护？？？？

**Comment by denobisipsis** [comment]
Sign may be not needed. Anyway, sign could be base64_encode of encode from

http://www.acfun.cn/video/getVideo.aspx?id=3240809

where id come from html source_id

**Comment by zhangn1985** [comment]
the problem is I don't know how to decrypt data in  http://aauth-vod.cn-beijing.aliyuncs.com/acfun/web?vid=CMTE1NjkzMDg=&ct=85&sign=MXwxNDg3Mzc0OTc5fDI3Njc3ZmFkMmM5ZWFhMGIxNmYzZWQ5NmZkZmY0Njlj&time=1487374980375

**Comment by denobisipsis** [comment]
@zhangn1985 

import urllib2,json,base64

api='http://aauth-vod.cn-beijing.aliyuncs.com/acfun/web?vid=CMTE1NjkzMDg=&ct=85&sign=MXwxNDg3Mzc0OTc5fDI3Njc3ZmFkMmM5ZWFhMGIxNmYzZWQ5NmZkZmY0Njlj&time=1487374980375'

c=base64.b64decode(json.load(urllib2.urlopen(api))['data'])

a="328f45d8"

"""str, str->str
This is an RC4 encryption."""

f = h = 0
b = list(range(256))

while h < 256:
	f = (f + b[h] + ord(a[h % len(a)])) % 256
	b[h], b[f] = b[f], b[h]
	h += 1
q = f = h = 0
result = ''
while q < len(c):
	h = (h + 1) % 256
	f = (f + b[h]) % 256
	b[h], b[f] = b[f], b[h]
	if isinstance(c[q], int):
		result += chr(c[q] ^ b[(b[h] + b[f]) % 256])
	else:
		result += chr(ord(c[q]) ^ b[(b[h] + b[f]) % 256])
	q += 1

print(result);

**Comment by zhangn1985** [comment]
the function you provide is same as ykdl.extractors.youkujs.rc4  or ykdl.extractors.youkujs.L
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/youkujs.py#L111


but how to get "328f45d8"

**Comment by denobisipsis** [comment]
Sorry, 

from cloud.swf com.youku.core.model.YoukuServiceProxy.decrypt com.youku.data.PlayerConstant.SPECIAL_TYPE_KEY_ACFUN + "f45" + "d8";

**Comment by zhangn1985** [comment]
thank you.
