### ISSUE TITLE
pip 安装后不能正常使用

### ISSUE THREAD

**Issue by freeleefly** [zhangn1985/ykdl#65]
wiki看的不是很明白。
Windows 10 下
并没有生成可执行文件`ykdl.exe`，在script文件夹下找到`ykdl.py`
比如 cmd下，`ykdl.py http://www.acfun.cn/v/ac3499035`
均显示 

`ykdl.py: error: the following arguments are required: video_urls`

应该是我哪里没弄明白，希望能稍微解释下，谢谢。
主要是因为you-get 对acfun下载失败了，刚看到转过来的。

发现
`python "C:\Python35\Scripts\ykdl.py" http://www.iqiyi.com/v_19rracw19g.html`
这样是可以下载的，但是这也太...  应该是我的打开方式不对，还是请问正确的使用方式是什么？

**Comment by zhangn1985** [comment]
因为我还没有win10+py35的环境，在XP+py34没有这个问题
我并不清楚发生了什么。

直接用ykdl http://www.acfun.cn/v/ac3499035 这样如何呢？

**Comment by freeleefly** [comment]
是不行的。
直接在win10下的话 直接ykdl.py 是可以调用，但是应该是参数解析时候有问题，所以一直找不到视频网址的感觉。

**Comment by mengmo** [comment]
关于`Scripts`下没生成`ykdl.exe`，详见这个 issue https://github.com/zhangn1985/ykdl/issues/20
我是这样做的
`xcopy /D /V /Y "...\Python\Scripts\ykdl.py" "...\Python\Lib\site-packages\ykdl\__main__.py"`
然后就可以
`python -m ykdl http://www.acfun.cn/v/ac3499035`
还可以更进一步
新建一个名为`ykdl.cmd`的文件，然后这样写
```
@echo off
python -m ykdl %1 %2 %3 %4 %5 %6 %7 %8 %9
```
扔到系统环境变量的 path 中的任一目录下，就可以直接
`ykdl http://www.acfun.cn/v/ac3499035`
当然，也可以不复制`ykdl.py`。这样写`ykdl.cmd`
```
@echo off
python "...\Python\Scripts\ykdl.py" %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Comment by freeleefly** [comment]
@mengmo 
看了 #20 发现 之前不能直接使用`ykdl`是因为 `%PATHEXT%` 没有添加 `.PY`,添加之后可以使用。
但是还是一样的问题 不能正常的解析参数，一直提示 `ykdl.py: error: the following arguments are required: video_urls`

然后似乎又引出了很多基础知识的问题，果然是我不扎实。
另存为成`__main__.py`应该是把 `ykdl`从模块又变成一个包，我这么理解没错吧？

~~按照您上面这么操作的话，应该是可以的。不过，既然都已经使用如此作弊的手段的话，那么我觉得：--
跳过`xcopy`步骤，在`ykdl.cmd` 文件里面直接写
`@echo off
python "C:\Python35\Scripts\ykdl.py" %1 %2 %3 %4 %5 %6 %7 %8 %9`~~

打完才发现您已经写了，怪我不认真。

@zhangn1985 
最后就上面这个链接`http://www.acfun.cn/v/ac3499035`
解析之后
Traceback (most recent call last):
  [...]
  File "C:\Python35\lib\site-packages\ykdl\extractors\youkubase.py", line 26, in get_custom_stream
    self.stream_data = data['stream']
KeyError: 'stream'
是不是，A站和youku合作的视频解析方面还有点问题？

**Comment by mengmo** [comment]
要正常解析 A站的视频，你需要手动下载项目中最新的`acorig.py` `youkubase.py` `youkujs.py`这几个文件替换

**Comment by mengmo** [comment]
@freeleefly 或者直接用 git

**Comment by zhangn1985** [comment]
感谢@mengmo acfun 再次更新导致key失效。

我看看是否需要用setuptools来创建pip包。
