### ISSUE TITLE
A站 列表下载 会重复下载

### ISSUE THREAD

**Issue by freeleefly** [zhangn1985/ykdl#72]
`ykdl -l http://www.acfun.cn/v/ac2630271`
一个是一次没有全部下载成功的，再次输入命令的话，又会重新下载已经下载过的视频。
另一个是小问题，命名问题，生成的文件是类似 `video_id-3312981_HD.mp4`这种，不太好区分。不过是小问题，但是因为没有区分，也就不知道到底哪集没下哪集已经下了。

有`--start` 参数，但是没有跳过某一个文件的选项，希望可以有

好像是好几个问题，但是感觉其实是一个问题哦。
加油

**Comment by zhangn1985** [comment]
看来的确是有这个问题。因为视频分片已经被删除了，所以会重新下载。

**Comment by freeleefly** [comment]
对的，如果是分片还在的话，那是会继续下载的，应该再在外面加一个判断。
还有，好看一点的话，可以顺便把用来ffmpeg合并的文档给悄悄的删除了 💯

**Comment by zhangn1985** [comment]
FFMPEG合并的文档，在Windows平台下是不会删除了。
这是因为ykdl在创建出ffmpeg之后，就会退出，从而会删除这个文档。当ffmpeg再需要访问的时候，就出现了没有文件的错误。
在Linux平台，ykdl在创建ffmpeg之后，会等待ffmpeg，所以不存在文件被删除的问题。

关于--start这个参数，在最近被删掉了，会以某种形式加回去。
ACFUN的名字问题，需要观察，ACFUN的视频目前是否都是一种存储形式。
如果是的话，可以比较容易的修改。

静观其變吧。

**Comment by zhangn1985** [comment]
暂时先用-O NAME来处理吧。
https://github.com/zhangn1985/ykdl/commit/c600ec40cb66c648a8166775460e9a625621ecdd

**Comment by freeleefly** [comment]
对于一个文件来讲，其实无所谓。问题是列表，对于列表，-O好像又不能用了。。。。，还是说有，另外的用法？

**Comment by zhangn1985** [comment]
```
site:                AcFun 优酷合作视频
title:               video_id:3311730
artist:              None
streams:
    - format:        HD
      container:     mp4
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Download: 测试_0 part 0

site:                AcFun 优酷合作视频
title:               video_id:3312980
artist:              None
streams:
    - format:        HD
      container:     mp4
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Download: 测试_1 part 0

Download: 测试_1 part 1
```
刚改好的。

**Comment by freeleefly** [comment]
哦。NAME后面自动加后缀哦。。。

**Comment by zhangn1985** [comment]
那么--start + -O的自动重命名，应该可以workaround了吧。

**Comment by freeleefly** [comment]
暂时可以，如果没有中间某几个出问题的话。

**Comment by zhangn1985** [comment]
先关闭，有其他问题在报Bug
