### ISSUE TITLE
通过pip安装后，'ykdl' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#76]
我的是Python 3.5.2， Win7 32bit
通过pip安装后，
```
C:\Users\i>ykdl
'ykdl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\i>
```
隔壁的you-get安装后
```
C:\Users\i>you-get
Usage: you-get [OPTION]... [URL]...

Startup options:
    -V | --version                      Print version and exit.
    -h | --help                         Print help and exit.

Dry-run options: (no actual downloading)
    -i | --info                         Print extracted information.
    -u | --url                          Print extracted information with URLs.
         --json                         Print extracted URLs in JSON format.

Download options:
    -n | --no-merge                     Do not merge video parts.
```
现在就只能通过下面这种方式使用了，感觉好憋扭
```
C:\Users\i>Python C:\Users\i\AppData\Local\Programs\Python\Python35-32\Scripts\y
kdl.py
usage: ykdl.py [-h] [-l] [-i] [-j] [-F FORMAT] [-o OUTPUT_DIR]
               [-O OUTPUT_NAME] [-p PLAYER] [--proxy PROXY] [-t TIMEOUT]
               [--no-merge] [-s START]
               video_urls [video_urls ...]
ykdl.py: error: the following arguments are required: video_urls

C:\Users\i>
```
我知道可以手动设置下环境变量来解决问题，但是老大能否考虑一下像you-get那样在安装的时候自动设置一下啊！
希望老大考虑我的建议，我今天提了好几个问题，麻烦老大了，不好意思啊~~

**Comment by zhangn1985** [comment]
请`echo %PATH%`
把结果贴出来

**Comment by zhangn1985** [comment]
you_get是用setuptools安装的，ykdl用的是python自带的distutils，这是两者的区别。之前也有人反馈过pip安装后不能使用的问题。在搞清楚这个问题之前，没有计划切换到setuptools。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/issues/20#issuecomment-249411651

**Comment by redstoneleo** [comment]
```
C:\Users\i>echo %PATH%
C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\windows\system32;
C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\SinoVoice\jTTS 5.0 Desktop\Bin;C:\Program Files\Git\cmd;C:\Prog
ram Files\TortoiseSVN\bin;C:\Program Files\PuTTY\;C:\Users\i\AppData\Local\Progr
ams\Python\Python35-32\Scripts\;C:\Users\i\AppData\Local\Programs\Python\Python3
5-32\;C:\Users\i\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\PyQ
t5\;C:\Users\i\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\PyQt5
\Qt\bin\;C:\Program Files\Bandizip;C:\Program Files\Heroku\bin

C:\Users\i>echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

C:\Users\i>
```

> .py要在PATHEXT变量中
这个起什么作用？

**Comment by zhangn1985** [comment]
当你直接输入`ykdl`时，会自动补全.py。并赋予可执行权限。
还有，.py的打开方式是否是python。

**Comment by zhangn1985** [comment]
![2017-03-12 14-21-15](https://cloud.githubusercontent.com/assets/832666/23829538/3013fd18-072f-11e7-8160-deeedb742440.png)
类似于这样。

**Comment by SeaHOH** [comment]
我都是用鼠标手势调用，直接写到脚本里面，比手动命令行方便。

**Comment by redstoneleo** [comment]
@zhangn1985 
原来如此，谢谢指教！
对此，
（1） pip安装ykdl的时候并不会把.py加到PATHEXT变量中，所以你这里要求这一点可能有小点欠考虑（原谅我！），估计你换用像you_get那样的setuptools安装方式会少一些问题吧
（2）我的.py的打开方式是sublime，不是Python

**Comment by redstoneleo** [comment]
@SeaHOH 你用什么工具的鼠标手势调用？这么强大？！！

**Comment by zhangn1985** [comment]
.py加到PATHEXT变量 这个是python安装程序做的。
安装时选择“ADD Python3.5 to PATH”
https://github.com/zhangn1985/ykdl/wiki/windows-user-guide

**Comment by zhangn1985** [comment]
![2017-03-12 14-47-13](https://cloud.githubusercontent.com/assets/832666/23829670/2e5d25b8-0733-11e7-81ae-859de121cc20.png)

**Comment by redstoneleo** [comment]
谢谢指教！
不过我记得这个选项应该不是默认的吧？！所以还是要有这种考虑
另外，目前来讲安装后直接ykdl调用出现这个问题也是不便于使用哈
```
C:\Users\i>ykdl
'ykdl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\i>
```

**Comment by zhangn1985** [comment]
![untitled](https://cloud.githubusercontent.com/assets/832666/23829705/fec321b2-0733-11e7-8a39-adc60de54e54.png)

不是默认，可以考虑为windows专门提供Pip包，或者用setuptools。

**Comment by redstoneleo** [comment]
嗯嗯，谢谢大哥！
我在Linux上面pip安装后也不能直接用，用
`Python3 /usr/local/bin/ykdl.py -j http://www.tudou.com/listplay/HXTEm-Oxufc/QjrcnlhEflU.html
`
才行，估计像you_get那样采用setuptools安装方式会扫清这种小麻烦吧

**Comment by zhangn1985** [comment]
linux需要使用ykdl.py运行。

**Comment by redstoneleo** [comment]
要是能够统一起来都用ykdl就方便了

**Comment by SeaHOH** [comment]
@redstoneleo 
火狐 FireGestures，在链接上划手势。其它的应该也可以，原理一样，就是取 Url 为参数运行 py 脚本。

**Comment by zhangn1985** [comment]
@redstoneleo 你可以alias ykdl=ykdl.py
