### ISSUE TITLE
youku fail

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#90]
https://github.com/soimort/you-get/issues/1771

change
http://play.youku.com/play/get.json?ct=12&vid=
to
http://play-ali.youku.com/play/get.json?ct=12&vid=

**Comment by xmugenx** [comment]
once you change to play-ali you will also need to change the following
```
'fileid': stream['stream_fileid']
to
'fileid': stream['segs'][0]['fileid']
```

**Comment by zhangn1985** [comment]
是的，还有很多需要改的。

**Comment by zhangn1985** [comment]
等待优酷API稳定下来。
