### ISSUE TITLE
多线程下载视频没用？？？

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#96]
根据我测试，发现无论是多线程还是单线程下载视频速度都差不多。
我想原因可能是视频文件通常比较大，下载器下载的时候基本都会占满带宽来下载，这时候如果还开多线程下载只不过是平均分配有限的带宽，因此最终也并不会节省视频下载时间。

以上是菜鸟我的分析，请各位大神也来发表下意见！
这个问题和本项目还是有关的，请不要随便关闭本问题，多交流下技术，共同提高！

**Comment by SeaHOH** [comment]
好像不是多线程而是多任务。能占满带宽说明网络质量好。

**Comment by redstoneleo** [comment]
ykdl.py里用的就是ThreadPoolExecutor啊，怎么不是多线程了？并且可以通过`-j`来设置线程数量，实测多线程下载视频没什么用处

**Comment by redstoneleo** [comment]
@SeaHOH 能占满带宽说明网络质量好????
可以深入解释下吗？

**Comment by SeaHOH** [comment]
多线程一般指同一个任务用多个线程并行完成；
多任务就是说同时进行多个任务，层级不一样。

有些时候网络拥挤，速度上不去的，你这满速了不就是质量好嘛；
当然这个不能一概而论，还要看内容提供商的策略，可能会有限制行为。

**Comment by zhangn1985** [comment]
并不是所有视频都能满带宽的，比如腾讯的某些。
多线程在这些视频下载时还是很有帮助的。

**Comment by redstoneleo** [comment]
这个帖子解答的也不错http://stackoverflow.com/questions/24622038/does-downloading-with-multiple-threads-actually-speed-things-up

**Comment by jindaxia** [comment]
下载腾讯视频是肯定有用的，实测速度至少提高了10倍

**Comment by redstoneleo** [comment]
据我测试，貌似这个补丁已经破解腾讯限速问题了
https://github.com/soimort/you-get/pull/1685

**Comment by zhangn1985** [comment]
其实并没有

**Comment by qwIvan** [comment]
@redstoneleo 是的，不限速
