### ISSUE TITLE
WIN10斗鱼视频站下载问题若干

### ISSUE THREAD

**Issue by feranwq** [zhangn1985/ykdl#97]
WIN10 64 PYTHON3.6
分段下载可能会有某段视频没有生成下载,这样会导致拼接失败,还要手动改filelist手动拼接,所以我加了个判断确认文件是否存在,删除的时候同样加了个判断

不知道是否是ffmpeg环境变量相关问题,如果filelist里不知道绝对路径ffmpeg会报file not found.
请教下怎么设置可以自适应目录

WINDOWS下subprocess.call必须指定shell=True,否则会报错
cmd直接执行ffmpeg +相关参数会报ffmepg错误,但是手动在cmd执行同样的命令不会报错
一番尝试之后在前面加了个cmd /c就好了

另外提个建议,现在是把url部分作为文件名,可以抓一下视频标题来作为文件名

def launch_ffmpeg(basename, ext, lenth):
    #build input
    inputfile = compact_tempfile(mode='w+t', suffix='.txt', dir='.', encoding='utf-8')
    for i in range(lenth):
        if os.path.exists('D:\\Download\\you-get\\ykdl\\wa\\%s_%d_.%s' % (basename, i, ext)):
            inputfile.write('file \'D:\\Download\\you-get\\ykdl\\wa\\%s_%d_.%s\'\n' % (basename, i, ext))
    inputfile.flush()

    outputfile = basename+ '.' + ext

    cmd = ['cmd','/c','ffmpeg','-f', 'concat', '-safe', '-1', '-y', '-i', inputfile.name, '-c', 'copy', '-hide_banner','-absf', 'aac_adtstoasc']

    cmd.append(outputfile)
    log.d('Merging video %s using ffmpeg:' % basename)
    return subprocess.call(cmd, shell=True)

**Comment by zhangn1985** [comment]
了解。shell=True，评估一下，应该很快会加上的。

文件下载的时候，如果下了一半，出现http timedout，这个问题要考虑一下。
如果完全没有下载，ffmpeg会直接失败，而不会删除已经下载好的。

**Comment by feranwq** [comment]
因为我的网络不稳定,所以才会专门下载直播录像来看
目前发现的是playlist里一段文件没有生成或者下载失败的话不会影响其他视频
我只需要在filelist里排除问题视频,拼接/观看是没问题的
如果要做视频完整校验并且续传的话可能就需要对ffmpeg做修改了

**Comment by zhangn1985** [comment]
你如果用的是pip/源码安装的话，可以修改：
https://github.com/zhangn1985/ykdl/blob/master/bin/ykdl.py#L27
把True改成False，就是用FFMPEG来下载m3u8链接了。

**Comment by zhangn1985** [comment]
shell=True在Linux上有问题。
ffmpeg放在%PATH%上

**Comment by zhangn1985** [comment]
这个问题一部分被 https://github.com/zhangn1985/ykdl/commit/b006d047e2d772c045e5908c467714418b09a4f2 解决了，另外一部分 `shell=True` 因为Linux有问题，而没有其他人报告这个问题。
