### ISSUE TITLE
ykdl_win32.exe版本和ykdl.exe有什么区别啊？小白一个不懂~

### ISSUE THREAD

**Issue by liguge** [zhangn1985/ykdl#99]
小白一个不是很懂~

**Comment by mengmo** [comment]
可以看看这些，参考一下
https://github.com/zhangn1985/ykdl/wiki/windows-user-guide
https://github.com/zhangn1985/ykdl/issues/75

**Comment by mengmo** [comment]
@zhangn1985
wiki 该改了

**Comment by liguge** [comment]
@mengmo  谢谢啦 明白了~
